### ISSUE TITLE
Does this extension have VS2017 windows version?

### ISSUE THREAD

**Issue by strategist922** [Microsoft/vscode-tools-for-ai#10]
Hi,
  Does this extension available in VS2107 windows edition?
If yes, how can I install it?

**Comment by linmajia** [comment]
Hi strategist922,
This tool required latest VS code (version >= 1.16). You **cannot** install it for Visual Studio.

**Comment by ahgyger** [comment]
Hi @strategist922, we don't have support for VS 2017. We take note of your request however.
