### ISSUE TITLE
Improve workflow for json or conda_dependencies edits presented for the user to submit

### ISSUE THREAD

**Issue by paloukari** [microsoft/vscode-tools-for-ai#100]
The VS Code notifications for provisioning Azure resources are confusing because they timeout. Please make clear to the users how to open up again the expired notifications

**Comment by greazer** [comment]
This may require some investigation as to what other extensions might use or get input from the VS Code team.

**Comment by greazer** [comment]
related to https://github.com/Microsoft/vscode/issues/65459. I sent an internal MS email to Ben Pasero.

**Comment by swinner95** [comment]
@greazer any feedback on this?

**Comment by greazer** [comment]
Using codelenses as a workaround.

**Comment by shsuman** [comment]
I think codelenses have solved this problem
