### ISSUE TITLE
Support connecting to compute instances that don't have a public IP

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1005]
Public Preview for compute instances with non-public IP will occur end of May/early June. We want to support connecting to these compute instances through VS Code before the public preview.

If the compute instance does not have a public IP we should use the private IP returned. If we cannot retrieve a private IP we should fail gracefully and inform the user that neither public nor private IP information was found. 

**Scope:** Test for private-link enabled workspaces as CI team thinks we don't need to do any additional work.

**Comment by SiddhanthUnnithan** [comment]
Test this for a private-link enabled workspace.

**Comment by SiddhanthUnnithan** [comment]
Currently blocked because compute instances with private IP seem to not have outbound internet access (can't get VS Code server or websocket server bits).

**Comment by sevillal** [comment]
How to allow public access:
1. Setup firewall in vnet https://docs.microsoft.com/en-us/azure/firewall/tutorial-firewall-deploy-portal#configure-an-application-rule
2. Route communication from CI subnet to firewall (find instructions in previous link)
3. Outbound configuration https://docs.microsoft.com/en-us/azure/firewall/tutorial-firewall-deploy-portal#configure-an-application-rule
4. Add outbound rules to firewall:
  - Source: Subnet IP range
  - Protocol:port: http, https
  - Targets: update.code.visualstudio.com,*.vo.msecnd.net,github.com,raw.githubusercontent.com

**Comment by SiddhanthUnnithan** [comment]
Adding @luisquintanilla because this is relevant to the documentation change we've been discussing. Users should only have to add the target endpoints listed above to get the non-public IP CI scenario working.

**Comment by SiddhanthUnnithan** [comment]
Hey @luisquintanilla just checking to see when the docs for this is going to go out.

**Comment by SiddhanthUnnithan** [comment]
Docs to reflect this change are public. Closing for now.
