### ISSUE TITLE
Update CLI installation pointer to https://aka.ms/amlext-cli-install

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1018]
New public doc: https://review.docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli

Will get published in time for Build.

**Comment by SiddhanthUnnithan** [comment]
Our extension should point to this: https://aka.ms/amlext-cli-install

TODO: Update redirect to the new public doc after it has been published.

**Comment by shsuman** [comment]
https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2217347
