### ISSUE TITLE
Allow users to invoke "Create Resource" file context menu option without saving the file.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1022]
Prompt users to save the file after invoking the command, then run in the CLI.

**Comment by shsuman** [comment]
What do we do with this for 6.23 ?

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2238256
