### ISSUE TITLE
Add workspace, resource group, and subscription fields to CLI create commands

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1023]
Take a naive approach for now where we don't rely on the CLI to have default settings. Instead we use the workspace context that the user has and create the resource with the right arguments (ws, rg, sub).

The goal here is to ensure that users without default values set through the CLI will still be successful when submitting through our extension. Users would expect the extension workspace context to get retained and are not motivated to re-inputting the default values in the CLI.

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2226872
