### ISSUE TITLE
Executing CLI create command on a dirty file can be confusing for the user

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1031]
1. User has a valid resourcer.yaml file to create a resource
2. User modifies the file but does not save
3. User right clicks the file and selects "Azure ML: Create Resource"
4. The user be under the impression that the command will take the latest changes, but the command will use the latest saved version

**Comment by SiddhanthUnnithan** [comment]
Can we check to see whether there are unsaved changes or whether the file is in a dirty state when the command is executed?

**Comment by sevillal** [comment]
Yes, vscode api has a way to know if the file is dirty

**Comment by tbombach** [comment]
We can show a toast notification that asks the user to save their changes and uses vscode api to save the changes to their file. However, we need to determine what the experience will be - does the user have to deal with the toast notification before we show the CLI create command? Or do they see the CLI command before they click on a button in the toast notification. @SiddhanthUnnithan do you have any guidance on what the experience should be here?

**Comment by SiddhanthUnnithan** [comment]
We should show the following prompt:

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/d6906301-a852-4426-9562-a2c9bbfab30e)

The messaging should be:

Main - "Please save the changes you made to <filename>."

Sub - "You cannot create a machine learning resource without saving the file."

Button Options - Save, Cancel

**Comment by shsuman** [comment]
Opened issue on VSCode: https://github.com/microsoft/vscode/issues/124117
