### ISSUE TITLE
[Track] Extension is unable to load schema despite it being available on public blob

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1036]
![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/b7cd34c1-a2dc-4163-8c94-d05dd243668d)

The extension complains that there is no content for the schema despite the schema being available in the public blob. I was hitting this issue in both my remote and local windows.

I'm unable to see completions or diagnostics without a loaded schema.

**Comment by shsuman** [comment]
I am unbale to repro with any of the schemas. Plus, the codelens was also working perfectly for me for all of them. So, I guess both the issues were coupled

**Comment by SiddhanthUnnithan** [comment]
Track whether other customers are hitting this.

**Comment by SiddhanthUnnithan** [comment]
Already being tracked as part of #1067
