### ISSUE TITLE
A few issues with Remote Extension @ Rabobank

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1042]
Rabobank is facing a few issues with the Remote extension with file upload using Azure Storage extension, kernel management with Jupyter extension. I am creating this issue to track all those issues.

Azure Storage: https://github.com/microsoft/vscode-azurestorage/issues/975
Jupyter: https://github.com/microsoft/vscode-jupyter/issues/5949

@wdwit for visibility

**Comment by SiddhanthUnnithan** [comment]
@shsuman is there a follow-up for this? Is this issue still being hit? Can we close this?

**Comment by SiddhanthUnnithan** [comment]
Follow up 1: Reach out to the CI team to add libsecret-1-0 to the base image so that other users don't run into this problem.

Follow up 2: Check if kernel issue is reproducible on latest VS Code and with latest Jupyter.

Closing for now.
