### ISSUE TITLE
Use displayName for runs in tree view

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1048]
Recently studio changed the way it display runs from runNumber to displayName

**Comment by SiddhanthUnnithan** [comment]
@sevillal do you have the capacity to pick this up now that the interactive job work has been wrapped up?

**Comment by sevillal** [comment]
Yes, taking this one.

**Comment by sevillal** [comment]
Closing this as that behavior is not there anymore in the Studio, keeping the "Run <RUN_NUMBER>" format we currently have (matching studio).
