### ISSUE TITLE
[Triage] Investigate token failure issue and missing context menu options when connecting from Ubuntu machines

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1051]
Daimler was testing connecting to VS Code from an Ubuntu machines and they were unable to pass the "get_token_session" step. The same user and compute instance connection was working when initiated from a Windows machine.

**Comment by SiddhanthUnnithan** [comment]
Need to determine whether we should move from adal-node to msal-node library and whether that is what is causing token/auth failures.

**Comment by shsuman** [comment]
Was the missing context menu option still an issue with 0.6.23 ?

**Comment by SiddhanthUnnithan** [comment]
@shsuman is this still a relevant issue? Can we close this otherwise.

**Comment by SiddhanthUnnithan** [comment]
Closing.
