### ISSUE TITLE
Support Local Endpoint Debugging

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1052]

**Comment by sevillal** [comment]
- Integration with CLI work
- Prototype code cleanup
- Error handling
- Testing

**Comment by SiddhanthUnnithan** [comment]
Thanks Sergio! Curious what you mean by "integration with CLI work"?

**Comment by sevillal** [comment]
@SiddhanthUnnithan "Integration with CLI work" in my mind I was referring to, AML inference team will provide a beta version with the changes for us to test, from there we might re-adjust something or just validate that it everything is ready, I might change it to "integration test".

**Comment by SiddhanthUnnithan** [comment]
@sevillal Can you add issues that list what the current blockers are for the AML team?
