### ISSUE TITLE
Use MFE list and show REST APIs in the extension

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1059]
Swagger: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2021-03-01-preview

REST Docs: https://github.com/Azure/azure-docs-rest-apis/blob/machinel/docs-ref-conceptual/azureml/index.md

Mrudula Narkhede is AML contact for REST.

**Comment by SiddhanthUnnithan** [comment]
Blocked for:
- compute (need interfaces)
- data containers (show)
- data container = all versions of a dataset

**Comment by shsuman** [comment]
Covered in Rearchitecture
