### ISSUE TITLE
VSCODE-REMOTE Error while loading extensions. Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by YnnamTenob** [microsoft/vscode-tools-for-ai#1066]
## Expected Behavior
VSCODE Remote Extensions load without error

## Actual Behavior
Error while loading extensions. Cannot read property 'split' of undefined. This started happening this morning in themiddle of a notebook move on the remote server I lost the notebook in its entirety and I am unable to uninstall the extensions as I get the same error Cannot read property 'split' of undefined. This extension has been sketchy, always having difficulty with saving notebooks on remote server. As of now it is unusable.

## Steps to Reproduce the Problem

  1. Open VS Code from Compute instance
  1. Try to uninstall the extensions
  1.

## Specifications

  - VS Code Version: 1.56.2
  - Platform:  Windows

**Comment by tbombach** [comment]
Hi @YnnamTenob, thank you for reporting this issue. I'm very sorry to hear about the data loss that you experienced. Would you mind providing a list of other extensions that are installed in VS Code? We've worked to improve reliability (especially during remote connections) but we haven't seen issues relating to uninstalling the extension yet. Our team will try to reproduce this issue and figure out the cause.

**Comment by YnnamTenob** [comment]
@tbombach the error "Cannot read property 'split' of undefined" went away once I executed the _Remote: Close Remote Connection_ command. That said the reliability of a Remote Connection is the problem. Once VS Studio starts receiving "[Error - 2021-06-10 18:17:50.004] Failed to forward incoming connection to remote server: Unexpected server response: 401" from Azure - ML Remote then things go south from there and I have to be very careful to manually copy any changes in my current notebook to prevent losing them.
