### ISSUE TITLE
CLI V2 should not be default for the VSCode extension until it is GA

### ISSUE THREAD

**Issue by ezwiefel** [microsoft/vscode-tools-for-ai#1068]
## Expected Behavior
I expect the VSCode Extension to work the same day-to-day without having to install other CLI tools. 

## Actual Behavior
VSCode extension breaks if I don't have Azure ML CLI v2, and I'm expected to change a setting to revert the behavior back.

Until V2 CLI is GA'ed, this shouldn't be set as the default.

**Comment by ezwiefel** [comment]
@azeltov

**Comment by SiddhanthUnnithan** [comment]
Hey Erik, thanks for bringing this to our attention. The point you make about the 2.0 CLI mode being default is a valid one. I'll discuss with the extension and Azure ML teams to keep 1.0 as the default.

Regarding "expected to change a setting to revert" - there is a setting in the extension to be compatible with the 1.0 CLI:

![image](https://user-images.githubusercontent.com/6413608/120042933-ebc2c100-bfbf-11eb-8eb1-c98772cce66c.png)

Lastly, I'm curious what you were using the extension for that prompted wanting to return to the 1.0 CLI flow? I know there is a dependency on using the CLI but that should only come up at the point when you're trying to create a resource.

Happy to answer any questions!

**Comment by ezwiefel** [comment]
Hey Sid! 

@azeltov can give you more details on what he was trying to do... he lost an hour trying to troubleshoot why the extension was no longer working before he figured out it was due to the V2 of the CLI not being installed and discovering the setting to revert to CLI V1.

As for the note about "expected to change a setting to revert" - I knew that setting existed, but my comment was more that we're expecting users to know it's there and change it to fix broken behavior.

The broader issue with CLI V2 roll-out is that V2 doesn't have feature parity with V1 at this point and it can't co-exist with V1 either. As a result, if someone is a CLI user, I wouldn't recommend they change to V2 at this point.
