### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Cannot read property 'split' of undefined)

### ISSUE THREAD

**Issue by hillygoose** [microsoft/vscode-tools-for-ai#1086]
## Expected Behavior
Expected that using the Azure extension "Azure Machine Learning" I would be able to connect to the compute instance currently running on my companies Azure infrastructure

## Actual Behavior
When trying to connect (right clicking on the compute instance I want to use and selecting "Connect to Compute Instance") it opens up a new VS Code window but produces the error - 
Failed to connect to the remote extension host server (Error: Cannot read property 'split' of undefined)

## Specifications

  - VS Code Version: 1.53.2
  - Azure compute: Standard d2_v2
 
This is my first issue raised so apologies if I haven't given enough information

**Comment by SiddhanthUnnithan** [comment]
Hi @hillygoose - do you mind sharing what version of the Azure Machine Learning extension you're using?

As well, can you confirm whether you have ever been able to connect to a compute instance from VS Code?

**Comment by hillygoose** [comment]
Of course @SiddhanthUnnithan 
Version of Azure Machine Learning extension is - 0.6.23
And no this is the first time I have tried to connect to a compute instance from VS Code

**Comment by sevillal** [comment]
Thanks @hillygoose for sharing that information.

Do you mind sharing what version of the Azure Machine Learning - Remote extension you are using? Here a snapshot on how it looks:

![image](https://user-images.githubusercontent.com/56176070/122443602-9b060e80-cf54-11eb-94e7-c7636fd24c96.png)

**Comment by hillygoose** [comment]
Hi @sevillal my version for the Azure ML Remote is 0.1.0 which seems very old compared to your version!

**Comment by hillygoose** [comment]
![image](https://user-images.githubusercontent.com/86004303/122445620-a16aa980-cf99-11eb-8434-212018306c31.png)


Just for clarity

**Comment by sevillal** [comment]
Thanks @hillygoose, yes it is old, the latest one in the market place is 0.3.0, I see your vscode version is 1.53.2.

Can you try the following:

1. Update your vscode to the latest 1.57
2. Update the azure machine learning remote extension to 0.3.0

**Comment by sevillal** [comment]
Hello @hillygoose 

Following up with you to check if you faced any issue after upgrading VSCode and Azure Machine Extension - Remote, please let us know if there is anything else we can help with.

Thanks!

**Comment by hillygoose** [comment]
Apologies for not getting back sooner. I am now having a struggle with corporate IT getting VS Code updated so not your issue at all.
I can confirm though that other users at my company with a more up to date version of VS Code are able to connect to their compute instances so this issue must purely be due to the version I am working with.

Thanks for you help!

**Comment by SiddhanthUnnithan** [comment]
Thanks @hillygoose! Please let us know if you run into any other issues.
