### ISSUE TITLE
Command entry point for Interactive Session K8S

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1088]
We could try to add command entry point by:
- Select subscription
- Select workspace
- Select a job that mets:
  - Running
  - K8s target
  - Jupyter endpoint
  - VSCode endpoint
 
@SiddhanthUnnithan do you think we should have this should go on 24 release?

**Comment by SiddhanthUnnithan** [comment]
@sevillal how confident are we about the signals above indicating that this is an interactive job?

I was actually thinking about this entry point the other day but what I wasn't sure of was how easy it would be for us to classify that this is an interactive job vs. a regular one.

**Comment by sevillal** [comment]
With the approach we have now, to me an interactive job for K8s can be abstracted to a job running in K8s target exposing those two endpoints (jupyter and vscode). Initially I thought we should check "sleep infinity" which is the only "special" thing that the user might include in its yaml config, but as you have tested any long running job with those endpoint can be connected with the remote experience.

The part I am still not clear is we need to join the runDetails target infor to the targets in the workspace and check if the target is k8s

**Comment by SiddhanthUnnithan** [comment]
Discussed offline. Agreed that for now we don't need to check for K8s as a target to determine whether the job is interactive. We can check for Jupyter and VS Code interaction endpoints in a Running state.
