### ISSUE TITLE
[Design Discussion] Consolidate multiple Azure sign-in prompts into a single one after extension activation

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1092]
@sevillal can help provide more context on how the backend is implemented. 

My understanding of this is that we have multiple components that make use of the Azure Account extension. If all of those components are trying to "activate" at once, then we show the Sign-in prompt many times.

The desired experience for users is to only be shown the sign-in prompt once and for those credentials to be used across all the expected components.

Tagging @hnky who ran into this issue and can help share screenshots.

**Comment by shsuman** [comment]
This requires a wider discussion as how we should handle our sign-in. Our current approach is an on-demand sign in.

E.g. Consider, we have 3 different services in the extension. All of them are prompt for sign in when they are activated (by an user action or the extension itself). This is what leads to this problem. There are a couple of things we can do to here:
- Make sign in a necessary part of extension activation. So, we prompt the user to sign in if they want to use the extension. We halt loading of all services until the user is signed in.
- Keep what we have today and if auth is in progress, don't prompt user to for another sign in.

cc @SiddhanthUnnithan @tbombach @sevillal
