### ISSUE TITLE
Automatically set a default workspace for the user if they have a single subscription-workspace pair

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1093]
If the user has a single subscription-workspace pair for their currently signed in account we should automatically set the default workspace on their behalf.

Tagging @hnky who experienced this issue.

**Comment by shsuman** [comment]
Do we update both the workspace state and the global state here ?

**Comment by shsuman** [comment]
cc @SiddhanthUnnithan

**Comment by shsuman** [comment]
https://github.com/microsoft/vscode-azureml/pull/11
