### ISSUE TITLE
List models as groups in the extension tree view

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1095]
Adding @hnky for suggesting, and @shsuman who is working on moving to MFE.

Currently we show a flat list of models in the tree view. Instead we should group models and show versions as children of the top-level node.

**Comment by shsuman** [comment]
We should cover datasets and environments as well in this issue

**Comment by SiddhanthUnnithan** [comment]
@shsuman is this grouping included as part of the MFE work you've been doing?

**Comment by shsuman** [comment]
Yes, I have added it to the New Tree View Epic :)

**Comment by SiddhanthUnnithan** [comment]
Hey @shsuman just checking if you closed because we completed this work or if we decided we can't do it?

**Comment by shsuman** [comment]
I have already completed it
