### ISSUE TITLE
[Triage] Don't attempt starting a compute instance after it has already been started.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1100]
Scenario: customer started a compute instance to connect to but was shown a message that the compute was started again (retry) after it had already succeeded.

[Info - 2021-06-22 06:25:09.340] Compute instance f1adf1aplat-juratsa1-i1 started
[Error - 2021-06-22 06:25:25.870] Start Azure ML Compute Instance is only allowed when the instance f1adf1aplat-juratsa1-i1 is in 'stopped' state

We should start the instance once and not attempt a retry.

**Comment by shsuman** [comment]
Our start logic only starts the CI once, we don't attempt a retry. Is there any specific way to repro it ?

**Comment by shsuman** [comment]
Is there a specific way to repro it ? I was trying out different scenario and none of them, we have logic that would start the CI twice.

**Comment by shsuman** [comment]
cc @SiddhanthUnnithan

**Comment by shsuman** [comment]
Resolved in Azure Machine Learning v0.6.27
