### ISSUE TITLE
Azure ML Remote extension reaches an unusual state after restarting the Compute Instance

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1102]
![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/cf9510b7-0f25-4f2b-9819-8c005eb27fad)

While in this state Python extension is unusable.

Workaround: Reload window

**Comment by sevillal** [comment]
Other findings:
- Reproducible also connecting with SSH remote extension (and Azure ML Remote installed)

**Comment by sevillal** [comment]
* Cannot repro if Azure ML and Azure ML Remote are uninstalled both in local and in the CI

**Comment by SiddhanthUnnithan** [comment]
Follow-ups:
- Test with an older version of VS Code without the workspace trust feature.
- Test with Insiders to verify if the problem is related to CI restart vs. fresh VS Code server install.

**Comment by SiddhanthUnnithan** [comment]
What do we know right now?

- Reloads are the workaround.
- Frustrating for user who restarts machine many times.

**Comment by sevillal** [comment]
1. Reproducible in insiders
2. Azure Machine Learning - Remote installed in remote target
3. If "trusted workspaces" is disabled everything works fine

### Connecting with Remote - SSH extension:
- After trusting the folder, opening a python file and trying to run it, the Python extension is not loaded (and its commands are not found)
- Following is logged in "Log (Window)"
- [2021-07-13 13:21:21.839] [renderer9] [error] Error: [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
[2021-07-13 13:21:27.207] [renderer9] [error] ENOENT: no such file or directory, access 'c:/Users/sevillal/.vscode-insiders/extensions/ms-toolsai.vscode-ai-remote-0.3.0': Error: ENOENT: no such file or directory, access 'c:/Users/sevillal/.vscode-insiders/extensions/ms-toolsai.vscode-ai-remote-0.3.0'
- Azure Machine Learning - Remote shows "Reload Required"
- ![image](https://user-images.githubusercontent.com/56176070/125520193-4012e229-03f0-49c7-bf29-a088facef58a.png)
- After reloading Python extension is loaded successfully

### Connecting with Azure Machine Learning - Remote extension
- After trusting the folder, opening a python file and trying to run it, the Python extension is not loaded (and its commands are not found)
- [2021-07-13 13:28:55.449] [renderer10] [error] ENOENT: no such file or directory, access 'c:/Users/sevillal/.vscode-insiders/extensions/ms-toolsai.vscode-ai-remote-0.3.0': Error: ENOENT: no such file or directory, access 'c:/Users/sevillal/.vscode-insiders/extensions/ms-toolsai.vscode-ai-remote-0.3.0'
- Azure Machine Learning - Remote shows "Reload Required"
- After reloading Python extension is loaded successfully

**Comment by sevillal** [comment]
Created issue https://github.com/microsoft/vscode/issues/128573

**Comment by sevillal** [comment]
Talking to Rob Lourens for any pointers on how to further debug this.

**Comment by SiddhanthUnnithan** [comment]
@sevillal was there any update from the conversation with Rob about this issue?

**Comment by SiddhanthUnnithan** [comment]
Follow-up: create issues based on Rob's suggestions and include as part of 0.6.26 release.

**Comment by sevillal** [comment]
Fixed in latest VS Code stable.
