### ISSUE TITLE
Remote python extension not enabled?

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-tools-for-ai#1103]
### Discussed in https://github.com/microsoft/vscode-python/discussions/16558

<div type='discussions-op-text'>

<sup>Originally posted by **ehrlinger** June 24, 2021</sup>
I am using the python extension connecting to an Azure Compute Instance remotely. 

python v2021.6.944021595
azure ml v0.6.23

The extension is reporting "enabled on <remote ACI>"

However, there is no way to enable a conda environment on the status bar, and my "format on save" or manually formatting report "no formatter installed".

Additionally, there is no "output->python" log. SO I don't see how to debug this.

I can see the environment when working locally.

</div>

**Comment by SiddhanthUnnithan** [comment]
Investigating as part of #1102.

**Comment by SiddhanthUnnithan** [comment]
Will move to Done once we hear back from VS Code about untrusted workspace change.

**Comment by sevillal** [comment]
Not reproducible in latest VS Code stable
