### ISSUE TITLE
Replace "(Active)" for active experiment with Tree Item Description in VSCode 1.30.0

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#115]
Tree Item Description

You can now add a description to your tree item using the description property in TreeItem. If the tree item is backed by a resource, you can also let VS Code derive the description from the resource by setting description to true.

/**
 * A human readable string which is rendered less prominently.
 * When `true`, it is derived from [resourceUri](#TreeItem.resourceUri), and when `falsy`, it is not shown.
 */
description?: string | boolean;

**Comment by greazer** [comment]
Note that we will need to gracefully handle the case where a user is not yet running 1.30.0.

**Comment by shsuman** [comment]
Can you explain a little bit more about what we are trying to achieve with this ?
