### ISSUE TITLE
Self contained remote extension

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1160]
Make the remote extension standalone, covering the following objective:

Remote extension will allow connection to any remote target that has a jupyter endpoint exposed (used to install dependencies) and a exposed port(s) for vscode communication. 
How to abstract authorization in the previous objective statement?

Design summary:
1. Remote extension does not depend on other extensions 
2. Remote extension handles one URI entry point
3. Remote extension has a well defined structure of the parameters the URI handler can receive (Jupyter URL, websocket port, telemetry identifiers, sessions, remote target name, remote target type, etc)
4. Remote extension can handle remote authorization

**Comment by shsuman** [comment]
I think this is covered under the Basis investigation that sevillal is doing
