### ISSUE TITLE
[Triage] Connection error - frequently getting disconnected

### ISSUE THREAD

**Issue by bkuriach** [microsoft/vscode-tools-for-ai#1167]
Issue Type: <b>Bug</b>

[Error - 2021-07-14 07:12:02.206] Failed to forward incoming connection to remote server: Unexpected server response: 401

Extension version: 0.4.0
VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1051-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (2.76GB free)|
|Process Argv|--open-url --crash-reporter-id bb5a6bf5-d714-48a5-9eba-811de0544190 -- vscode://ms-toolsai.vscode-ai/computeInstance/remote?computeId=/subscriptions/da9091ec-d18f-456c-9c21-5783ee7f4645/resourceGroups/bkuriachan-rg/providers/Microsoft.MachineLearningServices/workspaces/crop-classification-aml/computes/crop-classification-cpu&sessionId=cKUKn|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Azure ML: crop-classification-cpu|
|OS|Linux x64 5.4.0-1051-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (4 x 2095)|
|Memory (System)|27.43GB (21.50GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vspre833:30321513
vshan820:30294714
vscus158:30321503
vscod805cf:30301675
bridge0708:30335490

```

</details>

**Comment by SiddhanthUnnithan** [comment]
Hey @bkuriach! Thanks for filing this issue -- I'm curious whether you can help share the following:
1. How old is the compute instance you're using?
2. How often do you run into this issue?
3. Do you find that you run into the issue after a certain period of time (e.g., after being connected for 1 - 2 hours)?
4. What do you usually do to resolve this issue?

**Comment by bkuriach** [comment]
Hey Sid,

Please find my response inline.

1. How old is the compute instance you're using? - *Its a new AML compute
and was restarted daily*
2. How often do you run into this issue? - *whenever vscode is idle
for some time* (30 mins)
3. Do you find that you run into the issue after a certain period of time
(e.g., after being connected for 1 - 2 hours)?* ~ 30 mins - 1 hour*
4. What do you usually do to resolve this issue?* reconnect to compute*

*Regards,*
*Binil Kuriachan*

**Comment by bkuriach** [comment]
![image](https://user-images.githubusercontent.com/65594418/125773506-567719c2-9754-4c73-b973-a5b54b55816f.png)

**Comment by bkuriach** [comment]
Hello,

I was using VSCode and in the meanwhile start getting this error. Its occurring very frequently.

***@***.***D77A3D.8BDCDC20]


Regards,
Binil Kuriachan

From: Binil Kuriachan ***@***.***>
Sent: Thursday, July 15, 2021 2:56 PM
To: microsoft/vscode-tools-for-ai ***@***.***>; Binil Kuriachan ***@***.***>
Cc: microsoft/vscode-tools-for-ai ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/vscode-tools-for-ai] Connection error - frequently getting disconnected (#1167)

Hey Sid,

Please find my response inline.

1. How old is the compute instance you're using? - Its a new AML compute and was restarted daily
2. How often do you run into this issue? - whenever vscode is idle for some time (30 mins)
3. Do you find that you run into the issue after a certain period of time (e.g., after being connected for 1 - 2 hours)? ~ 30 mins - 1 hour
4. What do you usually do to resolve this issue? reconnect to compute

Regards,
Binil Kuriachan


On Thu, Jul 15, 2021 at 3:38 AM Sid Unnithan ***@***.******@***.***>> wrote:

Hey @bkuriach<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2F%2Fgithub.com%2Fbkuriach__%3B!!IKRxdwAv5BmarQ!OltJSRv6SBgawnbguN5kjEQYSVVpWTphcApLm47OYpMBrgdupPTy_HkFXQ_K0hY%24&data=04%7C01%7Cbkuriachan%40microsoft.com%7Cf099f9068ec140a976b508d94772a54d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637619380018668784%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gAoB%2FjexRKeFBjx8SvN%2FmGiFUy5D0s3lXmBxKL0cm1c%3D&reserved=0>! Thanks for filing this issue -- I'm curious whether you can help share the following:

  1.  How old is the compute instance you're using?
  2.  How often do you run into this issue?
  3.  Do you find that you run into the issue after a certain period of time (e.g., after being connected for 1 - 2 hours)?
  4.  What do you usually do to resolve this issue?

-

**Comment by SiddhanthUnnithan** [comment]
Hi @bkuriach. Sorry for getting back to you so late -- I have been out of the office for the past few days.

Thank you for providing answers to the questions I had posed earlier. Some follow-ups:

1. Why is your compute instance restarted daily?
2. What steps do you take to reconnect to the compute? Have you tried reloading the window after the connection fails?

**Comment by bkuriach** [comment]
1. Why is your compute instance restarted daily? - When I am not using it, I would not want to keep it running and increase the cost. By this question, did you mean something else?
2. What steps do you take to reconnect to the compute? Have you tried reloading the window after the connection fails? - Yes. I end up reconnect from the AML (VSCODE) itself. Its really inconvenient 

![image](https://user-images.githubusercontent.com/65594418/128465198-60bac5f0-5674-4f82-9b76-5e77fe406629.png)

**Comment by sevillal** [comment]
@bkuriach We have released a new version of the "Azure Machine Learning - Remote" extension that fixes this. https://github.com/microsoft/vscode-tools-for-ai/issues/1285

I will close this issue for now, please feel free to reach our or reopen the issue if you keep seeing it.
