### ISSUE TITLE
Migrate to strict mode

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1171]
Dup of https://github.com/microsoft/vscode-tools-for-ai/issues/113
Depends on output from : https://github.com/microsoft/vscode-tools-for-ai/issues/682

With the refactor work done it could be a good time to move to strict mode at least in a gradual mode:

Options:
- Tsconfig files for dev and build (dev with strict mode enabled)
- ts-strictify
- Turning on individual flags

**Comment by shsuman** [comment]
We have now enabled strict mode for V2 using the [typescript-strict-plugin](https://github.com/allegro/typescript-strict-plugin). It is not enforced at compilation but it shows errors in VSCode IDE and it provides a script which checks for any strict mode errors in the v2 folder. I have added a new check  in our pipeline (npm run typecheck) to ensure nothing gets passed without adhering to strict mode in V2 folder.
