### ISSUE TITLE
[Triage] VS Code cannot connect to compute instances in Azure Machine Learning

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1173]
Track this SO post: https://stackoverflow.com/questions/68485660/vs-code-cannot-connect-to-computer-instances-in-azure-machine-learning

Gist:
- Trying to connect to compute instances from within VS Code.
- Jupyter server terminal hangs and is unresponsive after some connections are initiated from VS Code.
- Studio notebooks works as expected because no reliance on the terminal.

**Comment by shsuman** [comment]
Closing as there has been no response from the user.

**Comment by sevillal** [comment]
Emailed customer to upgrade the extension and retry remote connection.

**Comment by shsuman** [comment]
Closing this as we have shipped the fix and has got no response from the customer for over 7 days.
