### ISSUE TITLE
[Problem] Executing bash in Jupyter Terminal hangs jupyter server and failed subsequent connections

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1174]
- Tries to connect to VS Code compute instances from Studio UI
- Subsequent connection is attempted but fails because Terminal is unresponsive, thus VS Code and websocket servers cannot be installed
- User is prompted to restart their compute instance to re-create the Terminal

**Comment by shsuman** [comment]
I am not able to repro it. Is there a way to repro it ?

**Comment by shsuman** [comment]
I have contacted Yutong Tie, she is the customer engineer who responded to the customer on Docs where the issue has been opened, to see if we could meet the customer.

**Comment by SiddhanthUnnithan** [comment]
Followed up with the user about the issue. Hoping to meet over the next few days.

**Comment by shsuman** [comment]
Closing as there has been no response from the user.

**Comment by sevillal** [comment]
Stress test result:
1. Run command back to back against jupyter server started by the CI
- Result: It fails randomly after ~10 cycles

2. Start a jupyter server manually on the same CI and run the command against it
- Result: It does not hang the server (tested up to 400 times)

With the above results we think the problem might be the Jupyter server instance, we  have open an IcM 264249032 for CI team to help us triage.

**Comment by sevillal** [comment]
@shsuman  https://portal.microsofticm.com/imp/v3/incidents/details/264249032/home

**Comment by foxale** [comment]
We get this a lot. Opening CI, then running random cells inside AzureML built-in Jupyter notebook (which activates kernel) and only then switching to VSCode with "Edit in VS Code" button helps to mitigate this issue most of the time, but not always. I'm up for a contact anytime if it helps.

**Comment by foxale** [comment]
> @foxale Thanks for sharing info about the issue. I have some questions:
> 
> * Are you having issues when you use the "Edit in VS Code" button? If so, what issues are you experiencing?

Correct. A new VSCode window opens and tries to set up VSCode <-> AzureML compute instance connection but is quickly stuck forever on the _"Installing VS Code server on <compute-instance-name> Retry - <n>"_ prompt:

![image](https://user-images.githubusercontent.com/14327763/137779501-f7b17933-0724-4108-a841-2137599fe7b0.png)

What's interesting is that in our case it occurs:

- always, or almost always when we try connecting directly from VSCode AzureML extension to a stopped compute instance
- always, or almost always when we use "Edit in VS Code" button on freshly started instance but "No kernel" attached
- almost never when we first run any cell in any jupyter notebook (which forces the kernel to be attached) and then use "Edit in VS Code" button

**Comment by sevillal** [comment]
@foxale we have released version 0.0.6 of Azure Machine Learning - Remote extension which contains a fix to ensure the connection, could you please upgrade your extension and retry the connection to the CI? Let us know if you find any issue. Thanks!

**Comment by shsuman** [comment]
Closing this as we have shipped the fix and there has been no response for over 7 days.

**Comment by foxale** [comment]
We tested in for the past 7 days and can confirm that the issue is gone :) Thanks!
