### ISSUE TITLE
[DRI-Lite] All Items for week of 7/19

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1175]

**Comment by shsuman** [comment]
Summary Report

Week: July 19th, 2021

\# of Issues: 3

Impacted Customers:
1.	Canada Life – Srini Gajjela as a support engineer proxy.
2.	Daimler.
3.	Internal – Binil Kuriachan.
4.	[Unknown] – Lu.

Issues Triaged:
1. Connection Error – frequently getting disconnected. [Internal]
2. Reconnection after remote session has been open for a while. [Daimler]
3. VS Code cannot connect to compute instances in Azure Machine Learning. [External]

Issues Fixed:
None

Open Items:
[Problem] VS Code connection causes Jupyter terminal hang and failed subsequent connections · microsoft/vscode-tools-for-ai (zenhub.com)
-	Need to understand why the Jupyter terminal hangs; only time we use the Jupyter terminal is for script execution and server install
-	Need to understand whether we are responsible for the hang or if another service (AzNb) can cause it
-	Possible follow-up: speak to the compute instance team about an alternate way to execute shell commands against a compute instance (e.g., reliable API owned by the compute instance team).

Reconnection mitigation · microsoft/vscode-tools-for-ai (zenhub.com)
-	Possible mitigation approaches are listed in the issue
