### ISSUE TITLE
Try to use Azure Account extension while making a remote connection

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1180]
We would have to build the Azure Account extension with [workspace, ui] as their extensionKind and then see if that is available in the ui context

**Comment by SiddhanthUnnithan** [comment]
@shsuman tried this. No extension APIs are available when executing the resolver. The conclusion here is that we can't add Azure Account as a dependency to our remote extension.

Follow up with VS Code core about extension APIs being available in the remote resolver.
