### ISSUE TITLE
Create a distribution list for vscai customer support

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1182]
How does vscai-cs@microsoft.com sound ?

**Comment by SiddhanthUnnithan** [comment]
![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/2c71670c-8483-4811-a559-4e85bbeb25ab)

Will send a test/validation mail.

**Comment by SiddhanthUnnithan** [comment]
Created a new DG -- vscai-support@microsoft.com. Will move this to Done once I can send a test/validation mail to the group. I suspect that it will take a few hours before it is up and running.

**Comment by SiddhanthUnnithan** [comment]
Sent test mail and validated.
