### ISSUE TITLE
[DRI-Lite] All Items for week of 7/26

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1188]

**Comment by shsuman** [comment]
Summary Report

Week: July 26th, 2021

# of Issues: 3

Impacted Customers:
1.	Wolfgang Pauli

Issues Triaged:
1.	Debug file opened twice on remote CI [Internal]

Issues Fixed:
None

Open Items:
[Problem] VS Code connection causes Jupyter terminal hang and failed subsequent connections · microsoft/vscode-tools-for-ai (zenhub.com)
-	Need to understand why the Jupyter terminal hangs; only time we use the Jupyter terminal is for script execution and server install
-	Need to understand whether we are responsible for the hang or if another service (AzNb) can cause it
-	Possible follow-up: speak to the compute instance team about an alternate way to execute shell commands against a compute instance (e.g., reliable API owned by the compute instance team).

Reconnection mitigation · microsoft/vscode-tools-for-ai (zenhub.com)
-	Possible mitigation approaches are listed in the issue

[Triage] When debugging on remote CI file with breakpoints is opened twice pointing to different locations
-	Customer using the latest versions of the extension, connection to remote working fine.
-	Not easy to repro for the customer, seems to be related on how long the connection has been open. 
-	Next steps: Try to repro on one of our CI’s.
