### ISSUE TITLE
Getting account list failed...

### ISSUE THREAD

**Issue by xuehui1991** [Microsoft/vscode-tools-for-ai#12]
I install Azure Machine Learning Workbench and go to find "ML Sample", but when I install I receive as follow:

![image](https://user-images.githubusercontent.com/6280746/31492358-3f74ca2a-af7d-11e7-8c1f-4ccd14348cc6.png)

---------------------------------------------------------------------------------------------------------------

=== Create Project From Gallery ===
Please input the project name
Please input the project installation folder
Getting account list....
Create project from gallery failed, error=Error: Can not get existing accounts, please create one account and try later.

---------------------------------------------------------------------------------------------------------------

I already login, anyone could give me some suggestion?

Thank you !

**Comment by visionalsky** [comment]
Hi Xuehui1991, could you check: 1. you have selected the correct subscriptions. (you can use select subscription command in vs code to do it) 2. you have a valid azure ml accounts created. (you can reference this https://docs.microsoft.com/en-us/azure/machine-learning/preview/quickstart-installation )

Thank you.

**Comment by qfyin** [comment]
Caused by user's subscription setting.
