### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by clerval** [Microsoft/vscode-tools-for-ai#121]
- Issue Type: `Performance`
- Extension Name: `vscode-ai`
- Extension Version: `0.4.0`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/armando/ms-toolsai.vscode-ai-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load
[ms-toolsai.vscode-ai-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-tools-for-ai/files/2703706/ms-toolsai.vscode-ai-unresponsive.cpuprofile.txt)

**Comment by greazer** [comment]
Needed more info.
