### ISSUE TITLE
[Triage] Frequent disconnection while working itself

### ISSUE THREAD

**Issue by bkuriach** [microsoft/vscode-tools-for-ai#1212]
Issue Type: <b>Bug</b>

VSCODE is gettign disconnected from compute frequently while working (not idle). 
[Error - 2021-08-10 06:13:04.303] Websocket 38 error sending data: Error: WebSocket is not open: readyState 3 (CLOSED)

Extension version: 0.6.24
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1051-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.18GB free)|
|Process Argv|--open-url --crash-reporter-id bb5a6bf5-d714-48a5-9eba-811de0544190 -- vscode://ms-toolsai.vscode-ai/computeInstance/remote?computeId=/subscriptions/da9091ec-d18f-456c-9c21-5783ee7f4645/resourceGroups/bkuriachan-rg/providers/Microsoft.MachineLearningServices/workspaces/crop-classification-aml/computes/crop-classification-bk&sessionId=0FEl4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Azure ML: crop-classification-bk|
|OS|Linux x64 5.4.0-1051-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (16 x 2397)|
|Memory (System)|110.16GB (99.64GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
dockerwalkthru:30344881
bridge0723cf:30346311

```

</details>

**Comment by bkuriach** [comment]
![image](https://user-images.githubusercontent.com/65594418/128817487-907bbacc-203b-4022-8468-4fded7f06f3d.png)

**Comment by bkuriach** [comment]
Compute is still working and I am able to continue with JupyterLab

**Comment by tbombach** [comment]
Hi @bkuriach! Thanks for filing this. It seems like it's related (but different) from the other issue you filed: https://github.com/microsoft/vscode-tools-for-ai/issues/1167 since this is happening when you're actively using it now. Our apologies for the inconvenience and we'll try to get to the bottom of it.

Do you see this occur more with certain network conditions? (e.g. wifi)

**Comment by shsuman** [comment]
Closing this issue because it hasn't seen any activity in the last 14 days. Please comment on it, if you would like this to be reopened :).
