### ISSUE TITLE
[Triage] Websocket errors on AML compute instance

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1234]
https://github.com/microsoft/vscode/issues/130374

Tagging @YnnamTenob and @eduedix for relevance.

VS Code connection becomes unstable immediately.

What do we need to help triage?
1. All the logs in the "Output" tab of the Remote Window created.
2. Logs from the compute instance itself. You can access the terminal via Jupyter or the Studio and copy the logs from /home/azureuser/.vscode-server/<vscode_commit_id>.log and /home/azureuser/.azureml_remote_websocket_server/.stable/<vscode_commit_id>.log. You can get the VS Code commit ID by clicking on "Help" => "About" in your local VS Code window.
3. Is the disconnect happening immediately? What is the flow you're going through to reproduce the issue? Is this being seen through all the entry points (Compute and Notebook page)?
4. Do you have any special network configurations that we should be aware of? VNET + private link?

@ynnamtenob and @eduedix if you could provide answers and logs to the above points, that would be great. We may follow up with you over the next few days if we need further information.

**Comment by YnnamTenob** [comment]
This has gotten so bad that I have to kill VSCod every 20 minutes to try and get anything done. Needless to say I'm not getting much of anything done. I have no choice but to try and figure out your problem so maybe I can get back to work. Note VSCode becomes unusable halting my worklfow everytime it senses mouse movement or carriage return

The disconnect time is not immediate but constant. a few minutes after startign to type in the editor the memory spikes in VSCode and the UI becomes unusable.

The issue happens through any entry point.

Network: nothing special not connected to VPN. Cisco AMP Orbital, Cisco AMP for Endpoints and Cisco Security Connector running.

Remote Log files: copied and pasted below

 
******************************** Output Window Logs **********************************
[Info - 2021-08-24 18:11:35.820] Using commit id "3866c3553be8b268c8a7f8c0482c0c0177aa8bfa" and quality "stable" for server
[Info - 2021-08-24 18:11:48.015] ea874096-d9aa-43ec-86e5-c7c048b3aced: running
Acquiring lock on /home/azureuser/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/vscode-remote-lock.azureuser.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Found old VS Code install b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, attempting to clean up
Deleting old install from /home/azureuser/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Deleting old log file from /home/azureuser/.vscode-server/.b4c1bd0a9b03c749ea011b06c6d2676c8091a70c.log
Installing to /home/azureuser/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa...
ea874096-d9aa-43ec-86e5-c7c048b3aced%%1%%
Downloading with wget
Download complete
ea874096-d9aa-43ec-86e5-c7c048b3aced%%2%%
tar --version:
tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
Installing extensions...
Installing extensions...
Extension 'ms-vscode.azure-account' is already installed.
Updating the extension 'ms-toolsai.jupyter' to the version 2021.8.2031161920
Installing extension 'ms-toolsai.jupyter'...
Extension 'ms-python.vscode-pylance' is already installed.
Extension 'ms-toolsai.vscode-ai-remote' is already installed.
Extension 'ms-toolsai.vscode-ai' is already installed.
Extension 'ms-python.python' is already installed.
Extension 'ms-toolsai.jupyter' v2021.8.2031161920 was successfully installed.
Checking /home/azureuser/.vscode-server/.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa.log and /home/azureuser/.vscode-server/.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa.pid for a running server
Starting server with command... /home/azureuser/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/azureuser/.vscode-server/.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa.log" < /dev/null
printenv:
    CONDA_SHLVL=1
    MSI_ENDPOINT=http://127.0.1.1:46808/MSI/auth
    LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/mic/lib::/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/
    LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
    CONDA_EXE=/anaconda/bin/conda
    JUPYTER_SERVER_ROOT=/mnt/batch/tasks/shared/LS_root/mounts/clusters/cpu-ds3-v2-tenob-m/code
    LESSCLOSE=/usr/bin/lesspipe %s %s
    LANG=C.UTF-8
    AZURE_EXTENSION_DIR=/opt/az/extensions
    INVOCATION_ID=e86be24d933a43dda4d075a9fc8335d4
    CI_RESOURCE_GROUP=ax-ae1-dv-idc-mlshared-rg
    NODE_PATH=/usr/lib/node_modules
    JUPYTER_SERVER_URL=http://localhost:8888/
    CONDA_PREFIX=/anaconda/envs/azureml_py38
    _CE_M=
    CLASSPATH=/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/lib/mpi.jar
    USER=azureuser
    AML_CloudName=AzureCloud
    CI_WORKSPACE=ax-ae1-dv-mlworkspace-test
    MKL_THREADING_LAYER=GNU
    PWD=/mnt/batch/tasks/shared/LS_root/mounts/clusters/cpu-ds3-v2-tenob-m/code
    LINES=1000
    HOME=/home/azureuser
    CONDA_PYTHON_EXE=/anaconda/bin/python
    JOURNAL_STREAM=9:32104
    CUPIT_LIB_PATH=/usr/local/cuda/extras/CUPTI/lib64/
    XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
    DEFAULT_IDENTITY_CLIENT_ID=clientid
    _CE_CONDA=
    APPSETTING_WEBSITE_SITE_NAME=AMLComputeInstance
    CUDA_ROOT=/usr/local/cuda
    LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/:
    CONDA_PROMPT_MODIFIER=(azureml_py38) 
    COLUMNS=1000
    CI_NAME=cpu-ds3-v2-tenob-m
    SHELL=/bin/bash
    TERM=xterm
    MSI_SECRET=7BfVf0VrpITj8afsIPa1
    PYXTERM_DIMENSIONS=80x25
    SHLVL=2
    CI_LOCAL_UBUNTU_USER=azureuser
    MANPATH=/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/man:/anaconda/envs/azureml_py38/man:/anaconda/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
    VSCODE_AGENT_FOLDER=/home/azureuser/.vscode-server
    LOGNAME=azureuser
    PATH=/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/bin:/anaconda/envs/azureml_py38/bin:/anaconda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/azureuser/.dotnet/tools:/usr/local/cuda/bin:/home/azureuser/.dotnet/tools
    CONDA_DEFAULT_ENV=azureml_py38
    I_MPI_ROOT=/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi
    LESSOPEN=| /usr/bin/lesspipe %s
    _=/usr/bin/printenv
    OLDPWD=/home/azureuser/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Spawned remote server: 3675
Waiting for server log...
 
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*
 
ea874096-d9aa-43ec-86e5-c7c048b3aced: start
listeningOn==33551==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/tmp==
platform==linux==
ea874096-d9aa-43ec-86e5-c7c048b3aced: end
[Info - 2021-08-24 18:11:48.017] VSCode server listening on: 33551
[Info - 2021-08-24 18:11:54.221] 7d20f96b-0a24-4dd1-9eb3-99e37849e24a: running
Acquiring lock on /home/azureuser/.azureml_remote_websocket_server/bin/v0.2/vscode-remote-lock.azureuser.v0.2
No v0.1 websocket server running
Found existing installation at /home/azureuser/.azureml_remote_websocket_server/bin/v0.2...
Checking /home/azureuser/.azureml_remote_websocket_server/.stable.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa.v0.2.log and /home/azureuser/.azureml_remote_websocket_server/.stable.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa.v0.2.pid for a running server
Starting server with command... /home/azureuser/.azureml_remote_websocket_server/bin/v0.2/server.sh --port=0 --vscode-server-port=33551 --commit=3866c3553be8b268c8a7f8c0482c0c0177aa8bfa &> "/home/azureuser/.azureml_remote_websocket_server/.stable.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa.v0.2.log" < /dev/null
printenv:
    CONDA_SHLVL=1
    MSI_ENDPOINT=http://127.0.1.1:46808/MSI/auth
    LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/mic/lib::/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/
    LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
    CONDA_EXE=/anaconda/bin/conda
    JUPYTER_SERVER_ROOT=/mnt/batch/tasks/shared/LS_root/mounts/clusters/cpu-ds3-v2-tenob-m/code
    LESSCLOSE=/usr/bin/lesspipe %s %s
    LANG=C.UTF-8
    AZURE_EXTENSION_DIR=/opt/az/extensions
    INVOCATION_ID=e86be24d933a43dda4d075a9fc8335d4
    CI_RESOURCE_GROUP=ax-ae1-dv-idc-mlshared-rg
    NODE_PATH=/usr/lib/node_modules
    JUPYTER_SERVER_URL=http://localhost:8888/
    CONDA_PREFIX=/anaconda/envs/azureml_py38
    _CE_M=
    CLASSPATH=/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/lib/mpi.jar
    USER=azureuser
    AML_CloudName=AzureCloud
    CI_WORKSPACE=ax-ae1-dv-mlworkspace-test
    MKL_THREADING_LAYER=GNU
    PWD=/mnt/batch/tasks/shared/LS_root/mounts/clusters/cpu-ds3-v2-tenob-m/code
    LINES=1000
    HOME=/home/azureuser
    CONDA_PYTHON_EXE=/anaconda/bin/python
    JOURNAL_STREAM=9:32104
    CUPIT_LIB_PATH=/usr/local/cuda/extras/CUPTI/lib64/
    XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
    DEFAULT_IDENTITY_CLIENT_ID=clientid
    _CE_CONDA=
    APPSETTING_WEBSITE_SITE_NAME=AMLComputeInstance
    CUDA_ROOT=/usr/local/cuda
    LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/:
    CONDA_PROMPT_MODIFIER=(azureml_py38) 
    COLUMNS=1000
    CI_NAME=cpu-ds3-v2-tenob-m
    SHELL=/bin/bash
    TERM=xterm
    MSI_SECRET=7BfVf0VrpITj8afsIPa1
    PYXTERM_DIMENSIONS=80x25
    SHLVL=2
    CI_LOCAL_UBUNTU_USER=azureuser
    MANPATH=/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/man:/anaconda/envs/azureml_py38/man:/anaconda/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
    VSCODE_AGENT_FOLDER=/home/azureuser/.azureml_remote_websocket_server
    LOGNAME=azureuser
    PATH=/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/bin:/anaconda/envs/azureml_py38/bin:/anaconda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/azureuser/.dotnet/tools:/usr/local/cuda/bin:/home/azureuser/.dotnet/tools
    CONDA_DEFAULT_ENV=azureml_py38
    I_MPI_ROOT=/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi
    LESSOPEN=| /usr/bin/lesspipe %s
    _=/usr/bin/printenv
Spawned remote server: 3893
Waiting for server log...
Waiting for server log...
Waiting for server log...
7d20f96b-0a24-4dd1-9eb3-99e37849e24a: start
listeningOn==8890==
osReleaseId==ubuntu==
arch==x86_64==
platform==linux==
downloadTime====
installTime====
serverStartTime==109==
7d20f96b-0a24-4dd1-9eb3-99e37849e24a: end
[Info - 2021-08-24 18:11:54.221] Websocket server listening on: 8890
[Info - 2021-08-24 18:11:54.222] VSCode url: cpu-ds3-v2-tenob-m-8890.eastus.instances.azureml.ms/ws
[Error - 2021-08-24 18:15:53.839] Websocket 8 error sending data: Error: WebSocket is not open: readyState 3 (CLOSED)

************************************* .3866c3553be8b268c8a7f8c0482c0c0177aa8bfa.log *************************
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 33551

[18:11:47] Extension host agent started.
[18:11:54] [127.0.0.1][046436fd][ManagementConnection] New connection established.
[18:11:55] [127.0.0.1][8240f208][ExtensionHostConnection] New connection established.
[18:11:55] [127.0.0.1][8240f208][ExtensionHostConnection] <3967> Launched Extension Host Process.
[18:11:55] [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
[18:12:21] [127.0.0.1][8240f208][ExtensionHostConnection] The client has reconnected.
[18:12:43] [127.0.0.1][8240f208][ExtensionHostConnection] The client has reconnected.
[18:15:10] [127.0.0.1][8240f208][ExtensionHostConnection] The client has reconnected.
[18:15:31] [127.0.0.1][8240f208][ExtensionHostConnection] The client has reconnected.
[18:15:53] [127.0.0.1][8240f208][ExtensionHostConnection] The client has reconnected.
[18:16:14] [127.0.0.1][8240f208][ExtensionHostConnection] The client has reconnected.
[18:16:34] [127.0.0.1][8240f208][ExtensionHostConnection] The client has reconnected.
[18:16:55] [127.0.0.1][8240f208][ExtensionHostConnection] The client has reconnected.
[18:17:16] [127.0.0.1][8240f208][ExtensionHostConnection] The client has reconnected.
[18:17:37] [127.0.0.1][8240f208][ExtensionHostConnection] The client has reconnected.
[18:17:57] [127.0.0.1][8240f208][ExtensionHostConnection] The client has reconnected.

************************************************** .stable.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa.v0.2.log 
(azureml_py38) azureuser@cpu-ds3-v2-tenob-m:~/.azureml_remote_websocket_server$ cat .stable.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa.v0.2.log
Azure ML websocket server listening on 8890


[18:11:53] Azure ML websocket server started
[18:11:54] Websocket 0 connected.
[18:11:54] Socket 0 connected.
[18:11:54] Websocket 1 connected.
[18:11:54] Socket 1 connected.
[18:11:56] Websocket 2 connected.
[18:11:56] Socket 2 connected.
[18:11:56] Websocket 3 connected.
[18:11:57] Socket 3 connected.
[18:12:01] Socket 2 closed, had_error = false.
[18:12:01] Connection 2 closed. Active connections: 3
[18:12:21] Websocket 4 connected.
[18:12:21] Socket 4 connected.
[18:12:29] Socket 1 closed, had_error = false.
[18:12:29] Connection 1 closed. Active connections: 3
[18:12:40] Websocket 5 connected.
[18:12:40] Socket 5 connected.
[18:12:43] Websocket 6 connected.
[18:12:43] Socket 6 connected.
[18:12:43] Socket 4 closed, had_error = false.
[18:12:43] Connection 4 closed. Active connections: 4
[18:12:45] Socket 3 closed, had_error = false.
[18:12:45] Connection 3 closed. Active connections: 3
[18:12:45] Socket 5 closed, had_error = false.
[18:12:45] Connection 5 closed. Active connections: 2
[18:15:10] Websocket 7 connected.
[18:15:10] Socket 7 connected.
[18:15:10] Socket 6 closed, had_error = false.
[18:15:10] Connection 6 closed. Active connections: 2
[18:15:30] Websocket 8 connected.
[18:15:30] Socket 8 connected.
[18:15:38] Socket 7 closed, had_error = false.
[18:15:38] Connection 7 closed. Active connections: 2
[18:15:51] Websocket 9 connected.
[18:15:51] Socket 9 connected.
[18:15:53] Socket 8 closed, had_error = false.
[18:15:53] Connection 8 closed. Active connections: 2
[18:16:14] Websocket 10 connected.
[18:16:14] Socket 10 connected.
[18:16:20] Socket 9 closed, had_error = false.
[18:16:20] Connection 9 closed. Active connections: 2
[18:16:34] Websocket 11 connected.
[18:16:34] Socket 11 connected.
[18:16:34] Socket 10 closed, had_error = false.
[18:16:34] Connection 10 closed. Active connections: 2
[18:16:55] Websocket 12 connected.
[18:16:55] Socket 12 connected.
[18:17:01] Socket 11 closed, had_error = false.
[18:17:01] Connection 11 closed. Active connections: 2
[18:17:16] Websocket 13 connected.
[18:17:16] Socket 13 connected.
[18:17:16] Socket 12 closed, had_error = false.
[18:17:16] Connection 12 closed. Active connections: 2
[18:17:36] Websocket 14 connected.
[18:17:36] Socket 14 connected.
[18:17:42] Socket 13 closed, had_error = false.
[18:17:42] Connection 13 closed. Active connections: 2
[18:17:57] Websocket 15 connected.
[18:17:57] Socket 15 connected.
[18:17:57] Socket 14 closed, had_error = false.
[18:17:57] Connection 14 closed. Active connections: 2

**Comment by shsuman** [comment]
Refer to ongoing discussion in [microsoft/vscode#130374](https://github.com/microsoft/vscode/issues/130374)

**Comment by sevillal** [comment]
@YnnamTenob sorry for the late response and thanks for sharing all those details. 

From the logs it seems like the file watcher is reaching its limit, can you try adding a pattern to "Text Editor" > "Files" > "Watcher Exclude" setting to exclude some folder or files from the watcher? 
![image](https://user-images.githubusercontent.com/56176070/133335982-b9066124-1dec-4ddd-a3de-a2d8e24f1db3.png)

If you are open to it I can setup a quick call for us to walk through and diagnose the issue.

**Comment by eduedix** [comment]
@sevillal I just checked my settings and saw that the "Watcher Exclude" patterns were same as in your attachment above.

Also I have a stable connection now and after testing for a few days I will let you know if I still have the problem with Websocket connections.

**Comment by sevillal** [comment]
@YnnamTenob following up here, are you still running into issues with the connection?

**Comment by eduedix** [comment]
@sevillal I am unsure if this is the right place to talk about it though I had some connection issues probably due to sleep mode or similar and had to reload the window and rerun cells in the jupyter notebook, which I find a bit inconvenient. Do you know if the jupyter kernel starts in the background as a separate process so that it would not be influenced by the disconnections?

**Comment by shsuman** [comment]
Hey @eduedix, 
The kernel and the VSCode server runs in separate process. Moreover, the kernel is managed by the Jupyter extension and the remote connection is managed by Azure ML - Remote extension. 

I am closing this issue for now. Can you please open a separate issue regarding the last problem you described and provide some more details please ? :)
