### ISSUE TITLE
deployment.scaleSettings.scaleType's value in Managed Online Endpoint template does not adheres to its schema

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1242]
![image.png](https://images.zenhubusercontent.com/5c1828cfc50615756d6b3d5a/8bdc97ca-72b4-490e-87d4-beb9dbd1835e)

**Comment by SiddhanthUnnithan** [comment]
@shsuman did we get a chance to reach out to Brandon H. about this fix?

**Comment by shsuman** [comment]
No response from Brandon. Pinged him again

**Comment by shsuman** [comment]
Response from Brandon:

found the issue, someone added that it should be capitalized. This goes against the format of all our other strings in yaml, so I'm not sure why this was done.
I'm making the change for the october contract, where the scale type is "default" not "manual"

**Comment by shsuman** [comment]
The template has changed and this field no longer exists in the template
