### ISSUE TITLE
Design our URI handler so that we can keep adding support for URIs (paths) without having to modify the URI handler itself

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1251]

**Comment by shsuman** [comment]
Couple of approaches we could do: - Expose a register method in the URI handler so that all the clients can register themselves - Use inversify to do the same thing like we did in the v2/ExtensionActivationService

**Comment by SiddhanthUnnithan** [comment]
Do we think there are other URI paths we expect to register in the future?

Does the interactive job path support any compute type or is it specific to K8s?

**Comment by SiddhanthUnnithan** [comment]
Handling two URIs today: compute instance connection, interactive job.

Interactive job path inputs: Jupyter endpoint and port that we want to run the websocket server on.

**Comment by SiddhanthUnnithan** [comment]
Keeping this issue in the Parking Lot for now. The next time we want to add a new URI for a browser click-out experience, we will include this work as part of it.
