### ISSUE TITLE
A11y_AzureMachineLearningExtension_DataSets_ScreenReader: NVDA/Narrator is not reading resource/workspace name when focus lands on them.

### ISSUE THREAD

**Issue by NiharikaTipirishetty** [microsoft/vscode-tools-for-ai#1261]
**Github Tags:**
#A11yMAS;#A11yTCS;#WCAG1.3.1;#ScreenReader;#Narrator;#NVDA;#Win32;#DesktopApp;#A11ySev2;#SH-AzureMachineLearningExtension-Win32-Aug2021;#Development and Test Resources for VS and VSCode AI Tools;

### Environment Details:
Visual Studio Code

### Repro Steps:

1. Turn on Narrator/NVDA
2. Hit the Azure Machine Learning Studio URL and sign in with appropriate credentials.
2. Tab till Notebooks in the left pane and press enter. Select any file from the pane, tab till "Edit in VS code "option in command bar and press enter.
3. A pop up will appears on the screen to open VS Code app, tab till 'Open' button and press enter
4. Tab till Azure in the left pane and press enter, tab till any subscription ex: ML.Net Model Builder Demo and press enter.
5. Tab till any workspace ex: Basic Workspace or a resource ex: Experiment/Model/Dataset under the subscription
6. Verify whether screen reader reads its name when focus lands on them.

### Actual Result:
NVDA/Narrator is not reading resource/workspace name when focus lands on them. NVDA/Narrator reads description about the workspace/resource but the name is not read.

### Expected Result:
NVDA/Narrator should read resource/workspace name when focus lands on them. NVDA/Narrator should first read workspace/resource name and then should read description about the workspace/resource.
Ex: Basic Workspace The worskpace is top level etc

### User Impact:
Screen reader users will not clearly understand the info if workspace name is not read.

**Comment by tbombach** [comment]
Similar to #1263, we need to set AccessibilityInfo for the TreeNode. This will allow us to set the string that gets read out, because currently it has a generic message about workspaces/resources: "The workspace is top level etc" instead of the name of the workspace
