### ISSUE TITLE
UNIX [No such file or directory] error when connecting to instance from VSCode

### ISSUE THREAD

**Issue by Servot** [microsoft/vscode-tools-for-ai#1265]
## Expected Behavior
Connecting to  a running compute instance with the `Azure ML: Connect to Compute Instance` command

## Actual Behavior
The following error in the `Output` window:

```
[Info - 2021-09-07 09:47:19.469] Compute instance to connect to: https://<instancename>.northeurope.instances.azureml.ms
[Error - 2021-09-07 09:47:20.105] UNIX[No such file or directory]
```

## Steps to Reproduce the Problem

  1. `Azure ML: Sign-in`
  2. Have a running compute instance
  3. Run `Azure ML: Connect to Compute Instance` (or right-click `VS Code` in the `Compute` tab of the online Azure ML platform)

## Specifications

  - VS Code Version: 1.60.0 (Universal)
  - Local machine : macOS Big Sur v11.5.2

**Comment by SiddhanthUnnithan** [comment]
Thanks for reporting this @servot. Can you help confirm the following:
1. What version of the AML extension and AML - Remote extension do you have installed?
2. Are you signed into your Azure account before invoking the "Connect to Compute Instance" command?
3. Are you able to see the extension tree view in the editor? I noticed that in the logs it says "https://<instancename>". I'm assuming the extension is incorrectly fetching the compute details and thus unable to establish the connection.
4. Were you able to connect to the compute instance in the past? If so, do you know if anything changed in between (extension version, VS Code version).

**Comment by Servot** [comment]
Dear Sid,

Thanks for your reply.
 I apologies for not trying  this before the bug report, but completely shutting down the compute instance  and then restarting resolved the issue. (Just restarting didn't do the trick for some reason)

For completeness I will answer your questions:
1. AML extension 0.6.25 and  AML - Remote 0.4.0
2. I was signed in (tried logging out and in again with the `Sign out` and `Sign out`  commands)
3. I am/was able to see the extension tree view
4. I was able to connect without  any issues before

**Comment by sevillal** [comment]
@Servot Thanks for sharing those details, please open an issue in case you face another issue.
