### ISSUE TITLE
[Triage] Issue retrieving websocket bits during remote connection setup

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1266]
We received an error report from CI support engineering, stating that the customer was unable to connect to a compute instance, though their other ones worked. The error they saw in logs referenced being unable to download websocket server bits.

```
[Error - 2021-08-27 16:39:28.544] Maximum retries exhausted. Could not install Azure ML websocket server on [Compute Instance]: Downloading Websocket server failed. Please try again later.
```

**Comment by tbombach** [comment]
I've asked the support engineer to check with the customer and see if the compute instance is in a VNET and if the required websites are allowed. We'll have to investigate further if that's not the case

**Comment by sevillal** [comment]
Support engineer still waiting for customer to apply outbound rules.

**Comment by shsuman** [comment]
Customer asked to archive the case for now. Reopen if need be.
