### ISSUE TITLE
[Triage] VS Code is stuck installing server when connecting to CI (jupyter, jupyterlab and terminal stuck)

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1271]
Related icm: https://portal.microsofticm.com/imp/v3/incidents/details/258900809/home

**Comment by sevillal** [comment]
Looks related to: https://github.com/microsoft/vscode-tools-for-ai/issues/1174

**Comment by sevillal** [comment]
Followed up with support engineer to check if new release with bash minifications solves the issue for the customer.

**Comment by shsuman** [comment]
Closing this as we have shipped the fix and has got no response from the customer for over 7 days.
