### ISSUE TITLE
[Triage] Run and debug experiments locally not possible

### ISSUE THREAD

**Issue by 1-Peter** [microsoft/vscode-tools-for-ai#1274]
## Expected Behavior
Following the steps described here: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-debug-visual-studio-code, section "Debug experiment locally", Point 4 and 5, there should be the points "Create experiment" and "Run experiment".

## Actual Behavior
In VS Code, right-clicking on an experiment, there is no "Create experiment" or "Run experiment".
![grafik](https://user-images.githubusercontent.com/42338589/133412802-23872479-a30b-4232-9810-da8c2f4c1c84.png)

## Steps to Reproduce the Problem

  1. Install VS Code Plugin "Azure Machine Learning" following  https://docs.microsoft.com/en-us/azure/machine-learning/how-to-debug-visual-studio-code
  1. Connect Azure, select Subscription, Experiment etc.
  1. Right-Click Experiment

## Specifications

  - Version:
    - VS Code: 1.6
    - Azure Machine Learing: v0.6.25
  - Platform: win10

**Comment by sevillal** [comment]
@1-Peter thanks for sharing this. 

It looks like the docs needs to be updated, in the meanwhile could you please try the following:

1. Open your VS Code
2. Open the setting "Cmd + <comma>"
3. Look for Extensions -> Azure Machine Learning -> "Azure ML: CLI Compatibility Mode" and change it to "1.0"
4. Right click on the experiment again, the expected context menu's should be available now

![image](https://user-images.githubusercontent.com/56176070/133474755-fbbe6555-a1da-4fba-9383-fe14e69d9662.png)

Please let me know if you face any issue. Thanks!

**Comment by 1-Peter** [comment]
@sevillal thanks for this import hint. The Documentation already stated that the CLI version in the guide is based on v1. Somehow I expected backward compatibility.

Out curiosity: Will CLI v2 support local debugging of ML Experiments in Future?

Since issue is resolved it can be closed

**Comment by sevillal** [comment]
cc @SiddhanthUnnithan

@1-Peter  That's something we would like to have, but at this point, we are in its investigation phase. We would be glad to contact you when we have more clarity there.
