### ISSUE TITLE
[Triage] Unable to establish connection with AzureML remote compute instance

### ISSUE THREAD

**Issue by minasouliman** [microsoft/vscode-tools-for-ai#1279]
## Expected Behavior
Click on the vscode button in the ML portal and connect to that remote instance
![image](https://user-images.githubusercontent.com/49690571/134232502-71293875-6e99-4466-97c5-bc84710ff071.png)

## Actual Behavior
Never able to establish the connection and get the following debug messages--
```
[Debug - 2021-09-21 19:03:01.539] Azure ML - Remote for VSCode 0.4.0
[Debug - 2021-09-21 19:03:01.539] Platform: win32
[Debug - 2021-09-21 19:03:01.629] Sending Telemetry: AzureML-Remote/resolve/start
	{"telemetryTrackingId":"9a563f9f-e888-464b-951a-097c1ce59ecb","timestamp":"2021-09-21T19:03:01.625Z","sessionId":"4b4aS","resolveAttempt":1}
[Debug - 2021-09-21 19:03:01.633] Sending Telemetry: AzureML-Remote/acquireBearerToken/start
	{"telemetryTrackingId":"9a563f9f-e888-464b-951a-097c1ce59ecb","timestamp":"2021-09-21T19:03:01.632Z","sessionId":"4b4aS"}
[Debug - 2021-09-21 19:03:01.634] Sending Telemetry: AzureML-Remote/getTokenAcquisitionParams/start
	{"telemetryTrackingId":"9a563f9f-e888-464b-951a-097c1ce59ecb","timestamp":"2021-09-21T19:03:01.633Z","sessionId":"4b4aS"}
[Debug - 2021-09-21 19:03:02.387] Sending Telemetry: AzureML-Remote/getTokenAcquisitionParams/success
	{"telemetryTrackingId":"9a563f9f-e888-464b-951a-097c1ce59ecb","timestamp":"2021-09-21T19:03:02.386Z","sessionId":"4b4aS"}
[Debug - 2021-09-21 19:03:04.126] Sending Telemetry: AzureML-Remote/acquireBearerToken/success
	{"telemetryTrackingId":"9a563f9f-e888-464b-951a-097c1ce59ecb","timestamp":"2021-09-21T19:03:04.125Z","sessionId":"4b4aS"}
[Debug - 2021-09-21 19:03:04.128] Sending Telemetry: AzureML-Remote/installVSCodeServer/start
	{"telemetryTrackingId":"9a563f9f-e888-464b-951a-097c1ce59ecb","timestamp":"2021-09-21T19:03:04.127Z","sessionId":"4b4aS"}
[Info - 2021-09-21 19:03:04.136] Using commit id "83bd43bc519d15e50c4272c6cf5c1479df196a4d" and quality "stable" for server
[Debug - 2021-09-21 19:03:05.063] Sending Telemetry: AzureML-Remote/connect/get_terminal_session
	{"telemetryTrackingId":"9a563f9f-e888-464b-951a-097c1ce59ecb","timestamp":"2021-09-21T19:03:05.062Z","sessionId":"4b4aS"}
[Error - 2021-09-21 19:05:05.914] VSCode server installation timed out.
[Info - 2021-09-21 19:05:06.926] Using commit id "83bd43bc519d15e50c4272c6cf5c1479df196a4d" and quality "stable" for server
[Debug - 2021-09-21 19:08:57.854] Sending Telemetry: AzureML-Remote/connect/get_terminal_session/error
	{"telemetryTrackingId":"9a563f9f-e888-464b-951a-097c1ce59ecb","timestamp":"2021-09-21T19:08:57.854Z","Error":"Error: Invalid response: 408 Request Timeout","sessionId":"4b4aS"}
[Error - 2021-09-21 19:08:57.855] Invalid response: 408 Request Timeout
[Error - 2021-09-21 19:08:57.855] Cannot communicate with the Jupyter endpoint.
[Info - 2021-09-21 19:08:58.869] Using commit id "83bd43bc519d15e50c4272c6cf5c1479df196a4d" and quality "stable" for server
```

Additionally, this renders the compute instance inaccessible through the other endpoints (jupyter, jupyterlab, terminal). Once vscode is stuck in this retry loop, and even after manually closing the remote connection window, trying to access the compute instance results in the following error message--

```
Timed out attempting to connect to this compute instance.
Check to make sure the compute instance is started. If you just started it, try again in a minute or two.
```

The only way to enable connection back to the remote instance through jupyter is to restart it.

## Specifications

  - VS Code Version: Both v1.60.1 (stable) and v1.61.0 (insider)
  - Platform: Windows 10, remote instance is a Standard_D1_v2

**Comment by sevillal** [comment]
@minasouliman thanks for sharing those details. Could you please confirm that you can access the Terminal from the ML Studio in your browser before attempting remote connection with VS Code?

**Comment by minasouliman** [comment]
@sevillal, yep, that's correct. Prior to attempting the remote connection, I'm able to access the terminal as well as jupyter. Additionally everything is functional through the jupyter connection as well as the azure ml studio native notebooks interface. It's only after attempting to establish the connection in vscode that the former options stop working and the compute needs to be restarted.

**Comment by sevillal** [comment]
@minasouliman Thanks for your response. Couple of questions:
1. Does the issue happens every time you try to connect? Or it works some times? 
2. Does it happen with other compute instances?

**Comment by shsuman** [comment]
Closing this as there has been no response for over 7 days. Please reopen it if need be
