### ISSUE TITLE
[Triage] Trusted workspace prompt is shown always when connecting to CI

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1280]
Trusted workspace prompt is shown on subsequent connections even if the workspace was trusted before. Ideally it should be shown on the first connection only.

**Comment by shsuman** [comment]
@sevillal Was this a customer issue ?

**Comment by sevillal** [comment]
@shsuman it was reported by support eng, I have added you to the thread and the details are also in the Customer Issues internal one note.

**Comment by shsuman** [comment]
Dupe of #1275
