### ISSUE TITLE
Test strategy for schemas and templates being staged to public store

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1283]
Incoming schemas are stored in "preview" store. Currently referenced one are stored in "latest" store.

We need a better test strategy for schemas and templates currently in preview. In particular we want to validate:

1. Are the schema completions being surfaced correctly? This will involve testing in the YAML and checking the schema for "arm_id" tags where appropriate.

2. Are the templates being generated correctly?

3. Are completions and diagnostics being shown for the template and schema properties?

**Comment by tbombach** [comment]
Sid has a PR out for a spec for handling latest/preview toggling: https://github.com/Azure/azureml_run_specification/pull/508

**Comment by tbombach** [comment]
We'll close this once the above PR is merged. We'll also need to do work for supporting individual Preview candidates, which are located in a subfolder inside the preview directory.
