### ISSUE TITLE
Test newly added URI telemetry events for VS Code click-out

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1284]
Telemetry events here: https://github.com/microsoft/vscode-internalbacklog/issues/2312

Test e2e CI connection flow to see whether all desired events are captured.

**Comment by shsuman** [comment]
I think these are the events that Sid was talking about:

EventName | count_
-- | --
monacoworkbench/uri_invoked/install_extension/start | 1087
monacoworkbench/uri_invoked/start | 18788
monacoworkbench/uri_invoked/end | 16109
monacoworkbench/uri_invoked/cancel | 377
monacoworkbench/uri_invoked/install_extension/accept | 980
monacoworkbench/uri_invoked/enable_extension/start | 89
monacoworkbench/uri_invoked/enable_extension/cancel | 6
monacoworkbench/uri_invoked/activate_extension/start | 8
monacoworkbench/uri_invoked/enable_extension/accept | 88
monacoworkbench/uri_invoked/install_extension/cancel | 92
monacoworkbench/uri_invoked/activate_extension/accept | 8


They are now available in Kusto

**Comment by shsuman** [comment]
I think these are the events that Sid was talking about:

EventName | count_
-- | --
monacoworkbench/uri_invoked/install_extension/start | 1087
monacoworkbench/uri_invoked/start | 18788
monacoworkbench/uri_invoked/end | 16109
monacoworkbench/uri_invoked/cancel | 377
monacoworkbench/uri_invoked/install_extension/accept | 980
monacoworkbench/uri_invoked/enable_extension/start | 89
monacoworkbench/uri_invoked/enable_extension/cancel | 6
monacoworkbench/uri_invoked/activate_extension/start | 8
monacoworkbench/uri_invoked/enable_extension/accept | 88
monacoworkbench/uri_invoked/install_extension/cancel | 92
monacoworkbench/uri_invoked/activate_extension/accept | 8


They are now available in Kusto
