### ISSUE TITLE
Change the default workspace to a newly created one automatically, or at least prompt the user to change it.

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1294]
After creating a new workspace:
- Change it to be default automatically
or
- Ask with notification if the user wants to make it the default

**Comment by tbombach** [comment]
Yep, this would be great to do. Sid/I think that asking the user if they want to make the new workspace the default one is better.

**Comment by shsuman** [comment]
Since, we are relying on the CLI to create the workspace, we do not have indication for the creation of the new workspace.

Closing it for now.
