### ISSUE TITLE
[Triage] Plot is not rendering in VSCode while connecting to AML Compute

### ISSUE THREAD

**Issue by bkuriach** [Microsoft/vscode-tools-for-ai#1297]
Issue Type: <b>Bug</b>

Plot is not rendering in VSCode while connecting to AML Compute (Not in debug mode). 

Steps to reproduce:
1. Connect VSCode to any AML Compute
2. execute below code

import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.show()

Same is working in local VSCode (connected to local machine)

Please let me know if you need more details.

Extension version: 0.4.0
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.22473
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.0-1056-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.65GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/bkuriachan/Projects/Crop%20Classification/crop-classification --remote=wsl+Ubuntu-20.04 --crash-reporter-id bb5a6bf5-d714-48a5-9eba-811de0544190|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|7.64GB (4.63GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Azure ML: attention-model-gpu|
|OS|Linux x64 5.4.0-1056-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (6 x 2596)|
|Memory (System)|54.92GB (47.17GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805cf:30301675
vsccppwt:30377799
bridge0708:30335490
bridge0723:30353136
vsqsis300:30374797
vsaa593:30376534

```

</details>

**Comment by sevillal** [comment]
@bkuriach thanks for filing this issue. I need to look into this a little bit more but seems like this is an issue on how to display UI from remote apps in vscode. (Trying this same code on Remote WSL or Remote SSH will be the same).

In the meantime I can suggest the following workarounds:
1.  Use "plt.savefig("image-name.png")" and open PNG in the same vscode remote window
2.  Run the code in interactive window. Right click and select "Run current file in interactive window"
![image](https://user-images.githubusercontent.com/56176070/137383878-c2a34c7c-f062-40a3-b438-dbfa49b92097.png)
3. Use interactive window + inline jupyter cell. Wrap your code in #%% to mark the start of a jupyter cell, editor will show codelenses to run cell.
![image](https://user-images.githubusercontent.com/56176070/137384270-be9644dc-fc61-4b69-817a-3e6ee4b8c498.png)

**Comment by shsuman** [comment]
@bkuriach Were the above workarounds helpful ?
