### ISSUE TITLE
Handle Azure signin the same way other Azure extensions do. 

### ISSUE THREAD

**Issue by greazer** [Microsoft/vscode-tools-for-ai#130]
Take any of the other Azure extensions in the marketplace and notice that until Azure is signed into, each extension's respective tab on the Azure panel displays the same messages with links 

Sign in to Azure... 
Create a free Azure Account... 

except ours. We need to look and act exactly like them.

**Comment by shsuman** [comment]
Has dependency on #119 . All the other extensions use Azure Tools for VS Code which has the inbuilt functionality to handle this. They don't do this themselves.
