### ISSUE TITLE
[Triage] Cannot connect to remote compute instance

### ISSUE THREAD

**Issue by natke** [microsoft/vscode-tools-for-ai#1336]
## Expected Behavior
Connect to remote instance using the Azure ML: connect to compute instance command

## Actual Behavior
See attached screenshot

## Attempts to fix
I have tried uninstalling and re-installing the extensions, I disabled any YAML extensions, I deleted the .vscode files for the extensions, I re-booted my machine, I changed my Azure CLI version to 1.0

## Steps to Reproduce the Problem

  1.Run Azure ML: connect to compute instance

## Specifications

  - VS Code Version:
    ```
    Version: 1.61.1 (user setup)
    Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
    Date: 2021-10-14T01:19:42.089Z
    Electron: 13.5.1
    Chrome: 91.0.4472.164
    Node.js: 14.16.0
    V8: 9.1.269.39-electron.0
    OS: Windows_NT x64 10.0.19043
    ```

  - Platform:
    ```
    Edition	Windows 10 Enterprise
    Version	21H1
    Installed on	‎9/‎10/‎2020
    OS build	19043.1288
    Experience	Windows Feature Experience Pack 120.2212.3920.0
    ```

  - Extensions version
    ```
    Released on
    9/25/2017, 06:15:07
    Last updated
    8/25/2021, 11:32:40
    Identifier
    ms-toolsai.vscode-ai
    ```

    ```
    Released on
    2/11/2021, 16:56:46
    Last updated
    7/13/2021, 16:42:10
    Identifier
    ms-toolsai.vscode-ai-remote
    ```

![image](https://user-images.githubusercontent.com/3302433/138147185-1e3505a4-6bc2-46ed-b999-7aff26ea9936.png)

**Comment by natke** [comment]
Any updates on this @SiddhanthUnnithan? Thanks!

**Comment by natke** [comment]
Thank for the reply @SiddhanthUnnithan. 

I tried the steps above, and I can connect to the remote compute going through the Azure tab on VS Code, so that's good and is a workable solution to my problem.

However, I still get the above error when I try and do the same thing with the command palette ie CRTL-SHIFT p -> AML: Connect to remote instance.

Let me know if you need more details.

**Comment by sevillal** [comment]
@natke we released a new version of the extension earlier this week that contains a fix for that. Could you please update your extension to 0.6.26 and retry? Please let me know if you face any issue.

**Comment by sevillal** [comment]
Closing for now. @natke please reopen if you still facing the same issue.
