### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#134]

**Comment by mdapri** [comment]
In the "Train and tune models in Visual Studio Code"  in step 
_5. Input the name for the Run Configuration. Once created, right click and select Run Experiment_
is not clear what to do. An Explorer windows opens prompting for a file. I have tried using a train.py file built with the tutorial notebook on mnist [https://docs.microsoft.com/en-us/azure/machine-learning/service/tutorial-train-models-with-aml](url) but ML extension complains with "Azure ML requires that the experiment script be contained in the base directory."

**Comment by shsuman** [comment]
Closing the non relevant and old V1 issues.
