### ISSUE TITLE
[Triage] (Error that occurs when trying to open VSCode from AML)

### ISSUE THREAD

**Issue by jmagosta** [microsoft/vscode-tools-for-ai#1367]
Does this occur consistently?  Yes 
Repro steps:

1. PRess the "OPen in VSCode button in AML

Action: handleUri
Error type: TypeError
Error Message: Cannot read property 'subscription' of undefined

Version: 0.6.27
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.62.0
Language: en

<details>
<summary>Call Stack</summary>

```
p.<anonymous> extension.js:2:4261889
a extension.js:2:4261214
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by shsuman** [comment]
@jmagosta  Are you using an Azure Account which is linked with multiple tenants ?

**Comment by shsuman** [comment]
Closing this as We have not received any response for over 7 days. Please feel free to reopen it if need be :)
