### ISSUE TITLE
[Triage] issue when trying to connect to aml compute instance 

### ISSUE THREAD

**Issue by azeltov** [Microsoft/vscode-tools-for-ai#1368]
Does this occur consistently? 
Repro steps:

1.
2.

Action: handleUri
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.6.27
OS: darwin
OS Release: 20.6.0
Product: Visual Studio Code
Product Version: 1.62.0
Language: en

<details>
<summary>Call Stack</summary>

```
new t extension.js:451:37728
t.<anonymous> extension.js:451:23411
extension.js:646:1761
Object.throw extension.js:646:1866
s extension.js:646:656
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by shsuman** [comment]
@azeltov Can you please update the extensions to the latest version and try again ?
