### ISSUE TITLE
Update Workspace YAML template used in "Create Workspace" command

### ISSUE THREAD

**Issue by HaoHoo** [microsoft/vscode-tools-for-ai#1371]
## Expected Behavior
Click tab '+' or using "Azure ML: Create Workspace" command. Auto-create an YAML file and using it to deploy ML Workspace.

## Actual Behavior
Default parameter 'friendly_name' is not exist and may replaced by 'display_name'.
And 'resource_gourp' is required so may be need to add to default YAML example.  

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:

**Comment by tbombach** [comment]
Hi @HaoHoo - thank you for filing this issue! We just tested this and saw the same behavior you described. The format of the YAML file has changed, so we need to update the example file that we create with the "Azure ML: Create Workspace" command. I'll post an update here when that issue is fixed.
