### ISSUE TITLE
File completion support in YAML for paths to local files

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1377]
We want to have file completions that allow the user to specify a local file in their YAML files. One use case of this is the `local_path` property in [Command Jobs](https://azuremlsdk2.blob.core.windows.net/latest/commandJob.schema.json)

As suggested by @shsuman, we should architect this in a way that parts of the code can be re-used for other file completions (like datasets) when we implement them.

Other aspects of this work:
- We need to work with AML so that this is driven by a schema property, just as we use arm_type for AML resources
- We also would like basic diagnostics for this property. If the user types a file path that is not valid, we should show an error in the editor. However, it is out of scope to analyze the file or file type for validity.

**Comment by shsuman** [comment]
Available in main, waiting for schema changes from Azure ML team
