### ISSUE TITLE
Editing computes error 

### ISSUE THREAD

**Issue by swinner95** [microsoft/vscode-tools-for-ai#138]
When I edit either the maxnNodeCount or minNodeCount for an AMLCompute target that I created, I get the error below (even though I did not edit the 'nodeIdleTimeBeforeScaleDown')

Error message: "Invalid input, provide an integer duration in seconds"

**Comment by shsuman** [comment]
I think Xiaoyun already fixed this. PR 902384. I am not getting the error any more. I edited both max and min node count and they work fine now.

**Comment by swinner95** [comment]
I just edited both the max and min node count for different computes and I got the same error message 'Invalid input, provide an integer duration in seconds'.

**Comment by shsuman** [comment]
@swinner95  please try this build https://msasg.visualstudio.com/_apis/resources/Containers/5740305?itemPath=vsix&$format=zip

**Comment by swinner95** [comment]
@shsuman I just tried with the new build and I am getting the same error

**Comment by shsuman** [comment]
@swinner95  I don't know but I am trying to edit an existing aml compute and its working fine. i will try to create a new one and then try again

**Comment by shsuman** [comment]
@swinner95  I tried it, creating a new compute and then editing it. It worked fine for me. Can you try this build https://msasg.visualstudio.com/_apis/resources/Containers/5835022?itemPath=vsix&$format=zip although its the same branch but still. Also can you send me the screenshots of the properties page which appear at the time of creating the compute, also while editing the compute and the error

**Comment by greazer** [comment]
@swinner95 I'm thinking this can be closed?

**Comment by swinner95** [comment]
yes
