### ISSUE TITLE
When Azure Compute instance is removed, Connected VS Code hangs

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-tools-for-ai#1385]
Issue Type: <b>Bug</b>

When Azure ML Studio compute instance is removed on Azure, the VS Code workspace that was connected to that ML Studio compute instance that is open locally hangs.  I just see the spinning "connecting" icon in the lower left / far left of the status bar.  I cannot close VS Code, I cannot change to a different workspace.  The entire program becomes un-responsive.  Though I still can minimize and maximize the window. The only way to close it is forcibly through the Task Manager. 

Extension version: 0.5.0
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.19GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593:30376534
vssld246cf:30401891
vscop804cf:30404767

```

</details>

**Comment by tbombach** [comment]
Hi @clayms, thank you so much for filing this! We hadn't tested this scenario, so we really appreciate you bringing it to our attention. I just tested the steps you provided and saw the same behavior you described. I don't think we get a good signal or event that a compute is deleted (which would let us show a dialog and close the window gracefully), but I think we could stop retrying to connect after a certain amount of time and try to stop whatever operation is causing the window to freeze. We'll schedule work to fix this and I'll keep you posted when we have a fix. Thank you again!

**Comment by shsuman** [comment]
This state is now handled in the latest version.
