### ISSUE TITLE
[Triage] WebSocket Errors on AML compute instance with Jupyter Notebooks

### ISSUE THREAD

**Issue by YnnamTenob** [microsoft/vscode-tools-for-ai#1386]
Issue Type: <b>Bug</b>

After the July update 4 days ago connections to compute instances become unstable very quickly. VSCode reports socket Errors.
[Error - 2021-08-08 22:49:35.458] Websocket 6 error sending data: Error: WebSocket is not open: readyState 3 (CLOSED)
[Error - 2021-08-08 22:49:41.032] Websocket 7 error sending data: Error: WebSocket is not open: readyState 3 (CLOSED)

These errors appear to render VSCode unusable du to slowness. during this episode VSCode exhibits High Memory and CPU usage. The only way to get VSCode working again is to esstablish a new connection with the remote compute resource; however after only a few minutes that connection experiences the same error.   

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.17134
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1043-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (6 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (6.12GB free)|
|Process Argv|--crash-reporter-id 8af295f0-b048-43c3-a501-083ca0c08aa2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Azure ML: cpu-ds3-v2-tenob-m|
|OS|Linux x64 5.4.0-1043-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (4 x 2397)|
|Memory (System)|13.67GB (1.76GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ai-remote|ms-|0.4.0
vscode-azurecognitivesearch|ms-|0.2.0
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623
vscode-ai|ms-|0.6.24
vscode-ai-remote|ms-|0.4.0
azure-account|ms-|0.9.8
vscode-sanddance|msr|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by sevillal** [comment]
@alexdima transfered to vscode-tools-for-ai

**Comment by sevillal** [comment]
@eduedix do you have a sample notebook to repro the issue? Thanks

**Comment by shsuman** [comment]
Closing this as there has been no response for over 7 days. Please reopen if need be.
