### ISSUE TITLE
[Triage] VS Code server download for aml inconsitent

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1388]

**Comment by sevillal** [comment]
Suggested customer to whitelist donwload endpoints for VS Code server and websocket server.

**Comment by shsuman** [comment]
@sevillal met with the customer and suggested to whitelist some additional endpoints. Waiting for customer's reply.

**Comment by shsuman** [comment]
Looks like an issue for AML team. Isis, Abe and Vijeta are following up
