### ISSUE TITLE
[DRI-Lite] All items for the week of 11/29 & 12/6

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1389]
### New Issues
- [ ] #1388 
- [ ] #1385
- [x] #1394 
### Issues from previous week 
- [x] #1286 
- [x] #1275 
- [x] #1172 
- [x] #1332 
- [x] #1331 
- [ ] #1280 
- [ ] #1165 
- [x] #1173 
- [x] #1174 
- [x] #1271 
- [x] #1386 
- [ ] #1362 
- [x] #1262

**Comment by sevillal** [comment]
Closing in favor of #1408
