### ISSUE TITLE
Read only 'View Compute Properties'

### ISSUE THREAD

**Issue by swinner95** [microsoft/vscode-tools-for-ai#139]
When I right click on a compute target and select 'View Compute Properties'; I can still edit the properties.json file. Even though these changes do not save as this is a read only file, users might think that their edits are being saved and expect different results. We should prevent users from editing this json file.

**Comment by shsuman** [comment]
Not sure if VS code API supports this. Didn't find any flags that would stop the user from editing a doc

**Comment by shsuman** [comment]
Opened a new issue with VSCode regarding this

**Comment by greazer** [comment]
This is probably simple. After creating the json on disk, just use the os library to mark the file as read-only. VSCode will likely just honor that.

**Comment by greazer** [comment]
It's better we at least make the file read-only. If VSCode gives us additional features in the future to make this even more obvious, then we'll deal with that then.
