### ISSUE TITLE
Quote file paths to YAML files in the CLI command when running "Execute YAML"

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1391]
If we don't put quotes around file paths when we generate our CLI command, the user cannot run their command (see https://github.com/microsoft/vscode-tools-for-ai/issues/1370)

**Comment by tbombach** [comment]
Shantnu has code that addresses this (for all arguments, not just file paths).

**Comment by shsuman** [comment]
Available in main. Tested
