### ISSUE TITLE
Not possible to start AML Remote session: "No remote extension installed to resolve amlext"

### ISSUE THREAD

**Issue by jmagosta** [microsoft/vscode-tools-for-ai#1394]
Issue Type: <b>Bug</b>

# Error: Not possible to start AML Remote session: "No remote extension installed to resolve amlext"

Error only occurs on newly acquired local machine.  

- Installed VS Code,
-  WSL Ubuntu 20.04,
- In WSL installed VS Code extensions for:  Azure Account / Azure ML / Azure ML Remote

Connect to Compute Instance works on VS Code on an existing local machine -- which does not use WSL remote. 

Since this error occurs on one local machine and not another the error is with the local machine & VS code, not with AML. 

## Steps to recreate

1. Create new AML workspace
2. Create new WS Compute instance

3. Configure VS code AML extension
    - VS Code status bar shows Azure login. 
	- Set default Azure subscription. 
	- select AML workspace in Azure ML list
	- browse running Compute instance
	
4. Select "Connect to Compute instance" from Azure ML extension on local VS Code
> Response 
    - New VS Code instance appears
	- "Failed to connect to the remote extension host server (Error: No remote extension installed to resolve amlext.)
	Remote-connected instance of VS Code shows the same error in the list of VSCODE-REMOTE -INSTALLED extensions. So it's not possible to install remote extensions from this instance. 

5. Attempt workaround.  Search for extensions in the EXTENSIONS: MARKETPLACE. 
	Select "Azure Machine-Learning" 
	"Install in VSCode - Remote"
	> response: Installation hangs with "Installing msg".   Fails. 

THese changes do not fix the problem:

- Install all optional Windows updates. 
- Reboot local machine
- Restart remote compute instance
- Create new remote instance
- Create new remote AML workspace
- Reinstall VS CODE, and reinstall AML and AML remote extensions on WSL: remote

Windows 10 OS:  19044.1348
Subscription:   c9126719-f58d-4455-a79c-6ddc2c326802
Workspace URL:  https://ml.azure.com/?tid=72f988bf-86f1-41af-91ab-2d7cd011db47&wsid=/subscriptions/c9126719-f58d-4455-a79c-6ddc2c326802/resourcegroups/total-digital-factory-rg/workspaces/total-aml-workspace

Compute instance: jmagosta-large   IP:  52.188.44.215

Extension version: 0.6.27
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.71GB (39.04GB free)|
|Process Argv|--crash-reporter-id b075abe4-909f-4851-8db8-f53aa02e8181|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|Memory (System)|37.38GB (36.67GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsdfh931cf:30280410
vshan820:30294714
vscod805cf:30301675
vsccppwt:30393681
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vscop804cf:30404767
vscop940:30404999

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by jmagosta** [comment]
Further information: 

The problem occurs when the local instance of VS Code is running as "WSL remote".  This is evident because preferences for "select default windows profile" only shows bash options.  

_How VS Code gets "stuck" in WSL remote isn't obvious._

**Comment by shsuman** [comment]
Hey @jmagosta ,

Thanks for reporting this issue. Unfortunately, you have run into an unsupported scenario. We do not support connecting to an Azure ML Compute instance from a WSL window. This a cross extension remote in remote scenario which is beyond the scope of our current infrastructure. When you open a VSCode window using WSL CLI, it opens up a new remote window connected to your WSL. Note that, any VSCode instance connected to your WSL is effectively a remote window and not local window.

You can connect to Azure ML CI using a local VSCode window or we also support remote in our remote for our extension. That means, that while connected to one CI, you can connect to another CI from that remote window only.

Please let me know if this answers your query or if you any other questions/issues. I am closing this for now :). Please reopen it if need be :)
