### ISSUE TITLE
FAIL TO LOGIN TO AZURE ACCOUNT WHEN HAVE VARIOUS DIRECTORIES UNDER ONE SUBSCRIPTION.  ONLY SEES ONE DIRECTORY, IGNORES THE OTHERS

### ISSUE THREAD

**Issue by jpagan17** [microsoft/vscode-tools-for-ai#1398]
Does this occur consistently? YES
Repro steps:

1.
2.

Action: handleUri
Error type: r
Error Message: Failed to login to Azure Account.

Version: 0.6.27
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.63.0
Language: en

<details>
<summary>Call Stack</summary>

```
m.<anonymous> extension.js:2:4824492
a extension.js:2:4822345
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by shsuman** [comment]
@jpagan17  Can you provide some more information, repro steps ?

**Comment by sevillal** [comment]
Closing due inactivity in the last 7 days. @jpagan17  please reopen if you continue facing this issue. Thanks!
