### ISSUE TITLE
[Investigate] Empty completions when triggered on "azureml:" 

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1404]
## Expected Behavior
Show list of completions for the given property

## Actual Behavior
No completions shown

## Steps to Reproduce the Problem

  1. Open a yaml file to create a resource (i.e. commandJob)
  1. On environment property trigger completions after "environment: azureml:"
  1.

**Comment by tbombach** [comment]
We think this may be because the format of the string is the same as a JSON/YAML property. We need to investigate whether or not we can provide completions correctly in this case.

**Comment by shsuman** [comment]
Closing this as the behavior is limited by the syntactic features of Yaml language.
