### ISSUE TITLE
Investigate why field completions are shown after double space

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1406]
## Expected Behavior
Should not show completions

## Actual Behavior
Showing completions after double space

## Steps to Reproduce the Problem

  1. Open a yaml file to create a resource (i.e. commandJob)
  1. Remove default compute property
  1. Enter "compute:<space>"
  2. Trigger completions, zero completions shown
  3. Enter another space "compute:<space><space>"
  4. Trigger completions, why some completions are show?

Note:
- Test this using RedHat yaml extension only, is it reproducible? If so we should file an issue to RedHat.

**Comment by shsuman** [comment]
I think this is the same problem as discussed in #1404 . So as mentioned in this [comment](https://github.com/microsoft/vscode-tools-for-ai/issues/1404#issuecomment-1206650795) the behavior is limited by the syntactic features of Yaml language.
