### ISSUE TITLE
Wrong path in notebook when in remote compute instance

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1412]
More information in IcM: https://portal.microsofticm.com/imp/v3/incidents/details/281042172/home

Next steps:
- Try to repro with latest version of AzureML and Jupyter ext
- Check if repro in Remote SSH, if so, transfer to Jupyter team

**Comment by shsuman** [comment]
@sevillal  Do we have an upstream issue with Jupyter on this ?

**Comment by sevillal** [comment]
Asked support engineer for more data and to try out something else. If that does not work we will have a call with the customer to triage, get logs and open an issue for Jupyter.

**Comment by sevillal** [comment]
I met with customer and customer was confused selecting the Remote CI for the Jupyter server, following issue will avoid the consufion https://github.com/microsoft/vscode-tools-for-ai/issues/1451. In the meanwhile customer is using "local" jupyter server (local to the CI) and that fixed the issue.
