### ISSUE TITLE
Update usage of VS Code Proposed API

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1413]
VS Code Proposed APIs now use a scope to enable fine-grained control over permission to use proposed APIs. We need to migrate to the new method in our package.json, as described here: https://github.com/microsoft/vscode/issues/136964. This should be done for both the main and remote extension (although I believe all proposed API usage is only in the remote extension now, we should make sure we're up to date on both).

We will also do the same thing for the gather extension: https://github.com/microsoft/vscode-gather

**Comment by jrieken** [comment]
@tbombach fyi - deadline a approaching

**Comment by tbombach** [comment]
@jrieken Thank you for the ping! I've merged the PR for this: https://github.com/microsoft/vscode-azureml-remote/pull/15. We'll be releasing on Wednesday

**Comment by tbombach** [comment]
@jrieken Just to close the loop - we have released new versions of our extensions that include this change
