### ISSUE TITLE
Azure ML: Install Azure ML SDK gets nothing

### ISSUE THREAD

**Issue by shizn** [microsoft/vscode-tools-for-ai#142]
I'm a new user to Azure ML extension and trying to install the AML SDK via command palette. Both in my Macbook and Windows desktop, when I trigger Azure ML: Install Azure ML, nothing happens, which is different from the behavior in the instructions [here](https://github.com/Microsoft/vscode-tools-for-ai/blob/master/docs/installation.md#3-install-the-azure-machine-learning-sdk).

![image](https://user-images.githubusercontent.com/3619378/51147992-3c7f5800-1811-11e9-9925-8b096e807215.png)

**Comment by LittleLittleCloud** [comment]
The instruction page you are looking on is for 0.3.3, so it's out of date .usually, after 0.4.0 you don't have to install it manually. Just open the extension and it will install automatically.

@greazer do you think we need to show something to tell users that the SDK is installed whenever they run the command or just remove the command

**Comment by shsuman** [comment]
@greazer  I think its time we get rid of the install Azure ML SDK command. I think I have already discussed it with you before the last release. But, since we were not sure at that time about the sdk installation workflow, we skipped it

**Comment by shsuman** [comment]
@greazer  Should we remove the command ?

**Comment by swinner95** [comment]
I updated the information in instructions page.

**Comment by greazer** [comment]
Yes. We should.
