### ISSUE TITLE
Azure ML: Create Resource command is not working

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1449]
Unmatched closing tag: br Line: 23 Column: 113 Char: >

**Comment by SiddhanthUnnithan** [comment]
@shsuman I saw this issue while using the telemetry build you sent. It occurs with create resource and when trying to invoke any completions in the YAML. Remote seems to be working as expected.

**Comment by SiddhanthUnnithan** [comment]
This issue was occurring because Azure ML changed their blobs from storing XML to raw HTML. A fix was made to revert the blobs to XML. Schema/template retrieval and resource creation works as expected now.
