### ISSUE TITLE
Remote Connection Improvements

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1450]
We have identified the following problematic areas in our remote connection experience:

## Reconnection

Customers are reporting that after prolonged sleep time their connection is lost and they need to reload the window. 
By design VS Code Server will shutdown Extension Host connection after 3 hours of disconnection, this will force the customer to reload their window when they wake up their system. This should not cause any data loss since the default Hot Exit will kick in and save all the text buffer states in the local machine.
- [x] #1455

## Kernels

The default behavior for running a notebook with the Jupyter extension is that a kernel will be spawn up to run the code. The assumption is that this is the way customers are running notebooks when connected to the CI and this approach has its limitation. 
Instead we should start the kernel using the default Jupyter server running on the CI, that way we can keep the kernel alive regardless if the user closes VS Code and it can be reconnected later in case of long running processes.
- [ ] Jupyter Extension: Detect when notebook is being run on CI remote connection, call an API in the Azure ML extension to get the native Jupyter server URL and list the kernels from there
- [ ] Jupyter Extension: Kernel reconnection
- [ ] Jupyter Extension: Long running kernels output sync
- [ ] Azure ML Extension: Expose API to get the currently connected CI Jupyter server URL

## Remote URI related

The current remote URI schema contains dynamic values (i.e. telemetryTrackerId, sessionId) ending up on having different URIs to represent the same remote target workspace. This lead to behaviors like multiple prompts to trust the workspace, multiple entries of the same workspace in the recent files and losing the editor state between sessions. We need to change the remote URI to be unique and pass the dynamic data with other mechanism.
- [x] #1453

## VS Code window state blocking

- [x] #1454

## Authorization

- [x] https://github.com/microsoft/vscode-tools-for-ai/issues/1159
- [x] #1456
- [ ] Investigate: Can we know if the refresh token has expired when getting a new access token? If so we should warn the customer and guide them how to refresh it

## Error handling

- [x] #1489

## Multiple windows
- [x] #1490

**Comment by tbombach** [comment]
Thank you Sergio! I added this as a big rock for the 0.6.29 Iteration and removed needs triage from each of the child items

**Comment by sevillal** [comment]
Thanks @edgBR for your feedback and I am sorry to hear that you are having troubles with the remote connection. We would do our best to improve this experiences, what are the issues that you and your team are facing the most currently when connecting?

**Comment by edgBR** [comment]
Hi @sevillal 

Most of the issues are regarding the TTL of the connection to the azureML instance.  I have had a similar issue in the past with the SSH extension (similar issue described here: https://github.com/microsoft/vscode-remote-release/issues/3096) for connecting to EC2 instances (I was using AWS before).

But in AML instances is much worst. If my connection fails just for a second I need to reload the window and restart my jupyter notebooks to run everything again. Also sometimes the connection is lost and the changes in the notebooks are not saved despite of having autosave enabling. 

BR
E

**Comment by ma11034** [comment]
Hi! totally agree with @edgBR, sometimes connection fails and then need to rerun notebooks, what sometimes takes a lot of time to complete.

**Comment by sevillal** [comment]
Closing this for now since remote improvements have been made. Track Kernel improvements in different issue.
