### ISSUE TITLE
Remove "Azure ML Compute Instance" from Jupyter server selector in remote window

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [Microsoft/vscode-tools-for-ai#1451]
We currently surface the "Azure ML Compute Instance" option in all windows (regardless of remote or local context) when the user clicks on the Jupyter server selector. Having the option in a remote window, already connected to their compute instance, is confusing; the intent of having the server selector option was to provide an "intermediary" experience for users to connect their local notebooks to the remote Jupyter server in a highly streamlined manner. Through this option, the Jupyter extension creates a placeholder notebook at the root of the Jupyter server (cloudfiles/code for CIs) to relay all "locally" executed commands. When users connect to this option from within a remote window, instead of using their current notebook context (e.g., cloudfiles/code/Users/siunnith/hello.ipynb), the Jupyter extension uses the placeholder notebook approach as it is unaware that the user is already connected to their compute instance. Usage of the placeholder notebook in the remote window results in mismatched execution contexts when the user runs notebook cells (e.g., !pwd in the notebook returns cloudfiles/code instead of cloudfiles/code/Users/siunnith).

The Azure ML extension is aware that the user is in a remote window corresponding to their Azure ML compute instance. When in this state, the extension should omit the "Azure ML Compute Instance" command from the Jupyter server selector list. In doing so, users will only be able to choose the "Default" server option, which reverts to a "local" server (note: local here is local to the compute instance as the user is in the remote window). The user may see other server options (e.g., Spark) but we're uninterested in their behaviour.

Relevant customer problem can be found here: https://github.com/microsoft/vscode-jupyter/issues/8885

**Comment by tbombach** [comment]
Added to 0.6.29 Iteration Plan

**Comment by shsuman** [comment]
I think this has been settled by the changes that sergio made
