### ISSUE TITLE
[DRI-Lite] All items for the week of 02/07/22

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1452]
### Issues from previous week 

- [ ] #1417
- [ ] https://github.com/microsoft/vscode-tools-for-ai/issues/1410
- [x] https://github.com/microsoft/vscode-tools-for-ai/issues/1412
- [ ] #1286 
- [ ] #1275 
- [ ] #1172 
- [ ] #1332 
- [ ] #1331 
- [ ] #1280 
- [ ] #1165 
- [ ] #1385

#### OCVs
- [ ] #1422
- [ ] #1423
- [ ] #1424
- [ ] #1425 
- [ ] #1426 
- [ ] #1427 
- [ ] #1428 
- [ ] #1429 
- [ ] #1430
- [ ] #1431 
- [ ] #1432 
- [ ] #1433 
- [ ] #1434 
- [ ] #1435 
- [ ] #1436 
- [ ] #1437 
- [ ] #1438 
- [ ] #1439 
- [ ] #1440 
- [ ] #1441

**Comment by sevillal** [comment]
Closing in favor of https://github.com/microsoft/vscode-tools-for-ai/issues/1465
