### ISSUE TITLE
Implement our own dialog when remote connection needs window reload to something like "Your remote connection was idle for X time, we've saved your data. [Continue]"

### ISSUE THREAD

**Issue by sevillal** [Microsoft/vscode-tools-for-ai#1455]
## Goal

Display a more meaningful message to customers which remote connection tries to reconnect after a prolonged idle time. 

There is a known limitation with VS Code Server that after client disconnects it keeps the Extension Host alive for 3 hours to accept any reconnection, otherwise it shutdowns and a reload is required. Please note that Extension Host is an expensive process, holding language servers and extensions, that's why VS Code minimizes the amount of time it runs.

I think it is better to teach the customer that long idle connections will require them to reload the window when they come back, instead of just showing an unable to connect error forcing them to reload.

## Scenario improved

Common scenario is leaving the remote connection open overnight, after a while local system will enter sleep mode and disconnect, vscode-server keep Extension Host alive for 3 hours to accept reconnections otherwise it will shutdown and a window reload will be required.

## Proposal

In the resolver do the following:
- If reconnection (resolveAttempt > 1)
- Check if VS Code server is running on the remote machine (Write a thin script to check if server is running, without installation steps or dependencies checks, etc)
- If running, then continue resolver execution
- If not running, we've detected the scenario we've described
- [Do not await] Show our customer dialog "Your connection was idle for some time, we need to reload the window. We have saved your data" [Continue (will call reload window)]
- Throw RemoteAuthorityResovlerError.NotAvailable(..., handled=true) to prevent vs code showing the generic failure dialog.

**Comment by shsuman** [comment]
PR ready: https://github.com/microsoft/vscode-azureml-remote/pull/25
