### ISSUE TITLE
Handle 403 error better by not retrying server installation or reconnection and showing a better message

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1456]
HTTP error 403 should mean forbidden, so proxy knows who the user is but it is not allowed use the resource.

- If connecting to Jupyter returns 403 do not retry multiple times installing stuff and immediately throw the error
- In the resolver catch the error an check if error is "forbidden/403" show a meaningful message like "Connection is forbidden. Please make sure you are logged in with the right account." [Close remote connection]

**Comment by shsuman** [comment]
I am getting a 403 error when the compute instance doesn't exist, so how do we differentiate between a compute that doesn't exist and a compute that the user is not authorized to use ?
