### ISSUE TITLE
Just tried create a New file and VS Code threw error "UserCancelledError"

### ISSUE THREAD

**Issue by pc300000** [microsoft/vscode-tools-for-ai#1458]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: {
    "name": "UserCancelledError"
}

Version: 0.6.28
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.64.0
Language: en

<details>
<summary>Call Stack</summary>

```
t.MultiStepInput.<anonymous> extension.js:2:4823043
l extension.js:2:4819306
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by sevillal** [comment]
@pc300000 thanks for filing this. I have some questions:
- What type of file are you creating? 
- Before seeing this error, did you see a notification and you closed it or cancelled it?

**Comment by sevillal** [comment]
Details: The issue might be caused because azure tools ui is relying on the constructor name of the error object, the webpacked version might be changing it and preventing to block the notification.

**Comment by sevillal** [comment]
This should be fixed in next release.
