### ISSUE TITLE
Edit in VS Code always opens in VS Code vs. VS Code Insiders

### ISSUE THREAD

**Issue by rukiafarraj** [microsoft/vscode-tools-for-ai#1460]
## Expected Behavior
Launching VS Code from AzureML opens with VS Code Insiders (preview features version)

## Actual Behavior
Actually opens in VS Code without preview features, workaround is to search through a really long list to find Insiders.

## Steps to Reproduce the Problem
1. In an Azure Machine Learning workspace, with compute instance running
2. Navigate to Notebooks
3. Open or create a new notebook
4. In the global toolbars, click "Edit in VS Code"

## Specifications
  - Version:
  - Platform:

**Comment by tbombach** [comment]
We've had some discussions about how VS Code insiders would be supported. From a technical standpoint, our extension does support VS Code insiders. The studio opens VS Code/our extension by using a custom URI format: `vscode://`. The corresponding URI format for insiders is `vscode-insiders://` These get registered with the user's OS, so we don't have a way of responding to one URI format and opening the other version of VS Code.

If this is important to a lot of users, we could work to change the studio UI to add another options to open in VS Code insiders. However, this might confuse users on which to use and could cause confusions if a user is set up in one version (logged in, downloaded extension, etc) but not in the other version. 

As a workaround, the user can copy the URL from the studio that opens VS Code and modify it to change `vscode://` to `vscode-insiders://`

**Comment by rukiafarraj** [comment]
Thanks, Thomas - this is a good workaround for now unless we start to get additional feedback.

**Comment by shsuman** [comment]
Closing this for now. Please reopen if need be :)
