### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Invalid response: 400 Bad Request)

### ISSUE THREAD

**Issue by rukiafarraj** [microsoft/vscode-tools-for-ai#1463]
## Expected Behavior
Successfully launch VS Code from AzureML

## Actual Behavior
400 error (tried a few different workspaces/files to launch from)

## Steps to Reproduce the Problem

1. In an Azure Machine Learning workspace, with compute instance running
2. Navigate to Notebooks
3. Create a new file or open existing file
4. In the global toolbars, click "Edit in VS Code"
![Snag_adc6540](https://user-images.githubusercontent.com/98782203/154339708-309a3cb1-013d-4d07-a842-d44ed7def536.png)

## Specifications

  - Version:
  - Platform:

**Comment by sevillal** [comment]
@rukiafarraj closing this since you mentioned your compute was shutdown.

Improvements for this scenario will be tracked by: https://github.com/microsoft/vscode-tools-for-ai/issues/1489
