### ISSUE TITLE
Cannot read properties of undefined (reading 'trim) 

### ISSUE THREAD

**Issue by jplummer01** [microsoft/vscode-tools-for-ai#1464]
Does this occur consistently? Yes
Repro steps:
Expand Machine Learning Node and attempt to connect to compute instance. Error is "Cannot read properties of undefined (reading 'trim') and same error when chossing default subscription

Action: azureAccount.onSubscriptionsChanged
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'trim')

Version: 0.6.28
OS: win32
OS Release: 10.0.22543
Product: Visual Studio Code - Insiders
Product Version: 1.65.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:168982extension.bundle.js:2:168982
Function.StringUtils.trimArrayEntries extension.bundle.js:2:168956
new ScopeSet extension.bundle.js:2:185274
SilentFlowClient.<anonymous> extension.bundle.js:2:247421
step extension.bundle.js:2:147853
Object.next extension.bundle.js:2:147958
extension.bundle.js:2:146868extension.bundle.js:2:146868
__awaiter extension.bundle.js:2:146554
SilentFlowClient.acquireCachedToken extension.bundle.js:2:246780
SilentFlowClient.<anonymous> extension.bundle.js:2:246481
step extension.bundle.js:2:147853
Object.next extension.bundle.js:2:147958
extension.bundle.js:2:146868extension.bundle.js:2:146868
__awaiter extension.bundle.js:2:146554
SilentFlowClient.acquireToken extension.bundle.js:2:246337
PublicClientApplication.acquireTokenSilent extension.bundle.js:2:296828
```

</details>

**Comment by sevillal** [comment]
@jplummer01 Thanks for opening this issue. 

- Could you please let us know what version of the Azure Account extension are you using?
- After seeing the error, are you able to connect to the compute instance or interact with the tree view?

**Comment by jplummer01** [comment]
Azure Machine Learning v0.6.28
Azure Machine Learning  - Remote v0.7.0
Azure Machine Learning  - Inference v0.1.0

**Comment by jplummer01** [comment]
confirmed that downgrading to Azure Account extension v0.9.11 worked
