### ISSUE TITLE
Investigate if "machinelearningservices" interfere with "ml" extension in the CLI

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1469]
I followed these instructions to make sure my cli extension is set up correctly: [Install and set up the CLI (v2) - Azure Machine Learning | Microsoft Docs](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli)Here is the output from my commands:

```
C:\WINDOWS\system32>az extension add -n ml -y
The installed extension 'ml' is in preview.C:\WINDOWS\system32>az extension list
No module named 'azure.ml'
[
{
"experimental": null,
"extensionType": "whl",
"name": "machinelearningservices",
"path": "F:\\git\\sdk-cli-v2\\sdk-cli-v2\\src\\cli\\src\\machinelearningservices",
"preview": null,
"version": null
},
{
"experimental": false,
"extensionType": "whl",
"name": "ml",
"path": "F:\\git\\sdk-cli-v2\\sdk-cli-v2\\src\\cli\\src\\ml",
"preview": true,
"version": "2.0.7"
}
]
```

However, I still get this message in VSCode about needing to install CLI extension and I am still not able to execute a YAML file. Any ideas what could be missing?

![image](https://user-images.githubusercontent.com/56176070/155205615-7fa20c3e-e133-43a8-b795-3adbf23892e2.png)

**Comment by shsuman** [comment]
I am getting this error message when trying to install machinelearningservices extension.

No matching extensions for 'machinelearningservices'. Use --debug for more information.

**Comment by shsuman** [comment]
One proposed solution is we can check for these conflicting extensions: [machinelearningservices, azure-cli-ml] and then prompt the users to uninstall them and then install the ml extension.

**Comment by shsuman** [comment]
After some more investigation, its clear that there are these two conflicting extension namely machinelearningservices, azure-cli-ml, and the only way for us is to make sure that the users get correctly prompted to uninstall these extensions. Also, the azure-cli-ml extension on a new CI is conscious choice by Azure ML and will be upgraded to ml extension in the future.

Closing this as our investigation is complete and #1513 has been opened to address this issue.
