### ISSUE TITLE
Docs need an update

### ISSUE THREAD

**Issue by chris-han** [Microsoft/vscode-tools-for-ai#147]
In the getting start [page,](https://github.com/Microsoft/vscode-tools-for-ai/blob/master/docs/getting-started-aml-vscode.md) the last step 'Attach your folder to your experiment' is not there any more. Instead I see 'Set as Active Experiment'. I'm on v 0.4.2.

**Comment by greazer** [comment]
Need to modify the github page to Shane's msdn updated docs.

**Comment by greazer** [comment]
This has been addressed
