### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by YoshioHagino** [microsoft/vscode-tools-for-ai#1471]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: {
    "name": "UserCancelledError"
}

Version: 0.6.28
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.64.2
Language: ja

<details>
<summary>Call Stack</summary>

```
extension.js:2:4673269extension.js:2:4673269
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by sevillal** [comment]
@YoshioHagino thanks for filing this issue.

- Once you reach this error, can you interact with the Azure ML extension treeview?
- What version of the Azure Account extension are you using?
- If your Azure Account is version v0.10.0, what is your vscode setting for "Azure: Authentication Library"?

**Comment by sevillal** [comment]
Dup of https://github.com/microsoft/vscode-tools-for-ai/issues/1458

Related to the user cancelled error shown in the notification. There is a fix already in place in our next release.
