### ISSUE TITLE
Cannot read subscription property

### ISSUE THREAD

**Issue by rajmadhavan** [microsoft/vscode-tools-for-ai#1473]
Does this occur consistently? 
Repro steps:

1.
2.

Action: handleUri
Error type: TypeError
Error Message: Cannot read property 'subscription' of undefined

Version: 0.6.28
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
p.<anonymous> extension.js:2:4112862
a extension.js:2:4112187
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by sevillal** [comment]
@rajmadhavan thanks for filing this issue.

Could you please elaborate what are you trying to do with the extension? Are you trying to connect to a remote compute instance?

Also, could you please try the following?

1. Open VS Code
2. Click on the Azure icon on the left hand side and expand the Azure Machine Learning extension section
3. Please make sure the subscription you want to use is not filtered (it should be visible in the tree view)
4. Retry the operation you wanted to perform

![image](https://user-images.githubusercontent.com/56176070/157126925-3c8ffb89-baef-4411-b40f-fd6bc3125f35.png)

**Comment by shsuman** [comment]
Closing this as there has been no response in over two weeks. Please reopen if need be :)
