### ISSUE TITLE
Azure ML not updating Mac OS (Mac mini)

### ISSUE THREAD

**Issue by iyerk-ml** [microsoft/vscode-tools-for-ai#1474]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: {
    "name": "UserCancelledError"
}

Version: 0.6.28
OS: darwin
OS Release: 21.3.0
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:4673269
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by sevillal** [comment]
@iyerk-ml thanks for filing this issue.

Could you please elaborate on what do you mean by "Azure ML not updating"? Also could you please describe what are you trying to do with the extension to have more context?

**Comment by sevillal** [comment]
Dup of https://github.com/microsoft/vscode-tools-for-ai/issues/1458

User cancelled error shown in notification. This should be fixed in our next release.
