### ISSUE TITLE
Server did not start successfully

### ISSUE THREAD

**Issue by jplummer01** [microsoft/vscode-tools-for-ai#1476]
## Expected Behavior
From Azure ML Extension, right click on cpmpute instance and "connect to compute instance" to start  a new instance of VS Code and connect to remote compute

## Actual Behavior
Server Did not start successfully error

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

Version: 1.65.0-insider (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T03:15:15.809Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22563

Server did not start successfully. Full server log at /home/azureuser/.vscode-server-insiders/.b5205cc8eb4fbaa726835538cd82372cc0222d43.log >>>
server.sh is being replaced by 'bin/code-server-insiders'. Please migrate to the new command and adopt the following new default behaviors:
* connection token is mandatory unless --without-connection-token is used
* host defaults to `localhost`
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
To accept the license terms, start the server with --accept-server-license-terms
<<< End of server log
e335a3fb-de4e-4cdc-8d8f-d7b1322989ef: start
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/tmp==
platform==linux==
e335a3fb-de4e-4cdc-8d8f-d7b1322989ef: end
[Error - 2022-03-02 11:41:56.555] VS Code server installation failed with error: The VS Code server failed to start Retrying...
[Error - 2022-03-02 11:42:01.488] VSCodeServerInstallerError: 
	at s (c:\Users\xxxxxxx\.vscode-insiders\extensions\ms-toolsai.vscode-ai-remote-0.7.0\dist\src\extension.js:2:1970141)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async T.resolve (c:\Users\xxxxxxxx\.vscode-insiders\extensions\ms-toolsai.vscode-ai-remote-0.7.0\dist\src\extension.js:2:1988800)
	at async d.$resolveAuthority (c:\Users\xxxxxxx\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:20312) []

**Comment by sevillal** [comment]
@jplummer01 thanks for filing this issue.

This should be fixed in version 0.8.0 of the Azure Machine Learning - Remote extension, could you please try upgrading and connecting again?

Please reopen this issue if the 0.8.0 does not fix your problem.
