### ISSUE TITLE
VS Code Server Installation Error on Azure Machine Learning Cluster

### ISSUE THREAD

**Issue by ThiagoCM** [microsoft/vscode-tools-for-ai#1478]
After the latest Visual Code update (1.65), I'm not able to connect to my Compute Cluster in an Azure Machine Learning Workspace anymore. 

<img width="814" alt="image" src="https://user-images.githubusercontent.com/7265826/156828935-06120a8b-db91-4f8c-ac4c-2d87dfbe1c41.png">

After trying to install the Visual Code Server on the compute cluster that's running, the following message appears,

<img width="759" alt="image" src="https://user-images.githubusercontent.com/7265826/156829047-0b2b084b-d24e-498e-8ea3-6f294c37ff22.png">

Any thoughts?

**Comment by eyast** [comment]
This is not cluster-specific and I am facing the same issues. The VSCode server would not install (I have eve tried to create a new compute instance: in vain)
Output view of Vscode:
[Error - 2022-03-07 01:36:16.052] VS Code server installation failed with error: The VS Code server failed to start Retrying...
[Error - 2022-03-07 01:38:43.241] VSCodeServerInstallerError: 
	at s (c:\Users\eyast\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.7.0\dist\src\extension.js:2:1970141)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async T.resolve (c:\Users\eyast\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.7.0\dist\src\extension.js:2:1988800)
	at async d.$resolveAuthority (c:\Users\eyast\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:20312) []


Log contents:
server.sh is being replaced by 'bin/code-server'. Please migrate to the new command and adopt the following new default behaviors:
* connection token is mandatory unless --without-connection-token is used
* host defaults to `localhost`
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
To accept the license terms, start the server with --accept-server-license-terms

**Comment by arnabbiswas1** [comment]
On my windows box, I have VSCode 1.65.0. This instance is not able to connect to the compute instance.

On my windows box, I have VSCode 1.61.2. This instance is connecting to the same compute instance seamlessly.

**Comment by eyast** [comment]
I opened a severity B ticket and a support engineer has reached out to collect info/logs.

**Comment by sevillal** [comment]
@ThiagoCM @eyast @arnabbiswas1 thanks for filing and commenting on this issue.

This should be fixed in version 0.8.0 of the Azure Machine Learning - Remote extension, could you please try upgrading and connecting again?

If the issue persist, please reopen this bug and we will take a look ASAP.

**Comment by arnabbiswas1** [comment]
Thanks! It's working with version  0.8.0 of the Azure Machine Learning - Remote extension!

**Comment by ThiagoCM** [comment]
Working just fine! Thanks a lot.
