### ISSUE TITLE
Unable to connect to remote compute instance. 

### ISSUE THREAD

**Issue by GMGSPT** [microsoft/vscode-tools-for-ai#1481]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: {
    "name": "UserCancelledError"
}

Version: 0.6.28
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.65.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:4673269extension.js:2:4673269
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by sevillal** [comment]
@GMGSPT thanks for filing this issue.

We recently fixed an issue connecting to remote compute instance in version 0.8.0 of the Azure Machine Learning - Remote extension, could you please try upgrading and connecting again?

Please reopen this issue if the 0.8.0 does not fix your problem.
