### ISSUE TITLE
Remote connection extension VS code crashing

### ISSUE THREAD

**Issue by mrussoCGNZ** [microsoft/vscode-tools-for-ai#1483]
## Expected Behavior
Connect to compute instance remotely from AZ Machine Learning Remote extension

## Actual Behavior
[Error - 2022-03-07 09:45:19.891] Error: {
    "name": "UserCancelledError"

## Steps to Reproduce the Problem

  1. Compute instance remote connection
  2. Installing VS Code server on m015761-sherlocketl Retry - n
  3. After different retries shows . "Maximum retries exhausted. Could not install VS Code server on m015761-sherlocketl: The VS Code server failed to start"

## Specifications

Version: 1.65.0 (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by marcusRB** [comment]
> @mrussoCGNZ thanks for filing this issue.
> 
> This should be fixed in version 0.8.0 of the Azure Machine Learning - Remote extension, could you please try upgrading and connecting again?
> 
> Please reopen this issue if the 0.8.0 does not fix your problem.

Resolved with v 0.8.0 - Thanks @sevillal
