### ISSUE TITLE
"Installing VS Code server on computename" fails after max retries

### ISSUE THREAD

**Issue by madamak** [microsoft/vscode-tools-for-ai#1484]
## Expected Behavior
Successful connection to a remote compute instance. I have tried from the Azure ML Studio interface but also from the Azure Extension on VS Code but no method have worked. It was working fine before.

## Actual Behavior
Unsusccessfull connection. Extension shows "Installing VS Code server on computename" (which is weird since I used it last week). It fails, then retries 10 times until it proposes to kill server and retry (which does not work).

## Steps to Reproduce the Problem
Everything was working fine for a week. While I was working on the remote I saw that VS Code had a new update available. I installed it (it was Thursday or Friday). Since then, I have the issue.

I have tried https://github.com/microsoft/vscode-tools-for-ai/issues/1419
I also have tried rm -rf /home/azureuser/.vscode-server/ via the Terminal on Azure ML Studio.
You will find full logs of the extension.

Edit:
I have tried uninstalling VS Code completely (all extensions and everything) from my laptop and reinstalling it.
I have tried creating new compute instances.

## Specifications

  - VS Code Version: 1.65.0
  - Platform: Mac OS 11.6.2 on Macbook Air M1

[AzureML-connect_to_remote.log](https://github.com/microsoft/vscode-tools-for-ai/files/8196695/AzureML-connect_to_remote.log)

**Comment by sevillal** [comment]
@madamak thanks for filing this issue. 

This should be fixed in version 0.8.0 of the Azure Machine Learning - Remote extension, could you please try upgrading and connecting again?

Please reopen this issue if the 0.8.0 does not fix your problem.

**Comment by eliorc** [comment]
I'm on version 0.34.0 and this still happens

**Comment by sevillal** [comment]
@eliorc I've opened a new issue here, could you please add more information about the error you are facing? https://github.com/microsoft/vscode-tools-for-ai/issues/2165
