### ISSUE TITLE
Failed to login to Azure Account

### ISSUE THREAD

**Issue by mantrasys** [microsoft/vscode-tools-for-ai#1486]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: Failed to login to Azure Account.

Version: 0.6.28
OS: darwin
OS Release: 21.3.0
Product: Visual Studio Code
Product Version: 1.65.0
Language: en

<details>
<summary>Call Stack</summary>

```
g.<anonymous> extension.js:2:4669439
a extension.js:2:4666664
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by sevillal** [comment]
@mantrasys thanks for filing this issue.

- What version of the Azure Account extension are you using? 
- If your Azure Account is version v0.10.0, what is your vscode setting for "Azure: Authentication Library"?
- Once you reach this error, can you interact with the Azure ML extension treeview?

**Comment by shsuman** [comment]
Closing this as We have not received any response for over 7 days. Please feel free to reopen it if need be :)
