### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ya13yo** [microsoft/vscode-tools-for-ai#1487]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: {
    "name": "UserCancelledError"
}

Version: 0.6.28
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.65.0
Language: ru

<details>
<summary>Call Stack</summary>

```
extension.js:2:4673269extension.js:2:4673269
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by sevillal** [comment]
Dup https://github.com/microsoft/vscode-tools-for-ai/issues/1458
