### ISSUE TITLE
Make remote connection new window/same window behavior consistent with Codespaces/remote SSH

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1490]
## Goal
Minimize the number of windows when connecting to remote

## Proposal
When opening a CI remote connection handle new windows as follows:
- If the VS Code window handling the URI does not have a workspace open, then reuse the window
- If the VS Code window handling the URI does have a workspace open, then open the remote connection in a new window

**Comment by tbombach** [comment]
@SiddhanthUnnithan This covers the "Open from studio" scenario pretty well and details how we want to open a new window vs keep same window. However, we've also discussed with Kai that other remote extensions usually open a remote connection in the same window (e.g. if they use the Remote connections pane). Do we want to make our default behavior that we open remote connections in the same window if the user connects to a CI from the tree?
