### ISSUE TITLE
Microsoft BLOWS

### ISSUE THREAD

**Issue by Brient** [microsoft/vscode-tools-for-ai#1492]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: {
    "name": "UserCancelledError"
}

Version: 0.6.28
OS: win32
OS Release: 10.0.22567
Product: Visual Studio Code
Product Version: 1.65.1
Language: en

<details>
<summary>Call Stack</summary>

```
t.MultiStepInput.<anonymous> extension.js:2:4823043
l extension.js:2:4819306
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by sevillal** [comment]
@Brient thanks for filing this issue.

Some questions to understand when this is happening:
- Are you doing some specifics with the Azure ML extension?
- Does it block the action you are trying to achieve with the ML extension?

**Comment by Brient** [comment]
Yes not only did it block the install, MICROSOFT kept the program from
plugging in to VSCode. & fubarred the entire installation & now don’t how
to correct build.
Even though I changed the firewall settings to private to allow file
sharing, it still stops the blasted programs!

**Comment by sevillal** [comment]
@Brient I am sorry  you are running into these issues.

We might need some details to help triage the issue:
- Could you please describe the steps you are doing? (i.e. 1. opening vscode, 2. Opening Azure ML extension treeview, 3. Expanding nodes and right click on Compute Instance to connect)
- You mention "block the install", what install are you referring to?
- You mention "kept the program from plugging in to VSCode", what program are you referring to?

**Comment by shsuman** [comment]
Closing this as We have not received any response for over 7 days. Please feel free to reopen it if need be :)
