### ISSUE TITLE
Not able to select Python Interpreter

### ISSUE THREAD

**Issue by arnabbiswas1** [microsoft/vscode-tools-for-ai#1493]
Does this occur consistently? yes
Repro steps:
1. Connect to Azure ML Compute Instance from local installation of VSCode in my Windows laptop
2. Pop up comes up with Forbidden message

![image](https://user-images.githubusercontent.com/4428191/157446591-fc2a83e3-b2ce-435b-96d3-3352781befe6.png)
3. Once connected to the remote compute instance, I can select the Python Interpreter (through Shift + Ctrl + P). But the status bar does not show anything indicating that (probably) default environment is selected.

![image](https://user-images.githubusercontent.com/4428191/157446907-ac387502-9761-4202-9fed-2586b1f47546.png)

Action: azureAccount.onSubscriptionsChanged
Error type: 403
Error Message: Forbidden

Version: 0.6.28
OS: linux
OS Release: 5.4.0-1064-azure
Product: Visual Studio Code
Product Version: 1.65.1
Language: en

<details>
<summary>Call Stack</summary>

```
t.createAzureMLHttpError extension.js:2:4074057
n.<anonymous> extension.js:2:4076966
a extension.js:2:4075585
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by sevillal** [comment]
@arnabbiswas1 thanks for filing this issue.

I can identify two different problems from this issue:
- Forbidden message, I have open the following issue to track this https://github.com/microsoft/vscode-tools-for-ai/issues/1494
- Not able to select python interpreter

Some questions regarding the issues you are facing:

1. What version of Azure ML Remote extension and Python extension do you have installed
2. How are you connecting to the remote CI? From ML Studio or from the extension treeview?
3. Does the "Forbidden" message block you from connecting to the remote? Or does the remote connection succeds?
4. After you set the interpreter can you open a python file and check if you see the interpreter information on your status bar right hand side
![image](https://user-images.githubusercontent.com/56176070/157495757-ccd90583-33c4-46ed-a2a3-19cfb8a08a39.png)

**Comment by arnabbiswas1** [comment]
Thanks for your quick reply! :-)

1. What version of Azure ML Remote extension and Python extension do you have installed
- Azure ML Remote extension - v0.8.0
- Python extension - v2022.2.1924087327
2. How are you connecting to the remote CI? From ML Studio or from the extension treeview?
- From the extension tree view
3. Does the "Forbidden" message block you from connecting to the remote? Or does the remote connection succeeds?
- Remote connection succeeds
4. After you set the interpreter can you open a python file and check if you see the interpreter information on your status bar right hand side
- Yes, I can see the interpreter information on mouse hovering. I was not aware of this option.
![Screenshot (5)](https://user-images.githubusercontent.com/4428191/157594978-911420b4-85f9-400d-b8d8-68b2f8436420.png)

**Overall, I am having a feel that this is not major issue, since there is workaround.**

**Comment by sevillal** [comment]
Thanks @arnabbiswas1 for your reply. One question, are you still seeing the "Forbidden" error message?

**Comment by arnabbiswas1** [comment]
@sevillal Yes, I am still getting the "Forbidden" error message?

Since the issue has been closed, I want to re-emphasize on the point that the name of the interpreter is not actually visible on right side of the status bar (as shown in the first message of this thread). 

 Interpreter information is available on right side of the status bar only mouse hovering. For an end user this could be confusing (I am assuming that most of the users will check on the right side of the status bar.)

**Comment by sevillal** [comment]
@arnabbiswas1 We'll track the Forbidden issue at https://github.com/microsoft/vscode-tools-for-ai/issues/1494

About the Python interpreter it is an experiment that Python extension is running, please refer to: https://github.com/microsoft/vscode-python/issues/18283
