### ISSUE TITLE
Forbidden error message

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1494]
Action: azureAccount.onSubscriptionsChanged
Error type: 403
Error Message: Forbidden

Version: 0.6.28
OS: linux
OS Release: 5.4.0-1064-azure
Product: Visual Studio Code
Product Version: 1.65.1
Language: en

Call Stack
t.createAzureMLHttpError extension.js:2:4074057
n.<anonymous> extension.js:2:4076966
a extension.js:2:4075585
processTicksAndRejections task_queues.js:93:5

**Comment by shsuman** [comment]
Closing this as We have not received any response for over 7 days. Please feel free to reopen it if need be :)
