### ISSUE TITLE
Log-In issue.

### ISSUE THREAD

**Issue by singha04** [microsoft/vscode-tools-for-ai#1496]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: Failed to login to Azure Account.

Version: 0.6.28
OS: darwin
OS Release: 21.3.0
Product: Visual Studio Code
Product Version: 1.65.1
Language: en

<details>
<summary>Call Stack</summary>

```
g.<anonymous> extension.js:2:4669439
a extension.js:2:4666664
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by sevillal** [comment]
@singha04 thanks for filing this issue.

Could you please share what version of the Azure Account extension are you using?

**Comment by shsuman** [comment]
Closing this as We have not received any response for over 7 days. Please feel free to reopen it if need be :)
