### ISSUE TITLE
VS code error

### ISSUE THREAD

**Issue by amitdingareNovelis** [microsoft/vscode-tools-for-ai#1499]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.6.28
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code - Insiders
Product Version: 1.66.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
g.<anonymous> extension.js:2:4669826
a extension.js:2:4666664
```

</details>

**Comment by tbombach** [comment]
Hi @amitdingareNovelis, thank you so much for reporting this! Would you mind sharing what version of the Azure Account extension you are using? Additionally, we've seen issues like this sometimes go away if you reload the VS Code window (Ctrl + Shift + P, then search for the "Restart Window" command). We'll try to get to the bottom of this but hopefully this helps in the meantime

**Comment by shsuman** [comment]
Closing this as we have not received any response in over 7 days. Please reopen if need be :)
