### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by edgaradel** [microsoft/vscode-tools-for-ai#1501]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: Failed to login to Azure Account.

Version: 0.6.28
OS: darwin
OS Release: 21.3.0
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
g.<anonymous> extension.js:2:4669439
a extension.js:2:4666664
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by tbombach** [comment]
Hi @edgaradel, thank you so much for reporting this! Would you mind sharing what version of the Azure Account extension you are using? Additionally, we've seen issues like this sometimes go away if you reload the VS Code window (Ctrl + Shift + P, then search for the "Restart Window" command). We'll try to get to the bottom of this but hopefully this helps in the meantime

**Comment by shsuman** [comment]
Closing this as we have not received any response in over 7 days. Please reopen if need be :)
