### ISSUE TITLE
"You have been signed out because reading stored authentication information failed"

### ISSUE THREAD

**Issue by ErnieZapata** [microsoft/vscode-tools-for-ai#1502]
Launching VSCode will result in a popup stating "You have been signed out because reading stored authentication information failed.". Started happening yesterday, 03/17/2022. Not sure if related, but I changed my network domain password the previous day and not sure why this would matter.

I have attached the log output for "Microsoft Authentication". Logs for Settings Sync do not seem to show any errors.

## Expected Behavior

Expect to launch VS Code with no alerts.

## Actual Behavior

Rendering alert with "You have been signed out because reading stored authentication information failed."

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

  - Platform:
OS: Windows_NT x64 10.0.19042

**Comment by ErnieZapata** [comment]
[MicrosoftAuthentication.log](https://github.com/microsoft/vscode-tools-for-ai/files/8307647/MicrosoftAuthentication.log)

**Comment by tbombach** [comment]
Hi @ErnieZapata! Thank you so much for reporting this! Does this error message still occur if the Azure Machine Learning extension is uninstalled? We rely on the [Azure Account extension for Visual Studio Code](https://github.com/microsoft/vscode-azure-account/) to store/retrieve authentication information, so that would help narrow down if the error is coming from that extension

**Comment by ErnieZapata** [comment]
@tbombach 

FYI - I was provided with a solution on StackOverflfow which has resolved the issue - https://stackoverflow.com/questions/71558011/visual-studio-code-authentication-error
