### ISSUE TITLE
Azure ml set as default

### ISSUE THREAD

**Issue by maheakdave** [microsoft/vscode-tools-for-ai#1503]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: {
    "name": "UserCancelledError"
}

Version: 0.6.28
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
t.MultiStepInput.<anonymous> extension.js:2:4823043
l extension.js:2:4819306
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by tbombach** [comment]
Hi @maheakdave, thank you for reporting this! We have a fix for this issue in our next release, which we expect to make public next week.

Duplicate of https://github.com/microsoft/vscode-tools-for-ai/issues/1458
