### ISSUE TITLE
Trying to create compute instance and job not working

### ISSUE THREAD

**Issue by KrisvanderMast** [microsoft/vscode-tools-for-ai#1506]
Does this occur consistently? YES
Repro steps:

I've been following this video [(2437) Supercharge Your Azure ML Development Through Visual Studio Code - YouTube](https://www.youtube.com/watch?v=YJePRMYCTOM) but I noticed that quite a lot of things are not (anymore) working.
- setting a default workspace by right clicking it doesn't function - via the command palette it can be done still
- Creating a compute instance: in the video this is done nicely via a wizard but it seems nowadays only an empty yaml file (with only a schema reference shows up - really bad user experience experience. I had to search on all kinds of pages until I finally stumbled onto this page: [CLI (v2) compute instance YAML schema - Azure Machine Learning | Microsoft Docs](https://docs.microsoft.com/en-us/azure/machine-learning/reference-yaml-compute-instance). 
- After creating a compute instance I was able to connect to the compute instance- However the next day I could only connect but the setup on the vm for VS Code remoting didn't work anymore. I had to delete the vm and go through the same process again.- In the video later on (https://youtu.be/YJePRMYCTOM?t=457) it goes through setting up a job experiment. Again no wizard nor getting that json to start a job. Here I basically gave up.

Please fix this. I wanted to show this coming Friday during the global ai bootcamp but I'm likely not going to as things aren't working as they're supposed to at the moment.

Version: 0.6.28
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:4673269extension.js:2:4673269
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by shsuman** [comment]
@KrisvanderMast I am sorry that you are facing all these problems. The extension is going through major changes right now and the video you are referring to uses an old version of the extension.

* The quick picks and wizards are gone now and we have shifted to a Yaml file authoring based experience.
* The connect to Compute instance part is still there and should work.

Would you like to connect with me on Thursday, I can provide you with pre-release builds of our extensions and then you can decide if you would like to show that at the bootcamp ?

**Comment by shsuman** [comment]
Closing this as @SiddhanthUnnithan has scheduled a meeting with @KrisvanderMast
