### ISSUE TITLE
Azure ML "Edit in VSCode" fails to launch for specific subscription

### ISSUE THREAD

**Issue by charleswm** [microsoft/vscode-tools-for-ai#1508]
Does this occur consistently? Yes
Repro steps:

1. Click "Edit in VSCode"
![image](https://user-images.githubusercontent.com/11549389/159737490-6ed490de-c43b-4346-8729-f5c4ca4ab972.png)
2. VSCode launches locally as expected
![image](https://user-images.githubusercontent.com/11549389/159737394-a2c49fcb-d5cd-46d7-ba19-7fb2f71466e6.png)
3. Azure ML Connection fails to launch because it can't read the subscription.
![image](https://user-images.githubusercontent.com/11549389/159737327-f2d14f21-75e2-40b3-9c2c-131a45a5f5bc.png)

I am logged into my Microsoft account in VSCode and set the default workspace to the workspace in question.

This functionality works on other workspaces/subsccriptions I have. Not sure if it's a permissions thing or what, but the error message is not very informative.

Action: handleUri
Error type: TypeError
Error Message: Cannot read property 'subscription' of undefined

Version: 0.6.28
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
p.<anonymous> extension.js:2:4112862
a extension.js:2:4112187
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by shsuman** [comment]
@sevillal  Can you please take a look at this ? I believe this is related to the Azure Account migration.

**Comment by sevillal** [comment]
@charleswm thanks for filing this issue. 

There is a new version of the Azure ML and Azure ML - Remote extensions, could you please update them and try to repro?

Please reopen this is the issue persist.

**Comment by charleswm** [comment]
@sevillal It seems to be fixed. I was able to connect to this workspace and run some cells. Thanks!
