### ISSUE TITLE
unable to login to azure ml from vscode

### ISSUE THREAD

**Issue by SailajaSarbada** [microsoft/vscode-tools-for-ai#1510]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: Failed to login to Azure Account.

Version: 0.6.28
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

<details>
<summary>Call Stack</summary>

```
g.<anonymous> extension.js:2:4669439
a extension.js:2:4666664
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by shsuman** [comment]
Closing this as we haven't received a response in over 7 days. Please reopen if need be :)
