### ISSUE TITLE
Notebooks

### ISSUE THREAD

**Issue by LidiaEnriquez2307** [Microsoft/vscode-tools-for-ai#1511]
Does this occur consistently? 
Repro steps:

1.
2.

Action: handleUri
Error type: TypeError
Error Message: Cannot read property 'subscription' of undefined

Version: 0.6.28
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
p.<anonymous> extension.js:2:4112862
a extension.js:2:4112187
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by shsuman** [comment]
@sevillal This seems to be the same Azure Account issue mentioned in #1508. Can you please take a look into it ?

**Comment by sevillal** [comment]
@LidiaEnriquez2307 thanks for filing this issue.

There is a new version of the Azure ML and Azure ML - Remote extensions, could you please update them and try to repro?

Please reopen this is the issue persist.
