### ISSUE TITLE
Cannot connect to Azure ML Compute from VS Code on laptop

### ISSUE THREAD

**Issue by jofishe** [microsoft/vscode-tools-for-ai#1512]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscodeai.azureml.computeInstance.connectToJupyterServer
Error type: Error
Error Message: command 'jupyter.selectjupyteruri' not found

Version: 0.6.28
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code - Insiders
Product Version: 1.66.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
S._tryExecuteCommand workbench.desktop.main.js:1660:3532
S.executeCommand workbench.desktop.main.js:1660:3414
```

</details>

**Comment by shsuman** [comment]
Hey @jofishe, Can you please try this in the stable VSCode instead of insiders and let me know your findings ?

**Comment by shsuman** [comment]
Closing this as We have not received any response for over 7 days. Please feel free to reopen it if need be :)
