### ISSUE TITLE
issue connecting to Azure Gov in VScode

### ISSUE THREAD

**Issue by islamtg** [microsoft/vscode-tools-for-ai#1517]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: r
Error Message: {
    "name": "UserCancelledError"
}

Version: 0.6.28
OS: win32
OS Release: 10.0.22581
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:4673269extension.js:2:4673269
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by shsuman** [comment]
@islamtg Can you please update the extension to latest version and try again ?

Azure ML - 0.8.0
Azure ML - Remote - 0.10.0
