### ISSUE TITLE
Support for the attachment of Azure Lake Analytics and Azure Databrick computes 

### ISSUE THREAD

**Issue by swinner95** [microsoft/vscode-tools-for-ai#152]
The attachment of computes 'Azure Databricks' and 'Azure Lake Analytics'  should be supported and exposed from the command palette for users to select. The user should then be able to specify the properties in a JSON file to then 'Submit'.

**Comment by shsuman** [comment]
Needs info about the default properties that needs to be attached a the time of creation or is it the same as  VM and HDI i.e.
{
        address: '',
        sshPort: 22,
        administratorAccount: {
            username: '',
            privateKeyData: '',
            passphrase: ''
        }

**Comment by greazer** [comment]
@swinner95, Shane can you provide the info Shantnu needs?
