### ISSUE TITLE
Cannot get userid although already logged in with same user

### ISSUE THREAD

**Issue by nemetht** [microsoft/vscode-tools-for-ai#1522]
Does this occur consistently? 
Repro steps:

1.
2.

Action: AzureMLTreeDataProvider.getChildren
Error type: 124
Error Message: Failed to get user object id for user redacted:email

Version: 0.8.0
OS: linux
OS Release: 5.16.14-1-MANJARO
Product: Visual Studio Code
Product Version: 1.66.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:1993350
```

</details>

**Comment by sevillal** [comment]
@nemetht thanks for filing this issue. 

Is the subscription you are using assigned to a tenant other than the default? Could you please follow the instructions [here](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#configure-your-tenant-in-the-azure-account-extension)

**Comment by shsuman** [comment]
@nemetht Please accept my deepest apologies for the issues are facing.

We are aware of the issue and if everything goes well, we will release a fix tomorrow (0.8.1). In the meantime, if you would like to get unblocked you can try one of the following:

* If you have a multi tenant account and your subscription is assigned to a tenant other than the default, follow the instructions [here](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#configure-your-tenant-in-the-azure-account-extension)
* Alternatively,  you can downgrade the extension to the previous version by following the instructions [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions)

**Comment by nemetht** [comment]
Thanks for the support, using the "Azure: Select Tenant" solution it works fine.
