### ISSUE TITLE
Failed to load subscription

### ISSUE THREAD

**Issue by sksyp** [microsoft/vscode-tools-for-ai#1523]
Does this occur consistently? 
Repro steps:

1.
2.

Action: AzureMLTreeDataProvider.getChildren
Error type: 124
Error Message: Failed to get user object id for user redacted:email

Version: 0.8.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.66.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:1993350extension.js:2:1993350
```

</details>

**Comment by shsuman** [comment]
@sksyp thanks for filing this issue. 

Is the subscription you are using assigned to a tenant other than the default? Could you please follow the instructions [here](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#configure-your-tenant-in-the-azure-account-extension)

**Comment by shsuman** [comment]
@sksyp Could you please upgrade the Azure ML extension to 0.8.1 and confirm whether that resolves your issue ?

**Comment by shsuman** [comment]
Closing it because of inactivity :). Please reopen if need be
