### ISSUE TITLE
object id not found

### ISSUE THREAD

**Issue by xenonyu** [microsoft/vscode-tools-for-ai#1524]
Does this occur consistently? 
Repro steps:

1. connect vscode to azure ML
2. return user object id not found

Action: UriHandler.handleUri
Error type: 124
Error Message: Failed to get user object id for user redacted:email

Version: 0.8.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.66.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:1993350extension.js:2:1993350
```

</details>

**Comment by shsuman** [comment]
@xenonyu Do you have a multi tenant account ? You can check this by running the command (Ctrl + Shift + P) `Azure: Select Tenant`. You will see a list of tenants in the quickpick like this:

![image](https://user-images.githubusercontent.com/44413557/161490719-0ed2d769-fb34-4324-bf2c-7ca937a97711.png)

**Comment by shsuman** [comment]
@xenonyu Could you please upgrade the Azure ML extension to 0.8.1 and confirm whether that resolves your issue ?

**Comment by shsuman** [comment]
Closing it because of inactivity :). Please reopen if need be
