### ISSUE TITLE
azureAccount.onSubscriptionsChanged

### ISSUE THREAD

**Issue by Behordeun** [microsoft/vscode-tools-for-ai#1527]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND eastus2.api.azureml.ms

Version: 0.8.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.66.0
Language: en

<details>
<summary>Call Stack</summary>

```
new t extension.js:2:486489
t.<anonymous> extension.js:2:470040
extension.js:2:2452648extension.js:2:2452648
Object.throw extension.js:2:2452753
c extension.js:2:2451543
```

</details>

**Comment by shsuman** [comment]
@sevillal Can you please look into this ?

**Comment by sevillal** [comment]
@Behordeun thanks for filing this issue. 

Could you please provide more information on what were you trying to do with the extension that caused this issue?

**Comment by Behordeun** [comment]
@sevillal, I was activating the Microsoft extension on my VSC when the error message popped up. It occurred a couple of times, but I guess it has been fixed (let's hope it's permanently fixed).
