### ISSUE TITLE
Not able to connect to Azure ML computing instance

### ISSUE THREAD

**Issue by dataubc** [microsoft/vscode-tools-for-ai#1528]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.Open AzureML computing instane
2. Click on Vs code
3. You will see a message the user xxx may not have permissions to connect to the Compute instance xxxx. Please ensure that you're signed into the right Azure Account and connecting to the right Compute instance.( even though it does)

**Comment by sevillal** [comment]
Transferred the issue to the Azure ML Extension repo.

**Comment by shsuman** [comment]
@dataubc @lukedavoli @behrezaie @ehrlinger, Please accept my deepest apologies for the problems you are facing.

We are aware of the issue and if everything goes well, we will release a fix tomorrow (0.8.1). In the meantime, if you would like to get unblocked you can try one of the following:

* If you have a multi tenant account and your subscription is assigned to a tenant other than the default, follow the instructions [here](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#configure-your-tenant-in-the-azure-account-extension)
* Alternatively,  you can downgrade the extension to the previous version by following the instructions [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions)

**Comment by lukedavoli** [comment]
0.8.1 has solved this for me. Thanks for the quick turnaround on this issue! 💙

**Comment by shsuman** [comment]
@dataubc, @behrezaie, @ehrlinger Could you confirm whether 0.8.1 works for you or not ?

**Comment by ehrlinger** [comment]
0.8.1 works on both Windows and MacOS again. THX!

**Comment by behrezaie** [comment]
Downgrading Azure Machine Learning extension to v0.8.1 solved my issue as well. Thanks for your help @shsuman.

**Comment by shsuman** [comment]
@behrezaie Just to confirm, you mean upgrading the extension because 0.8.1 is the latest version HAHA ?

**Comment by shsuman** [comment]
Closing it because of inactivity :). Please reopen if need be
