### ISSUE TITLE
Error when running an experiment from the Command Palette

### ISSUE THREAD

**Issue by swinner95** [microsoft/vscode-tools-for-ai#153]
Issues when using the command palette to run an experiment:

When I do Ctrl+Shift+P and select 'AML:Run as Experiemnt in Azure..'
error: Cannot read property 'fsPath' of undefined

When I do Ctrl+Shift+P 'Azure Run Experiment( recently used)
Error: Cannot read property 'parant' of undefined OR
Error: Cannot read property 'fsPath' of undefined

**Comment by shsuman** [comment]
Well, running an experiment from command palette doesn't make much sense now. @greazer  should we remove the Run Experiment command completely ?

**Comment by greazer** [comment]
As we discussed, no. There should be one version of the command in the command palette. It should prompt the user for a py script to use and then do what right clicking on a file would normally do. If possible, default the file to the file that's currently open (if it's a python file).
