### ISSUE TITLE
Error when signing into Azure Account

### ISSUE THREAD

**Issue by bostdiek** [microsoft/vscode-tools-for-ai#1532]
Does this occur consistently? 
Repro steps:

1. Signed out of Azure account and then resign back in. Trying to get subscriptions from multiple accounts linked to my email address.
2. Only finds my primary subscription and not the other tenants.

Action: azureAccount.onSubscriptionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.8.1
OS: darwin
OS Release: 21.4.0
Product: Visual Studio Code
Product Version: 1.66.0
Language: en

<details>
<summary>Call Stack</summary>

```
b.<anonymous> extension.js:2:1992179
s extension.js:2:1989080
```

</details>

**Comment by bostdiek** [comment]
I agree, this does look to be more of an Azure Account than your extension
issue. Thank you for your help with this. The Select Tenant at least seems
like it is a solid workaround. I am at least able to connect to my compute
instances now.

**Comment by shsuman** [comment]
@bostdiek This is the response I got from Azure Account team:

*That has to do with their AAD configuration. I'm guessing some users have to explicitly select their tenant because their org uses a tenant other than the default tenant "common"*

I am going to close this issue now :)
