### ISSUE TITLE
avatarify-python-master % - won!'t be able to update !

### ISSUE THREAD

**Issue by singha04** [microsoft/vscode-tools-for-ai#1540]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSubscriptionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.8.0
OS: darwin
OS Release: 21.4.0
Product: Visual Studio Code
Product Version: 1.65.1
Language: en

<details>
<summary>Call Stack</summary>

```
v.<anonymous> extension.js:2:1992279
s extension.js:2:1989060
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by sevillal** [comment]
@singha04 thanks for filing this issue. I have some questions to help us triage this issue:

- Can you elaborate on the issue's title? "avatarify-python-master % - won!'t be able to update !" 
- What Azure ML extension feature are you trying to use?
- Is the issue blocking some of your work?
