### ISSUE TITLE
Migrate from @azure/ms-rest-node-auth to @azure/identity

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1550]
We currently use the https://www.npmjs.com/package/@azure/ms-rest-nodeauth package for authentication and Azure credential token interfaces. However, this is no longer maintained and we should move to the @azure/identity package.

Migration guide: https://github.com/Azure/ms-rest-nodeauth/blob/master/migrate-to-identity-v2.md There is a plugin package that we should use for vs code: https://www.npmjs.com/package/@azure/identity-vscode

**Comment by shsuman** [comment]
![image](https://user-images.githubusercontent.com/44413557/180201401-5740637e-17d9-409d-a568-e6b540da3a1b.png)

This is the response from Brandon Waterloo of the Azure Account team when asked about the migration. To summarize, there are some serious shortcomings in MSAL that limits users coming from alternative identity providers, non-pubic cloud or having a multi tenant account. Until those are addressed it is unfeasible to migrate. 

We should hold off until then as well.

**Comment by shsuman** [comment]
Blocked by https://github.com/microsoft/vscode-azure-account/issues/203
