### ISSUE TITLE
Can't sync with codes

### ISSUE THREAD

**Issue by rosban** [microsoft/vscode-tools-for-ai#1575]
Does this occur consistently? 
Repro steps:

1.
2.

Action: handleUri
Error type: TypeError
Error Message: Cannot read property 'subscription' of undefined

Version: 0.6.27
OS: linux
OS Release: 5.10.0-1050-oem
Product: Visual Studio Code
Product Version: 1.61.2
Language: en

<details>
<summary>Call Stack</summary>

```
p.<anonymous> extension.js:2:4261889
a extension.js:2:4261214
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by tbombach** [comment]
Hi @rosban, I apologize for this issue you're experiencing. I noticed that you're using version 0.6.27 - would you mind trying to update to the latest version of our Azure Machine Learning extension (and the latest version of the Azure Machine Learning - Remote extension) and seeing if you still experience this issue?

**Comment by rosban** [comment]
> Hi @rosban, I apologize for this issue you're experiencing. I noticed that you're using version 0.6.27 - would you mind trying to update to the latest version of our Azure Machine Learning extension (and the latest version of the Azure Machine Learning - Remote extension) and seeing if you still experience this issue?

An update solved it, thank you for the support :)
