### ISSUE TITLE
407 Authentication Required

### ISSUE THREAD

**Issue by konabuta** [microsoft/vscode-tools-for-ai#1576]
## Expected Behavior

Connect to Compute Instance from VSCode.

## Actual Behavior

Can't connect to Compute Instance from VSCode.

## Steps to Reproduce the Problem

  1. Start Azure ML Compute Instance
  1. Click VSCode
  1. Got Error

_Failed to connect to the remote extension host server (Error: Invalid response: 407 Proxy Authentication Required)_

![image](https://user-images.githubusercontent.com/3815677/169457917-985a34d2-d41c-4f94-8a77-c169ce96a07b.png)

## Specifications

  - VS Code Version: 1.67.1
  - Platform: Windows (client)

**Comment by konabuta** [comment]
According to the [document](https://docs.microsoft.com/en-US/azure/machine-learning/how-to-secure-workspace-vnet?tabs=pe%2Ccli#required-public-internet-access),  `update.code.visualstudio.com` & `*.vo.msecnd.net` & `raw.githubusercontent.com/microsoft/vscode-tools-for-ai/master/azureml_remote_websocket_server/*` are required for outbound traffic from Compute Instance. But I can't find required access from client PC that VSCode is installed to the public internet.

**Comment by shsuman** [comment]
@konabuta Can you please share the **Trace** logs with us ? 

You can enable **Trace** logging by changing the user setting azureML - Remote.logging.level to **trace**

![image](https://user-images.githubusercontent.com/44413557/161809386-9dd36d4e-3a50-4b01-98e0-72cf977c09cb.png)

Then just try to make a remote connection in the VSCode window and after it fails, open the output channel (Ctrl + Shift + U or View -> Output), and select the **Azure ML - Remote** output:

![image](https://user-images.githubusercontent.com/44413557/161811181-abc0a190-a968-4955-8d5b-e41923898c30.png)
