### ISSUE TITLE
No connection to AZURE

### ISSUE THREAD

**Issue by Kevin-Prod-Env** [microsoft/vscode-tools-for-ai#1577]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSessionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.10.0
OS: linux
OS Release: 5.4.0-1077-azure
Product: Visual Studio Code
Product Version: 1.67.2
Language: de

<details>
<summary>Call Stack</summary>

```
_.<anonymous> extension.js:2:2324475
s extension.js:2:2321343
```

</details>

**Comment by tbombach** [comment]
Hi @Kevin-Prod-Env, thank you for reporting this issue. Since [this other issue](https://github.com/microsoft/vscode-tools-for-ai/issues/1578) that you filed had the same error, I'm going to close this one so there's one place for communication
