### ISSUE TITLE
Royal International Affairs A Issue

### ISSUE THREAD

**Issue by Cortana-Knight** [microsoft/vscode-tools-for-ai#1581]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.commandPalette.workspace.createConfigFile
Error type: r
Error Message: Error Creating Error: Could NOT open editor for "untitled:Untitled-2". config file: {2}

Version: 0.10.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.67.2
Language: en

<details>
<summary>Call Stack</summary>

```
c.<anonymous> extension.js:2:2729471
c extension.js:2:2728848
```

</details>

**Comment by sevillal** [comment]
Hi @Cortana-Knight, I saw you closed this issue, please reopen if needed.
