### ISSUE TITLE
Unexpected notification when opening a notebook

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-tools-for-ai#1587]
I opened an Untitled `.ipynb` in an empty workspace through the "New File" button on the Welcome page. I was prompted with this extension but it's completely unexpected since I wasn't doing anything AzML related:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/12758612/171748651-fae947fc-c091-4cbe-bc89-8e3efc18fac2.png">

Also not sure what a AzML workspace is so it was more confusing for me.

## Steps to Reproduce the Problem

  1. Open a new Jupyter file in an empty workspace
  1. See notification

## Specifications

Version: 1.68.0-insider (Universal)
Commit: 15253f1528573fc8f84e956b21af4bad57f38c07
Date: 2022-06-02T05:16:30.515Z
Electron: 17.4.6
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0
Azure Machine Learning:  v0.11.2022060209

**Comment by sevillal** [comment]
@tanhakabir thanks for filing this issue!

We are aware of the improvements we need to make to the experience an we have the following issue to track it https://github.com/microsoft/vscode-tools-for-ai/issues/1555. I will close this issue for now.

Currently the extension activates when a Jupyter Notebook is open, at activation time we are checking if there is default workspace setup. The proposal is to move the default workspace verification only when it is needed.
