### ISSUE TITLE
Cannot decrease minNodeCount in Edit Compute

### ISSUE THREAD

**Issue by shsuman** [Microsoft/vscode-tools-for-ai#160]
Not sure if this is by design in Azure but whenever increase the minNodeCount to say 1 for a compute and then try to set it back to 0, the changes are not reflected.

**Comment by greazer** [comment]
This is doable in the portal, so lets investigate our end.

**Comment by shsuman** [comment]
Not a bug, the sdk returns after submitting the request for resize, but resize takes time, so the new size is not reflected in view properties immediately
