### ISSUE TITLE
Fix log streaming with latest log/output format on Azure ML

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1613]
ML Studio 
![image](https://user-images.githubusercontent.com/56176070/178755289-90929f9c-366a-423a-98e7-7f0a4363eee7.png)

ML Extension
![image](https://user-images.githubusercontent.com/56176070/178755381-e5785ea1-a994-454d-b0e7-226cfa242898.png)

Azure ML extension is tagging these files as outputs, note that in the extension anything under outputs is not available for streaming and only for download.

**Comment by tbombach** [comment]
Added to August milestone to consider it when planning that iteration
