### ISSUE TITLE
AzureML Prompts twice to login when VS Code (Insiders) loads

### ISSUE THREAD

**Issue by binderjoe** [microsoft/vscode-tools-for-ai#1627]
## Expected Behavior
If the user is logged out, the AML extension should not prompt to login until the user specifically tries to run an AzureML command. Prompting when VS Code loads is disruptive and unnecessary, and no other extensions for AWS or Azure do this.

## Actual Behavior
If you are signed out of the Azure ML extension and reload VS Code, you are prompted to login when it loads (Issue #1). If you click cancel, you are prompted again (#2). 

## Steps to Reproduce the Problem
  1. Install the Azure ML Extension
  2. Login
  3. Logout
  4. Reload VS Code
  5. Click "Cancel" when prompted to login

## Specifications
Azure ML Extension Version 0.16.0
 
Version: 1.70.0-insider (Universal)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-03T05:55:27.651Z (1 day ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0

**Comment by greazer** [comment]
Notes: 
- The Azure ML extension is activated when a python or notebook file is opened. It's not activated when VS Code is opened. 
- The prompt is a modal dialog box, which can be particularly annoying and should only be used if the user is completely blocked from doing some related operation without being notified. 
-

**Comment by jedcheng** [comment]
Hi there

I got in touch with an engineer from Microsoft after encountering the exact same problem last month (with chrome).

I believe there was a recent update that fixed this problem for Chrome but not for Safari. 

We just tested signing in again with both Safari and Chrome. It is indeed the case.

**Comment by shsuman** [comment]
I think this is no longer valid as we have switched to native VS Code auth.
