### ISSUE TITLE
Azure ML extension is keep on asking for login without success

### ISSUE THREAD

**Issue by meetsriharsha** [microsoft/vscode-tools-for-ai#1638]
Does this occur consistently? Yes 
Repro steps:

1. Azure ML extension is failing to login. It worked earlier. now, it's failing 

Action: azureAccount.onSessionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.16.0
OS: linux
OS Release: 5.15.0-1014-azure
Product: Visual Studio Code
Product Version: 1.70.2
Language: en

<details>
<summary>Call Stack</summary>

```
_.<anonymous> extension.js:2:2029998
s extension.js:2:2026803
```

</details>

**Comment by meetsriharsha** [comment]
I had to uninstall and reinstall the extension to fix the issue

**Comment by shsuman** [comment]
@tbombach Seems to be the same problem here
