### ISSUE TITLE
Create a debugging page Azure ML SDK on git hub

### ISSUE THREAD

**Issue by shsuman** [Microsoft/vscode-tools-for-ai#164]

**Comment by swinner95** [comment]
@shsuman Can you explain this further?

**Comment by shsuman** [comment]
We have always had problems with the Azure SDK problems. Right now, we have completely automated the process and I am trying to cover all the cases where an error can occur, however, there still can be some problem in the user's machine as is evident from some of the previous issues, I wanted to create a debugging page on Github, so something like if you have a problem in runtime installation depedencies, click here for more information, where I will give the user a sample script file (if a file download is possible) or a text script for all platforms and he/she can run it on his system (it will be executable) and look for errors himself.

**Comment by greazer** [comment]
We could create this doc on our github. Shane' can link to it from elsewhere.

**Comment by greazer** [comment]
https://github.com/Microsoft/vscode-tools-for-ai/blob/c88885603e3f31b1025c1f40c2197a729de2a560/docs/aml-sdk-debugging.md
