### ISSUE TITLE
View Dataset properties fails

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1640]
Transferred from private repo

Version: v0.11.2022060309
Steps:

Open Datasets
Right click on a dataset
Select "Show properties"
Expected: Dataset properties should be shown in editor
Actual: Failure message

This is only reproducible on Mac. Also reproducible in this issue: https://github.com/microsoft/vscode-tools-for-ai/issues/1621

**Comment by tbombach** [comment]
Merged fix: https://github.com/microsoft/vscode-azureml/pull/328
