### ISSUE TITLE
[Web Experience] Improve auth flow by reducing log ins and reusing ML Studio credentials

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1645]
## Proposal

This is VS Code proposal (see: https://github.com/microsoft/vscode-dev/issues/570 for more details)
![image](https://user-images.githubusercontent.com/56176070/160686497-99581683-f927-4223-b70b-8d8a54d85379.png)

### VS Code
- [ ] https://github.com/microsoft/vscode-dev/issues/535
- [x] https://github.com/microsoft/vscode-internalbacklog/issues/2800
- [x] https://github.com/microsoft/vscode-dev/issues/570

### Azure ML
- [x] Update the behavior of the "Edit in VS Code" entry points (i.e. Notebooks and CI page)

**Comment by sevillal** [comment]
This has been completed.
