### ISSUE TITLE
Prevent user from stopping compute they are connected to (endless loop ensues)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1648]
1. Connected to my-compute1 compute
2. Right click 'my-compute1' in sidebar & select ```Stop```
3. IDE gets stuck in a stopping / reconnecting loop

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/812783/157299285-60421b65-5ee6-499e-ace3-79d4479db300.png">

Had to reload the window to get out.

**Comment by shsuman** [comment]
This is now handled and we fail with the appropriate message
