### ISSUE TITLE
Disable workspace trust in remote extension

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1649]
Make use of ResolvedOptions.isTrusted to trust remote workspaces by default.

https://github.com/microsoft/vscode/blob/eb2a7eef68c3fe2c425ff323d4d965e80282b1eb/src/vscode-dts/vscode.proposed.resolvers.d.ts#L32-L33

**Comment by shsuman** [comment]
I think this is no longer required as we only prompt workspace trust once :)
