### ISSUE TITLE
Persist kernel context when moving from the Notebooks tab to VS Code

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1652]
Like how we persist file context, we should also persist kernel context. This means automatically setting the kernel to the one that the user was connected to in the Azure ML Studio. Currently, there is no kernel automatically selected:

![image](https://user-images.githubusercontent.com/6413608/162022548-3a37912e-9ef4-4c36-8b96-b0000a5ab28e.png)

However, if you run a cell then there is a "suggested" kernel that is consistent with the previously used kernel.

![image](https://user-images.githubusercontent.com/6413608/162022637-49539097-f5d5-42db-b1b7-cd920cd1e330.png)

We don't want users to have to go through an extra action to select their kernel.

After conversation with rich, here's the summary of the discussion:
* The Studio only shows Jupyter kernels and not conda envs or other python envs whereas the Jupyter extension shows all of them
* The Studio shows the default Jupyter kernel but the Jupyter extension doesn't. It doesn't exist on disk and isn't a real kernel
* Kernel state can be persisted as long as the display names of the kernel are unique in the metadata. The kernels included as part of the CI's initialization are unique and as long as the user selects one of them, the state can be persisted
* The problems arises in the case of the default kernel and the user created kernels
* One way would be to write the kernelId in the metadata beforehand by the Studio. This would require the Studio the calculate the kernelId in the same way the Jupyter extension does. It will basically trick Jupyter extension into thinking that its's their kernelId and it will just set the right kernelId. A kernelId is unique

**Comment by sevillal** [comment]
Support added by: https://github.com/microsoft/vscode/issues/146339

https://user-images.githubusercontent.com/56176070/202595252-139f9ca0-e480-4063-82ed-2372b27673aa.mp4
