### ISSUE TITLE
Can't use Azure ML features when remotely connected to a compute

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1655]
Since we changed the vscode-azureml-remote extension to be of UI type it is not supported anymore in the web or codespaces.

Given that main extension depends on vscode-azureml-remote, main is also unavailable in the web or codespaces.

Changing the dependency should enable the main extension in the web context again.

**Comment by sevillal** [comment]
Yes, this is only on web platforms like vscode.dev or codespaces.
