### ISSUE TITLE
Fix "Report Issue" button in remote extension

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1657]
Report issues button is broken and is trying to use the following URL

https://github.com/Microsoft/vscode-ai-remote/body=%0A%0A%0ADoes%20this%20occur%20consistently%3F%20%0ARepro%20steps%3A%0A%0A%0A1.%0A2.%0A%0AAction%3A%20Resolver.resolve%0AError%20type%3A%2072%0AError%20Message%3A%20Invalid%20response%3A%20502%20Bad%20Gateway%0A%0A%0AVersion%3A%200.13.2022052509%0AOS%3A%20win32%0AOS%20Release%3A%2010.0.22000%0AProduct%3A%20Visual%20Studio%20Code%0AProduct%20Version%3A%201.67.2%0ALanguage%3A%20en%0A%0A<details>%0A<summary>Call%20Stack<%2Fsummary>%0A%0A%60%60%60%0As%20extension.js%3A2%3A2183282%0A_.checkServerStatus%20extension.js%3A2%3A2229584%0AA.handleReconnection%20extension.js%3A2%3A2215894%0Aextension.js%3A2%3A2213540extension.js%3A2%3A2213540%0A%60%60%60%0A%0A<%2Fdetails>%0A

**Comment by shsuman** [comment]
Fixed with https://github.com/microsoft/vscode-azureml-remote/pull/62
