### ISSUE TITLE
Associate MLTable with YAML 

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1665]
Originally created by @samuel100

The AzureML extension should automatically add an association for MLTable files to be YAML in VSCode settings:

 ![image](https://user-images.githubusercontent.com/9161628/172897730-4d715388-6832-4355-ae6c-ed0e37b430ef.png)

Code completion then works:

![image](https://user-images.githubusercontent.com/9161628/172897888-90ede35e-11f2-452e-98f9-815e568fd423.png)

**Comment by samuel100** [comment]
@greazer - is there an ETA on this one?

**Comment by samuel100** [comment]
@shsuman -- is there an ETA on this one?

**Comment by shsuman** [comment]
@samuel100 We can discuss it for next month's plan. 

In the meantime, you can also manually associate file extensions to languages using the steps mentioned [here](https://stackoverflow.com/questions/29973619/how-to-make-vs-code-treat-a-file-extensions-as-a-certain-language)
