### ISSUE TITLE
Azure ML Extension activates too aggressively, requiring sign-in when not necessary.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1672]
While we can disable the Azure ML extension from activating when a py or ipynb file is opened, we really need it for yaml as editing yaml for AzML resource management is a mainline scenario for users. This can affect users who aren't using yaml for AzML, but it's far less people than for py or ipynb.

We also do support snippets for py files that will not be available until the extension is activated. A way to address this problem is to create a separate extension just for snippets. It can be installed with our extension.

Another option to consider is to not activate the extension at all. As long as the extension is installed, the "Execute YAML" and "Refresh Resource" buttons will be available. When they are clicked, the extension will activate.

**Comment by shsuman** [comment]
This has been fixed now and only requires sign in when absolutely necessary
