### ISSUE TITLE
Update online documentation

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1680]
These docs need to be updated. The doc writers do not have the technical background to update, so we need to provide PR's or whatever they need to get them updated

- [x] https://github.com/Azure/azureml-previews/tree/main/previews/vscode-interactive-job
- [x] https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-train-deploy-image-classification-model-vscode

**Comment by tbombach** [comment]
PR for image classification doc update: https://github.com/MicrosoftDocs/azure-docs/pull/98933
