### ISSUE TITLE
Add telemetry event to detect whether workspace is open when URI is invoked

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1684]
We've been discussing how to decide whether to reuse the same window or open a new one during the remote connection flow. Adding telemetry around workspace state will help with how we set the default behaviour for users.

We want to add a telemetry event that detects whether the user has a workspace folder open or is in a fresh VS Code window when the remote URI is invoked. If majority of users are in a fresh window, we will set the default behaviour to be reusing the same window.

Eventually we should have logic to change the behaviour based on the current state.

**Comment by shsuman** [comment]
I think this is no longer valid as we have `Connect` and `Connect in new window` commands separately and the Studio click out has windowId=_blank specified, so it always opens a new window.
