### ISSUE TITLE
Unknown Error retrieving susbcriptions from Azure Account extension

### ISSUE THREAD

**Issue by lc673850771** [microsoft/vscode-tools-for-ai#1693]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSessionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.16.0
OS: linux
OS Release: 5.15.0-1014-azure
Product: Visual Studio Code
Product Version: 1.69.2
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
_.<anonymous> extension.js:2:2029998
s extension.js:2:2026803
```

</details>

**Comment by shsuman** [comment]
@lc673850771  We have shipped a fix for this issue. Can you please upgrade the extension to 0.18.0 and let us know if its fixed for you?

**Comment by John-Vance** [comment]
0.18.0 seems to have fixed it for me, thanks!

 ~ John
________________________________

**Comment by shsuman** [comment]
@John-Vance Thanks for confirming :). Closing this now
