### ISSUE TITLE
Cache Azure CLI and ML extension presence on the machine to avoid checking every time

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1695]
In this gif you can see that I press the "Execute YAML" button, but it then takes several seconds before the command-shell appears that executes the line. Is this something we can improve? 

![Recording 2022-09-01 at 15 24 57](https://user-images.githubusercontent.com/11685408/188023312-ef54e17b-0d54-48ae-b5e8-239aef34afab.gif)

**Comment by sevillal** [comment]
Test shows the following:
- Total time from click until the command is executed in the terminal (just executed not finished)  = 16.75
- Most of that time was spent on a check to verify Azure CLI and ML CLI extension takes most of that time = 15.63 sec
- Time to open the terminal and execute the command was ~1 sec

**Comment by sevillal** [comment]
Important: How can we make it fast also for the first time trying to execute the yaml?
