### ISSUE TITLE
[Question] Azure Machine Learning from Remote - Containers

### ISSUE THREAD

**Issue by aytekinar** [microsoft/vscode-tools-for-ai#1709]
Hi,

I am using the [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension, and I have created a development environment with the following OS and Azure CLI versions:

```cmd
(base) root@ab7861b7a422:/workspace/golang# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
(base) root@ab7861b7a422:/workspace/golang# az --version
azure-cli                         2.40.0

core                              2.40.0
telemetry                          1.0.8

Extensions:
ml                                 2.7.1

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.10.5 (main, Sep  2 2022, 05:41:01) [GCC 10.2.1 20210110]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
(base) root@ab7861b7a422:/workspace/golang# 
```

Even though I have enabled the Azure Machine Learning extension in my development container, when I go to the Azure extension and click, say, the refresh button under "Azure: Machine Learning," I receive the following error: `command 'azureml.viewTitle.refresh' not found`. This happens whenever I try to click on or run any command related to the extension.

How can I, if at all, use the extension under my development containers? It's a pain to open two different VSCode windows, one within the container and the other on the host, to be able to code (inside the container) while benefiting from the auto-complete features of the extension (on the host).

**Comment by sevillal** [comment]
@aytekinar thanks for filing this issue. I was able to repro the issue and I will start investigating what could be the root cause.

**Comment by sevillal** [comment]
The workaround I found is the following:
- Install Python extension
- Open a python file to activate Python extension
- Go to the Azure ML extension tree view 

It seems that the Azure ML extension is failing to activate if the Python and Jupyter extension are not activated first, I am still doing some investigation but let me know if the previous workaround works.

**Comment by aytekinar** [comment]
Hi @sevillal,

Thank you for your time, fast response and help.

Indeed, following the 3-step procedure/workaround you have listed, I could get it to work inside my remote development container(s). However, if the dependency on (1) having installed the Python extension and (2) activating it prior to using the Azure ML extension is a strict, could we have it handled automatically behind the scenes by the extension rather than us needing to follow the steps properly?

**Comment by sevillal** [comment]
Hey @aytekinar, yes, for now it is just a workaround, we are investigating further to have a proper solution. I will keep this issue updated with more details.

**Comment by sevillal** [comment]
@aytekinar we have merged a fix for this issue, it should be available on our next release on the first days of October.
