### ISSUE TITLE
Error connecting to VS Code Web when using compute instance that has not been restarted

### ISSUE THREAD

**Issue by slumley** [microsoft/vscode-tools-for-ai#1711]
## Expected Behavior
I would expect that when clicking vs code web from AML compute screen that the connection will be successful

## Actual Behavior
Received following in console
ERR Failed to open websocket.: Error: Failed to open websocket.
    at WebSocket.<anonymous> (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/vscode-ai-remote-web/0.1.2022090609/extension/dist/webOpener.js:2:627747)

![image](https://user-images.githubusercontent.com/5076124/188955609-fdc49e44-859d-44c5-a4a5-6c05fea19819.png)

## Steps to Reproduce the Problem

  1.  I think the issue had to do with a using a compute which has not been restarted in a while
  2.  Here are the compute details:
  
![image](https://user-images.githubusercontent.com/5076124/188956043-ad6de336-b33a-4cd4-b277-3b019d46cb31.png)

## Specifications

  - Version:
  - Platform:

**Comment by sevillal** [comment]
Closing this since we don't have enough logs to triage.
