### ISSUE TITLE
Remote web: Include Jupyter pre-release extension?

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-tools-for-ai#1718]
When I open in VS Code Web, I get an insiders.vscode.dev URL, which I expected would use the prerelease version of the Jupyter extension since it's Insiders VS Code and to help avoid this prompt:

![image](https://user-images.githubusercontent.com/25310137/191130586-fe02057d-9127-4024-a720-2ca79fe3babf.png)

I believe the label should be: `area-remote-web`.

**Comment by sevillal** [comment]
I'll follow up with VS Code team to check if we have a way to indicate the VS Code server if we want to install the 'release' or 'pre-release' version by default.

This is how this works:
- The Azure ML extension installs the VS Code server on the remote machine
- When installing and starting the VS Code server there is a parameter tp install certain extensions by default (Jupyter, Python, etc)
- The parameter only accepts a list of extension ids (maybe there is a way to indicate the version or if pre-released is desired)

**Comment by sevillal** [comment]
Closing as this does not apply anymore since we take customers to stable VS Code.
