### ISSUE TITLE
Remote Web: IntelliSense indicates failure, but run is successful

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-tools-for-ai#1719]
When running the first import cell in my notebook, I thought it'd have trouble as there were many red squiggles. However, the run appears successful, although the red squiggles remain:

![image](https://user-images.githubusercontent.com/25310137/191131130-c5f41f74-32c7-468d-bd04-20b6c5ec685a.png)

Not sure if this is expected, and/or more of a Python/Pylance issue to file?

**Comment by sevillal** [comment]
@bamurtaugh this looks like a Jupyter issue because I was able to repro when first landing and opening a notebook, if I re-select the same kernel in the notebook (by manually clicking the kernel picker) the squiggles disappear in my notebook. 

I will follow up with Jupyter team.

**Comment by sevillal** [comment]
Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/13095
