### ISSUE TITLE
[Safari] Issue when connecting vscode.dev remote session to CI

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1720]
Note: Only applies to Safari. Update posted in the comments

When I clicked out from Compute Instance to VS Code Web, I got an error:
<img width="899" alt="Screen Shot 2022-09-19 at 3 24 05 PM" src="https://user-images.githubusercontent.com/779479/191131138-87ce3e14-5c68-4bb8-b0d5-4983b2894e3e.png">

The following is no longer relevant:

~~In the network tab, it shows an error with the /api/terminal endpoint~~
![Screen Shot 2022-09-19 at 3 28 44 PM](https://user-images.githubusercontent.com/779479/191131160-b0e54731-82c9-4c53-954c-ea0f7bb12e33.png)

~~I have attached the .har network logs:~~
[terminal_404.har.zip](https://github.com/microsoft/vscode-tools-for-ai/files/9602734/terminal_404.har.zip)

~~And the output of `journalctl -utc -u tundra > tundra-log.txt`  ~~
[tundra-log.txt](https://github.com/microsoft/vscode-tools-for-ai/files/9602737/tundra-log.txt)

**Comment by tbombach** [comment]
Update thanks to Zoey: This error message shows up when trying to use lookbehind regex in Safari (which isn't supported).

I found this regex in our server installation code : https://github.com/microsoft/vscode-azureml-remote-web/blob/457926a19b4126074104523fc9cfb6549bcf86b8/src/webOpener/serverInstallers/serverInstallerBase.ts#L36

We'll need to update this regex to have it work in Safari

**Comment by sevillal** [comment]
@tbombach could you please confirm this is fixed for you when using the prod version of the remote extension for web?
