### ISSUE TITLE
Remote Web: "Open Remote Repository" does nothing

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-tools-for-ai#1722]
- Open Remote Explorer view
- Switch to Remote Repositories in dropdown
- Click button to "Open Remote Repository"
- :bug: Nothing happens
![image](https://user-images.githubusercontent.com/25310137/191132083-cebe93f8-8d73-4fc3-8838-6d8a5065f819.png)

If this isn't a flow we want to enable, could we hide it, or provide some sort of failure notification?

**Comment by sevillal** [comment]
Unable to repro working fine in latest stable vscode.dev.
