### ISSUE TITLE
Need Azure ML CLi for create compute but extension ml is installed

### ISSUE THREAD

**Issue by MalcolmMielle** [microsoft/vscode-tools-for-ai#1728]
## Expected Behavior

I'm trying to create a new compute from the SVCode Azure extension.

I'm running this yaml file 

```
$schema: https://azuremlschemas.azureedge.net/latest/computeInstance.schema.json
type: computeinstance
#enter name for the compute
name: test-compute1
#enter VM size
size: STANDARD_DS3_v2
```

I have installed the ml extension and removed the azure-cli-ml one.

```
az extension list
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "azure-devops",
    "path": "C:\\Users\\miellema\\.azure\\cliextensions\\azure-devops",
    "preview": false,
    "version": "0.25.0"
  },
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "ml",
    "path": "C:\\Users\\miellema\\.azure\\cliextensions\\ml",
    "preview": false,
    "version": "2.8.0"
  }
]
```

When right clicking on the yaml file and selecting `Azure ML: Execute YAML`, I expect the compute to be created.

## Actual Behavior

I am prompted to install the Azure CLI ML extension every time. Funnily enough, if I install the azure-cli-ml it doesn't prompt the error message but I have the error `'compute' is misspelled or not recognized by the system.` which means that it expect the ml extension.

## Steps to Reproduce the Problem

  1. Create YAML fiile
  2. Install azure cli with pip
  3. Install ml extension in azure cli
  4. Log in azure cli
  5. Run YAML File

## Specifications

  - Versions: 
      - Vscode insider 1.72.0
      - Azure cli 
      ```
      az --version
      azure-cli                         2.40.0
      core                              2.40.0
      telemetry                          1.0.8
      Extensions:
            azure-devops                      0.25.0
            ml                                 2.8.0
      Dependencies:
            msal                            1.18.0b1
            azure-mgmt-resource             21.1.0b1
      Python location 'C:\Users\miellema\Miniconda3\envs\insulated\python.exe'
      Extensions directory 'C:\Users\miellema\.azure\cliextensions'
      Python (Windows) 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)]
      Legal docs and information: aka.ms/AzureCliLegal
      Your CLI is up-to-date.
      ```
      -Azure Machine learning VSCode extension: v0.18.0
  - Platform: Windows 10

**Comment by shsuman** [comment]
@MalcolmMielle Can you please run the following commands to uninstall all the ml extensions:

`az extension remove -n azure-cli-ml
az extension remove -n ml`

and then run this to install the latest ml extension
`az extension add -n ml`

then run
`az ml -h` to verify the installation

Please try again after doing the above steps and let me know the results

**Comment by MalcolmMielle** [comment]
Running the commands:

```
$az extension remove -n azure-cli-ml
The extension azure-cli-ml is not installed.

$az extension remove -n ml

$az extension add -n ml
 - Installing ..
$az ml -h

Group
    az ml : Manage Azure Machine Learning resources with the Azure CLI ML extension v2.
        Install Azure CLI ML extension v2
        https://docs.microsoft.com/azure/machine-learning/how-to-configure-cli.        

Subgroups:
    batch-deployment     : Manage Azure ML batch deployments.
    batch-endpoint       : Manage Azure ML batch endpoints.
    component            : Manage Azure ML components.
    compute              : Manage Azure ML compute resources.
    connection [Preview] : Manage Azure ML workspace connection.
    data                 : Manage Azure ML data assets.
    datastore            : Manage Azure ML datastores.
    environment          : Manage Azure ML environments.
    job                  : Manage Azure ML jobs.
    model                : Manage Azure ML models.
    online-deployment    : Manage Azure ML online deployments.
    online-endpoint      : Manage Azure ML online endpoints.
    schedule             : Manage Azure ML schedule resources.
    workspace            : Manage Azure ML workspaces.

To search AI knowledge base for examples, use: az find "az ml"
```

Same behavior then:

![Screenshot 2022-09-26 163210](https://user-images.githubusercontent.com/4457840/192303598-f0e2255f-8ef6-4d97-94af-3f5bff27faca.png)

**Comment by shsuman** [comment]
Hey @MalcolmMielle ,

I See that you have installed Azure CLI using pip. So, my guess is you must have installed the cli in a python virtual environment or a conda environment.

Please note that we do not support such scenarios and Azure CLI needs to be installed globally on your system following the steps mentioned [here](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli).

Please install Azure CLI globally and try again. Let me know if this resolves your issue otherwise we can connect over a call to investigate the issue further.

**Comment by MalcolmMielle** [comment]
Sadly I'm missing admin rights to do so at the moment. I will let you know if I manage

**Comment by shsuman** [comment]
@MalcolmMielle Were you able to resolve the issue that you are facing ?

**Comment by MalcolmMielle** [comment]
No I ended up creating it manually :/

**Comment by shsuman** [comment]
I will close this issue then because its a known limitation. Let me know if you need hep with anything else :)

**Comment by shsuman** [comment]
@pauldj54 Can you run the below command in your VS Code terminal and let me know the output ?

`az extension list`

**Comment by pauldj54** [comment]
> @pauldj54 Can you run the below command in your VS Code terminal and let me know the output ?
> 
> `az extension list`

Hi @shsuman, 
It was my mistake after touching too many things, but after that I got that error: 

> error: the following arguments are required: --name/-n, --resource-group/-g

So, I just execute the creation command in the CLI and it worked, but this is not the intended usage of the extension.

**Comment by shsuman** [comment]
@pauldj54 Can you please open a new issue describing the repro steps for the above error ?
