### ISSUE TITLE
VS Code Tools for AI Remote: Remote Bug reports redirect to non existing page

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-tools-for-ai#1730]
## Expected Behavior
Open the bug report page in the `vscode-tools-for-ai` repo

## Actual Behavior
Open the bug report page in `vscode-ai-remote` (non existing or public page)

## Steps to Reproduce the Problem

  1. Find an error with the extension (in my case I used the Insiders versions and connected to an ML environment
  1. When the extension finds an issue it prompts the user to report it to the wrong link, for example:
  https://github.com/Microsoft/vscode-ai-remote/issues/new?body=%0A%3C!--%20IMPORTANT%3A%20Please%20be%20sure%20to%20remove%20any%20private%20information%20before%20submitting.%20--%3E%0A%0ADoes%20this%20occur%20consistently%3F%20%3C!--%20TODO%3A%20Type%20Yes%20or%20No%20--%3E%0ARepro%20steps%3A%0A%3C!--%20TODO%3A%20Share%20the%20steps%20needed%20to%20reliably%20reproduce%20the%20problem.%20Please%20include%20actual%20and%20expected%20results.%20--%3E%0A%0A1.%0A2.%0A%0AAction%3A%20Resolver.resolve%0AError%20type%3A%2070%0AError%20Message%3A%20Invalid%20response%3A%20502%20Bad%20Gateway%0A%0A%0AVersion%3A%200.19.2022092309%0AOS%3A%20darwin%0AOS%20Release%3A%2021.6.0%0AProduct%3A%20Visual%20Studio%20Code%20-%20Insiders%0AProduct%20Version%3A%201.72.0-insider%0ALanguage%3A%20en%0A%0A%3Cdetails%3E%0A%3Csummary%3ECall%20Stack%3C%2Fsummary%3E%0A%0A%60%60%60%0As%20extension.js%3A2%3A1922783%0Aextension.js%3A2%3A1952971extension.js%3A2%3A1952971%0A%60%60%60%0A%0A%3C%2Fdetails%3E%0A

 ![reportbug-azuremlremote2](https://user-images.githubusercontent.com/79476/192226399-b8e6a8dc-1243-40dc-b696-8f98146476da.gif)

## Specifications

**VS Code Environment:**
Version: 1.72.0-insider
Commit: b9f7f85e90b4d51b38fcbf4232801ab04bd659cb
Date: 2022-09-23T08:15:07.186Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**VS Code Extensions**
Azure Machine Learning - Remote: v0.19.2022092309 Pre-Release

**Operating System**
macOS Monterrey 12.6
Macbook Air (M1, 2020)

**Comment by shsuman** [comment]
@iemejia Thanks for bringing this up. We will fix this in the next iteration

**Comment by iemejia** [comment]
Excellent, thanks @shsuman !
