### ISSUE TITLE
Remove + Add new [Object] option while using edit or remove command with any [Object]

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#174]

**Comment by greazer** [comment]
@shsuman, can you provide a bit more detail here? I'm not clear what you're suggesting. Maybe a hard example would help.

**Comment by shsuman** [comment]
So, Whenever you open the command palette and say use some Edit/Remove Compute, it will show you a list of workspaces and also a +Create new Workspace option which is weird from a user point a view because user wanted to remove something, not create a workspace, so remove all those + options which come in the path of Edit/Remove Command
