### ISSUE TITLE
Placeholder: Fix critical bugs discovered during private preview

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1743]
# Critical
- [x] https://github.com/microsoft/vscode-tools-for-ai/issues/1720
- [x] #1755

## Nice to have
- [x] https://github.com/microsoft/vscode-tools-for-ai/issues/1717
- [x] https://github.com/microsoft/vscode-tools-for-ai/issues/1712
- [x] #1718 
- [x] #1719 
- [ ] #1721 
- [x] #1722
- [x] #1655

**Comment by sevillal** [comment]
Closing this placeholder issue as most of the issues has been fixed.
