### ISSUE TITLE
Datastores have moved under Data and existing Datasets under Data ->Data Assets in Studio

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1752]
New Hierarchy:
Data
       |______ Datstores
       |______ Data Assets

**Comment by tbombach** [comment]
I think we should probably keep the same hierarchy (rather than create a new level for "Data") but let's rename our "Data" node to "Data assets"

**Comment by shsuman** [comment]
Do we update Data -> Data Assets in other places like command palette as well ? E.g. `Create Data Asset`, `View Data Asset Properties` etc...
