### ISSUE TITLE
delete dataset

### ISSUE THREAD

**Issue by Wkxinin** [microsoft/vscode-tools-for-ai#1761]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.commandPalette.dataset.version.delete
Error type: 400
Error Message: Bad Request

Version: 0.20.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.72.2
Language: en

<details>
<summary>Call Stack</summary>

```
t.createAzureMLHttpError extension.js:2:1962835
t.HttpService.<anonymous> extension.js:2:1964904
s extension.js:2:1963059
```

</details>

**Comment by shsuman** [comment]
@Wkxinin Deleting a Dataset is no longer supported by the Azure ML APIs. We will be removing support for Delete in the upcoming release. Instead **Archive** Dataset functionality will be introduced in our next release.

I hope this will resolve your issue. I am closing the issue for now. Please let me know if you have any other question :)
