### ISSUE TITLE
[Azure ML Tundra] Fix Tundra service unexpected timeout

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1767]
- Causes connection failures
- Workaround: Restart tundra service or the whole CI

https://msdata.visualstudio.com/Vienna/_workitems/edit/1957832/?triage=true

**Comment by tbombach** [comment]
Upstream item has been marked as done - let's verify that it fixes the issue

**Comment by sevillal** [comment]
Unable to repro anymore. Closing it for now but, waiting for confirmation from Tundra team that this is fixed for compute instances.
