### ISSUE TITLE
Visual Studio Azure ML extension error on "View Properties" 

### ISSUE THREAD

**Issue by hatan4ik** [microsoft/vscode-tools-for-ai#1783]
To reproduce the issue:
Right click on ML default project in left hand bar.
From the menu click "View Properties" and getting:

[UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")

**Comment by sevillal** [comment]
Hi @hatan4ik,

Thanks for opening this issue. @tbombach has merged a fix for this and it will be included in our upcoming release. We will post an update here when we have released.

**Comment by shsuman** [comment]
@stevebanik This was fixed in latest release. Can you please update the extension to 0.24,0 and test it ?

**Comment by tbombach** [comment]
Closing as fixed
