### ISSUE TITLE
Public Preview: vscode.dev web connection experience

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1784]
# Public Preview Scope

- Private link support (not required, but desirable) [Further context in this comment below](https://github.com/microsoft/vscode-tools-for-ai/issues/1784#issuecomment-1319399446)
- Non-public clouds support (not required)
- Experience
- VS Code CLI integration
- Telemetry
- Testing
- Performance

<details>
 <summary>Legend</summary>
Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |
</details>

# Tasks

## VS Code CLI
- [ ] Investigate what is needed to move to the VS Code CLI

https://github.com/microsoft/vscode-tools-for-ai/issues/1784#tasklist-block-fd07e56f-2771-48e0-8c9f-9c68a156991e

## Telemetry
- [x] #1867
- [x] #1868
- [x] #1869

## Testing
- [x] #1870
- [x] #1871
- [ ] #1799 

## Experience
- [x] #1801
- [x] #1800
- [x] https://github.com/microsoft/vscode-tools-for-ai/issues/1834
- [x] #1826 
- [x] #1814 

## Performance
- [ ] #1877

# Other
- [x] #1876

**Comment by tbombach** [comment]
Summarizing the meeting this morning with Sean/Leah to confirm Private Link requirements:

Private Link is not a checklist item that gates all AzureML features before they are allowed to release a Public Preview (but is recommended for AzureML features). However for this Clickout to vscode.dev feature, we agreed during the planning stage that Private Link is an important part of the scenario based on the target customers and their requirements for connectivity and security. We re-confirmed today that before this feature moves to Public Preview, we will need to support Private Link.

**Comment by sevillal** [comment]
Closing this placeholder issue since most of the issues are closed. 

Missing issues are added to this quarter's milestone.
