### ISSUE TITLE
Improper refreshing of left menu when setting an active experiment 

### ISSUE THREAD

**Issue by swinner95** [microsoft/vscode-tools-for-ai#179]
Repro steps:

1. User has multiple workspaces and multiple experiments associated with each workspace. 
2. User selects an experiment from a different workspace and sets the experiment as 'Active'
3. The explorer pages refreshes to show only the list of workspaces (instead of showing which experiment is active. User then has to find(again) which experiment is actually active)

**Comment by shsuman** [comment]
This is by design of refresh function

**Comment by greazer** [comment]
@shsuman Are you saying that it's not possible to open the tree to a particular spot after refresh is done?

**Comment by shsuman** [comment]
I don't believe opening a tree at a point is possible programatically, and even it would be possible through function it would require the node to be opened which we don't necessarily have
