### ISSUE TITLE
Failed to re-connect to the remote azure ml compute instance

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1791]
Hi, I'm having the same problem, when I try to connect to a project that I'm working on (I never close the vs code window after I hibernate my laptop), I had this error:
![image](https://user-images.githubusercontent.com/56176070/200648845-8a4baaba-96f9-4c01-9db3-e99bae575632.png)

Then I closed remote connection, then retry connecting to the compute instance. A window popped up after I entering my password three times:
![image](https://user-images.githubusercontent.com/56176070/200648895-7f6b9a86-8932-4540-b5f3-e5907dfd88e4.png)

**Comment by sevillal** [comment]
@QiwenZheng1234 Thanks for filing this issue.

How are you connecting to your target again? I see the second screenshot is throwing an error from the `remote-ssh` extension and which is unrelated to the Azure ML Remote connection.

**Comment by QiwenZheng1234** [comment]
@sevillal thanks for the hints. I used **remote-ssh: Add** to connect to the compute. I resolved the problem by removing connection to my azureml compute instance by deleting the ssh target in the config file. Then I redo the steps to add it as ssh target, reenter my password to azure ml studio in a pop up screen in Chrome browser. Then I have access again to the folders in my compute.

**Comment by sevillal** [comment]
@QiwenZheng1234 thanks for sharing that information. 

Have you tried connecting using the Azure ML Extension? With the Azure ML Extension you don't need to setup SSH at all. Here you can find the [docs ](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-set-up-vs-code-remote?tabs=studio) on how to do it, please let me know if you have any question

Closing this issue.
