### ISSUE TITLE
Should also remove option + when selecting resource group

### ISSUE THREAD

**Issue by LittleLittleCloud** [Microsoft/vscode-tools-for-ai#180]
when creating workspace, there's an option to create a new one when selecting resource group. In order to keep it uniform, we should move that too

**Comment by swinner95** [comment]
I am a bit confused here, can you clarify what you are referring to? A user can have multiple resource groups tied to a subscription and users should be able to create a workspace in any resource group that they have available to them under that subscription. Users should also be able to switch amongst different resource groups of the subscription from the extension(I filed a bug for this already).

**Comment by greazer** [comment]
@LittleLittleCloud, let's talk about this. I'm not sure what you're saying either.
