### ISSUE TITLE
Preserve active file context when clicking out from notebook editor

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1800]
Depends on: #1939

**Comment by sevillal** [comment]
# Proposal
Technically we could solve it in two ways:

## Querystring
ML Studio adds a new query parameter like `&editorContext=["path/to/file1", "path/to/file2"]`, then the remote web extension can read it and when the connection is ready, call `vscode.workspace.openNotebookDocument(uri).then(vscode.window.showNotebookDocument);` or the equivalent for textdocuments.

**Note**: I would suggest that we use this approach just to transfer active editor context and not multiple editors to avoid long URLs. Browser URLs have a size limit of 2048 characters.

🟡 **Discuss**: I propose we clear the query param once it is used, this to open the file only the first time connected. If the customer closes the file, open others and reload the window it would not open that "default" file automatically.

## POST request
ML Studio does a POST call with the `continueOn` route which includes a redirect URL to the already known vscode.dev extension URL, in the request body it includes a JSON containing an array of the files to open automatically after connecting. The extension's web opener will receive the JSON data which can be used to open the files.

✋ This approach depends on: https://github.com/microsoft/vscode-dev/issues/681

🟡 **Discuss**: If there is no clear evidence that customers want to transfer all the open editors context it will be faster to use the query string approach.
