### ISSUE TITLE
Couldn't connect from VS Code with my azure user

### ISSUE THREAD

**Issue by olivercortinas** [microsoft/vscode-tools-for-ai#1812]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSessionsChanged
Error type: 123
Error Message: Error desconocido al recuperar suscripciones de la extensión de la cuenta de Azure

Version: 0.22.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.73.1
Language: es

<details>
<summary>Call Stack</summary>

```
b.<anonymous> extension.js:2:1976096
s extension.js:2:1972783
```

</details>

**Comment by sevillal** [comment]
FYI @tbombach

**Comment by shsuman** [comment]
@olivercortinas Are you still facing this issue ?

**Comment by olivercortinas-orangeloops** [comment]
> @olivercortinas Are you still facing this issue ?

Probably but not focus on that anymore, regards!
