### ISSUE TITLE
Unable to login in Azure ML extension in VSCode

### ISSUE THREAD

**Issue by subhasisj** [microsoft/vscode-tools-for-ai#1817]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSessionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.22.0
OS: linux
OS Release: 5.15.0-1022-azure
Product: Visual Studio Code
Product Version: 1.68.1
Language: en

<details>
<summary>Call Stack</summary>

```
b.<anonymous> extension.js:2:1976096
s extension.js:2:1972783
```

</details>

**Comment by sevillal** [comment]
@tbombach could you please take a look at this issue?

**Comment by shsuman** [comment]
@subhasisj Are you still facing this issue ?

**Comment by subhasisjethy** [comment]
No all good, thanks!
