### ISSUE TITLE
Executing YAML - Always asks to install Azure ML CLI extension

### ISSUE THREAD

**Issue by fmerinop** [microsoft/vscode-tools-for-ai#1824]
## Expected Behavior

Execute the instructions included in the YAML file. In this case, create a Compute cluster.

## Actual Behavior

The YAML execution starts but always asking launching the message "You need to install Azure ML CLI extension to use this command." it is already installed

az version
{
  "azure-cli": "2.27.2",
  "azure-cli-core": "2.27.2",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-iot": "0.14.1",
    "eventgrid": "0.4.9",
    "ml": "2.11.0"
  }
} 

## Steps to Reproduce the Problem

  1. Start VSCode
  2. Click on Azure Icon-->Machine Learning--> Select the workspace-->Compute-->Compute Cluster-->Right Button-->Create AML compute--> update the template with required values-->Right Button-Azure ML:Execute YAML
  3. Execution starts and always ask for Azure ML CLI extension

## Specifications

  - Version: VScode 1.73, Azure Machine Learning extension v0.22.0
  - Platform: Windows 11 Enterprises

**Comment by sevillal** [comment]
@fmerinop thanks for filing this issue.

Could you please try running `az ml -h` in your terminal and share what's the output of the command?

**Comment by fmerinop** [comment]
@sevillal , here is the output of az ml -h

`az ml -h`
cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\mgmt\core\policies\__init__.pyc)
'ml' is misspelled or not recognized by the system.

**Comment by sevillal** [comment]
@fmerinop according to [this question](https://learn.microsoft.com/en-us/answers/questions/934301/cannot-use-the-ml-cli-v2.html) it might be that you need to upgrade your Azure CLI with `az upgrade` command. Could you please try?

**Comment by fmerinop** [comment]
@sevillal, Thanks a lot! Now it is working :)

**Comment by sevillal** [comment]
@fmerinop that good to know! :)
