### ISSUE TITLE
Fix "Open folder" from vscode.dev UI toolbar menu (current workaround: modify URL manually)

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1834]
Depends on: #1939 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/779479/205825031-17d48779-6c3b-4e69-8d42-67683f466b2c.png)

This is because the query parameters are not preserved by vscode.dev when opening a different folder.

**Comment by lebaro-msft** [comment]
Another (likely related) issue: if you use the url to change the folder, the source control isn't recognizing the folder you are in so it doesn't work anymore
