### ISSUE TITLE
canno get Azure env

### ISSUE THREAD

**Issue by rstaltari** [microsoft/vscode-tools-for-ai#1841]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSessionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.22.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.74.0
Language: en

<details>
<summary>Call Stack</summary>

```
b.<anonymous> extension.js:2:1976096
s extension.js:2:1972783
```

</details>

**Comment by shsuman** [comment]
Dup of #1842
