### ISSUE TITLE
extention cannon sign in azure account

### ISSUE THREAD

**Issue by rstaltari** [microsoft/vscode-tools-for-ai#1842]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSessionsChanged
Error type: 123
Error Message: Unknown Error retrieving susbcriptions from Azure Account extension

Version: 0.22.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.74.0
Language: en

<details>
<summary>Call Stack</summary>

```
b.<anonymous> extension.js:2:1976096
s extension.js:2:1972783
```

</details>

**Comment by shsuman** [comment]
@rstaltari Can you please update the extension to 0.24.0 and then try again ? If it still doesn't work, can you try to manually sign in by running the command `Azure: Sign In`.

Note: To run a command, click `Ctrl/Cmd + Shift + P`

**Comment by rstaltari** [comment]
@shsuman  it worked nicely! Thanks for prompt reply
