### ISSUE TITLE
After CI disconnects, I'm greeted with what I believe are invalid ways of reconnecting...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1843]
## Steps to Reproduce the Problem

  1. Connect to an Azure ML CI using vscode.dev or vscode desktop
  1. Wait for disconnect. I don't know how long this typically takes. But overnight works.

I get this:
<img width="553" alt="image" src="https://user-images.githubusercontent.com/11685408/207741063-b73c1f87-8c41-415d-ba3f-43988903bcc2.png">

  1. To try and reconnect I click on the "remote" section of the status bar at the bottom left.
  3. I'm presented with this: 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/11685408/207738716-6cb62041-dea4-4beb-bd1d-9d4ec0b5a275.png">

I don't think any of these are valid options for our scenario. 

## Specifications

  - VS Code Version:
  - Platform:

**Comment by tbombach** [comment]
I think we'll have to investigate if there is a way to disable these other methods during our connection (but I don't think it's likely there are today). If not, we'll have to put in a feature request for VS Code remote area

**Comment by sevillal** [comment]
Closing this since does not apply anymore. 

After long idle times we show a special error with a "Reload" button which reconnect the browser.
