### ISSUE TITLE
Opening a notebook in vscode.web vs vscode desktop results in different root folder being opened.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1849]
1. Open an ipynb file in AzML Studio.
2. Open a vscode.web and vscode desktop session.

**Actual Behavior**
Vscode.web limits the user to seeing just the folder that contains that ipynb file that was being worked on. VS Code desktop opens the same parent folder the user was viewing in AzML Studio. 

**Expected Behavior**
The folder that's opened should be the same. Which is the right choice is a different question :). Thought opening the parent folder at least provides a solution for #1848

**Comment by sevillal** [comment]
Let's discuss this on our next sync with Azure ML.

**Comment by sevillal** [comment]
After discussion we decided to make web consistent with desktop and land by default in `/home/azureuser/cloudfiles/code/`

Upstream issue: https://msdata.visualstudio.com/Vienna/_workitems/edit/2155509

**Comment by sevillal** [comment]
Upstream issue completed.
