### ISSUE TITLE
Unable to delete workspace (if deleted in Azure Portal)

### ISSUE THREAD

**Issue by trbran** [Microsoft/vscode-tools-for-ai#185]
Issue Type: <b>Bug</b>

If I delete a workspace from Azure Portal, the workspace this shows up under the list of workspaces and is impossible to remove from VS Code extension. How can I remove the workspace from VS Code?

Extension version: 0.4.2
VS Code version: Code - Insiders 1.32.0-insider (43228c493069ead7cfb7d57b2da1db20fc0acdaf, 2019-03-06T01:28:07.880Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (7.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by greazer** [comment]
@trbran To be clear, you said that if you refresh the window... Top right icon, the workspace still shows?

**Comment by trbran** [comment]
True.

I have three ws, where aml106ws was deleted in the portal.

[A screenshot of a cell phone  Description automatically generated]

This still shows in the extension. Trying to Remove Workspace will give me this error.

[A picture containing screenshot  Description automatically generated]

Refresh or not, it still shows up. Removing one of the other that still is live in the portal will work.

Output windows does show that both was removed, but refresh and only the last one (that is still live in the portal) shows up:

[A screenshot of a cell phone  Description automatically generated]

Tried to reinstall the extension too, but it will still show aml106ws

Trond

**Comment by greazer** [comment]
@shsuman, I know at one point the extension had some sort of workspace cache. Could it be that this is the cause of this problem? Refresh is failing to delete the cache?

**Comment by greazer** [comment]
We no longer cache the workspaces

**Comment by trbran** [comment]
😊 Works perfect, thank you.

Regards,
Trond

**Comment by shsuman** [comment]
@greazer Is this issue resolved ?
