### ISSUE TITLE
502 Bad Gateway error after running Tesla K80 compute instance on azure ML

### ISSUE THREAD

**Issue by Sruinard** [microsoft/vscode-tools-for-ai#1850]
Does this occur consistently? YES 
Repro steps:

1. Create compute instance in azure ML (Tesla K80) and add schedule
2. Connect with VSCode on day 2. 

Action: Resolver.resolve
Error type: ce
Error Message: Failed to connect to target. Make sure that it exists and is in a running state (Error: Invalid response: 502 Bad Gateway)

Version: 0.22.0
OS: darwin
OS Release: 22.1.0
Product: Visual Studio Code
Product Version: 1.74.1
Language: en

<details>
<summary>Call Stack</summary>

```
ce.NotAvailable extensionHostProcess.js:92:17513
b.handle400BadRequestAnd502BadGateway extension.js:2:1949684
b.handleError extension.js:2:1948588
o.value extension.js:2:1911817
extension.js:2:1960308
```

</details>

**Comment by shsuman** [comment]
@Sruinard Did you check if the Compute instance is running as mentioned in the error ?

**Comment by Sruinard** [comment]
I did and it was running. I have even restarted it, but the error persisted. I had the issue for 4 days, but didn't experience any issues in the past few days. So it seems to be resolved somehow.

Thanks for coming back to me.

All the best,

Stef Ruinard

________________________________

**Comment by shsuman** [comment]
It may have been a transient issue with the CI's Jupyter severs. Glad to know its resolved :)
