### ISSUE TITLE
Investigate: Inconsistent notebook debugging experience as debug chevron is shown depending on the kernel selected

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1854]
Works for azureml_py310_sdkv2 (Python 3.10.4) but does not work for azureml_py38 (Python 3.8.5).

Reproducible on desktop.

**Comment by shsuman** [comment]
https://github.com/microsoft/vscode-jupyter/issues/12847

**Comment by sevillal** [comment]
@shsuman I saw Don closed the upstream issue with some comments, have you been able to verify that?

**Comment by shsuman** [comment]
Upgrading the ipykernel fixes the issue. The problem lies with the v6.8.0 of the ipykernel, v6.21.3 works fine.

**Comment by shsuman** [comment]
Closing in favor of #1970
