### ISSUE TITLE
Kernel state is lost after refreshing the web window

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1857]
How to repro?
- Open a notebook and declare a variable, check it in the variable explorer
- Refresh the browser and the variable is not in the variable explorer anymore

- Reproducible with local jupyter extension.
- State is preserved in Azure Notebooks

Needs discussion as this might be something we'll like to have.

**Comment by greazer** [comment]
I am no longer reproing this. Here's a scenario I followed.

•  Create a new AzML notebook in studio. Run a cell to establish compute and kernel
•  Click out to vscode.dev. 
•  Manually open the file that was being edited. Kernel selection has not been done. User must choose. This is the topic of [Issue 1908](https://github.com/microsoft/vscode-tools-for-ai/issues/1908).
•  Click the "Select Kernel" button and make your way through choosing kernel on the remote Azure ML compute
•  The live kernel has been connected. Note that this used to be a problem. Apparently Don (on the Jupyter team) addressed this, which is great news.
•  Refresh the browser window. The live kernel is reconnected. I believe this is the crux of [Issue 1857](https://github.com/microsoft/vscode-tools-for-ai/issues/1857). Furthermore, if you close both AzML's tab and vscode.dev, then perform the whole clickout routine again, the live kernel is reconnected all the way through. Therefore, I think 1857 should be considered closed.
