### ISSUE TITLE
Change the runconfig icon. 

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#189]
Currently looks like a box inside brackets. Why? Don't know. It should look like something related to "running", say a play button or something that looks "active".

**Comment by swinner95** [comment]
@swinner95 follow up with Chris as to why the runconfig icon is the way it is.

**Comment by swinner95** [comment]
There is no specific reason why this original icon was chosen, we can change this and we should.

**Comment by tbombach** [comment]
Obsolete/no longer necessary
