### ISSUE TITLE
Remote Linux Machine configuration

### ISSUE THREAD

**Issue by bchamand** [Microsoft/vscode-tools-for-ai#19]
Hi,

It's the first time where I use this extensions and I don't understand how I can configure the extension correctly. I would like to run a PyTorch code on a remote machine, in local, it work perfectly.

### Environment data
VS Code version: 1.19
Python Extension version: 0.91
Visual Studio Code Tools for AI version: 0.1.6
Python Version: 3.6.5
OS and version: OSX High Sierra

###  Remote server:
Python Version: 3.5.2
OS and version: Ubuntu 16.04 LTS

### Actual behavior
When I run a job, I get the following error : 
<img width="585" alt="" src="https://user-images.githubusercontent.com/10047581/34185557-54153288-e526-11e7-8ddb-815c437794d9.png">

### Expected behavior
Automatic connection to the server, I think.

### Steps to reproduce:
* Add Platform configuration
* Set host, userName variables for a SSH connexion
* Right click of your python code and click on "AI: Submit Job"

Do you have examples or a documentation to configure the ai_job_properties.json file and a remote server ? Because maybe I have misconfigured the extension

Thank you

**Comment by qfyin** [comment]
Hi @bchamand, the schema of remote Linux machine configuration file was changed.
In the upcoming **0.1.8** release, you can config the remote Linux machine like this:
{
    host: 'sample.org',
    port: 22,
    username: 'sample',
    password: 'password',
    privateKeyFilePath: '/home/sample/.ssh/id_rsa'
 }
at least one of username/privateKeyFilePath should be provided.
If a password phrase is used for the key file, please also provide the phrase like this:
{
    host: 'sample.org',
    port: 22,
    username: 'sample',
    password: 'password',
    privateKeyFilePath: '/home/sample/.ssh/id_rsa',
    passphrase: 'phrase'
 }
