### ISSUE TITLE
Drive Jupyter team to attach to running kernel

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1902]

**Comment by sevillal** [comment]
Dup of: https://github.com/microsoft/vscode-tools-for-ai/issues/1857

**Comment by greazer** [comment]
Jupyter can attach to running kernels. This is no longer an issue. However, there's still remains the ability for Jupyter to automatically connect to a running kernel based on a source notebook location other than VS Code. I.e. AzML Studio.
