### ISSUE TITLE
Stale refresh token fails to cause re-authentication

### ISSUE THREAD

**Issue by pletnes** [microsoft/vscode-tools-for-ai#1914]
Does this occur consistently?  No
Repro steps:

Not sure how to reproduce, but this is what I did:

1. Open VSCode from Azure ML Studio (*not* classic!)
2. Use it for some time
3. After a few days, try to open again. The `OUTPUT` window contains errors with this message
   ```
   AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2023-01-redacted and the maximum allowed lifetime for this request is redacted.
   ```

I would expect the VSCode extension to re-authenticate in this case. Re-authenticating with `az` CLI does not help.

Action: Resolver.resolve
Error type: 72
Error Message: invalid_grant: redacted:id - [redacted:id redacted:id53Z]: AADSTS70043: The refresh redacted:key expired or is invalid due to sign-in frequency checks by conditional access. The redacted:key issued on redacted:id05T07redacted:id4796609Z and the maximum allowed lifetime for this request is redacted:id.
Trace ID: redacted:id
Correlation ID: redacted:id
Timestamp: redacted:id redacted:id53Z - Correlation ID: redacted:id - Trace ID: redacted:id

Version: 0.22.0
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.74.3
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.js:2:1926294
```

</details>

**Comment by shsuman** [comment]
@pletnes Can you please share the trace logs with us ? [Here's](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-trace-logs-for-azure-machine-learning---remote-extension-) how you can get those.

**Comment by pletnes** [comment]
Fortunately / unfortunately I managed to re-login after a couple of hours of restarting vscode, logging out in various places, etc. I can't reproduce it but I will post logs here again if I encounter the issue again.

In general, the extension looks really, really promising but has a few bugs here and there. I hope you get the time to work them out!

**Comment by shsuman** [comment]
@pletnes Glad that you were able to resolve the issues. Please reopen it or file a new issue if you face the problem again :)

Also, for any other bugs or issues that you are facing, please feel free to create issues :)
