### ISSUE TITLE
Unable to clickout to VS Code on long-running compute

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1922]
I was using a Azure ML compute to run a notebook a couple weeks ago. Unfortunately, it appears as though I forgot to set it to shut down automatically so it's been running all this time. :) I had a notebook open and was able to run a cell. I tried to click out to VS Code, but it seems that for some reason our extension is unable to install VS Code server onto the compute. 

Log sent to Sergio in chat.

**Comment by tbombach** [comment]
I'll try to repro with a long running cell

**Comment by tbombach** [comment]
I did a few tests with long-running notebook cells (sleeps, downloading files, loops). I wasn't able to repro the issue, since clickout still worked fine for me while the cells were running. I'll take a look at the logs and see if I can see anything there.
