### ISSUE TITLE
Unable to connect to Compute Instance from VS Code

### ISSUE THREAD

**Issue by akrsrivastava** [microsoft/vscode-tools-for-ai#1944]
## Expected Behavior
In the Azure ML Notebook page, clicking on "Edit in VS Code" link should open VS Code and connect to the compute Instance.

## Actual Behavior
I get error message "The user may not have permission to Connect to the Compute Instance xxxx. Please ensure that you're signed into the right Azure Account and connecting to the right Compute Instance" 
I am able to login to Azure ML portal using the same id/pwd

## Steps to Reproduce the Problem

  1.Click on Edit in Visual Studio link in Azure ML Notebook
  2. Provide AzureML id and password when prompted in the browser
  

## Specifications

  - VS Code Version: 1.75.1
  - Platform: MacOS Monterey 12.6.2

**Comment by tbombach** [comment]
Hi @akrsrivastava, I apologize for this issue that you are experiencing. Is this Compute Instance one that you created, or did someone else create it and granted you permissions to access it?

**Comment by akrsrivastava** [comment]
It was created by someone else and I was provided permission to it.
