### ISSUE TITLE
Not able to connect Azure ML via VS code

### ISSUE THREAD

**Issue by sada31** [microsoft/vscode-tools-for-ai#1945]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: 70
Error Message: request to redacted:url failed, reason: unable to get local issuer certificate

Version: 0.24.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.js:2:1981665
extension.js:2:2017140extension.js:2:2017140
```

</details>

**Comment by tbombach** [comment]
Hi @sada31, I apologize for this issue that you are experiencing. Just to confirm: this error occurred when you tried to connect to a Compute Instance with VS Code, correct?

If so, is this Compute Instance in a private link workspace? Additionally, are you able to use other applications on the Compute Instance (like Jupyter)?

**Comment by tbombach** [comment]
@sada31 I'm going to close this issue for now, but please re-open it if you still experience this problem

**Comment by olihofmann** [comment]
I have this issue since today, any updates?
