### ISSUE TITLE
Azure Machine Learning Remote extension install issue W10 WSLv2

### ISSUE THREAD

**Issue by corticalstack** [microsoft/vscode-tools-for-ai#1948]
## Expected Behavior
In VS Code, following right-click of a running compute instance within the default AML workspace, I click connect, as I want to run a workload on the compute instance compute.  VS Code indicates the AML Remote extension is required to perform the selected operation, and offers an "Install now" option. I click on this, and it runs for several minutes before timing out with error.

I have also tried installing the AML Remote extension via the extensions view. I can install it from here, **but note**. I'm launching VS Code from WSLv2 hosted on Windows 10. So after VS Code has installed the AML Remote extension, and then I view the installed extensions, I see Azure Machine Learning remote in the "Local - Installed" collection of extensions, and the main Azure Machine Learning extension installed in the "WSL:Ubuntu" collection.

## Specifications

  - Version: VS Code 1.75.1
  - Platform: WSLv2 running Ubuntu 20.04 LTS under W10

**Comment by tbombach** [comment]
Hi @corticalstack. I apologize for the issue you are experiencing. We haven't tested using the AzureML remote extension in a WSLv2 scenario (which we consider a remote-in-remote scenario since the WSLv2 connection involves a VS Code/VS Code server connection). I will try this scenario and see if I can figure out what is going wrong here.

In the meantime, would you be able to work around this issue by logging into Azure in your Windows 10 VS Code client and connecting to your Azure Machine Learning compute instance that way (without WSL)?

**Comment by corticalstack** [comment]
> Hi @corticalstack. I apologize for the issue you are experiencing. We haven't tested using the AzureML remote extension in a WSLv2 scenario (which we consider a remote-in-remote scenario since the WSLv2 connection involves a VS Code/VS Code server connection). I will try this scenario and see if I can figure out what is going wrong here.
> 
> In the meantime, would you be able to work around this issue by logging into Azure in your Windows 10 VS Code client and connecting to your Azure Machine Learning compute instance that way (without WSL)?

Thanks for the suggestions. VS Code launched directly from host Windows OS (so not virtualised), the AML remote function doesn't work either. This is perhaps due to my AML workspace being behind a VNET and private endpoint connection. I can manage some of the workspace and run AML tasks, like create new compute instances, datasets, and submit a training job command (Python SDK v2 ) from local VS Code. So this indicates I'm getting through to the workspace at least (connected via VPN). 

I wonder if it's a websocket issue - when trying to connect, I get VS Code notifications for "Installing VS code server on CI", "Installing websocket server on CI", and then it just stops working then failes with "WebSocket close with status code 1006".

Incidentally, WSL under Windows is common setup scenario for data scientists with corporate laptops working with machine learning - the AML remote extension should work under such scenarios.

**Comment by shsuman** [comment]
Closing in favor #2078
