### ISSUE TITLE
Unable to connect to Azure compute instance. Getting 502 Bad Gateway error.

### ISSUE THREAD

**Issue by mohdsaqibdd2b** [microsoft/vscode-tools-for-ai#1950]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: Z
Error Message: Failed to connect to target. Make sure that it exists and is in a running state (Error: Invalid response: 502 Bad Gateway)

Version: 0.24.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
Z.NotAvailable extensionHostProcess.js:94:17105
w.handle400BadRequestAnd502BadGateway extension.js:2:2005585
w.handleError extension.js:2:2004449
o.value extension.js:2:1967010
extension.js:2:2018460extension.js:2:2018460
```

</details>

**Comment by sevillal** [comment]
Thanks for filing this issue @mohdsaqibdd2b.

Could you please confirm that the compute instance exist and is in running state?

**Comment by sevillal** [comment]
Closing this due inactivity, please reopen if needed.
