### ISSUE TITLE
Upgrade to the latest vscode-extension-telemetry package

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1956]
Upstream: https://github.com/microsoft/vscode-extension-telemetry/issues/143

Discuss and define next steps regarding the upstream fix that we were facing with telemetry-extension.

**Comment by tbombach** [comment]
Let's look at telemetry in our weekly meeting and see if almost everyone is on VS Code 1.76.0, then we can upgrade the telemetry library we use

**Comment by sevillal** [comment]
### Issue
The **vscode-telemetry-extension** in version **0.6.2** drops error messages from 3rd remote authorities and in that version of the package the `amlext` is not part of the 1st party extension ids. 

Azure ML main and remote extensions use that version of the package, causing the missing resolver error event in our telemetry data.

### Solution
Updating to the latest version of the package should fix this issue. VS Code fixed this in the version **vscode-telemetry-extension** version **0.7.5** and VS Code version 1.76.0.

It is safe to do this change considering the following numbers:
- Remote: In the last month, 95% of the customers using the remote connection updated their extension to the latest version, and 99% of those customers are using VS Code > 1.76.0.
- Main: In the last month, 93% of the customers using main extension updated the extension to the latest version, and 99.7% of them are suing VS Code > 1.76.0.

By updating to the latest version, we also gain support of logging all our telemetry message into the `Extension Telemetry` output channel.

### Changes to be aware
New telemetry library will change the event and extension names in Kusto by prepending the publisher id. For example, extension name will change from "vscode-ai-remote" to "ms-toolsai.vscode-ai-remote" and event "vscode-ai-remote/resolve/error" will change to "ms-toolsai.vscode-ai-remote/resolve/error".

### Next steps
- [ ] Coordinate with the vscode-azure-tools to update the telemetry package in their library
- [ ] Update the remote desktop telemetry dashboard accordingly to use the appropriate error event name
- [ ] Inform Alex K about this update and potential impact to his dashboards

**Comment by sevillal** [comment]
Merged in remote extension.
