### ISSUE TITLE
Can't us VScode with azure

### ISSUE THREAD

**Issue by harshita-rygbee** [microsoft/vscode-tools-for-ai#1959]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: 70
Error Message: The terminal process did not finish within 120 seconds. Aborting to exit.

Version: 0.24.0
OS: darwin
OS Release: 22.2.0
Product: Visual Studio Code
Product Version: 1.74.3
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.js:2:1981665
extension.js:2:2017140extension.js:2:2017140
```

</details>

**Comment by tbombach** [comment]
Hey @harshita-rygbee, thank you for filing this. The timeout can occur during transient communication issues - are you still experiencing this issue or has it resolved itself?

**Comment by tbombach** [comment]
@harshita-rygbee I'm going to close this issue for now, but please re-open it if you're still experiencing this issue.
