### ISSUE TITLE
Error messsages when submiting a run

### ISSUE THREAD

**Issue by swinner95** [microsoft/vscode-tools-for-ai#196]
When I try to create a submit a run I get the error messages below: 

1) Cannot read property 'map' of undefined

2) AMLFlask: Traceback (most recent call last): File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\compute\compute.py", line 342, in list resp.raise_for_status() File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\requests\models.py", line 940, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://management.azure.com/subscriptions/15ae9cb6-95c1-483d-a0e3-b1a1a3b06324/resourceGroups/shwinner/providers/Microsoft.MachineLearningServices/workspaces/pipelines/computes?api-version=2018-11-19 During handling of the above exception, another exception occurred: Traceback (most recent call last): File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\common\decorator.py", line 26, in wrapper return function(*args, **kwargs) File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\con...

**Comment by swinner95** [comment]
This seems to randomly happen when:

1) I was working elsewhere in VSCode and then switched to use the extension
2) When I open the extension, sometimes I get a flask error and sometimes I don't. Not sure what is happening. 

Suggestion: Clean up stack base error

**Comment by shsuman** [comment]
Can you try to extract the message from the error you are getting ?
