### ISSUE TITLE
Clickout from AzML Studio to vscode.dev or desktop should auto-select and connect the kernel that was being used in the Studio

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#1961]
Not only should it select the same kernel based on the metadata written to the ipynb file, it should also connect to the same instance of the kernel (if one had been started). Here's the scenario:

1) Open NotebookA.ipynb in AzML Studio.
2) Choose "Azure ML Python 3.10" (or whatever name of kernel that's available on the compute).
3) Run a cell in Studio.
4) Clickout to vscode.dev.

Expected
VSCode.dev should open in a tab with the target notebook opened. In addition, the kernel that was instantiated in AzML Studio at step 3, above, should be chosen and connected to automatically.

**Comment by greazer** [comment]
Blocked on upstream: https://github.com/microsoft/vscode-jupyter/issues/12987

**Comment by sevillal** [comment]
Upstream issue has been closed and now we are capable of pre-select the same kernel session only for the active notebook in ML Studio that we are coming from.
