### ISSUE TITLE
Unable to connect to compute instance from VS Code

### ISSUE THREAD

**Issue by grizzlybearg** [microsoft/vscode-tools-for-ai#1962]
Does this occur consistently? 
Repro steps:

1. Trial 1: From Azure extension, connect to Machine Learning Compute Instance
2. Trial 2: From Azure ML Studio, open terminal from notebooks. Select editor as VS Code

In both cases a 502 bad Gateway occurs. Do I need to setup another compute instance?

Action: Resolver.resolve
Error type: Z
Error Message: Failed to connect to target. Make sure that it exists and is in a running state (Error: Invalid response: 502 Bad Gateway)

Version: 0.24.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
Z.NotAvailable extensionHostProcess.js:94:17105
w.handle400BadRequestAnd502BadGateway extension.js:2:2005585
w.handleError extension.js:2:2004449
o.value extension.js:2:1967010
extension.js:2:2018460extension.js:2:2018460
```

</details>

**Comment by tbombach** [comment]
Hi @grizzlybearg, my apologies for this issue that you are experiencing. Is this Compute Instance within a Private Link workspace? Additionally, are you able to use other applications (like JupyterLab) with this Compute Instance?

**Comment by tbombach** [comment]
Thank you for letting us know! Closing this issue
