### ISSUE TITLE
Cannot Connect to Azure ML

### ISSUE THREAD

**Issue by bigapple716** [microsoft/vscode-tools-for-ai#1966]
Does this occur consistently? 
Repro steps:

1. Open AML Compute Instance
2. Click VS Code to connect

Action: Resolver.resolve
Error type: 70
Error Message: The terminal process did not finish within 120 seconds. Aborting to exit.

Version: 0.24.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.0
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.js:2:1981665
extension.js:2:2017140extension.js:2:2017140
```

</details>

**Comment by tbombach** [comment]
Hey @bigapple716, thank you for filing this. The timeout can occur during transient communication issues - are you still experiencing this issue or has it resolved itself?

**Comment by bigapple716** [comment]
I tried deleting `.vscode-server/` on my AML Compute instance and haven't experienced connection issues since then.
