### ISSUE TITLE
Error message when trying to submit a run again after cancelling the submission of the previous runconfig

### ISSUE THREAD

**Issue by swinner95** [Microsoft/vscode-tools-for-ai#197]
Repro steps:
1) right click on a file and select 'Azure ML: run as an experiment in azure'
2) selected my compute target from command palette
3 Created a new runconfig
4) selected the python framework
5) Instead of selecting the 'Submit' button, I selected 'Cancel'.
6) I tried to run the experiment again by right clicking on the file and selecting 'Azure ML: run as an experiment in azure'
7) Selected my compute from the command palette 
8) Got this Error message **'Cannot read property 'target' of null'**

**Comment by greazer** [comment]
Fixed by #190
