### ISSUE TITLE
The popup prompting me *incessantly* to set up a default workspace is evil and should be banished from this Earth

### ISSUE THREAD

**Issue by vladiliescu** [microsoft/vscode-tools-for-ai#1972]
## Expected Behavior

I'm not prompted with a popup asking, pleading, begging me to set up a default workspace each time I do something that invokes the extension (like, say, editing a `.py` file). 

Alternatively, if the powers that be insist on having this popup, make it so that I can dismiss it once and for good (and not each and every time I edit a `.py` file or a `.yaml` file or anything, really).

I do not need features such as completions and validations in my YAML files, I really don't. 

You may suggest actually setting up a default workspace to quench its thirst, but this doesn't really work when using multiple tenants/accounts.

## Actual Behavior

A popup appears from the mist of time, announcing that "No default Azure ML Workspace is selected. You need to select a default workspace to enable features such as completions and validations in your YAML files.". Dismissing it only makes it stronger, strong enough for it to appear the next time I start VS Code. And the next time. And the next.

## Steps to Reproduce the Problem

  1. Start VS Code
  1. Do anything useful (edit a `.py` file, for example)
  1. The popup appears
  2. Disable the AML extension once again, so that you can have some peace and quiet

## Specifications

  - Version: v0.28.0
  - Platform: MacOS
  - Screen Reader: Nope

**Comment by tbombach** [comment]
Hi @vladiliescu, I apologize for this issue. We have some logic so that this prompt is supposed to remember that you've dismissed it but it seems that it's not working as intended. I'll look into the code and figure out why that is.

Additionally, we seem to be prompting any time our extension activates (e.g. with python files) when we really should limit it just to YAML files (and of course still allow users to dismiss the prompt for good). I'll work on making this change for an upcoming release.

**Comment by vladiliescu** [comment]
Thanks @tbombach, both your proposed changes sound good!

**Comment by vladiliescu** [comment]
Hi, are there any news on this?

**Comment by shsuman** [comment]
@vladiliescu Are you still facing this issue ?

**Comment by vladiliescu** [comment]
@shsuman Last time I've checked (sometime in the past couple of months) it was still there. I've solved this by gradually not using the AML extension.

**Comment by shsuman** [comment]
> Hi @vladiliescu, I apologize for this issue. We have some logic so that this prompt is supposed to remember that you've dismissed it but it seems that it's not working as intended. I'll look into the code and figure out why that is.
> 
> Additionally, we seem to be prompting any time our extension activates (e.g. with python files) when we really should limit it just to YAML files (and of course still allow users to dismiss the prompt for good). I'll work on making this change for an upcoming release.

@vladiliescu We no longer prompt on python files as @tbombach proposed here.
