### ISSUE TITLE
Azure Machine Learning Remote Extension Installation Failed

### ISSUE THREAD

**Issue by snazaire** [microsoft/vscode-tools-for-ai#1981]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.viewContext.computeInstance.connect
Error type: 412
Error Message: Unable to install Azure Machine Learning - Remote extension, please retry installing from VS Code Extensions view. Operation timed out.

Version: 0.28.0
OS: linux
OS Release: 5.15.0-1031-azure
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:2098745
```

</details>

**Comment by sevillal** [comment]
Hi @snazaire, I apologize for this issue that you are experiencing. We'll look into this issue, could you please try to install the "Azure Machine Learning - Remote" extension manually from the extensions tab in VS Code and retry connecting to the Compute Instance.

**Comment by sevillal** [comment]
Closing due inactivity, please reopen if the issue persists.
