### ISSUE TITLE
Cannot Connect to Azure ML 

### ISSUE THREAD

**Issue by hamfrysl** [microsoft/vscode-tools-for-ai#1991]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'type')

Version: 0.28.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.77.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:2332083extension.js:2:2332083
```

</details>

**Comment by tbombach** [comment]
Hi @hamfrysl. Thank you for reporting this. Would you be able to update your version of the Azure Machine Learning extension to 0.30.3? We made a change and I think it should be resolved in that later version.

**Comment by hamfrysl** [comment]
Hi @tbombach ,
Many thanks for getting back to me on this. Indeed the problem was with the latest update at the time. I first went round it by downgrading AML and after a week updated it with no problems. Sorry forgot to update status on here.
