### ISSUE TITLE
Cant delete a deployed service.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#200]
You get this error:
AMLFlask: Traceback (most recent call last):   File "c:\Users\Jim\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\common\decorator.py", line 26, in wrapper     return function(*args, **kwargs)   File "c:\Users\Jim\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\controller\service.py", line 171, in delete_services     service[0].delete() AttributeError: 'dict' object has no attribute 'delete'

**Comment by shsuman** [comment]
i just deleted a service successfully. Maybe was some temporary error on the Azure side

**Comment by shsuman** [comment]
Moving it to Done for now
