### ISSUE TITLE
Can't sign in to my VM

### ISSUE THREAD

**Issue by odellus** [microsoft/vscode-tools-for-ai#2018]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: 72
Error Message: invalid_grant: redacted:id - [redacted:id redacted:id19Z]: AADSTS70043: The refresh redacted:key expired or is invalid due to sign-in frequency checks by conditional access. The redacted:key issued on redacted:id27T18redacted:id6466605Z and the maximum allowed lifetime for this request is redacted:id.
Trace ID: redacted:id
Correlation ID: redacted:id
Timestamp: redacted:id redacted:id19Z - Correlation ID: redacted:id - Trace ID: redacted:id

Version: 0.28.1
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.js:2:1981747
async n.acquireBearerToken extension.js:2:1924701
```

</details>

**Comment by tbombach** [comment]
Hi @odellus, I apologize for this issue that you are experiencing. Are you able to use any other Azure extensions for VS Code? The Azure Machine Learning extension authenticates with the same credentials that are used for all Azure extensions. If you are able to use them, then this will help narrow down if the issue only affects the Azure Machine Learning extension.
