### ISSUE TITLE
VSCode not picking up on git credential helper

### ISSUE THREAD

**Issue by ijlyttle** [microsoft/vscode-tools-for-ai#2020]
## Expected Behavior

That VS Code use the git credential helper when git is configured (on Azure ML VM) using:

```
[credential "https://github.com"]
        helper = !gh auth git-credential
```

This follows a [suggestion from the gh cli team](https://github.com/cli/cli/pull/2449#issuecomment-732382105).

## Actual Behavior

VS Code prompts me for a git user/password. However using `git` at the command line works as expected.

## Steps to Reproduce the Problem

  1. Create AzureML VM
  1. Connect to VM using VS Code
  1. Install `gh` on VM
  1. Set `user.name` and `user.email` using `git config`
  1. Set environment variable: `GH_TOKEN`
  1. Confirm token working using `gh auth status`
  1. Add lines from previous section to `~/.gitconfig`
  1. Make a commit
  1. Push the commit using the VS Code interface

## Specifications

  - Version: 
      ```
       Name: Azure Machine Learning - Remote
       Id: ms-toolsai.vscode-ai-remote
       Version: 0.29.2023050109
     ```
  - Platform: MacOS

**Comment by tbombach** [comment]
Hi @ijlyttle, thank you for reporting this issue and for the very clear repro steps. We haven't used the Github CLI in our remote connections in the past, so we're a bit unfamiliar with configuring VS Code to use the credential helper. We will follow your steps and investigate further and let you know what we find.

**Comment by shsuman** [comment]
@ijlyttle I followed the steps above and got the VSCode's error to ser name and email:

```log
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
```

But after setting those, I was able to commit and publish using the VSCode's interface.

What is the exact error that you are getting ?
Have you checked the scope of your token ?

**Comment by ijlyttle** [comment]
@shsuman Thanks - I should have added the `git config` steps to the steps above. In my case, I had moved a `.gitconfig` file into place.

I don't think it's a token-scope issue because I can push and pull from the command line of the compute instance.

**Comment by shsuman** [comment]
@ijlyttle Can you provide me with the VSCode's git logs ? Here's the steps you can follow: 

* Set VSCode's log level to _Trace_ by running the command (Ctrl + Shift + P) `Developer: Set Log Level`
* Do some git operation using VSCode interface like pull, commit etc...
* Open the Output Channel (Ctrl + Shift + U or View -> Output), and select the _Git_ output:
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/44413557/0e86e1e6-b1ca-488f-8e4e-1735ddba110f)

__Important: Make sure to redact any PIIs from the logs__

**Comment by ijlyttle** [comment]
@shsuman Here's the output from VSCode, which does not succeed:

```
2023-06-07 14:31:19.354 [trace] Operation start: Push (blocking: true, readOnly: false; retry: false; showProgress: true)
2023-06-07 14:31:30.534 [info] > git push -u origin test [11180ms]
2023-06-07 14:31:30.534 [info] remote: Repository not found.
fatal: Authentication failed for '===url for repo redacted==='
2023-06-07 14:31:30.827 [info] > git config --get commit.template [132ms]
2023-06-07 14:31:30.942 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/test refs/remotes/test [233ms]
2023-06-07 14:31:31.443 [info] > git status -z -uall [490ms]
2023-06-07 14:31:31.445 [trace] Operation end: Push (blocking: true, readOnly: false; retry: false; showProgress: true)
```

Here's what I do, using the terminal, which does succeed:


```
git push -u origin test
```

```
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Writing objects: 100% (3/3), 444 bytes | 6.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
remote: 
remote: Create a pull request for 'test' on GitHub by visiting:
remote:      ===url for repo redacted===
remote: 
To ===url for repo redacted===
 * [new branch]      test -> test
branch 'test' set up to track 'origin/test'.
```

(all PII redacted)

**Comment by shsuman** [comment]
@ijlyttle This seems like a VSCode issue. Can you please open an issue on their repo https://github.com/microsoft/vscode/issues.

Please mention that you are on an Azure ML Remote environment. Feel free to tag me, so I can follow up and provide any details needed from our side.

I will close this issue now, please reopen a new issue if you need any help with something else :)
