### ISSUE TITLE
unable to open remote connection 

### ISSUE THREAD

**Issue by sumeyraunal** [microsoft/vscode-tools-for-ai#2026]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: 70
Error Message: request to redacted:url failed, reason: unable to get local issuer certificate

Version: 0.28.1
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.78.0
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.js:2:1981706
extension.js:2:2007388extension.js:2:2007388
```

</details>

**Comment by sevillal** [comment]
Closing as duplicate of: https://github.com/microsoft/vscode-tools-for-ai/issues/2030
