### ISSUE TITLE
Spark job templates missing

### ISSUE THREAD

**Issue by timoklimmer** [microsoft/vscode-tools-for-ai#2028]
## Expected Behavior
When clicking on + / "Create Resource", there is no template for creating a Spark job. I am expecting a template for creating a Spark job as well as a Spark pipeline step, including the ability to specify extra packages for the job.

## Actual Behavior
See above.

## Steps to Reproduce the Problem

  1. Open the AML extension in VS.Code.
  2. Create a new template by clicking on + / "Create a Resource"
 
-> There are no templates for Spark.

## Specifications

  - Version: v0.30.3
  - Platform: AzureML Compute Instance

**Comment by shsuman** [comment]
@timoklimmer We are aware of this limitation and are tracking the same in #2090. The templates are not controlled by us and rather filled by a CDN owned by Azure ML team. We are working with them to get this done.
