### ISSUE TITLE
VS Code is not connecting to Azure ML Compute instance's Kernel

### ISSUE THREAD

**Issue by karthik9001** [microsoft/vscode-tools-for-ai#2039]
Does this occur consistently? 
Repro steps:

!
![Screenshot 2023-05-12 at 9 29 39 AM](https://github.com/microsoft/vscode-tools-for-ai/assets/58678097/f29a7cb3-e7de-4935-873a-f6ea8127bae4)
(https://github.com/microsoft/vscode-tools-for-ai/assets/58678097/5e7ad7e2-360f-48e7-b230-063cab6181fb)

1.
2.

Action: azureml.commandPalette.workspace.setDefault
Error type: ECONNRESET
Error Message: Invalid response body while trying to fetch redacted:url read ECONNRESET

Version: 0.32.2
OS: darwin
OS Release: 22.4.0
Product: Visual Studio Code
Product Version: 1.77.2
Language: en

<details>
<summary>Call Stack</summary>

```
Gunzip.<anonymous> extension.js:2:1782955
```

</details>

**Comment by sevillal** [comment]
Hi @karthik9001, I apologize for the issue you encountered. Could you please check if the workspace you are trying to access is visible in the Azure ML extension tree view?

Also could you please share the Azure ML extension log by following [this instructions](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-trace-logs-for-azure-machine-learning-extension-).

**Comment by karthik9001** [comment]
Please find below the requested trace log. I would really appreciate a faster response to fix this problem. It just keeps going in circles between choosing my Azure ML Workspace and Kernel, but wouldn't connect with my compute instance or its kernel.

[Trace - 2023-05-19 23:35:59.730] JupyterUriProviderFactory.getJupyterUriProvider called with arguments: []
[Debug - 2023-05-19 23:35:59.730] Registering Azure ML Uri Hanlder with path:  /computeInstance/remote
[Debug - 2023-05-19 23:35:59.730] Registering Azure ML Uri Hanlder with path:  /interactiveSession/distributedJob
[Debug - 2023-05-19 23:35:59.730] Registering Azure ML Uri Hanlder with path:  /interactiveSession
[Trace - 2023-05-19 23:35:59.730] DefaultWorkspace.showSelectWorkspacePromptIfNeeded called with arguments: [
    "No default Azure ML Workspace is selected. You need to select a default workspace to enable features such as completions and validations in your YAML files."
]
[Trace - 2023-05-19 23:35:59.730] DefaultWorkspaceService.get called with arguments: []
[Trace - 2023-05-19 23:35:59.731] AuthenticationService.getAzureMLService called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:35:59.731] AuthenticationService.getSubscriptionById called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:35:59.731] AuthenticationService.listSubscriptions called with arguments: []
[Info - 2023-05-19 23:35:59.749] Using ComputeInstanceJupyterUriProvider
[Debug - 2023-05-19 23:35:59.749] Registering compute instance remote server provider
[Debug - 2023-05-19 23:35:59.749] Ensuring Jupyter extension is installed
[Debug - 2023-05-19 23:35:59.750] Jupyter extension is already installed
[Debug - 2023-05-19 23:35:59.750] Attempting to activate the extension: Jupyter
[Trace - 2023-05-19 23:35:59.751] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:35:59.799] ComputeInstanceJupyterUriProvider.getServerUri called with arguments: [
    "/subscriptions/cf43594e-a4eb-4df4-9d69-78a74185a541/resourceGroups/rg-machine-learning-qa2-northeurope/providers/Microsoft.MachineLearningServices/workspaces/mlw-bb-data-analyt-qa2-neu/computes/nakkekx-compute-qa2"
]
[Trace - 2023-05-19 23:35:59.799] Telemetry Event: remote/computeInstance/jupyterUriProvider/getServerUri Measures: undefined Props: {}
[Trace - 2023-05-19 23:35:59.799] AuthenticationService.getAzureMLService called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:35:59.799] AuthenticationService.getSubscriptionById called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:35:59.799] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-05-19 23:35:59.800] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:36:02.174] DefaultWorkspaceService.get called with arguments: []
[Trace - 2023-05-19 23:36:02.174] Refreshing tree view 
[Trace - 2023-05-19 23:36:02.174] DefaultWorkspaceService.get called with arguments: []
[Trace - 2023-05-19 23:36:02.219] DefaultWorkspaceService.set called with arguments: [
    "/subscriptions/cf43594e-a4eb-4df4-9d69-78a74185a541/resourceGroups/rg-machine-learning-qa2-northeurope/providers/Microsoft.MachineLearningServices/workspaces/mlw-bb-data-analyt-qa2-neu",
    false,
    false
]
[Trace - 2023-05-19 23:36:02.219] AuthenticationService.getAzureMLService called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:36:02.219] AuthenticationService.getSubscriptionById called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:36:02.219] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-05-19 23:36:02.220] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Info - 2023-05-19 23:37:22.130] Default workspace cache synchronized successfully.
[Info - 2023-05-19 23:37:23.339] Default workspace cache initialized successfully.
[Info - 2023-05-19 23:37:24.054] Default workspace cache synchronized successfully.
[Error - 2023-05-19 23:37:40.577] Error: Invalid response body while trying to fetch https://management.azure.com/subscriptions/cf43594e-a4eb-4df4-9d69-78a74185a541/providers/Microsoft.MachineLearningServices/workspaces?api-version=2022-10-01: read ECONNRESET
[Trace - 2023-05-19 23:38:19.799] AuthenticationService.getAzureMLService called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:38:19.799] AuthenticationService.getSubscriptionById called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:38:19.799] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-05-19 23:38:19.803] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:38:28.459] DefaultWorkspaceService.set called with arguments: []
[Trace - 2023-05-19 23:38:28.459] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-05-19 23:38:28.461] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:38:28.461] AuthenticationService.listSubscriptions called with arguments: [
    null
]
[Trace - 2023-05-19 23:38:28.462] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:38:30.193] Subscription.listWorkspaces called with arguments: [
    null
]
[Error - 2023-05-19 23:39:10.115] Error: Invalid response body while trying to fetch https://management.azure.com/subscriptions/cf43594e-a4eb-4df4-9d69-78a74185a541/providers/Microsoft.MachineLearningServices/workspaces?api-version=2022-10-01: read ECONNRESET
[Trace - 2023-05-19 23:39:17.477] DefaultWorkspaceService.set called with arguments: []
[Trace - 2023-05-19 23:39:17.477] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-05-19 23:39:17.479] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:39:17.479] AuthenticationService.listSubscriptions called with arguments: [
    null
]
[Trace - 2023-05-19 23:39:17.481] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:39:18.929] Subscription.listWorkspaces called with arguments: [
    null
]
[Error - 2023-05-19 23:39:55.267] Error: Invalid response body while trying to fetch https://management.azure.com/subscriptions/cf43594e-a4eb-4df4-9d69-78a74185a541/providers/Microsoft.MachineLearningServices/workspaces?api-version=2022-10-01: read ECONNRESET
[Trace - 2023-05-19 23:39:59.394] DefaultWorkspaceService.set called with arguments: []
[Trace - 2023-05-19 23:39:59.394] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-05-19 23:39:59.396] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:39:59.396] AuthenticationService.listSubscriptions called with arguments: [
    null
]
[Trace - 2023-05-19 23:39:59.397] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:40:01.311] Subscription.listWorkspaces called with arguments: [
    null
]
[Trace - 2023-05-19 23:40:38.068] DefaultWorkspace.initlializeCache called with arguments: []
[Trace - 2023-05-19 23:40:38.068] AuthenticationService.getSubscriptionById called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:40:38.068] AuthenticationService.listSubscriptions called with arguments: []
[Debug - 2023-05-19 23:40:38.068] [Azure ML JS SDK]Could not find discovery endpoints in cache for worksapce mlw-bb-data-analyt-qa2-neu. Calling the Workspace service to fetch discovery endpoint
[Trace - 2023-05-19 23:40:38.074] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Debug - 2023-05-19 23:40:38.822] [Azure ML JS SDK]Found discovery endpoints in cache for worksapce mlw-bb-data-analyt-qa2-neu. Returning the same.
[Trace - 2023-05-19 23:40:38.823] AuthenticationService.getBearerToken called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:40:38.823] AuthenticationService.getAuthTokenResponse called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:40:38.823] AuthenticationService.getCredentials called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:40:38.823] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-05-19 23:40:38.824] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:40:38.824] AuthenticationService.getSubscriptionById called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:40:38.824] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-05-19 23:40:38.825] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:40:38.828] Refreshing tree view 
[Trace - 2023-05-19 23:40:38.828] DefaultWorkspaceService.get called with arguments: []
[Trace - 2023-05-19 23:40:38.828] DefaultWorkspace.disableCache called with arguments: []
[Trace - 2023-05-19 23:40:38.828] AuthenticationService.getAzureMLService called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:40:38.828] AuthenticationService.getSubscriptionById called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:40:38.828] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-05-19 23:40:38.830] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:40:46.511] ComputeInstanceJupyterUriProvider.getQuickPickEntryItems called with arguments: []
[Trace - 2023-05-19 23:40:46.512] ComputeInstanceJupyterUriProvider.handleQuickPick called with arguments: [
    {
        "label": "$(device-desktop) Azure ML compute instances",
        "description": "Power your Notebook with an Azure ML compute instance",
        "detail": "Power your Notebook with an Azure ML compute instance",
        "default": true
    },
    true
]
[Trace - 2023-05-19 23:40:46.512] Telemetry Event: remote/computeInstance/jupyterUriProvider/handleQuickPick Measures: undefined Props: {}
[Trace - 2023-05-19 23:40:46.512] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-05-19 23:40:46.514] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:40:46.514] AuthenticationService.listSubscriptions called with arguments: [
    null
]
[Trace - 2023-05-19 23:40:46.515] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:40:47.903] Subscription.listWorkspaces called with arguments: [
    null
]
[Info - 2023-05-19 23:41:13.793] Default workspace cache initialized successfully.
[Trace - 2023-05-19 23:41:17.175] DefaultWorkspace.syncCache called with arguments: []
[Trace - 2023-05-19 23:41:29.957] ComputeInstanceJupyterUriProvider.getQuickPickEntryItems called with arguments: []
[Trace - 2023-05-19 23:41:29.957] ComputeInstanceJupyterUriProvider.handleQuickPick called with arguments: [
    {
        "label": "$(device-desktop) Azure ML compute instances",
        "description": "Power your Notebook with an Azure ML compute instance",
        "detail": "Power your Notebook with an Azure ML compute instance",
        "default": true
    },
    true
]
[Trace - 2023-05-19 23:41:29.957] Telemetry Event: remote/computeInstance/jupyterUriProvider/handleQuickPick Measures: undefined Props: {}
[Trace - 2023-05-19 23:41:29.957] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-05-19 23:41:29.958] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:41:29.958] AuthenticationService.listSubscriptions called with arguments: [
    null
]
[Trace - 2023-05-19 23:41:29.958] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:41:31.021] Subscription.listWorkspaces called with arguments: [
    null
]
[Trace - 2023-05-19 23:41:33.203] AuthenticationService.getUserObjectId called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:41:33.203] AuthenticationService.getAuthTokenResponse called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:41:33.203] AuthenticationService.getCredentials called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:41:33.203] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-05-19 23:41:33.204] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:41:33.204] AuthenticationService.getSubscriptionById called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:41:33.204] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-05-19 23:41:33.205] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:41:37.041] ComputeInstanceJupyterUriProvider.getServerUri called with arguments: [
    "/subscriptions/cf43594e-a4eb-4df4-9d69-78a74185a541/resourceGroups/rg-machine-learning-qa2-northeurope/providers/Microsoft.MachineLearningServices/workspaces/mlw-bb-data-analyt-qa2-neu/computes/nakkekx-compute-qa2"
]
[Trace - 2023-05-19 23:41:37.041] Telemetry Event: remote/computeInstance/jupyterUriProvider/getServerUri Measures: undefined Props: {}
[Trace - 2023-05-19 23:41:37.041] AuthenticationService.getAzureMLService called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:41:37.041] AuthenticationService.getSubscriptionById called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:41:37.041] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-05-19 23:41:37.045] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Info - 2023-05-19 23:41:54.595] Default workspace cache synchronized successfully.
[Trace - 2023-05-19 23:42:12.795] ComputeInstanceJupyterUriProvider.getServerUri called with arguments: [
    "/subscriptions/cf43594e-a4eb-4df4-9d69-78a74185a541/resourceGroups/rg-machine-learning-qa2-northeurope/providers/Microsoft.MachineLearningServices/workspaces/mlw-bb-data-analyt-qa2-neu/computes/nakkekx-compute-qa2"
]
[Trace - 2023-05-19 23:42:12.796] Telemetry Event: remote/computeInstance/jupyterUriProvider/getServerUri Measures: undefined Props: {}
[Trace - 2023-05-19 23:42:12.796] AuthenticationService.getAzureMLService called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:42:12.797] AuthenticationService.getSubscriptionById called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:42:12.797] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-05-19 23:42:12.805] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:42:15.504] ComputeInstanceJupyterUriProvider.getQuickPickEntryItems called with arguments: []
[Trace - 2023-05-19 23:42:15.505] ComputeInstanceJupyterUriProvider.handleQuickPick called with arguments: [
    {
        "label": "$(device-desktop) Azure ML compute instances",
        "description": "Power your Notebook with an Azure ML compute instance",
        "detail": "Power your Notebook with an Azure ML compute instance",
        "default": true
    },
    true
]
[Trace - 2023-05-19 23:42:15.505] Telemetry Event: remote/computeInstance/jupyterUriProvider/handleQuickPick Measures: undefined Props: {}
[Trace - 2023-05-19 23:42:15.505] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-05-19 23:42:15.505] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:42:15.506] AuthenticationService.listSubscriptions called with arguments: [
    null
]
[Trace - 2023-05-19 23:42:15.506] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:42:16.607] Subscription.listWorkspaces called with arguments: [
    null
]
[Debug - 2023-05-19 23:42:43.705] Ensuring that compute instance nakkekx-compute-qa2 is running
[Debug - 2023-05-19 23:42:43.705] Compute instance nakkekx-compute-qa2 is already running
[Trace - 2023-05-19 23:42:43.707] AuthenticationService.getAuthTokenResponse called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:42:43.707] AuthenticationService.getCredentials called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:42:43.707] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-05-19 23:42:43.712] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:42:43.712] AuthenticationService.getSubscriptionById called with arguments: [
    "cf43594e-a4eb-4df4-9d69-78a74185a541"
]
[Trace - 2023-05-19 23:42:43.712] AuthenticationService.listSubscriptions called with arguments: []
[Trace - 2023-05-19 23:42:43.714] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:42:56.810] ComputeInstanceJupyterUriProvider.getQuickPickEntryItems called with arguments: []
[Trace - 2023-05-19 23:42:56.810] ComputeInstanceJupyterUriProvider.handleQuickPick called with arguments: [
    {
        "label": "$(device-desktop) Azure ML compute instances",
        "description": "Power your Notebook with an Azure ML compute instance",
        "detail": "Power your Notebook with an Azure ML compute instance",
        "default": true
    },
    true
]
[Trace - 2023-05-19 23:42:56.811] Telemetry Event: remote/computeInstance/jupyterUriProvider/handleQuickPick Measures: undefined Props: {}
[Trace - 2023-05-19 23:42:56.811] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-05-19 23:42:56.811] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:42:56.811] AuthenticationService.listSubscriptions called with arguments: [
    null
]
[Trace - 2023-05-19 23:42:56.812] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:42:57.894] Subscription.listWorkspaces called with arguments: [
    null
]
[Trace - 2023-05-19 23:43:43.488] ComputeInstanceJupyterUriProvider.getQuickPickEntryItems called with arguments: []
[Trace - 2023-05-19 23:43:43.488] ComputeInstanceJupyterUriProvider.handleQuickPick called with arguments: [
    {
        "label": "$(device-desktop) Azure ML compute instances",
        "description": "Power your Notebook with an Azure ML compute instance",
        "detail": "Power your Notebook with an Azure ML compute instance",
        "default": true
    },
    true
]
[Trace - 2023-05-19 23:43:43.488] Telemetry Event: remote/computeInstance/jupyterUriProvider/handleQuickPick Measures: undefined Props: {}
[Trace - 2023-05-19 23:43:43.488] AuthenticationService.promptLoginIfNecessary called with arguments: []
[Trace - 2023-05-19 23:43:43.489] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:43:43.489] AuthenticationService.listSubscriptions called with arguments: [
    null
]
[Trace - 2023-05-19 23:43:43.489] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "result": "false"
}
[Trace - 2023-05-19 23:43:44.838] Subscription.listWorkspaces called with arguments: [
    null
]

**Comment by sevillal** [comment]
@karthik9001 thanks for sharing those logs, are you open to join a quick triage call to try to resolve this faster? Please send me an email to sevillal@microsoft.com and I'll setup some time.

**Comment by karthik9001** [comment]
I was requested to downgrade to Azure ML version 0.30.3, while the app team is going to look to fix the problem with version 0.32.2

Thanks, Sevillal for hoping on the call to review my issue.

**Comment by sevillal** [comment]
Closing in favor of: https://github.com/microsoft/vscode-tools-for-ai/issues/2075
