### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jeessan** [microsoft/vscode-tools-for-ai#2040]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: 70
Error Message: request to redacted:url failed, reason: self signed certificate in certificate chain

Version: 0.29.2023050909
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.78.1
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.js:2:1984620
extension.js:2:2010345extension.js:2:2010345
```

</details>

**Comment by sevillal** [comment]
@jeessan I apologize for the issue you are experiencing. Could you please try upgrading your VS Code to version 1.78.2 which contains fixes to certificates management.

To upgrade click the toolbar "Help" > "Check for Updates..."
