### ISSUE TITLE
Customer ask: How to run devcontainer on Azure Machine learning Compute Instance

### ISSUE THREAD

**Issue by nadeemrnd** [microsoft/vscode-tools-for-ai#2043]
Customer using devcontainers in vs code (.devcontainer.json) to manage environment, extensions, etc. when developing locally. Is there a way to use devconatiner with an Azure ML compute instance such that when they launch the compute it runs the same setup?
 
https://code.visualstudio.com/docs/devcontainers/containers#_getting-started

Would like to ubblock customer, only one option is to deployed the custom app on the CI.
We may need the image details for this kingd of the scenario.

Could you share or guide from where we can get the image so that it will be deployed as custom app on azure machine learning compute instance

**Comment by nadeemrnd** [comment]
@sevillal @tbombach , Could you please look at the customer request Thanks

**Comment by shsuman** [comment]
@nadeemrnd What's the ask here ? 
Does the customer already have a container with the same environment running on the CI ?

**Comment by iMicknl** [comment]
I hear a similar asks sometimes, to have a similar platform as GitHub Codespaces. Where everything is containerized via devcontainers, that can be easily changed and added to version control. So that everyone has exactly the same environment.

**Comment by nadeemrnd** [comment]
@shsuman , Thanks for looking into this?
Customer already using devcontainer in VScode to manage the environment.

He would to implement same with compute Instance. I think we achive this using custoimr app. For this as per ML PG it need image which support this. Do you any such image which we can use it . Or any other way which we can use devcontainer in compute instance

**Comment by shsuman** [comment]
@nadeemrnd We don't have any images that you might need. For all CI related requests, you can contact Isis McCafferty.

As for the VSCode connection to that container, we don't support that scenario right now. So today you can only connect to Azure ML Compute instances by using our remote extension and not any container within it. However, we will look into the feasibility and use cases for enabling connections to container.

**Comment by nadeemrnd** [comment]
Thanks for looking into this Shantnu
