### ISSUE TITLE
re-connection failed.

### ISSUE THREAD

**Issue by VijayRameshkumar** [microsoft/vscode-tools-for-ai#2045]
Does this occur consistently? 
Repro steps:

1. connection got failed with remote server when the remote server was running.

Action: Resolver.resolve
Error type: 72
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND vijayrinstance.centralindia.instances.azureml.ms

Version: 0.30.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.js:2:1984661
async y.checkServerStatus extension.js:2:2031336
async I.handleReconnection extension.js:2:2014467
extension.js:2:2010703extension.js:2:2010703
```

</details>

**Comment by sevillal** [comment]
Closing due inactivity. Please reopen if needed.
