### ISSUE TITLE
can not connect to azure machine learning studio by remote visual studio code... 

### ISSUE THREAD

**Issue by woodymoo** [microsoft/vscode-tools-for-ai#2046]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSessionsChanged
Error type: ECONNRESET
Error Message: Invalid response body while trying to fetch redacted:url read ECONNRESET

Version: 0.32.2
OS: darwin
OS Release: 22.4.0
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
Gunzip.<anonymous> extension.js:2:1782955
```

</details>

I have started the vs code once to connect to different jupter python file with a deleted instance.

**Comment by sevillal** [comment]
@woodymoo I apologize for the issue you encountered. 

1. Could you please confirm that you are logged into Azure in VS Code? 
2. Could you verify if you can see your subscription and workspace from the Azure ML tree view in VS Code?
3. Is the issue persistent or retrying helps?
4. Could you please share the trace logs of the Azure ML extension by following [this instructions](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-trace-logs-for-azure-machine-learning-extension-)

**Comment by sevillal** [comment]
Closing this due inactivity. Please reopen if needed.
