### ISSUE TITLE
VSCode - Azure extensions hang and block productive use of VSCode

### ISSUE THREAD

**Issue by jlbradley1844** [microsoft/vscode-tools-for-ai#2050]
Does this occur consistently? Yes
Repro steps:

1. Opening VSCode is all it takes. I get this error in the azure extension. No other extensions load. My VSCode install is now "bricked." I haven't rebooted yet, so don't know if that will resolve it.
2.

Action: Resolver.resolve
Error type: 182
Error Message: Internal extension error: redacted:key parameters cannot be read from extension context. Please try again

Version: 0.30.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
n.initializeTokenAcquisitionParams extension.js:2:1930557
async n.acquireTokenWithExpiration extension.js:2:1928206
async n.acquireBearerToken extension.js:2:1927615
```

</details>

**Comment by sevillal** [comment]
Hi @jlbradley1844, I apologize for the issue you encountered. 

To get out of that stuck state on the remote connection you can click "File" > "Close Remote Connection".

After doing that, could you please retry the remote connection to the compute instance from the Azure ML Studio and let me know if that works?

**Comment by jlbradley1844** [comment]
Yep that was it!
