### ISSUE TITLE
Connection not stable after upgrading to "preview" version.

### ISSUE THREAD

**Issue by soymilkia** [microsoft/vscode-tools-for-ai#2054]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: le
Error Message: Failed to connect to target. Make sure that it exists and is in a running state (Error: Invalid response: 502 Bad Gateway)

Version: 0.30.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.77.0
Language: en

<details>
<summary>Call Stack</summary>

```
le.NotAvailable extensionHostProcess.js:96:17055
w.handle400BadRequestAnd502BadGateway extension.js:2:1999139
w.handleError extension.js:2:1998010
o.value extension.js:2:1969921
extension.js:2:2011963extension.js:2:2011963
```

</details>

**Comment by shsuman** [comment]
@soymilkia I suspect that by preview you mean pre release version of the extension. Please note that these are untested builds which are released on a daily basis, thus there stability cannot be guaranteed. Also, in this case it looks like your CI might be shutdown.
