### ISSUE TITLE
Support for ADAL is ending on 20th June

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#2061]
We still don't support MSAL because of the missing refresh token in it but since ADAL is ultimately ending support, we need to think of something to tackle this problem and switch to MSAL.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-tools-for-ai/issues/2081
```

**Comment by vho002asr** [comment]
@shsuman are there any updates on MSAL support?

**Comment by shsuman** [comment]
We currently have it planned for October end

**Comment by shsuman** [comment]
MSAL support is available now with native VSCode auth
