### ISSUE TITLE
I cannot open Vscode in Azure ML

### ISSUE THREAD

**Issue by DanielPuentee** [microsoft/vscode-tools-for-ai#2066]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: he
Error Message: Failed to connect to target. Make sure that it exists and is in a running state (Error: Invalid response: 502 Bad Gateway)

Version: 0.30.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
he.NotAvailable extensionHostProcess.js:96:17050
w.handle400BadRequestAnd502BadGateway extension.js:2:1999139
w.handleError extension.js:2:1998010
o.value extension.js:2:1969921
extension.js:2:2011963extension.js:2:2011963
```

</details>

**Comment by shsuman** [comment]
@DanielPuentee Please make sure that your Compute instance is running :)

**Comment by DanielPuentee** [comment]
Thanks for the answer, however, the **Compute Instance is running.** I haven't solved the problem yet.

**Comment by shsuman** [comment]
@DanielPuentee Can you please send me the Azure ML - Remote _Trace_ logs for the connection ?

You can get _Trace_ logs by the following the steps [here](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-trace-logs-for-azure-machine-learning---remote-extension-)

**Comment by DanielPuentee** [comment]
This is the _Trace_

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/64250734/e244884c-bf0d-4ab6-accc-e0730eada866)

As it can be seen the **Compute Instance** is running

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/64250734/abb4bf37-ede7-4f4f-bf85-383efd5f37ac)

**Comment by shsuman** [comment]
@DanielPuentee Please send the full logs after redacting any PII.

Also, can you access Jupyter Lab from the Studio ?

**Comment by shsuman** [comment]
@DanielPuentee In that case, please contact Azure Machine Learning support as they would need to first resolve the Jupyter Lab Errors. We are completely dependent on the Jupyter Lab to make the connection happen

**Comment by shsuman** [comment]
You can create a support request [here](https://portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/resource/subscriptions/27de6be1-d524-44f2-9a95-10ab33646cc7/resourceGroups/shsuman-scus/providers/Microsoft.MachineLearningServices/workspaces/shsuman-scus/supportrequest)

I am closing this issue now as it is not related to our extensions. Also, feel free to open a new issue if you need any other help
