### ISSUE TITLE
Azure Machine Learning - Remote not working

### ISSUE THREAD

**Issue by Nguenda** [microsoft/vscode-tools-for-ai#2070]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.viewContext.computeInstance.connectInNewWindow
Error type: 412
Error Message: Unable to install Azure Machine Learning - Remote extension, please retry installing from VS Code Extensions view. Operation timed out.

Version: 0.32.2
OS: linux
OS Release: 5.15.0-1035-azure
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.js:2:2359477
```

</details>

**Comment by shsuman** [comment]
@Nguenda Are you connected to a container in VSCode ?

**Comment by Nguenda** [comment]
I am not sure. I am connected to an Azure Machine Learning account on
Vscode. Is that a container?

**Comment by shsuman** [comment]
@Nguenda You will see something like this in the remote section of your status bar (Bottom left, green section)

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/44413557/cfd2a817-28ae-4369-afbb-59bade331df9)

**Comment by Nguenda** [comment]
To get there what do I need to do?

**Comment by Nguenda** [comment]
I just installed Dev containers. What is it for?

**Comment by Nguenda** [comment]
As a matter of fact, I installed the Azure Machine learning - Remote, but every time I right click on an instance to open it in a new window, a pop message tells me that it is not installed that I have to install it. When I click on the install button, the installation starts until the pop up of this error message:" Unable to install Azure Machine Learning - Remote extension, please retry installing from VS Code Extensions view. Operation timed out."

**Comment by Nguenda** [comment]
It's working now. Thank you. What was the issue?

**Comment by shsuman** [comment]
So, if you are already connected to any kind of remote connection, SSH, Container, WSL, Azure ML, Codespaces, you cannot open another Remote connection from there. The requirement is that you open a local VSCode window (either a local folder on your machine or an empty window) and then do it. The close remote connection command basically closes the existing remote connection and open up an empty window. Hope that clarifies :). I am going to close this issue now.

**Comment by shsuman** [comment]
Feel free to open up an new issue if you have any other questions

**Comment by Nguenda** [comment]
Thanks
