### ISSUE TITLE
Configure Default AzureML Workspace via configuration?

### ISSUE THREAD

**Issue by mwisesyk** [microsoft/vscode-tools-for-ai#2072]
I just had a general question if there's an option to provide the extension the information which workspace to connect to during startup. When using dev containers for individual workspaces/projects it would be nice if it would start automatically connected to the right workspace.

**Comment by shsuman** [comment]
@mwisesyk I think it makes sense to read the .azureml/config.json and set the default workspace. However, writing back the the config.json that we might want to be cautious with. I will put this up for discussion in a separate issue and close this one. You can follow this issue for progress https://github.com/microsoft/vscode-tools-for-ai/issues/2076

**Comment by shsuman** [comment]
Please feel free to open another issue if you have some other questions
