### ISSUE TITLE
Losing Remote Connection to Azure ML Workspace Compute Node when Network is Interupted

### ISSUE THREAD

**Issue by strahl2e** [microsoft/vscode-tools-for-ai#2079]
Does this occur consistently? Yes
Repro steps:

1. Turn network connection off and on when using VSCode for remote connection to ML Workspace compute node.

Action: Resolver.resolve
Error type: 72
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND compute-name.region.instances.azureml.ms

Version: 0.30.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.79.0
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.js:2:1984661
async y.checkServerStatus extension.js:2:2031336
async I.handleReconnection extension.js:2:2014467
extension.js:2:2010703extension.js:2:2010703
```

</details>

**Comment by shsuman** [comment]
@strahl2e The remote connection relies on an uninterrupted network connection. The reliability of the connection cannot be guaranteed if the network isn't reliable.
