### ISSUE TITLE
Investigate consuming new azure auth package (vscode-azext-azureauth)

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2081]

**Comment by shsuman** [comment]
https://www.npmjs.com/package/@microsoft/vscode-azext-azureauth

https://github.com/microsoft/vscode-azuretools/tree/main/auth

https://code.visualstudio.com/api/references/vscode-api#authentication

https://github.com/microsoft/vscode/tree/main/extensions/microsoft-authentication

**Comment by shsuman** [comment]
A working prototype is ready for authentication using VSCode. 

* So, far all the information needed for the functioning of the main extension is available except user object id to determine ownership of CIs
* Also, the prototype has decoupled all the functions of the remote connections and the assumption is that will all be delegated to Azure ML - Remote extension which should work as in web
* Some functions need to be implemented by us like Subscription Filter, Create Azure Account etc... which were previously carried out by Azure Account extension
* Backward compatibility is important in things like Azure Cloud config, Subscription Filter etc,..

**Comment by shsuman** [comment]
Update:

* The prototype type now includes getUserObjectId() implementation to determine the ownership of CIs
