### ISSUE TITLE
File / folder move performs delete operation before confirmation of successful copy

### ISSUE THREAD

**Issue by LazaUK** [microsoft/vscode-tools-for-ai#2089]
## Expected Behavior
When files or folders are moved,
they should be copied to the new destination first and then only deleted.

## Actual Behavior
During move operations, the process hung. After refresh, source folder disappeared,
but there are no new folders in the destination area either.

## Steps to Reproduce the Problem

  1. Move folder or files in Azure ML workspace, e.g. notebooks.
  2. While operation is in process, reload VSCode

## Specifications

  - Version: Latest release (1.79.1)
  - Platform: Windows

**Comment by shsuman** [comment]
@LazaUK Please file issue on [VSCode](https://github.com/microsoft/vscode/issues) repository regarding this as extensions have no control over native file system operations.
