### ISSUE TITLE
Can not start my compute instance

### ISSUE THREAD

**Issue by humollil** [microsoft/vscode-tools-for-ai#2092]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.viewContext.computeInstance.connect
Error type: 404
Error Message: Not Found

Version: 0.24.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.73.1
Language: en

<details>
<summary>Call Stack</summary>

```
t.createAzureMLHttpError extension.js:2:1965099
t.HttpService.<anonymous> extension.js:2:1966807
s extension.js:2:1965323
```

</details>

**Comment by shsuman** [comment]
@humollil If you are still facing the problem, please open an Azure ML Support Request [here](https://portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/resource/subscriptions/27de6be1-d524-44f2-9a95-10ab33646cc7/resourceGroups/shsuman-scus/providers/Microsoft.MachineLearningServices/workspaces/shsuman-scus/supportrequest) as this is something beyond the scope of our extension.

Please open a new issue if you need help with something else :)
