### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nguenda** [microsoft/vscode-tools-for-ai#2096]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.viewContext.computeInstance.start
Error type: BadRequest
Error Message: Long running operation failed with error: "{"error":{"code":"StartComputeInstanceOnlyAllowedInStoppedState","message":"Start Azure ML Compute Instance is only allowed when the instance g455110851a is in 'stopped' state"}}".

Version: 0.32.2
OS: darwin
OS Release: 21.1.0
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
new t extension.js:2:42402
e.getRestError extension.js:2:3504
extension.js:2:12674
```

</details>

**Comment by shsuman** [comment]
@Nguenda It seems like your Compute instance state was not __Stopped__ when you tried to start it. It might be that its either __Stopping, Starting, Running__ etc...

Are you still facing this problem ?

**Comment by Nguenda** [comment]
Thank you for reaching out. I am no more facing this problem.
Thanks

**Comment by shsuman** [comment]
I will close this issue then :)
