### ISSUE TITLE
Failed to connect to the remote extension host server

### ISSUE THREAD

**Issue by gpacetti** [microsoft/vscode-tools-for-ai#2098]
The VS code is able to connect to the compute instance, even if the refresh token expires after 24h and I have to reconnect and authenticate the VS code again, but an unusual error happens during the 24h, the VS Code misses the connection and the following error occurs: Failed to connect to the remote extension host server (Error: Internal extension error: Token acquisition parameters cannot be read from extension context. Please try again).

Steps to Reproduce the Problem:
  1. Connect VS code to the CI
  2. Write Notebooks
  3. Wait for the error

## Specifications

  - VS Code Version: 1.79.2
  - Platform: Windows 2022

**Comment by shsuman** [comment]
@gpacetti We are aware of this issue and following up with VSCode [here](https://github.com/microsoft/vscode/issues/184490)
