### ISSUE TITLE
Viewing experiments & pipelines from the TreeView 

### ISSUE THREAD

**Issue by swinner95** [microsoft/vscode-tools-for-ai#210]
In the TreeView, when the user clicks on an experiment or published pipeline, the experiment/pipeline deeplink to the portal should open in the editor window in VS Code so the user can view the experiment/pipeline.  

![pic1](https://user-images.githubusercontent.com/43390034/54647578-3b141b00-4a60-11e9-9626-8136de661f81.JPG)

**Comment by greazer** [comment]
Use double-click if possible, and/or add a widget to the moused over item that is clickable and opens the portal.

**Comment by SiddhanthUnnithan** [comment]
Moving away from the Web View model so this is not something we'll be able to do.
