### ISSUE TITLE
Cannot connect to remote compute instance

### ISSUE THREAD

**Issue by GMGSPT** [microsoft/vscode-tools-for-ai#2107]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: 182
Error Message: Internal extension error: redacted:key parameters cannot be read from extension context. Please try again

Version: 0.30.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.79.2
Language: en

<details>
<summary>Call Stack</summary>

```
n.initializeTokenAcquisitionParams extension.js:2:1930557
async n.acquireTokenWithExpiration extension.js:2:1928206
async n.acquireBearerToken extension.js:2:1927615
```

</details>

**Comment by sevillal** [comment]
@GMGSPT I apologize for the issue you are facing. I am wondering does the connection work after retrying?

Closing this as it is a known issue and we are following up with VSCode [here](https://github.com/microsoft/vscode/issues/184490)
