### ISSUE TITLE
'View Experiment/Pipeline' from VSCode editor window 

### ISSUE THREAD

**Issue by swinner95** [Microsoft/vscode-tools-for-ai#211]
When users select to view an experiment or pipeline, the users should be able to view their experiment/pipeline from the editor window in VSCode versus have the users be directed to the portal outside of VSCode. This was also consistent feedback from the usability study.

**Comment by greazer** [comment]
We specifically made this change because VSCode was going to break the mechanism we were using the show an external webpage within VSCode. So reverting this behavior back would not be simple. In fact, it might be a large effort.
