### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by komal11lamba** [microsoft/vscode-tools-for-ai#2123]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: 70
Error Message: Cannot connect to Jupyter Lab Terminal. Please try again.

Version: 0.30.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.80.0
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.js:2:1984620
extension.js:2:2010345extension.js:2:2010345
```

</details>

**Comment by sevillal** [comment]
@tbombach could you please take a look at this one?

**Comment by tbombach** [comment]
@komal11lamba Please feel free to re-open this issue if you are still experiencing this issue
