### ISSUE TITLE
 Error obtaining refresh redacted:key your subscription. Please try again

### ISSUE THREAD

**Issue by screig** [microsoft/vscode-tools-for-ai#2125]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.viewContext.computeInstance.connect
Error type: 344
Error Message: Error obtaining refresh redacted:key your subscription. Please try again

Version: 0.33.2023071409
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.80.1
Language: en

<details>
<summary>Call Stack</summary>

```
j.<anonymous> extension.js:2:2557383
s extension.js:2:2553429
```

</details>

**Comment by sevillal** [comment]
@screig I apologize for the issue you are experiencing. What is the `Azure: Authentication Library` setting that you have (msal or adal)? You can check it by opening VS Code settings and looking for `azure.authenticationLibrary`.

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/56176070/9107560a-4251-4d13-898c-3af550635dcb)

Also could you please share here the logs of the Azure ML output channel, [here](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-trace-logs-for-azure-machine-learning-extension-) the instructions on how to do it.

**Comment by screig** [comment]
I opened another ticket

https://github.com/microsoft/vscode-azure-account/issues/832

That has the logs.

**Comment by sevillal** [comment]
Closing this in favor of https://github.com/microsoft/vscode-azure-account/issues/832
