### ISSUE TITLE
Pagination shows "Show more" option in an empty quick pick (filtered result)

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#2149]
- User is trying to connect to a remote compute instance jupyter server
- User selects subscription, workspace
- Compute instance quick pick is displayed empty with the "Show more" button
- Customer clicks multiple times the "Show more" then the compute instance that is being looked for appears

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/56176070/31e51b44-d4c6-4169-96d9-c722573bafdf)

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/56176070/d2a85776-a142-4925-b2c4-a9a389877d14)

**Comment by tbombach** [comment]
We suspect this is a filtering related bug to address. The customer seems to have been assigned a compute but it didn't appear in the first page. The entire first page was comprised of computes which he did not have permissions to use, so it was empty in this case but later pages did have the compute he had permissions. So we need to get more pages if there are empty pages.
