### ISSUE TITLE
[Web] Investigate uncategorized remote connection error: "Failed to fetch"

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#2154]

**Comment by shsuman** [comment]
From the error message, it seems like that the error comes from the fetch function provided to the Jupyter Lab Settings. This [issue](https://github.com/jupyterlab/jupyterlab/issues/3964) describes the same error in Jupyter Lab when trying to save a file which occurs for a variety of different reasons including VPN, 400, 502 etc...

**Comment by shsuman** [comment]
From looking inside, the @jupyterlab/services package, it is most likely coming from this piece of catch:

```typescript
// Use `call` to avoid a `TypeError` in the browser.
        return settings.fetch.call(null, request).catch((e) => {
            // Convert the TypeError into a more specific error.
            throw new ServerConnection.NetworkError(e);
        });
```

**Comment by tbombach** [comment]
Thomas will re-enable private link filter in dashboard to help diagnose this

**Comment by tbombach** [comment]
Other options:
- In resolve/connection-error maybe do our own fetch to Jupyter Terminal API and see what network error
- Is there more logging we can add to the standard fetch we pass to Jupyter SDK?

**Comment by shsuman** [comment]
After doing more deep dive in telemetry, it seems like the error is not persistent rather they are able to make successful connections as well, its just some of their connections failed. Also, it is spread over both Private Link and non Private Link scenarios. All this still suggest that it is a transient Network Error after all

**Comment by shsuman** [comment]
All of these errors are coming from `connection-error` telemetry event which is sent from AzureMLWebsocket  class. Additionally, only a handful of them are fatal errors as evident from the Measures.isfatalerror property

**Comment by tbombach** [comment]
Let's also update the error categories table to categorize this as a user error since it's the user's transient network conditions.

@tbombach - Create a OneNote page for storing these investigations

**Comment by shsuman** [comment]
Summary of the investigation:
* It is spread over both Private Link and non Private Link scenarios.
* All of the errors are coming from `vscode-ai-remote-web/connection-error` event which originates in AzureMLWebsocket class
* Most of the errors are not fatal in nature coming from websockets package. The ones which are fatal are coming from @jupyterlab/services package
* In the case of non fatal errors, most of the time the connection is successful as evident from `monacoworkbench/remoteconnectionsuccess` telemetry events
* Insights into the @jupyterlab/services code and some github discussions mention it to be a network error


All of these above points show that the error is particular to any configuration or package but rather randomly coming at different point of times in the lifetime of the connection and thus can be safely assumed to be a transient network error
