### ISSUE TITLE
Customer when run the code on vscode (Desktop /Web) an input box would appear asking for a snowflake URL token but it no longer appears

### ISSUE THREAD

**Issue by nadeemrnd** [microsoft/vscode-tools-for-ai#2162]
## Expected Behavior
Customer when run the code on vscode (Desktop /Web) an input box would appear asking for a snowflake URL token but it no longer appears. This used to work fine and now its not working for any user and afffeceting workflow.
This works fine when same code is run on Azure ML notebook. Only issue when run from VScode.
And customer want to use VScode.

Even tried with new compute instance and facing same issue.

This issue has effected other members of our team as well. 

Business impact: blocks us from doing any work, this is one of the pivotal parts to our authentication workflow

From Browser console logs: (For detail logs see the attachment
[No Input box appears to add the token when ran using VScode.docx](https://github.com/microsoft/vscode-tools-for-ai/files/12481204/No.Input.box.appears.to.add.the.token.when.ran.using.VScode.docx)
)
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': (k,D,M)=>{if(this.f&&this.u>this.f.threshold*3)return console.warn(`[${this.f.name}] REFUSES to accept new list...<omitted>...R} could not be cloned.
    at https://main.vscode-cdn.net/stable/6c3e3dba23e8fadc360aed75ce363ba185c49794/out/vs/workbench/workbench.web.main.js:591:47236
(anonymous) @ defaultWorkerFactory.ts:116
Promise.then (async)
postMessage @ defaultWorkerFactory.ts:116
sendMessage @ simpleWorker.ts:292
o @ simpleWorker.ts:254
(anonymous) @ simpleWorker.ts:132
sendMessage @ simpleWorker.ts:127
(anonymous) @ simpleWorker.ts:373

## Actual Behavior
Input should appear for asking token

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - VS Code Version:
  - Platform:

**Comment by nadeemrnd** [comment]
please reach out to nadkha@microsoft.com if you need more details.

I am from AML CSS team.
Thanks

**Comment by shsuman** [comment]
Closing in favor of https://github.com/microsoft/vscode-jupyter/issues/14262
