### ISSUE TITLE
[Dashboard] Create separate dashboard page for environment containers feature

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2164]

**Comment by shsuman** [comment]
https://dataexplorer.azure.com/dashboards/2bce21f9-b635-4acb-8067-6f14ee7155da?p-_startTime=7days&p-_endTime=now&p-isprivatelinkconnection=all#1ce98cd0-3f5d-47ce-9ed3-013e35257c79
