### ISSUE TITLE
Failed to Authenticate

### ISSUE THREAD

**Issue by paraame** [microsoft/vscode-tools-for-ai#2166]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.14.0
Browser Name: Chrome
Browser Version: 116.0.0.0
OS: OS X 10.15.7 64-bit
Product: Visual Studio Code
Product Version: 1.82.0
Language: en

<details>
<summary>Call Stack</summary>

```
kt.getSession webOpener.js:2:706485
https:/webOpener.js:2:784254
xr.measure webOpener.js:2:789958
Lr.getSession webOpener.js:2:784212
Lr.create webOpener.js:2:783948
Wn.resolve webOpener.js:2:741827
https:/webOpener.js:2:771663
xr.measure webOpener.js:2:789958
Mr.doRoute webOpener.js:2:771620
Module.jr webOpener.js:2:790551
```

</details>

**Comment by sevillal** [comment]
Hi @paraame , thanks for filing this issue.

This is a [known VS Code issue](https://github.com/microsoft/vscode/issues/197389), but we are currently testing the solution provided by VS Code team, your input is very valuable to improve this scenario. Could you please try the following and report if it fixed your issue?

1. Go to Azure ML Studio and open the `Compute` tab
2. Right click on the `VS Code (Web)` link of your compute instance and click `Copy link`
3. Open a new browser tab
4. Paste the link and add `&useMsal=true` at the end of the URL
5. Hit enter
6. Enter your credentials if needed and report if you are able to connect or if you see a different error

**Comment by sevillal** [comment]
Hi @paraame, we just rolled out a fix for this issue, could you please retry? Please reopen this issue if you face any problem.
