### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by imathiesonpwx** [microsoft/vscode-tools-for-ai#2169]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.16.0
Browser Name: Microsoft Edge
Browser Version: 116.0.1938.69
OS: Windows 10 64-bit
Product: Visual Studio Code
Product Version: 1.82.0
Language: en

<details>
<summary>Call Stack</summary>

```
kt.getSession webOpener.js:2:706485
https:/webOpener.js:2:785169
Pr.measure webOpener.js:2:792285
kr.getSession webOpener.js:2:785127
kr.create webOpener.js:2:784863
zn.resolve webOpener.js:2:741935
https:/webOpener.js:2:771779
Pr.measure webOpener.js:2:792285
wr.doRoute webOpener.js:2:771736
Module.Cr webOpener.js:2:792888
```

</details>

**Comment by sevillal** [comment]
Hi @imathiesonpwx , thanks for filing this issue.

This is a [known VS Code issue](https://github.com/microsoft/vscode/issues/197389), but we are currently testing the solution provided by VS Code team, your input is very valuable to improve this scenario. Could you please try the following and report if it fixed your issue?

1. Go to Azure ML Studio and open the `Compute` tab
2. Right click on the `VS Code (Web)` link of your compute instance and click `Copy link`
3. Open a new browser tab
4. Paste the link and add `&useMsal=true` at the end of the URL
5. Hit enter
6. Enter your credentials if needed and report if you are able to connect or if you see a different error

**Comment by sevillal** [comment]
Hi @imathiesonpwx, we just rolled out a fix for this issue, could you please retry? Please reopen this issue if you face any problem.
