### ISSUE TITLE
Issue while trying to open Azure ML notebook in VSCode

### ISSUE THREAD

**Issue by BecayeSoft** [microsoft/vscode-tools-for-ai#2170]
Hi, 

I can no longer connect to my remote compute instance to open my Azure ML notebooks in VSCode.

Does this occur consistently? No

Repro steps:

1. Go to Azure ML Workspace
2. Open Notebook
3. Select open notebook in VSCode

Action: UriHandler.handleUri
Error type: 343
Error Message: It seems like you are attempting to use a compute instance which is not running. Please start the compute instance and try again

Version: 0.36.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.82.0
Language: en

<details>
<summary>Call Stack</summary>

```
L.<anonymous> extension.js:2:2570360
extension.js:2:2568944extension.js:2:2568944
a extension.js:2:2568689
L.ensureComputeInstanceIsRunning extension.js:2:2569953
L.<anonymous> extension.js:2:2569308
extension.js:2:2568944extension.js:2:2568944
a extension.js:2:2568689
L.getServerUriForCompute extension.js:2:2569263
L.<anonymous> extension.js:2:2562129
s extension.js:2:2558487
```

</details>

**Comment by sevillal** [comment]
Thanks for reaching out  @BecayeSoft. I apologize for the issue you are facing, could you please confirm if that the Compute Instance you are trying to connect is in "Running" state? If that's the case, could you please try restarting it and retry the "Edit in VS Code (Desktop)" button.

If it fails, could you please send the logs by following these instructions: https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-trace-logs-for-azure-machine-learning-extension-

**Comment by BecayeSoft** [comment]
@sevillal  sorry for the delay. I didn't do anything, just tried it a few weeks later and it works perfectly now.
Thank you!
