### ISSUE TITLE
When connected to a compute instance via the AML extension, dev containers are not recognized

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/vscode-tools-for-ai#2172]
Type: <b>Bug</b>

When connected to a compute instance via SSH, I can use dev containers. However, when computing to the very same instance via the AML extension, a ".devcontainer" folder in the repo is not recognized. Neither can I use "remote explorer" to see dev containers, VSCode complains that I should install Docker first. If i connect to the same compute instance via SSH, that works just fine.

Repro steps:
* Create an AzureML compute instance with SSH access.
* Setup SSH to the compute instance from local box.
* Connect to the compute instance via an SSH target.
* Open "Remote explorer", choose "dev containers". Containers will be visible.
* Now connect via the AML extension: Click on "Connect: VSCode (desktop)" in AzureML. Wait for VSCode to come up.
* Open "Remote explorer". This will say that I need to install Docker first.

Extension version: 0.34.0
VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:45:05.575Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'wsl+ubuntu' could not be established
Remote OS version: Linux x64 5.15.0-1040-azure
Remote OS version: Linux x64 5.15.0-1040-azure
Connection to 'Azure ML: antonsc-cpu' could not be established  Connection error: Unauthorized client refused: auth mismatch

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (8.77GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/antonsc/radiology-copilot --crash-reporter-id 1cf8a6d7-9b7a-4341-a1df-8c7d1d2c42be|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+ubuntu' could not be established

|Item|Value|
|---|---|
|Remote|Azure ML: antonsc-v100|
|OS|Linux x64 5.15.0-1040-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (6 x 2593)|
|Memory (System)|110.05GB (106.37GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: antonsc-cpu|
|OS|Linux x64 5.15.0-1040-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2 x 2294)|
|Memory (System)|13.65GB (12.00GB free)|
|VM|0%|

Connection to 'Azure ML: antonsc-cpu' could not be established  Connection error: Unauthorized client refused: auth mismatch
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by sevillal** [comment]
@ant0nsc thanks for reaching out.

Unfortunately we don't support that scenario right now. So today you can only connect to Azure ML Compute instances by using our remote extension and not any container within it. However, we will look into the feasibility and use cases for enabling connections to container as we have heard from other customer that this is a desired feature.

I will close this issue for now since we are tracking those efforts here: https://github.com/microsoft/vscode-tools-for-ai/issues/2062
