### ISSUE TITLE
Port Forwarding from Azure ML Remote Machine broken with 1.82

### ISSUE THREAD

**Issue by bloewes** [microsoft/vscode-tools-for-ai#2174]
I already opened a ticket here https://github.com/microsoft/vscode/issues/192582

## Expected Behavior
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/117997874/976617c5-2154-4f15-8f04-9c18e81baf93)
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/117997874/a337dce6-0308-469c-81d9-efb69fb95ca6)
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/117997874/0e0d90ce-20dc-4e0c-b300-e630100b82b2)

Opening browser to localhost:5000 showing the websites returned by flask.

## Actual Behavior
Spinning circle in browser and no return. At one point timeout.

## Steps to Reproduce the Problem

Open Flask server on Azure ML compute instance, then access the server via port forwarding.

## Specifications

  - Version: VS Code 1.82.2 & Azure Machine Learning v0.36.0 & Azure Machine Learning - Remote  v0.34.0 
  - Platform: Windows 10

**Comment by shsuman** [comment]
@bloewes Can you please provide me with the Remote extension logs by following the steps [here](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-trace-logs-for-azure-machine-learning---remote-extension-) ?

**Comment by bloewes** [comment]
@shsuman 
Trace log of Azure ML Remote. The port opened by the app is 5000.
[azure_ml_remote_trace.txt](https://github.com/microsoft/vscode-tools-for-ai/files/12657701/azure_ml_remote_trace.txt)
Browser showing loading indefinitely
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/117997874/07d0a9e0-b0dc-465c-809e-c653f10b9cff)

**Comment by shsuman** [comment]
@bloewes Were you using this setting `azureML - Remote.portstoForward` before when it was working ?

**Comment by bloewes** [comment]
No this setting was not necessary. Clicking the Url:port in the terminal with ctrl+click was necessary and sufficient.

**Comment by shsuman** [comment]
I discussed it in our team yesterday and our extension's port forwarding mechanism works with that setting only. So, if you were not using that setting before then you were most likely using the VS Code's port forwarding.

Please provide me with that example. I will try it out myself and then talk to VS Code team to understand how exactly their port forwarding works and if there is anything that we need to do on the extension side after the latest update

**Comment by bloewes** [comment]
steps:
1. conda create -n flask_example python==3.10
2. conda activate flask_example
3. cd msdocs-python-flask-webapp-quickstart-main
4. pip install -r requirements.txt
5. python app.py
6. ctrl+click on terminal output showing "Running on http://127.0.0.1:5000"
7. Local browser will open showing test website forwarded on http://127.0.0.1:5000

Working example attached:
[msdocs-python-flask-webapp-quickstart-main.zip](https://github.com/microsoft/vscode-tools-for-ai/files/12670101/msdocs-python-flask-webapp-quickstart-main.zip)

You can also clone from here: https://github.com/Azure-Samples/msdocs-python-flask-webapp-quickstart.git

**Comment by shsuman** [comment]
Upstream https://github.com/microsoft/vscode/issues/192582

**Comment by alexr00** [comment]
@shsuman can you make some repro steps that don't involve conda? I am not a python user and I'm getting error after error with setting up conda.

**Comment by shsuman** [comment]
@alexr00 You can just do those in your global python environment as well. That should work :)

**Comment by bloewes** [comment]
@alexr00 Regarding conda. Most likely you need to do conda init at one point after creating your first env.
But as shsuman mentioned you can skip conda and do it with the global python binary. Just skip steps 1 & 2 from steps and start with installing the requirements for the example app.
> 
> 1. conda create -n flask_example python==3.10
> 2. conda activate flask_example
> 3. cd msdocs-python-flask-webapp-quickstart-main
> 4. pip install -r requirements.txt
> 5. python app.py
> 6. ctrl+click on terminal output showing "Running on http://127.0.0.1:5000"
> 7. Local browser will open showing test website forwarded on http://127.0.0.1:5000
> 
> Working example attached: [msdocs-python-flask-webapp-quickstart-main.zip](https://github.com/microsoft/vscode-tools-for-ai/files/12670101/msdocs-python-flask-webapp-quickstart-main.zip)
> 
> You can also clone from here: https://github.com/Azure-Samples/msdocs-python-flask-webapp-quickstart.git

**Comment by alexr00** [comment]
@shsuman I've outlined what's going on in https://github.com/microsoft/vscode/issues/192582#issuecomment-1737276488. Would you be willing to make the change in the Azure ML Remote extension to use `127.0.0.1` instead of `localhost` in the resolver?

**Comment by shsuman** [comment]
@alexr00 Replied in https://github.com/microsoft/vscode/issues/192582#issuecomment-1737835132
