### ISSUE TITLE
Can not connect to compute from Visual Studio Code Desktop and Web

### ISSUE THREAD

**Issue by edab-code** [microsoft/vscode-tools-for-ai#2177]
Does this occur consistently? 
Repro steps:

1.
2.

Action: UriHandler.handleUri
Error type: 344
Error Message: Error obtaining refresh redacted:key your subscription. Please try again

Version: 0.36.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.82.2
Language: en

<details>
<summary>Call Stack</summary>

```
L.<anonymous> extension.js:2:2562409
s extension.js:2:2558487
```

</details>

**Comment by shsuman** [comment]
@edab-code
Can you check the value of the setting `Azure: Authentication Library` ?
Also, What error are you getting in the Web ?

**Comment by edab-code** [comment]
[Error - 2023-09-21 08:33:39.089] Failed to get user object id for the user  ***@***.***
[Info - 2023-09-21 08:33:39.089] [Azure ML JS SDK]User Object id is null. Assuming user can use the compute instance.
[Info - 2023-09-21 08:33:39.089] [Azure ML JS SDK]User Object id is null. Assuming user can use the compute instance.
[Error - 2023-09-21 08:33:50.080] Failed to get user object id for the user  ***@***.***
[Info - 2023-09-21 08:33:50.081] [Azure ML JS SDK]User Object id is null. Assuming user can use the compute instance.
[Info - 2023-09-21 08:33:50.081] [Azure ML JS SDK]User Object id is null. Assuming user can use the compute instance.
[Error - 2023-09-21 08:33:50.324] Failed to get user object id for the user  ***@***.***
[Info - 2023-09-21 08:33:50.324] [Azure ML JS SDK]User Object id is null. Assuming user can use the compute instance.
[Info - 2023-09-21 08:33:50.325] [Azure ML JS SDK]Workspace amlworkspacexdwh2y2ha2hde  does not have a private endpoint connection
[Info - 2023-09-21 08:33:50.685] Compute instance to connect to: https://ci-lin-gpu-0-xdwh2y2.eastus2.instances.azureml.ms/
[Error - 2023-09-21 08:33:51.053] Error: Error obtaining refresh token for your subscription. Please try again


________________________________

**Comment by shsuman** [comment]
@edab-code Can you check the value of the setting `Azure: Authentication Library` ?

**Comment by edab-code** [comment]
[cid:66a2cb2e-eea7-41b1-9175-1b347d066ed8]
________________________________

**Comment by shsuman** [comment]
@edab-code It should look something like this 
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/44413557/6a566fba-6bba-4741-839d-206a97a6fe8f)

**Comment by edab-code** [comment]
thanks it helped
________________________________
