### ISSUE TITLE
Multiple jobs

### ISSUE THREAD

**Issue by msalvaris** [Microsoft/vscode-tools-for-ai#22]
I am using VS Code to submit jobs to a vm but there only seems to be one configuration file ai_job_properties.json. Is there a way to define multiple job_properties and select which one I wish to run?

**Comment by linmajia** [comment]
@msalvaris , thank you very much for the feedback.

This is a good idea, and we will add it to our backlog.

**Comment by greazer** [comment]
This extension has been reconfigured to target scenarios only dealing with Azure Machine Learning.
