### ISSUE TITLE
VScode web cannot load for AML compute instance

### ISSUE THREAD

**Issue by jrd232f** [microsoft/vscode-tools-for-ai#2207]
Does this occur consistently%3F 
Repro steps:

1. spin up a compute instance
2. click on the VSCode Web application

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.18.0
Browser Name: Chrome
Browser Version: 118.0.0.0
OS: Windows 10 64-bit
Product: Visual Studio Code
Product Version: 1.83.1
Language: en

<details>
<summary>Call Stack</summary>

```
kt.getSession webOpener.js:2:706485
https:/webOpener.js:2:785512
Ar.measure webOpener.js:2:792628
Tr.getSession webOpener.js:2:785470
Tr.create webOpener.js:2:785206
$n.resolve webOpener.js:2:742078
https:/webOpener.js:2:772343
Ar.measure webOpener.js:2:792628
Lr.doRoute webOpener.js:2:772300
Module.Ir webOpener.js:2:793231
```

</details>

**Comment by jrd232f** [comment]
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/123980080/57a80a80-c74d-4d15-9e2c-2b7b49070052)

**Comment by sevillal** [comment]
@jrd232f I apologize for the issue you are facing. Could you please send us the logs you get by following [these instructions](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-logs-for-azure-machine-learning---remote-web-connection-in-vs-code-web-vscodedev-)?

**Comment by jrd232f** [comment]
I guess the failed connection won't allow me to view any logs on the VSCode interface. Here's a screenshot of the VSCode interface after I clicked on "Cancel" from the error window uploaded previously. The "Reload" button only regenerates the error window itself, and the "Report an Issue" button leads to the Github Issue page. 

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/123980080/5ae3a36e-b026-49ef-a91b-82ca79c3e224)

**Comment by sevillal** [comment]
@jrd232f thanks for looking into that. I think you should be able to get the logs by clicking on the top left menu -> View -> Output. Then you can look for the right outputs using the dropdown.
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/56176070/13809b73-7f13-4b8a-bfaf-6fc4cf02c96a)

**Comment by jrd232f** [comment]
> @jrd232f thanks for looking into that. I think you should be able to get the logs by clicking on the top left menu -> View -> Output. Then you can look for the right outputs using the dropdown. ![image](https://user-images.githubusercontent.com/56176070/277762573-13809b73-7f13-4b8a-bfaf-6fc4cf02c96a.png)

This again opens the empty output panel at the bottom of the screen. It's the same with the screenshot:

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/123980080/3004e145-dec9-4b1d-a896-a5e8204d2995)

**Comment by sevillal** [comment]
@jrd232f in order to see the logs you need to select the right output channel, you can do that by selection `vscode.dev` and `Azure ML Remote Web` options from the following dropdown:

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/56176070/6cfc79dc-c5bb-4425-938d-8ec4250e3a5d)

**Comment by jrd232f** [comment]
Thanks for pointing that out. Here are the logs:

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/123980080/db8cb06f-d7f0-48d4-a168-937616d6f9e1)

**Comment by sevillal** [comment]
@jrd232f could you please also send the log from the `vscode.dev` output channel?

**Comment by sevillal** [comment]
@jrd232f following up regarding this issue? Is there anything I can do to help? If you are open we can have a triage call next week, please send me your availability and I can schedule some time. Please reach out to me to sevillal@microsoft.com with you availability and email so I can setup the call.

**Comment by jrd232f** [comment]
Hi there, I found another solution for me which is to install the jupyter-git extension inside the jupyterlab app of the compute. For now I don't need to use vscode. Thanks
