### ISSUE TITLE
Azure ML extension cannot Sign In to my Subscription

### ISSUE THREAD

**Issue by hugosouto** [microsoft/vscode-tools-for-ai#2209]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureAccount.onSessionsChanged
Error type: 125
Error Message: Cannot find subscription with id: redacted:id

Version: 0.37.2023102509
OS: linux
OS Release: 5.15.0-1040-azure
Product: Visual Studio Code
Product Version: 1.83.1
Language: en

<details>
<summary>Call Stack</summary>

```
E.<anonymous> extension.js:2:2267383
s extension.js:2:2264866
```

</details>

**Comment by sevillal** [comment]
Thanks for filing this issue @hugosouto . Could you please share the logs by following [these instructions](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-trace-logs-for-azure-machine-learning-extension-)?

**Comment by hugosouto** [comment]
I just reinstalled the Azure extensions on the Compute Instance and it worked. Thanks for the feedback, @sevillal !
