### ISSUE TITLE
Azure ML Studio Notebooks cannot be edited in VS Code

### ISSUE THREAD

**Issue by mfinocchiaro-sinequa** [microsoft/vscode-tools-for-ai#2210]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.commandPalette.computeInstance.connectToJupyterServer
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'toString')

Version: 0.36.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.83.1
Language: en

<details>
<summary>Call Stack</summary>

```
XE.selectJupyterUri extension.node.js:24:580866
n.h extensionHostProcess.js:125:84283
n.g extensionHostProcess.js:125:83278
n.executeCommand extensionHostProcess.js:125:83185
Object.executeCommand extensionHostProcess.js:140:21282
h.executeCommand extension.js:2:2285220
extension.js:2:2290027extension.js:2:2290027
```

</details>

**Comment by sevillal** [comment]
@mfinocchiaro-sinequa thanks for filing this issue. 

I think this is a bug in our code, I'll talk to the team to prioritize accordingly and define the right experience.

In the meantime, you could workaround it and connect your local notebooks to an Azure ML compute instance jupyter server by opening a notebook, then clicking the kernel picker, select the `Azure ML compute instances...` and follow the options to choose the desired compute instance.

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/56176070/d669f753-5ccc-4b2f-9742-658de361eb11)

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/56176070/f282bbee-759e-4949-b9a3-677e02a52fe3)

**Comment by sevillal** [comment]
Fixed.
