### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by shishirdash24** [microsoft/vscode-tools-for-ai#2212]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.18.0
Browser Name: Chrome
Browser Version: 118.0.0.0
OS: Windows 10 64-bit
Product: Visual Studio Code
Product Version: 1.83.1
Language: en

<details>
<summary>Call Stack</summary>

```
kt.getSession webOpener.js:2:706485
https:/webOpener.js:2:785512
Ar.measure webOpener.js:2:792628
Tr.getSession webOpener.js:2:785470
Tr.create webOpener.js:2:785206
$n.resolve webOpener.js:2:742078
https:/webOpener.js:2:772343
Ar.measure webOpener.js:2:792628
Lr.doRoute webOpener.js:2:772300
Module.Ir webOpener.js:2:793231
```

</details>

**Comment by sevillal** [comment]
@shishirdash24  I apologize for the issue you are facing. Could you please send us the logs you get by following [these instructions](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-logs-for-azure-machine-learning---remote-web-connection-in-vs-code-web-vscodedev-)?

**Comment by sevillal** [comment]
@shishirdash24 following up regarding this issue. Is there anything I can do to help?

**Comment by sevillal** [comment]
Closin due inactivity, please reopen if needed.
