### ISSUE TITLE
Unable to use Debuger in VSC with AML remote extension

### ISSUE THREAD

**Issue by soferreira** [microsoft/vscode-tools-for-ai#2221]
I am currently connected to my Azure ML compute instance in my VS Code. I am trying to debug my python script from VS Code. 

## Expected Behavior
Debugger should start and stop if there are breakpoints in the code.

## Actual Behavior
There is an error in the OUTPUT terminal and all breakpoints are ignored. Nonetheless, the code is executed.

Error message:

2023-11-02 14:48:36.187 [info] [Error - 2:48:36 PM] Request textDocument/codeAction failed.
2023-11-02 14:48:36.187 [info]   Message: Request textDocument/codeAction failed with message: Debug Failure. Unable to find notebook URI for vscode-notebook-cell://XXXXXX/home/azureuser/cloudfiles/code/Users/soferreira/Untitled.ipynb#XXXXX
  Code: -32603 

## Steps to Reproduce the Problem
  1. Connect VSC to Azure ML compute instance 
  1. Open one of the .ipynb file
  1. Insert breakpoints
  1. Click "Debug Cell"

## Specifications

  - Version: 
    - Azure Machine Learning - Remote v0.36.0
    - Azure Machine Learning v0.38.0
  - Platform: VSC 1.84

**Comment by soferreira** [comment]
This issue applies to .ipynb files. Debuger is working fine with .py files

**Comment by shsuman** [comment]
@soferreira Please open an issue in https://github.com/microsoft/vscode-jupyter

Let them know that its happening on Azure ML Remote Compute instance connection. Tag me as well, so I can follow up with them if need be
