### ISSUE TITLE
Cannot connect to compute instance because of "EventEmitter" error

### ISSUE THREAD

**Issue by lindsayevanslee** [microsoft/vscode-tools-for-ai#2224]
## Expected Behavior
I am trying to work with my Azure ML workspace with VS Code. I am expecting that when I click "VS Code (Desktop)" from the list of compute instances, my VS Code client will open and connect to the running compute instance and show me the files available in the workspace.

## Actual Behavior

When I try to open VS Code by clicking "VS Code (Desktop)" from the list of compute instances, VS Code opens but sends me an error `The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal`

## Steps to Reproduce the Problem

1. Go to Compute -> Compute Instances in the Azure ML workspace
2. Turn on a compute instance and wait for its startup to complete
3. Click "VS Code (Desktop)" 
4. Navigate to VS Code and see error

## Specifications

  - VS Code Version: 1.84.0
  - Azure Machine Learning extension version: 0.38.0
  - Azure Machine Learning - Remote extension version: 0.36.0
  - Platform: Windows_NT x64 10.0.19045

**Comment by tbombach** [comment]
Hi @lindsayevanslee, thank you for filing this issue and for the easy to follow repro steps! I will investigate this issue and provide an update on what I find.

**Comment by ameicler** [comment]
same here when trying to connect to compute instance on Mac version

Version: 0.15.1
VSCode Version: 1.83.1
Commit: 254fc847749811620c31fd780d453b15bd1013e0
Date: 2023-11-11T03:33:44.428Z
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.3.0

**Comment by lindsayevanslee** [comment]
@shsuman I checked again today and no longer have the issue. 

VSCode "About" details:

Version: 1.92.2 (user setup)
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Extension details:
Azure Machine Learning extension version: 0.50.0
Azure Machine Learning - Remote extension version: 0.50.0
