### ISSUE TITLE
After click Edit in VS Code (Desktop), error happened

### ISSUE THREAD

**Issue by aiwq2** [microsoft/vscode-tools-for-ai#2226]
Does this occur consistently? 
Repro steps:

1.
2.

Action: UriHandler.handleUri
Error type: 344
Error Message: Error obtaining refresh redacted:key your subscription. Please try again

Version: 0.38.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.84.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
j.<anonymous> extension.js:2:2529683
s extension.js:2:2525761
```

</details>

**Comment by sevillal** [comment]
@aiwq2 I apologize for the issue you are facing.

Could you please check the value of the setting Azure: Authentication Library? If it is set to MSAL could you please change it to ADAL, it should look like this:
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/56176070/d6ef103e-a52e-4f4b-a2a9-5570ed795e55)

**Comment by aiwq2** [comment]
Yeah, after I switch the configuration, it does work. Thanks a lot!
