### ISSUE TITLE
Error obtaining refresh token when using VS Code when connecting to Azure compute

### ISSUE THREAD

**Issue by jamesd44452** [microsoft/vscode-tools-for-ai#2227]
I have been using VS Code to access files on an Azure ML compute. Recently I have not been able to do so and get the error "Error obtaining refresh token for your subscription. Please try again". The steps leading to the error are below.

I have tried to uninstall and reinstall both the Azure Account and Azure Machine Learning extensions. I've tried going into my notebook within the Azure ML site and open VS Code that way but the same error.

Does this occur consistently? Yes
Repro steps:

1. Open VS Code
2. Sign in to Microsoft Azure within VS Code either using the option in the command pallette or by using the Azure Account extension
3. Open the Azure environment I work in and open up all of the computes in the side bar
4. Right-click on my compute and click 'Connect'
5. I then get the error 'Error obtaining refresh token for your subscription. Please try again' and the Source of the error is 'Azure Machine Learning (Extension)'

Action: azureml.viewContext.computeInstance.connect
Error type: 344
Error Message: Error obtaining refresh redacted:key your subscription. Please try again

Version: 0.38.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.84.1
Language: en

<details>
<summary>Call Stack</summary>

```
j.<anonymous> extension.js:2:2529683
s extension.js:2:2525761
```

**Comment by sevillal** [comment]
@jamesd44452 I apologize for the issue you are facing.

Could you please check the value of the setting Azure: Authentication Library? If it is set to MSAL could you please change it to ADAL, it should look like this:
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/56176070/d1c4797b-420b-471f-99ad-8201bfe599b3)
