### ISSUE TITLE
Rerunning last experiment with same configuration should account for changes in that configuration.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#223]
For example, if the user created a runconfig but forgot a python  package, after they figure that out they would update the runconfig appropriately. I would think they would likely expect that "Run experiment with last run config" would take that new change into account. Currently this is not the case. 

This command might be better named with the last runconfig used... Like "Run experiment with {name} runconfig"

**Comment by shsuman** [comment]
Well, then we are talking a completely different command here. Run with last configuration seems to be okay, it runs with the last config, we need a new command Run with last runConfig, which will just take the last runconfig or like you said run with {name} runconfig again. Something like that
