### ISSUE TITLE
unable to open VS code

### ISSUE THREAD

**Issue by Yashashri14** [microsoft/vscode-tools-for-ai#2236]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.40.0
Browser Name: Microsoft Edge
Browser Version: 119.0.0.0
OS: OS X 10.15.7
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

<details>
<summary>Call Stack</summary>

```
kt.getSession webOpener.js:2:706485
https:/webOpener.js:2:785509
Ar.measure webOpener.js:2:792625
Tr.getSession webOpener.js:2:785467
Tr.create webOpener.js:2:785203
$n.resolve webOpener.js:2:742078
https:/webOpener.js:2:772423
Ar.measure webOpener.js:2:792625
Lr.doRoute webOpener.js:2:772380
Module.Ir webOpener.js:2:793228
```

</details>

**Comment by sevillal** [comment]
Hi @Yashashri14 , thanks for filing this issue.

This is a [known VS Code issue](https://github.com/microsoft/vscode/issues/197389), but we are currently testing the solution provided by VS Code team, your input is very valuable to improve this scenario. Could you please try the following and report if it fixed your issue?

1. Go to Azure ML Studio and open the `Compute` tab
2. Right click on the `VS Code (Web)` link of your compute instance and click `Copy link`
3. Open a new browser tab
4. Paste the link and add `&useMsal=true` at the end of the URL
5. Hit enter
6. Enter your credentials if needed and report if you are able to connect or if you see a different error

**Comment by sevillal** [comment]
Hi @Yashashri14 , we just rolled out a fix for this issue, could you please retry? Please reopen this issue if you face any problem.
