### ISSUE TITLE
[Jan] Migrate to new Jupyter API

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#2248]
From Don: 

_Sergio Villalobos Shantnu Suman
With regards to issue [Unable to connect to the remote server (Azure Ml compute instance) · Issue #14925 · microsoft/vscode-jupyter (github.com)](https://github.com/microsoft/vscode-jupyter/issues/14925)
 
We can ship a recovery fix in Jan, 
However in the Jan Release (which will be shipped in early Feb), the old Jupyter Server API will be deprecated.
Thus AzML will need to ship a release version that adopts this new API
Please coordinate a release of a new version of AzML Extension before then (early Feb) to fully adopt the new (Stable) Jupyter Server API, which will ensure users do not break.
From what I understand the new Jupyter API is used but only behind a feature flag and only in VS Code Insiders.
 
Once again:
When releasing, I’d suggest setting the vscode engine to 1.86, that way the release goes out to users in vscode insiders and vscode stable when it’s officially released
And it will also line up perfectly with Jupyter release_

**Comment by sevillal** [comment]
@tbombach I've set this bug to current iteration, we need to follow up with Don and Jupyter extension team to align on this.

**Comment by sevillal** [comment]
Fixed by: https://github.com/devdiv-microsoft/vscode-azureml/pull/517
