### ISSUE TITLE
Azure ML Connecting to Compute Instance in VS Code (Using Desktop as well as web) is getting timed out : VSCodeServerInstallerError

### ISSUE THREAD

**Issue by nadeemrnd** [microsoft/vscode-tools-for-ai#2253]
[rjeffers VS Code Web 2023-12-27.txt](https://github.com/microsoft/vscode-tools-for-ai/files/13781885/rjeffers.VS.Code.Web.2023-12-27.txt)
## This was working fine, but since couple of week not able to access the compute instance using VSCode.
Getting below error
            "name": "TerminalError"
        },
        "name": "VSCodeServerInstallerError"
        
        I have been unable to connect to my Compute instance from VS Code for several weeks and receive an error stating 'Maximum retries exhausted. Downloading VS Code server failed. Please try again later. Source: Azure Machine Learning - Remote (Extension)'.
        
        Trace logs attached from trying to connect. If necessary, I can provide more trace logs from other team members, including one who is able to connect to his Compute on the same workspace from VS Code without any issue.

## Steps to Reproduce the Problem

  Customer when try to connect using VSCode Destop or Web based they are getting timeout issue

## Specifications

Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.17763
 
Alex Mak's VS Code Desktop version is (Working version for one user):
 
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.17763
 
[trace Azure ML Remote Output - Alex Mak- Good case.txt](https://github.com/microsoft/vscode-tools-for-ai/files/13781882/trace.Azure.ML.Remote.Output.-.Alex.Mak-.Good.case.txt)
[trace Azure ML Remote Output - Ovo Ojameruaye.txt](https://github.com/microsoft/vscode-tools-for-ai/files/13781883/trace.Azure.ML.Remote.Output.-.Ovo.Ojameruaye.txt)
[trace Azure ML Remote Output - Riley Jefferson.txt](https://github.com/microsoft/vscode-tools-for-ai/files/13781884/trace.Azure.ML.Remote.Output.-.Riley.Jefferson.txt)

**Comment by mhmdmodan** [comment]
Having a similar (same?) issue opening in VS Code Desktop with the AzureML remote extension

"Maximum retries exhausted. Could not install VS Code server on `compute-name`: Downloading VS Code server failed. Please try again later"

Downgrading from VS Code version 1.85.1 (Universal) to version 1.84.2 (Universal) fixes the issue

**Comment by sevillal** [comment]
@nadeemrnd sorry for the late response. Is this issue still reproducing? I've seen couple of issue in VS Code repo that it should be fixed by now.

**Comment by nadeemrnd** [comment]
@sevillal , yes issue still persist

**Comment by krisgeus** [comment]
@sevillal I can confirm the same issue and indeed downgrading VSCode desktop works. The VSCode web still has issues even after the vscode server is installed on the compute instance by using the desktop extension

**Comment by sevillal** [comment]
@krisgeus is your workspace secured behind a Vnet?
