### ISSUE TITLE
Add GH copilot and GH copilot chat to the default extensions of the environment containers connections

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#2270]
https://marketplace.visualstudio.com/items?itemName=GitHub.copilot
https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat

**Comment by shsuman** [comment]
https://github.com/devdiv-microsoft/vscode-azureml-remote/pull/153
https://github.com/devdiv-microsoft/vscode-azureml-remote-web/pull/151
