### ISSUE TITLE
VS Code auth provider investigations/post-switch updates

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2273]
We want to make sure we follow up on any reports or investigations since the switch to VS Code auth provider

**Comment by shsuman** [comment]
- [ ] https://github.com/devdiv-microsoft/vscode-azureml/pull/516
- [ ] https://github.com/devdiv-microsoft/vscode-azureml/pull/515
- [ ] https://github.com/devdiv-microsoft/vscode-azureml-remote/pull/152
- [ ] https://github.com/devdiv-microsoft/vscode-azureml-remote/pull/150
- [ ] https://github.com/devdiv-microsoft/vscode-azureml-remote/pull/149
