### ISSUE TITLE
Mark all telemetry events from the extension as coming from the extension.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#228]
From William: Looks like API calls made from the extension aren't setting a unique user-agent or any other identifying property, so we can’t query telemetry for things like “show me the failure rate of job submission just from the IDE extension”.

**Comment by shsuman** [comment]
Each telemetry is sent like this sendTelemetryEvent(AzureML/compute/edit, {properties}). So, I guess the string AzureML is an identifier. Do we need something else ?
