### ISSUE TITLE
Runconfig's with a compute target of NC, ND or NV should default to gpu based python packages.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#229]
Any other type of compute should fall back to non-gpu python packages

In other words, if a tensorflow training type was selected for a non-GPU based compute, then the pip package portion of the runconfig should specify tensorflow, not tensorflow-gpu.

**Comment by shsuman** [comment]
Closing this as training type is no longer supported. Instead, we have switched to Azure ML environments now. Users can select curated Azure ML environments or create new ones. In either case, the packages in those curated environments are managed by Azure ML
