### ISSUE TITLE
Improve experience for first connection (install time/perceived install time)

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2297]
Feedback from Azure AI Studio preview has been that the first install/connection experience takes more time than users expect. Let's investigate ways to improve the perceived time and the user experience here. The focus should be for Azure AI Studio scenarios but any fixes we make that can apply to all connections should be considered.

**Comment by shsuman** [comment]
This is for both Desktop and Web ?

**Comment by shsuman** [comment]
Desktop:

- No notification since start
- No notification between Authorization and Installation of VSCode server
- Percentage progress over single toast notification

**Comment by shsuman** [comment]
https://github.com/devdiv-microsoft/vscode-azureml-remote-web/pull/163

**Comment by shsuman** [comment]
https://github.com/devdiv-microsoft/vscode-azureml-remote/pull/169/files

**Comment by shsuman** [comment]
https://github.com/microsoft/vscode-tools-for-ai/issues/2313
