### ISSUE TITLE
Create proposal for provisioning VS Code connection within the service

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2298]
Let's create a 1 pager proposal to provide to the CI team for an endpoint that can provision VS Code and guarantee a running VS Code server at a known port.

**Comment by shsuman** [comment]
https://microsoft.sharepoint.com/:w:/t/AzureMLExtension/EeR46pQTkntElhYbLZIKoIQBLBhIX8W-BT68LfdZHJLUFw?e=e0JD9h
