### ISSUE TITLE
Refactoring for AI Studio extension

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2299]
We want to refactor our common packages so that they can be reused for all of our extensions. Let's start with the most straightforward packages as the P0 for this task:
- Telemetry
- Logging

If there's time, we can refactor out other packages as a P1:
- Auth
- More TBD

I think it makes the most sense to have a separate repository that has all of these packages as a library and publish them to a private NPM registry in the OnlineServices ADO org. Then they can be a package.json dependency. I'm open to other solutions if they make more sense though (e.g. git submodules).

**Comment by shsuman** [comment]
- [ ] Telemetry
- [ ] Logging
- [ ] Application Shell
- [ ] Extension Manager
- [ ] Auth

**Comment by shsuman** [comment]
Closing in favor of https://github.com/microsoft/vscode-tools-for-ai/issues/2319
