### ISSUE TITLE
List jobs doesn't work

### ISSUE THREAD

**Issue by msalvaris** [Microsoft/vscode-tools-for-ai#23]
Whenever I click on List Jobs I see nothing. If I go to visual studio and point to the same vm I can see all the jobs. Is this a bug or am I missing something

**Comment by qfyin** [comment]
Thanks @msalvaris for reporting this.
It will be fixed in upcoming **0.1.8** release, please stay tuned.

**Comment by qfyin** [comment]
Please check the latest 0.1.8.
