### ISSUE TITLE
Azure AI Studio: Getting this error while opening the project in VS code 

### ISSUE THREAD

**Issue by krishna-280792shinde** [microsoft/vscode-tools-for-ai#2323]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Invalid response: 403 
Error type: JupyterTerminalError
Original error: [<no-type>:<no-code>]

Version: 0.46.1
Browser Name: Chrome
Browser Version: 122.0.0.0
OS: Windows 10 64-bit
Product: Visual Studio Code
Product Version: 1.87.0
Language: en

<details>
<summary>Call Stack</summary>

```
t.create webOpener.js:2:129753
async t.startNew webOpener.js:2:152656
async d.startNew webOpener.js:2:150980
async Xt webOpener.js:2:722683
async sn.initialize webOpener.js:2:726625
async sn.ensureTerminalIsReady webOpener.js:2:724977
async sn.onMessageReceived webOpener.js:2:727107
async sn.runCommmand webOpener.js:2:724473
async nr.isTundraAvailable webOpener.js:2:766703
async kr.setupVSCodeServer webOpener.js:2:784149
```

</details>

**Comment by sevillal** [comment]
Thanks for filing this issue @krishna-280792shinde. 
1. Could you please share the trace logs following these instructions? https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-logs-for-azure-machine-learning---remote-web-connection-in-vs-code-web-vscodedev-
2. Is your project secured with Private Link? Are you trying to access the project from inside the secured vnet?
