### ISSUE TITLE
Not able to connect to Azure

### ISSUE THREAD

**Issue by rutautture** [microsoft/vscode-tools-for-ai#2324]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.46.1
Browser Name: Chrome
Browser Version: 122.0.0.0
OS: OS X 10.15.7 64-bit
Product: Visual Studio Code
Product Version: 1.87.1
Language: en

<details>
<summary>Call Stack</summary>

```
kt.getSession webOpener.js:2:706485
https:/webOpener.js:2:785622
Ar.measure webOpener.js:2:792738
Tr.getSession webOpener.js:2:785580
Tr.create webOpener.js:2:785316
$n.resolve webOpener.js:2:742078
https:/webOpener.js:2:772536
Ar.measure webOpener.js:2:792738
Lr.doRoute webOpener.js:2:772493
Module.Ir webOpener.js:2:793341
```

</details>

**Comment by sevillal** [comment]
Thanks for filing this issue @rutautture. Unfortunately this is a  [known issue](https://github.com/microsoft/vscode/issues/197389), we are working with VS Code team to get this fixed as soon as possible,.
