### ISSUE TITLE
Can't connect compute instance from VS Code

### ISSUE THREAD

**Issue by markjbrown** [microsoft/vscode-tools-for-ai#2327]
Does this occur consistently? 
YES

Repro steps:

1. Open Command Pallet
2. Select Azure ML: Connect compute instance to Jupyter Server
3. Click report an Issue toast in the bottom right of your screen.

Action: azureml.commandPalette.computeInstance.connectToJupyterServer
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'toString')

Version: 0.46.1
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.87.1
Language: en

<details>
<summary>Call Stack</summary>

```
II.selectJupyterUri extension.node.js:430:27170
l.h extensionHostProcess.js:150:184839
l.g extensionHostProcess.js:150:183831
l.executeCommand extensionHostProcess.js:150:183738
Object.executeCommand extensionHostProcess.js:160:21654
h.executeCommand extension.js:2:2347738
extension.js:2:2352560extension.js:2:2352560
```

</details>

**Comment by sevillal** [comment]
Thanks for filing this issue @markjbrown. This should be fixed in our next release v0.48.0 available later this week.

**Comment by markjbrown** [comment]
@sevillal when is this version coming out? I very much would like to be able to leverage this ASAP.

**Comment by sevillal** [comment]
@markjbrown could you please try the following and let me know if it works for you:

1. Open a notebook
2. Run the command "Azure ML: Connect to compute instance Jupyter server"

**Comment by markjbrown** [comment]
@sevillal got the same error
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/800166/86c1a1dd-5526-47a2-aa71-4a248a2d600a)

**Comment by sevillal** [comment]
@markjbrown could you please try installing the latest pre-release version of the Azure ML extension and retry? You can follow this instructions to install the pre-release. https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-install-pre-release-version-of-the-extension-
