### ISSUE TITLE
Run Experiment from a Compute node should prompt for runconfig before script

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#233]
Assuming the compute has at least one runconfig defined, when the user chooses to run an experiment from a compute node, the first thing that should be asked is what runconfig to use. Only if the user chooses Add New should we prompt for a script file.

**Comment by shsuman** [comment]
Well, I think we want the script to be tied to a runconfig, so in any path of run Experiment we want to prompt for runconfig first and only if user chooses add new we prompt for script, kind of like script is a parameter necessary to create a run config. Is that what you mean ?

**Comment by greazer** [comment]
Yes, what you describe is what I mean.
