### ISSUE TITLE
Can't connect to remote machine - keep getting this error

### ISSUE THREAD

**Issue by felicityallen** [microsoft/vscode-tools-for-ai#2331]
Does this occur consistently? 
Yes at the moment, but No as in it was doing it a week or two ago, then stopped for a few days, and is now doing it again. Not sure what's changed.

Repro steps:

1.  From Machine Learning studio in Azure, click on 'VS Code Desktop' for compute node.

Action: Resolver.resolve
Error type: ie
Error Message: Failed to connect to target. Jupyter is required to connect to the remote target. Please ensure Jupyter is installed and running on the remote machine and retry connecting from the extension or the ML Studio. (Error: Invalid response: 502 Bad Gateway)

Version: 0.46.0
OS: darwin
OS Release: 23.2.0
Product: Visual Studio Code
Product Version: 1.87.0
Language: en

<details>
<summary>Call Stack</summary>

```
ie.NotAvailable extensionHostProcess.js:148:8631
w.handle502BadGateway extension.js:2:1611528
w.handleError extension.js:2:1608225
o.value extension.js:2:1532109
extension.js:2:1624225
```

</details>

**Comment by felicityallen** [comment]
No, it seems to time out.On 13 Mar 2024, at 06:42, Shantnu Suman ***@***.***> wrote:﻿
@felicityallen Ae you able to access Jupyter Lab from Azure ML Studio when this error happens ?

**Comment by shsuman** [comment]
@felicityallen In that case, there seems to be a problem with the Jupyter running on Compute instances. VS Code depends on Jupyter to be up and running before we can make a connection. Please open an issue with [Azure ML Studio](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/27de6be1-d524-44f2-9a95-10ab33646cc7/resourceGroups/shsuman-scus/providers/Microsoft.MachineLearningServices/workspaces/shsuman-scus/supportrequest) directly

**Comment by felicityallen** [comment]
Why does VScode need Jupyter to be running when I'm not using Jupyter?  I will try logging a request with ML studio.

**Comment by shsuman** [comment]
@felicityallen We need Jupyter terminal to install and run VS Code server on the Compute instances
