### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by jeraxiang** [microsoft/vscode-tools-for-ai#2332]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.46.1
Browser Name: Microsoft Edge
Browser Version: 122.0.0.0
OS: Windows 10 64-bit
Product: Visual Studio Code
Product Version: 1.87.2
Language: ja

<details>
<summary>Call Stack</summary>

```
kt.getSession webOpener.js:2:706485
https:/webOpener.js:2:785622
Ar.measure webOpener.js:2:792738
Tr.getSession webOpener.js:2:785580
Tr.create webOpener.js:2:785316
$n.resolve webOpener.js:2:742078
https:/webOpener.js:2:772536
Ar.measure webOpener.js:2:792738
Lr.doRoute webOpener.js:2:772493
Module.Ir webOpener.js:2:793341
```

</details>

**Comment by shsuman** [comment]
@sevillal Please look into this :)

**Comment by sevillal** [comment]
Thanks for filing this issue @jeraxiang. Unfortunately this is a [known issue](https://github.com/microsoft/vscode/issues/197389), we are working with VS Code team to get this fixed as soon as possible. Are you able to use VS Code desktop to connect to your Compute Instance?

**Comment by jeraxiang** [comment]
Yes, I am able to use Destop, but not web
