### ISSUE TITLE
Azure VSCode extension on web can no longer connect to Azure compute instance

### ISSUE THREAD

**Issue by usoni1** [microsoft/vscode-tools-for-ai#2357]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.48.0
Browser Name: Chrome
Browser Version: 124.0.0.0
OS: Windows 10 64-bit
Product: Visual Studio Code
Product Version: 1.88.1
Language: en

<details>
<summary>Call Stack</summary>

```
kt.getSession webOpener.js:2:706485
https:/webOpener.js:2:785853
Ar.measure webOpener.js:2:792927
Tr.getSession webOpener.js:2:785811
Tr.create webOpener.js:2:785519
$n.resolve webOpener.js:2:742087
https:/webOpener.js:2:772433
Ar.measure webOpener.js:2:792927
Lr.doRoute webOpener.js:2:772390
Module.Ir webOpener.js:2:793530
```

</details>

**Comment by sevillal** [comment]
Hi @usoni1, thanks for filing this issue. Did it use to work before and suddenly stop working?

This is a [known VS Code issue](https://github.com/microsoft/vscode/issues/197389), but we are currently testing the solution provided by VS Code team, your input is very valuable to improve this scenario. Could you please try the following and report if it fixed your issue?

1. Go to Azure ML Studio and open the `Compute` tab
2. Right click on the `VS Code (Web)` link of your compute instance and click `Copy link`
3. Open a new browser tab
4. Paste the link and add `&useMsal=true` at the end of the URL
5. Hit enter
6. Enter your credentials if needed and report if you are able to connect or if you see a different error

**Comment by sevillal** [comment]
Hi @usoni1 , we just rolled out a fix for this issue, could you please retry? Please reopen this issue if you face any problem.
