### ISSUE TITLE
Unable to open VSCode web for accessing AzureML compute

### ISSUE THREAD

**Issue by usoni1** [microsoft/vscode-tools-for-ai#2358]
Does this occur consistently%3F Yes
Repro steps:

1. Go to the AzureML compute (see image)
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/23586503/235874d5-308e-4126-8e8e-06043e78972b)
 2. Open VSCode (Web)
 3. It used to work earlier but now it has started giving the following error. 

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.48.0
Browser Name: Chrome
Browser Version: 124.0.0.0
OS: Windows 10 64-bit
Product: Visual Studio Code
Product Version: 1.88.1
Language: en

<details>
<summary>Call Stack</summary>

```
kt.getSession webOpener.js:2:706485
https:/webOpener.js:2:785853
Ar.measure webOpener.js:2:792927
Tr.getSession webOpener.js:2:785811
Tr.create webOpener.js:2:785519
$n.resolve webOpener.js:2:742087
https:/webOpener.js:2:772433
Ar.measure webOpener.js:2:792927
Lr.doRoute webOpener.js:2:772390
Module.Ir webOpener.js:2:793530
```

</details>

The above was the stack trace generated automatically. But I also did inspect element to get some more logs for you from the console. 

Please see the following:

![image](https://github.com/microsoft/vscode-tools-for-ai/assets/23586503/15dba014-14e0-4acf-9f2a-bb15db81ee10)

I feel like for some reason VSCode is expecting to do Multi-factor authentication while it is never needed as I have a company laptop. 

Also, please note that VSCode web is working for some employees in the same workspace and it is not working for other people. 

Please let me know whatever help I can do from my end.

**Comment by sevillal** [comment]
Hi @usoni1, thanks for filing this issue.

This is a [known VS Code issue](https://github.com/microsoft/vscode/issues/197389), but we are currently testing the solution provide by VS Code team, your input is very valuable to improve this scenario. Could you please try the following and report if it fixed your issue?

1. Go to Azure ML Studio and open the `Compute` tab
2. Right click on the `VS Code (Web)` link of your compute instance and click `Copy link`
3. Open a new browser tab
4. Paste the link and add `&useMsal=true` at the end of the URL
5. Hit enter
6. Enter your credentials if needed and report if you are able to connect or if you see a different error

**Comment by usoni1** [comment]
@sevillal , thank for your input. VSCode desktop was working for me so I didn't try VSCode web. But I followed the steps you said out and it is working for me.

**Comment by sevillal** [comment]
@usoni1, does it work if you directly click on the `VS Code (Web)`  (without adding anything to the URL as I mentioned earlier)?

**Comment by usoni1** [comment]
@sevillal , it does not work without it.

**Comment by sevillal** [comment]
Thanks for your confirmation @usoni1. We are working on the rollout plan of this fix; I'll update this issue when I have more information.

**Comment by sevillal** [comment]
Hi @usoni1 , we just rolled out a fix for this issue, could you please retry? Please reopen this issue if you face any problem.
