### ISSUE TITLE
vs code web not opening

### ISSUE THREAD

**Issue by abhishekshd** [microsoft/vscode-tools-for-ai#2361]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Invalid response: 502 
Error type: JupyterTerminalError
Original error: [<no-type>:<no-code>]

Version: 0.48.0
Browser Name: Chrome
Browser Version: 124.0.0.0
OS: Windows 10 64-bit
Product: Visual Studio Code
Product Version: 1.89.0
Language: en

<details>
<summary>Call Stack</summary>

```
t.create webOpener.js:2:129753
async t.startNew webOpener.js:2:152656
async d.startNew webOpener.js:2:150980
async Xt webOpener.js:2:722683
async Xt webOpener.js:2:722969
async Xt webOpener.js:2:722969
async Xt webOpener.js:2:722969
async sn.initialize webOpener.js:2:727160
async sn.ensureTerminalIsReady webOpener.js:2:725512
async sn.onMessageReceived webOpener.js:2:727642
```

</details>

**Comment by sevillal** [comment]
Thanks for filing this issue @abhishekshd, is JupyterLab working and accessible from the Azure ML Studio on that compute instance? For context, as of today the Azure ML Remote extension relies on Jupyter to bootstrap the remote connection, failure to access or use Jupyter might lead to this issue.

**Comment by abhishekshd** [comment]
Hey Sergio,

It’s working now, was an issue with the data store subnet. And yes, Jupyter
was also down. Thank you for checking in!!

Best Regards,
Abhishek Sharda
