### ISSUE TITLE
Convert web automation tests to Managed Identity

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2365]
Currently our web automation tests use Entra Apps to authenticate an account. We want to convert this to managed identity using MSAL.js.

Code to change here: https://github.com/devdiv-microsoft/vscode-azureml-remote-web/blob/6205c78e544637802a483bb330a0a10e000c83ac/src/test/connection.browser.test.ts#L75

Tests: https://github.com/devdiv-microsoft/vscode-azureml-remote-web/actions/runs/9079050906/job/24947416125

Enabling Managed Identity in Github Actions: https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation#supported-scenarios

Managed Identity that can be used: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/27de6be1-d524-44f2-9a95-10ab33646cc7/resourceGroups/azuremlext-dw-build-infra/providers/Microsoft.ManagedIdentity/userAssignedIdentities/AzureMLExt_DW_API_Scan_Managed_Identity/overview

**Comment by sevillal** [comment]
Fixed.
