### ISSUE TITLE
[Error UX Improvements]: "Operation cancelled (Allow authorization dialog cancelled)"

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2384]
Let's improve the error message experience when users encounter this error. The ideal experience is actionable and specific to minimize friction for users. For example, a user could press a button in the error dialog to fix the issue. Or they could have a link that takes them directly to documentation for a complex issue. If they need to navigate to the Studio, we could provide a link to direct them to the right UI/tab as much as possible.

**Context**: The user cancelled one of the VS Code dialogs that allows our extension to use the signed in Microsoft account (and therefore Azure auth).

Screenshots/doc: https://microsoft-my.sharepoint-df.com/:w:/p/tbombach/EQr8lflQzDJKpspWiDV3N6MBKSlgeItWDYrj_o5v-oITcA?e=u3Q27x

Steps:

- [x] (PM) Define ideal error UX (work with dev as-needed to understand the error state/potential fixes)
- [x] (Dev) Implement improvements
- [x] (PM) Verify improvement

**Comment by yaoleo34** [comment]
- Improve error message to: "Failed to connect to Azure Machine Learning remote server (Error: Login failed)
- Action buttons:
 - Log In
 - Open Developer Tools
 - Cancel
- Implement "Trusted by Microsoft" to both Azure Machine Learning and Azure Machine Learning - Remote extension

**Comment by shsuman** [comment]
I have contacted Alex from Azure tools team to see how we can get our extensions added to the list of _Trusted by Microsoft_ extensions

**Comment by shsuman** [comment]
Reply from Alex:

_It will be in VS Code Insiders by End of Week_
_It will be in VS Code Stable early next month_

**Comment by shsuman** [comment]
> I have contacted Alex from Azure tools team to see how we can get our extensions added to the list of _Trusted by Microsoft_ extensions

Verified it today. It is already in VS Code Insiders but not yet in stable.

**Comment by shsuman** [comment]
https://github.com/devdiv-microsoft/vscode-azureml/pull/573
