### ISSUE TITLE
[Error UX Improvements]: "403 Forbidden"

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2385]
Let's improve the error message experience when users encounter this error. The ideal experience is actionable and specific to minimize friction for users. For example, a user could press a button in the error dialog to fix the issue. Or they could have a link that takes them directly to documentation for a complex issue. If they need to navigate to the Studio, we could provide a link to direct them to the right UI/tab as much as possible.

**Context**: The user is trying to connect to a compute instance that they do not have access to. The compute instance was either created by a different user (computes are only connectable by the creator) or not assigned to the user when it was created.

Screenshots/doc: https://microsoft-my.sharepoint-df.com/:w:/p/tbombach/EQr8lflQzDJKpspWiDV3N6MBKSlgeItWDYrj_o5v-oITcA?e=u3Q27x

Steps:

- [x] (PM) Define ideal error UX (work with dev as-needed to understand the error state/potential fixes)
- [x] (Dev) Implement improvements
- [x] (PM) Verify improvement

**Comment by yaoleo34** [comment]
- Improve error message to: "You do not have permission to access the compute instance"
- Action buttons:
  - Open Azure ML Studio (with link to the compute instance)
  - Cancel

**Comment by tbombach** [comment]
Marked as done - this has already been finished
