### ISSUE TITLE
[Error UX Improvements]: "The compute instance environment "---" is not running"

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2387]
Let's improve the error message experience when users encounter this error. The ideal experience is actionable and specific to minimize friction for users. For example, a user could press a button in the error dialog to fix the issue. Or they could have a link that takes them directly to documentation for a complex issue. If they need to navigate to the Studio, we could provide a link to direct them to the right UI/tab as much as possible.

**Context**: The docker container (environment container) that we are trying to connect to is not in a running state. The running container is a pre-requisite for connecting to environment containers.

Screenshots/doc: https://microsoft-my.sharepoint-df.com/:w:/p/tbombach/EQr8lflQzDJKpspWiDV3N6MBKSlgeItWDYrj_o5v-oITcA?e=u3Q27x

Steps:

- [x] (PM) Define ideal error UX (work with dev as-needed to understand the error state/potential fixes)
- [ ] (Dev) Implement improvements
- [ ] (PM) Verify improvement

**Comment by yaoleo34** [comment]
- Improve error message to: "Connection failed: the environment "{environment container name}" is not running"
- Action buttons:
  - Start environment container
  - Open Azure AI Studio (Link to the 'Code' tab)
  - Cancel
- Ask Azure AI to open the API for checking environment container status

**Comment by sevillal** [comment]
Current error in web: 
![image](https://github.com/user-attachments/assets/cf87134e-bec0-48dc-a6c0-13d7da094a42)

**Comment by sevillal** [comment]
After talking to Azure ML team we decided to update the behavior of the `Open Azure AI studio` button to take the user to the Compute Instance tab.
