### ISSUE TITLE
[Error UX Improvements]: "The Compute Instance is not in a running state"

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2388]
Let's improve the error message experience when users encounter this error. The ideal experience is actionable and specific to minimize friction for users. For example, a user could press a button in the error dialog to fix the issue. Or they could have a link that takes them directly to documentation for a complex issue. If they need to navigate to the Studio, we could provide a link to direct them to the right UI/tab as much as possible.

**Context**: We queried the compute instance properties endpoint and the RunStatus is not Running (pre-req for connecting). The user may have auto shutdown policies or manually shut off the compute

Screenshots/doc: https://microsoft-my.sharepoint-df.com/:w:/p/tbombach/EQr8lflQzDJKpspWiDV3N6MBKSlgeItWDYrj_o5v-oITcA?e=u3Q27x

Steps:

- [x] (PM) Define ideal error UX (work with dev as-needed to understand the error state/potential fixes)
- [x] (Dev) Implement improvements
- [x] (PM) Verify improvement

**Comment by yaoleo34** [comment]
Looks good so far! A couple questions and comments:

- What will happen when user clicks on "Start compute instance"?
- What page will "open AzureML studio" take the user to?

**Comment by tbombach** [comment]
This item is completed (it was the first error ux improvement completed and used as a reference). To answer Leo's questions:
- When the user clicks "Start compute instance", we warn them that starting a compute instance will incur charges since it will be running. If they continue, we use the Azure ML REST APIs to start the compute instance. Once it starts, we continue with the connection
- The "Open Azure ML Studio" page opens to the list of compute instances for the user's workspace.
