### ISSUE TITLE
Bad Gateway Failure when connecting to interactive jobs

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2410]
Error message: Failed to connect to the remote extension host server (Error: Bad Gateway)

More details in internal issue: https://github.com/devdiv-microsoft/vscode-azureml/issues/553

**Comment by tbombach** [comment]
Note: I do not see the Bad Gateway error in logs provided by customer. It is possible the customer provided logs from a different time than immediately after then issue occurred.

@shsuman Would you mind looking into this one? More details in the internal issue

**Comment by tbombach** [comment]
We may need to push for a contact in interactive jobs - we can't do much if the execution service returns Bad Gateway. I want to verify that we don't see anything in our extension as well though

**Comment by shsuman** [comment]
Closing this as I haven't received any communication from the Support Engineer.
