### ISSUE TITLE
unable to connect to Azure ML Compute via VS code

### ISSUE THREAD

**Issue by vyogitha** [microsoft/vscode-tools-for-ai#2434]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml-remote.commandPalette.computeInstance.connect
Error type: 120
Error Message: Network failure

Version: 0.51.2024080709
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.92.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.node.js:2:1347443extension.node.js:2:1347443
async f.connectToComputeInstance extension.node.js:2:1435800
```

</details>

**Comment by shsuman** [comment]
@vyogitha The error message clearly says its a network failure. I am not sure if we can do anything here :). I am closing this issue for now. Please reopen if need be :)
