### ISSUE TITLE
I can't access my compute instance...

### ISSUE THREAD

**Issue by RDuerichen** [microsoft/vscode-tools-for-ai#2443]
Does this occur consistently?  yes
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: re
Error Message: Failed to connect to target. Jupyter is required to connect to the remote target. Please ensure Jupyter is installed and running on the remote machine and retry connecting from the extension or the ML Studio. (Error: Invalid response: 502 Bad Gateway)

Version: 1.0.0
OS: darwin
OS Release: 23.5.0
Product: Visual Studio Code
Product Version: 1.91.0
Language: en

<details>
<summary>Call Stack</summary>

```
re.NotAvailable extensionHostProcess.js:152:8975
E.handle502BadGateway extension.node.js:2:1622882
E.handleError extension.node.js:2:1619337
s.value extension.node.js:2:1401691
L.<anonymous> extension.node.js:2:1502806
c extension.node.js:2:1498579
```

</details>

**Comment by shsuman** [comment]
@RDuerichen Are you able to access Jupyter Lab from the Azure ML Studio ?
