### ISSUE TITLE
Inquiry about WebSocket host port range

### ISSUE THREAD

**Issue by g-crocker** [microsoft/vscode-tools-for-ai#2445]
Hello,

I work in a very restricted environment where host machines deny any unexpected attempts to open WebSocket ports.

I am using the AML Remote extension to connect to a Compute Instance and would like to know if there is a documented range of ports that the extension attempts to use for WebSocket connections on the host machine. I understand that the ports on the AML Compute Instance range from 8704-8993, but I haven't been able to find information about the port range used on the host machine. This information is crucial to properly configure our network security settings.

I've observed that the extension appears to select different ports for WebSocket connections each time it is used, and I haven't been able to identify a specific pattern or range.

Could you please provide any details on the port range or explain how the extension determines which ports to use for WebSocket connections?

Thanks

**Comment by shsuman** [comment]
@g-crocker Please take a look at the required [hosts](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-access-azureml-behind-firewall?view=azureml-api-2&tabs=ipaddress%2Cpublic#hosts) and [ports](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-access-azureml-behind-firewall?view=azureml-api-2&tabs=ipaddress%2Cpublic#ports) to be whitelisted.
