### ISSUE TITLE
Ports Tab dissapears after remote conection to AzureML

### ISSUE THREAD

**Issue by oscarfloo** [microsoft/vscode-tools-for-ai#2454]
## Expected Behavior
The ports view disappears once the conection is finished.

## Actual Behavior
No ports view tab.

## Specifications

  - : 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
  - Platform: Windows 10

**Comment by oscarfloo** [comment]
![image](https://github.com/user-attachments/assets/b2e1ba87-2700-4845-87fc-600c76804d91)
![image](https://github.com/user-attachments/assets/0d21ef19-4b7b-4b6b-bb27-2826c98136af)

**Comment by aakashnand** [comment]
I am also getting this issue and it seems the port forwarding is not working for me. 

I have checked this issue https://github.com/microsoft/vscode-tools-for-ai/issues/2174 seems very similar

**Comment by shsuman** [comment]
@oscarfloo @aakashnand I am able to repro this issue and it seems like a problem with the latest version of VS Code. I am working with VS Code team to resolve this issue at the earliest. In the meantime, I will advise you to downgrade your VS Code version to 1.93.x. You can read here on [How to install an older version of VS Code ?](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-install-an-older-version-of-vs-code-)

**Comment by aakashnand** [comment]
@shsuman Just additional observation. Not only is the PORT tab missing, but auto port forwarding also stopped working in 1.94.x

**Comment by shsuman** [comment]
@oscarfloo @aakashnand We have released a fix in the version 1.2.0. Please upgrade both the extensions to 1.2.0 and try again :).

**Comment by aakashnand** [comment]
> [@oscarfloo](https://github.com/oscarfloo) [@aakashnand](https://github.com/aakashnand) We have released a fix in the version 1.2.0. Please upgrade both the extensions to 1.2.0 and try again :).

Can you clarify 1.2.0 version of what? Vscode or extension? I searched VSCode update but its still at 1.94.2. If possible please share the link

**Comment by shsuman** [comment]
**Please upgrade both the extensions to 1.2.0**

Please upgrade from the extensions from the extensions tab 
https://code.visualstudio.com/docs/editor/extension-marketplace#_browse-for-extensions

**Comment by oscarfloo** [comment]
@shsuman the last version I see is 1.0.0
![Image](https://github.com/user-attachments/assets/8a888e52-e8ad-442e-9353-a272c928dd60)

**Comment by shsuman** [comment]
@oscarfloo @aakashnand Apologies, it seems like the latest release didn't go through in time last week. It is now scheduled to go out early this week. I will let you know once its out there.

Once again, please accept my sincere apologies for this confusion.

**Comment by shsuman** [comment]
@oscarfloo @aakashnand Version 1.2.0 of the extension has been released now. Please update the extension now :)

**Comment by aakashnand** [comment]
@shsuman I confirmed that with latest version of vscode and azure machine learning remote extension 1.2.0 the bug is fixed. 

Out of curiosity is release cycle of this extension managed outside github? The release on this repository is very old.

**Comment by shsuman** [comment]
@aakashnand Thanks. I will close the issue now. And to answer your question, Yes.
