### ISSUE TITLE
Can't connect to my compute

### ISSUE THREAD

**Issue by BenL-DSG** [microsoft/vscode-tools-for-ai#2458]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: 332
Error Message: The terminal process did not finish within 120 seconds. Aborting to exit.

Version: 1.2.0
OS: darwin
OS Release: 23.6.0
Product: Visual Studio Code
Product Version: 1.93.1
Language: en

<details>
<summary>Call Stack</summary>

```
Timeout._onTimeout extension.node.js:2:330290
```

</details>

**Comment by JerryYangKai** [comment]
Hello @BenL-DSG 
Please provide the steps for repro, and whether this is a stable repro or an occasional occurrence.

**Comment by JerryYangKai** [comment]
Close it since there is no reply for seven days, feel free to reopen it.
