### ISSUE TITLE
VSCode to AzureML Compute: Connection timeout on port 8705

### ISSUE THREAD

**Issue by gre-jkpoynter** [microsoft/vscode-tools-for-ai#2459]
## Expected Behavior

Given
- AzureML secured with private endpoints
- Custom DNS configured
- ZScaler proxy, corporate firewalls
- ZScaler certs are present on remote AzureML compute instance and .wgetrc configured to use ZScaler ca certs
- NSG rules on subnet as per Azure docs

When
- A data scientist connects to the AzureML compute instance via VSCODE
- AzureML compute instance downloads installs / updates websocket server and vscode server as required
- Runs VScode server

Then
- Data scientist connects successfully from VSCode

## Actual Behavior

VSCode server runs on port 8705
![Image](https://github.com/user-attachments/assets/28eb9a5d-0490-4bfd-8115-befda8d9b5b9)

Connection times out as per above. We initially suspected an NSG configuration issue but have since ruled that out. I've been through the documentation for AzureML and could not find a reference to port 8705. 

## Specifications

  - VS Code Version:1.9.42
  - Platform: Windows

**Comment by Siglud** [comment]
Sorry for the delay.

Ports 8704 to 8710 is the VS Code server dynamically selects the first available port within this range. So, you must add 8704-8710 ports to your firewall traffic enable list.

You can find more detail in [this document](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-access-azureml-behind-firewall?view=azureml-api-2&tabs=ipaddress%2Cpublic#scenario-visual-studio-code).

**Comment by gre-jkpoynter** [comment]
Thanks @Siglud this makes sense I've spoken with our networks team and as you stated the firewall rules seem to be the source of the issue.
