### ISSUE TITLE
Flask Error after installation of extension

### ISSUE THREAD

**Issue by Spagoot420** [microsoft/vscode-tools-for-ai#246]
Hello,

After installation I am being prompted to login. After doing so, I get this in the output:

error: Flask Error: Error: spawn c:\Users\hoelzlM\.azureml\envs\amlsdk\Scripts\python.exe ENOENT
warn: Starting local flask server timed out.
warn: Azure ML extension flask server couldn't be initialized: Error: Timeout of 500ms exceeded
error: Internal extension error: Azure ML extension flask server couldn't be initialized: $Error: Timeout of 500ms exceeded
error: The request did not have a subscription or a valid tenant level resource provider.
warn: Get children failed in AzureMLTreeView, Cannot read property 'forEach' of undefined

This is very weired. I have a Python interpreter selected and this is a fresh install of windows...

**Comment by shsuman** [comment]
Hello @Spagoot420 , 

Looks like the extension is looking in a slightly incorrect directory for the python executable ? Can you confirm that you have c:\Users\hoelzlM\.azureml\envs\amlsdk\Scripts\python.exe on your machine and you don't have c:\Users\hoelzlM.azureml\envs\amlsdk\Scripts\python.exe ?

**Comment by Spagoot420** [comment]
Hello,

you are absolutely right. There isn't even a folder named '.azureml' in my users profile folder (on c:\ ).
But I found it somewhere else:
H:\.azureml\envs\amlsdk\Scripts

H:\ is (I think) a network drive where the users profile folder gets distributed. I think it is set up by my companys IT department. 

Here is my logfile:
[2019-05-07T100931.log](https://github.com/microsoft/vscode-tools-for-ai/files/3156206/2019-05-07T100931.log)


I tried moving the .azureml folder from the networkdrive over to my local profile folder, but now I get further errors:
```
error: Flask Error: Error: Command failed: c:\Users\hoelzlM\.azureml\envs\amlsdk\Scripts\python.exe c:\Users\hoelzlM\.vscode\extensions\ms-toolsai.vscode-ai-0.5.1\FlaskServers\amlflask\server.py -p 3073 -s None
Traceback (most recent call last):
  File "c:\Users\hoelzlM\.vscode\extensions\ms-toolsai.vscode-ai-0.5.1\FlaskServers\amlflask\server.py", line 29, in <module>
    from amlflask.common.utils import EPRINT,DEBUG, extract_from_compute_uri, get_auth_token, extract_from_workspace_uri
  File "c:\Users\hoelzlM\.vscode\extensions\ms-toolsai.vscode-ai-0.5.1\FlaskServers\amlflask\common\utils.py", line 8, in <module>
    from azureml.core.authentication import ArmTokenAuthentication
  File "c:\Users\hoelzlM\.azureml\envs\amlsdk\lib\site-packages\azureml\core\__init__.py", line 10, in <module>
    from azureml.core.workspace import Workspace
  File "c:\Users\hoelzlM\.azureml\envs\amlsdk\lib\site-packages\azureml\core\workspace.py", line 21, in <module>
    from azureml._project import _commands
  File "c:\Users\hoelzlM\.azureml\envs\amlsdk\lib\site-packages\azureml\_project\_commands.py", line 8, in <module>
    from azureml._base_sdk_common.common import create_role_assignment
  File "c:\Users\hoelzlM\.azureml\envs\amlsdk\lib\site-packages\azureml\_base_sdk_common\common.py", line 25, in <module>
    from azureml._vendor.azure_cli_core._profile import Profile
  File "c:\Users\hoelzlM\.azureml\envs\amlsdk\lib\site-packages\azureml\_vendor\azure_cli_core\_profile.py", line 33, in <module>
    from OpenSSL.crypto import load_certificate, FILETYPE_PEM
  File "c:\Users\hoelzlM\.azureml\envs\amlsdk\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "c:\Users\hoelzlM\.azureml\envs\amlsdk\lib\site-packages\OpenSSL\crypto.py", line 12, in <module>
    from cryptography import x509
  File "c:\Users\hoelzlM\.azureml\envs\amlsdk\lib\site-packages\cryptography\x509\__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "c:\Users\hoelzlM\.azureml\envs\amlsdk\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "c:\Users\hoelzlM\.azureml\envs\amlsdk\lib\site-packages\cryptography\x509\extensions.py", line 18, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "c:\Users\hoelzlM\.azureml\envs\amlsdk\lib\site-packages\cryptography\hazmat\primitives\constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._constant_time'

warn: Starting local flask server timed out.
warn: Azure ML extension flask server couldn't be initialized: Error: Timeout of 500ms exceeded
error: Internal extension error: Azure ML extension flask server couldn't be initialized: $Error: Timeout of 500ms exceeded
error: The request did not have a subscription or a valid tenant level resource provider.
warn: Get children failed in AzureMLTreeView, Cannot read property 'forEach' of undefined
```

**Comment by shsuman** [comment]
@Spagoot420 Thank you for providing all the info. Can you open the command prompt and check what does **echo "%HOMEDRIVE%%HOMEPATH%"** return ? 

Also, for now you can manually install the dependencies by running the following script on command prompt:

@echo off
setlocal
set AML_HOME=C:\Users\hoelzlM\\.azureml

set PYTHONBIN="your python path(version <3.7)"

for /f "tokens=2 delims= " %%i in ('call "%PYTHONBIN%" --version 2^>^&1') do set PYTHON_VERSION=%%i

call "%PYTHONBIN%" --version
if "%ERRORLEVEL%" neq "0" (
    exit /b 1
)

if "%PYTHON_VERSION%" lss "3.5" (
    exit /b 2
)

set /p AML_VERSION=1.0.15

call "%PYTHONBIN%" -c "import venv"
if "%ERRORLEVEL%" neq "0" (
    exit /b 3
)

REM create AML virtual environment
call "%PYTHONBIN%" -m venv "%AML_HOME%\envs\amlsdk"
call "%AML_HOME%\envs\amlsdk\scripts\activate.bat"

python -m pip install --upgrade pip
python -m pip install flask
python -m pip install werkzeug
python -m pip install azureml-sdk==%AML_VERSION%

REM The following is use to work around an azureml-sdk bug.
python -m pip install --upgrade ruamel.yaml

call "%AML_HOME%\envs\amlsdk\scripts\deactivate.bat"
exit /b 0

**Comment by shsuman** [comment]
@greazer  need to handle cases where %HOMEDRIVE%%HOMEPATH% and os.homedir() yields different results

**Comment by Spagoot420** [comment]
@shsuman 
Thank you very much for your quick response.

echo "%HOMEDRIVE%%HOMEPATH%" returns:
"H:\"

Thank you for your script. It is now working for me, but I had to perform some changes to it in order to make the script run without errors.

First of all I had to add some pause commands in order to debug it. Then I found out, that the script doesn't like my path to the python executable, because it contained a space character. Since i couldn't fix the issue, I set PYTHONBIN="python" in order to reference to the environment variable.

Also I had to remove the "/p" when setting the AML_VERSION variable, because otherwise it wouldn't work for me.

Here Is my script without my additional echos and pauses:
```
@echo off
setlocal
set AML_HOME=C:\Users\hoelzlM\.azureml

set PYTHONBIN="python"

for /f "tokens=2 delims= " %%i in ('call "%PYTHONBIN%" --version 2^>^&1') do set PYTHON_VERSION=%%i

call "%PYTHONBIN%" --version
if "%ERRORLEVEL%" neq "0" (
exit /b 1
)

if "%PYTHON_VERSION%" lss "3.5" (
exit /b 2
)

set AML_VERSION=1.0.15

call "%PYTHONBIN%" -c "import venv"
if "%ERRORLEVEL%" neq "0" (
exit /b 3
)

REM create AML virtual environment
call "%PYTHONBIN%" -m venv "%AML_HOME%\envs\amlsdk"
call "%AML_HOME%\envs\amlsdk\scripts\activate.bat"

python -m pip install --upgrade pip
python -m pip install flask
python -m pip install werkzeug
python -m pip install azureml-sdk==%AML_VERSION%

REM The following is use to work around an azureml-sdk bug.
python -m pip install --upgrade ruamel.yaml

call "%AML_HOME%\envs\amlsdk\scripts\deactivate.bat"
exit /b 0
```

Also I hgihly advice everyone to run the script as administrator, since for some reasons I had to do that in order to use pip in some folders...

Thank you very much, my issue has been resolved. If you want to, I am available for testing ^^

**Comment by shsuman** [comment]
@Spagoot420 Glad to hear that your issue is resolved. However, I apologize that you had to face some problems while running the script. Actually, the script is meant to be run in a subprocess where Python Path and AML_version are obtained and fed programatically instead of writing them manually. About your original issue, we will fix that in our next release so that we handle the cases like these where users have some other drive setup.

**Comment by shsuman** [comment]
Flask server dependency has been completely removed from the extension.
