### ISSUE TITLE
Isuse starting Azure ML Compute

### ISSUE THREAD

**Issue by soutrik71** [microsoft/vscode-tools-for-ai#2461]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Invalid response: 502 Bad Gateway
Error type: JupyterTerminalError
Original error: [<no-type>:<no-code>]

Version: 1.0.0
Browser Name: Chrome
Browser Version: 128.0.0.0
OS: Windows 10 64-bit
Product: Visual Studio Code
Product Version: 1.94.2
Language: en

<details>
<summary>Call Stack</summary>

```
t.create webOpener.js:2:129753
async t.startNew webOpener.js:2:152656
async d.startNew webOpener.js:2:150980
async Xt webOpener.js:2:722688
async Xt webOpener.js:2:722974
async Xt webOpener.js:2:722974
async Xt webOpener.js:2:722974
async sn.initialize webOpener.js:2:727165
async sn.ensureTerminalIsReady webOpener.js:2:725517
async sn.onMessageReceived webOpener.js:2:727647
```

</details>

**Comment by yukun-dong** [comment]
Hi @soutrik71 , Can you please kindly provide the Azure ML - Remote Trace logs by following these [steps](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-trace-logs-for-azure-machine-learning---remote-extension-) ?

**Comment by yukun-dong** [comment]
Close this issue because of inactivity. Please reopen if needed.
