### ISSUE TITLE
CPU Instance not working

### ISSUE THREAD

**Issue by Sparsh913** [microsoft/vscode-tools-for-ai#2463]
Action: Resolver.resolve
Error type: 72
Error Message: Invalid response: 500 InternalServerError

Version: 1.2.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.94.2
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.node.js:2:177190
async p.isTundraAvailable extension.node.js:2:280493
async f.ensureIsConnectable extension.node.js:2:196392
async f.getConnectionHub extension.node.js:2:195574
extension.node.js:2:252868extension.node.js:2:252868
```

</details>

**Comment by gitgud5000** [comment]
Same Issue for my workspace/team.

**Comment by oscarfloo** [comment]
I have the same issue.

Action: Resolver.resolve
Error type: 72
Error Message: Invalid response: 500 InternalServerError


Version: 1.2.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.95.0
Language: en

**Comment by gitgud5000** [comment]
Same problem #2464

**Comment by zijianjin0730** [comment]
I have the same issue
Action: Resolver.resolve
Error type: 72
Error Message: Invalid response: 500 InternalServerError


Version: 1.2.0
OS: darwin
OS Release: 24.0.0
Product: Visual Studio Code
Product Version: 1.94.2
Language: en

**Comment by gitgud5000** [comment]
Also related #2465

**Comment by yukun-dong** [comment]
Close this issue because of inactivity. Please reopen if needed.
