### ISSUE TITLE
Cannot Connect to Azure Machine Learning computes

### ISSUE THREAD

**Issue by winnieshen96** [microsoft/vscode-tools-for-ai#2464]
Does this occur consistently?  Yes, for all computes in all subscriptions
Repro steps:

1.Connect to a compute on Azure Machine Learning via VS code
2.The AML workspace is in an Azure Virtual Network and has custom DNS

Action: Resolver.resolve
Error type: 72
Error Message: Invalid response: 500 InternalServerError

Version: 1.2.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.95.0
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.node.js:2:177190
async p.isTundraAvailable extension.node.js:2:280493
async f.ensureIsConnectable extension.node.js:2:196392
async f.getConnectionHub extension.node.js:2:195574
extension.node.js:2:252868extension.node.js:2:252868
```

</details>

**Comment by nachogarciam** [comment]
Im having the same issue, also vscode web is not working.

**Comment by yukun-dong** [comment]
> Im having the same issue, also vscode web is not working.

For the vscode web issue, please check https://github.com/microsoft/vscode-tools-for-ai/issues/2466

**Comment by yukun-dong** [comment]
Close this issue because of inactivity. Please reopen if needed.
