### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by mark-naeem-qltech** [microsoft/vscode-tools-for-ai#2465]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: 72
Error Message: Invalid response: 500 InternalServerError

Version: 1.2.0
OS: linux
OS Release: 6.8.0-47-generic
Product: Visual Studio Code
Product Version: 1.95.0
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.node.js:2:177190
async p.isTundraAvailable extension.node.js:2:280493
async f.ensureIsConnectable extension.node.js:2:196392
async f.getConnectionHub extension.node.js:2:195574
extension.node.js:2:252868extension.node.js:2:252868
```

</details>

**Comment by yukun-dong** [comment]
Hi @mark-naeem-qltech , I apologize for the issue you're experiencing. Could you please try following this guide [remote connection issue](https://github.com/microsoft/vscode-tools-for-ai/wiki/Remote-connection-to-Compute-instance-issues) to help troubleshoot the problem?

**Comment by yukun-dong** [comment]
Close this issue because of inactivity. Please reopen if needed.
