### ISSUE TITLE
cannot connect to compute instance on vscode web

### ISSUE THREAD

**Issue by yukun-dong** [microsoft/vscode-tools-for-ai#2466]
## Description
Customers will face below issue when connecting to compute instance from vscode web.
![Image](https://github.com/user-attachments/assets/77c18403-fba6-43d3-8bc2-ec444081e462)
![Image](https://github.com/user-attachments/assets/5026498f-b4ff-4434-85bd-4def4be2c3dd)

## Cause
This bug is not caused by the Azure machine learning extension but by the vscode web side. We are working with vscode web side to resolve this bug. In the meantime, please try below method to workaround this bug.

## Workaround
Replace the url part "ms-toolsai.vscode-ai-remote-web" to be "ms-toolsai.vscode-ai-remote".

![Image](https://github.com/user-attachments/assets/03f8e3a9-ac06-4251-a683-00fd4109901e)

![Image](https://github.com/user-attachments/assets/fef9daed-83b2-44e5-813e-ab2cca563f00)

**Comment by JerryYangKai** [comment]
If the workaround does not work, I suggest try dd `vscode-esm=false` to their URL. That seems to disable this change that VS Code made and I was able to avoid the error message when I tried this.

**Comment by msnagireddi** [comment]
HI, thanks for the above. I have tried both workarounds but unable to open localfiles

![Image](https://github.com/user-attachments/assets/b8191fd1-7d70-48ba-9d29-06642a76639f)

**Comment by msnagireddi** [comment]
Tried VScode desktop but its asking to sign-on in loop![Image](https://github.com/user-attachments/assets/10a432fd-bb89-46b1-8b10-17293a6fbe66)

**Comment by bpasero** [comment]
The issue should now be addressed, can people confirm?

**Comment by yukun-dong** [comment]
This issue has now been resolved. @msnagireddi, please feel free to open a new issue if you encounter any further problems.
