### ISSUE TITLE
Jupyter is requited to connect to the remote target

### ISSUE THREAD

**Issue by slovakradim** [microsoft/vscode-tools-for-ai#2475]
Does this occur consistently? Yes
Repro steps:

1. Start the compute
2. Start VS Code (Desktop)
3. Result : ![Image](https://github.com/user-attachments/assets/82ba669c-ea6e-4a2b-8ea8-7e8be7af7f55)

Action: Resolver.resolve
Error type: Gg
Error Message: Failed to connect to target. Jupyter is required to connect to the remote target. Please ensure Jupyter is installed and running on the remote machine and retry connecting from the extension or the ML Studio. (Error: Invalid response: 502 Bad Gateway)

Version: 1.2.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.96.0
Language: en

<details>
<summary>Call Stack</summary>

```
Gg.NotAvailable extensionHostProcess.js:109:25252
x.handle502BadGateway extension.node.js:2:240429
x.handleError extension.node.js:2:236926
s.value extension.node.js:2:158276
extension.node.js:2:253496extension.node.js:2:253496
```

</details>

**Comment by JerryYangKai** [comment]
@slovakradim  Are you able to access Jupyter Lab from the Azure ML Studio ?

**Comment by slovakradim** [comment]
No, but I solved it myself already
