### ISSUE TITLE
Jupyter service unavailable.

### ISSUE THREAD

**Issue by sanjaylalwani** [microsoft/vscode-tools-for-ai#2480]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: Ug
Error Message: Failed to connect to target. Jupyter is required to connect to the remote target. Please ensure Jupyter is installed and running on the remote machine and retry connecting from the extension or the ML Studio. (Error: Invalid response: 502 Bad Gateway)

Version: 1.2.0
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.95.3
Language: en

<details>
<summary>Call Stack</summary>

```
Ug.NotAvailable extensionHostProcess.js:108:25199
x.handle502BadGateway extension.node.js:2:240429
x.handleError extension.node.js:2:236926
s.value extension.node.js:2:158276
extension.node.js:2:253496extension.node.js:2:253496
```

</details>

**Comment by JerryYangKai** [comment]
@sanjaylalwani Are you able to access Jupyter Lab from the Azure ML Studio ?

**Comment by sanjaylalwani** [comment]
Yes it works now. Thank you.
