### ISSUE TITLE
cant connect to azure compute instance, this has to be fixed, it's been months. Sending the fix too

### ISSUE THREAD

**Issue by emirks** [microsoft/vscode-tools-for-ai#2481]
Does this occur consistently? Yes
Repro steps:

1. Azure Sign in
2. Connect AzureML compute instance

Action: azureml-remote.commandPalette.computeInstance.connect
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 1.2.0
OS: win32
OS Release: 10.0.22631
Product: Cursor
Product Version: 1.93.1
Language: en

Fix of the problem:
**Steps to solve**

- Step 1: Fix Azure extensions on Cursor
    - Cursor does not come with Microsoft authentication, a builtin extension for vscode
    - I cannot find this extension on the internet
    - To get this extension, grab it from VSCode
    - \AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\microsoft-authentication
    - Copy the above folder to\AppData\Local\Programs\cursor\resources\app\extensions
- Step 2: Access Azure ML via cursor
    - Connecting to azure using a “vscode://” style link won’t work
    - Instead get the Azure Machine learning extension on cursor: [[Azure Machine Learning in Visual Studio Code](https://code.visualstudio.com/docs/datascience/azure-machine-learning)](https://code.visualstudio.com/docs/datascience/azure-machine-learning)
    - Then in command palette do “Azure ML: Sign In”
    - Restart cursor, open the new Azure tab, and you should be able to see all your compute instances and azure stuff
    - Open the extension tab with ctrl shift a, go to the machine learning tab, then right click your compute instance to attempt a connect
- Step 3: Sever installation
    - If you try to connect to ur compute instance, it will fail since the cursor remote server cannot be installed on azure for some reason
    - So we need to manually install it
    - First go to Help > About in cursor and get the version and commit
    - Manual cursor server download: https://cursor.blob.core.windows.net/remote-releases/0.41.1-10e3716b510a5d447c1a07b2edd37a352bbea4d0/vscode-reh-linux-x64.tar.gz
    - In that address, you need to use the version number from the help box along with the same commit. The version/commit must match!
    - Put this on the Compute instance you are interested in (u can upload via jupyter lab or ssh if available)
    - Do `ls ~/.cursor-server/bin/10e3716b510a5d447c1a07b2edd37a352bbea4d0` but use whatever commit you’re on
    - Then do “tar -xzvf filenamhere” with the tar file you downloaded
    - Then copy the contents of the resulting output, should be a folder like `vscode-reh-linux-x64` , basically dump the contents of this folder into the `~/.cursor-server/bin/10e3716b510a5d447c1a07b2edd37a352bbea4d0` folder
    - And that’s it for the manual server install

The problem is that we have to do this fix for every update, which is...

**Comment by nelly-controlrooms** [comment]
Why is this closed? This is still an issue.
Did you ever figure out a more streamlined solution. `~/.cursor-server/bin` gets automatically deleted in my case.
