### ISSUE TITLE
broken link in https://github.com/microsoft/vscode-tools-for-ai/blob/master/docs/getting-started-aml-vscode.md

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/vscode-tools-for-ai#254]
https://github.com/microsoft/vscode-tools-for-ai/blob/master/docs/getting-started-aml-vscode.md

![image](https://user-images.githubusercontent.com/39592018/58450774-ef0de280-8142-11e9-8695-0f009ad021e6.png)

**Comment by greazer** [comment]
These docs were removed from the github repo.
