### ISSUE TITLE
Support Notebook VM's as 1st class. Automate SSH connections for Remote Attach

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#258]
See https://github.com/microsoft/vscode-python/issues/2641.

This was a request by Daniel Schneider to make it easier for AML cluster users to debug their scripts.

From an internal email entitled "PTVSD"
Can vscode establish the tunnel for the user? Meaning, I give the tunneluser@tunnelip:tunnelport in addition to the debugip:debugport in the debug config, and vscode does the ssh tunneluser@tunnelip -p  tunnelport -L randomport:debughost:debugport for me — and the connects to localhost:randomport....

Also see https://github.com/danielsc/azureml-debug-training

Further discussion with Daniel resulted in this functionality desired:
* Have Notebook VM parent node (in addition to Compute)
* Right click to setup for remote VSCode access.
* You can then connect to the host with VSCode Remote from the notebook node.
* Everything else you can do with a compute should be available as well.
We need a full spec for this.

**Comment by greazer** [comment]
I believe this is basically about exposing Azure Notebook VM's as 1st class citizens in our tree view. And then creating menu commands to allow the user to setup remote VS Code connections to them.

**Comment by greazer** [comment]
For first release, we only need to support making the notebook VM's visible and link to the remote session (via launching a browser like we do for pipelines)

**Comment by shsuman** [comment]
Closing this as Notebook VMs has been deprecated and the work item is not longer relevant
