### ISSUE TITLE
Create code snippets for required Azure ML snippets needed in code to submit an experiment

### ISSUE THREAD

**Issue by akashraju4** [microsoft/vscode-tools-for-ai#268]
There is a VS Code Extension called "Tensorflow Snippets" where you can generate python files or Tensorflow operations such as "tf:import" or "tf:conv2d". 

Create similar snippets for Azure ML - e.g. "aml:log", "aml:import', etc. 
![image](https://user-images.githubusercontent.com/28133688/61767216-65703f00-ad98-11e9-9578-d54705b5a000.png)

**Comment by SiddhanthUnnithan** [comment]
Work is already being done in this space (more broadly) to enable AML snippets in VS Code.
