### ISSUE TITLE
Create templates for popular machine learning frameworks

### ISSUE THREAD

**Issue by akashraju4** [microsoft/vscode-tools-for-ai#269]
Similar to vs-code-tools-for-ai, create machine learning code examples for popular frameworks.

Add azure ML snippets for submitting an experiment

OR 

with notebook VM integration, will make it easy for someone creating a ML project and training it using Azure. 

List of ML Frameworks to approach:

![image](https://user-images.githubusercontent.com/28133688/61767526-6786cd80-ad99-11e9-9c20-69ea71bcb608.png)

**Comment by greazer** [comment]
Idea: Bring back start page and point to examples.

**Comment by SiddhanthUnnithan** [comment]
Related to broader snippets/templates work being done.
