### ISSUE TITLE
Syntax Highlighting for comments (particularly SQL) broke

### ISSUE THREAD

**Issue by huisben** [Microsoft/vscode-tools-for-ai#27]
This was a headache to debut but I narrowed it down to this extension. I suddenly noticed all of my syntax highlighting for comments with '--' broke. It would colour as regular text so any keywords inside and any single quotes (also apostrophes) would not end and break the entire document. I removed extensions one by one until I found this was the root cause.

For anyone searching on Google, SQL, highlight, comment, escape, single

**Comment by qfyin** [comment]
Thanks @huisben for reporting this.
We'll fix this very soon.
Please stay tuned.

**Comment by qfyin** [comment]
This is a duplicate of #21
