### ISSUE TITLE
Make AML Extension download page less intimidating

### ISSUE THREAD

**Issue by akashraju4** [microsoft/vscode-tools-for-ai#275]
![image](https://user-images.githubusercontent.com/28133688/61768068-1ed01400-ad9b-11e9-8bb0-e562eb1ca81a.png)

**Comment by greazer** [comment]
@akashraju4 , please add proposed changes.

**Comment by akashraju4** [comment]
![image](https://user-images.githubusercontent.com/28133688/62250209-2eee8180-b3a1-11e9-8009-1909f2fa4256.png)
