### ISSUE TITLE
AutoML integration in VS Code

### ISSUE THREAD

**Issue by akashraju4** [microsoft/vscode-tools-for-ai#282]
To better help data scientists with adapting data for machine learning model inputs, give them the option to use AutoML in a UI similar to the golden path with a free tier. Error handling for data inputs to be in numpy / pandas format. 

![image](https://user-images.githubusercontent.com/28133688/61890610-aa8d9180-aebc-11e9-9fa9-528f640db5b4.png)

**Comment by olufemig** [comment]
would be really useful to have AutoML support in VSCode...
