### ISSUE TITLE
error: Flask Error: Error: spawn .azureml\envs\amlsdk\Scripts\python.exe ENOENT

### ISSUE THREAD

**Issue by ravikumar-singi** [microsoft/vscode-tools-for-ai#284]
Issue Type: <b>Bug</b>

error: Flask Error: Error: spawn c:\Users\ravigi\.azureml\envs\amlsdk\Scripts\python.exe ENOENT
warn: Starting local flask server timed out.
warn: Azure ML extension flask server couldn't be initialized: Error: Timeout of 500ms exceeded
error: Internal extension error: Azure ML extension flask server couldn't be initialized: $Error: Timeout of 500ms exceeded
error: The request did not have a subscription or a valid tenant level resource provider.
warn: Get children failed in AzureMLTreeView, Cannot read property 'forEach' of undefined

Extension version: 0.5.1
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by greazer** [comment]
@ravikumar-singi, We have an existing issue we are in the midst of addressing that is likely the reason for the error you're receiving. Is the python interpreter you have set for VS Code 3.7+? And is it a conda environment? If so, the flask server (which is used to talk to the AzureML service) will not be able to start correctly. 

Until we are able to address it, a workaround is to ensure that a python 3.6 environment is set as your python interpreter before attempting to view the Azure Machine Learning panel.

Hopefully the following will work for you.
1) Uninstall the AzureML extension.
2) Close VS Code.
3) Delete the entire c:\users\[yourusername]\.azureml
4) Start VS Code.
5) Ensure you have a python 3.6 environment selected as you interpreter
6) Install the Azure ML extension again.
7) Open the Azure panel.

The extension should indicate that it is installing runtime dependencies. This will take a few minutes. 

If this is not the error you're experiencing, please follow up with more information!
