### ISSUE TITLE
If the Azure Machine Learning extension is not working at all on Windows... 

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#285]
If you are receiving "Flask" errors when attempting to use the Azure ML extension for the first time, the problem is likely related to having had an Anaconda or Miniconda based Python 3.7 interpreter set as the active python interpreter in VS Code when the extension is first used. This problem only affects Windows users.

We are in the midst of addressing this problem with a large architectural change, but until we are able to address it, a workaround is to ensure that a Python 3.6 environment is set as your python interpreter before using any aspect of the Azure Machine Learning extension for the first time. After it is setup correctly once, you changing your default Python interpreter to 3.7+ will be ok to do.

If you think you are experiencing this problem, please do the following:
1) Uninstall the AzureML extension.
2) Close VS Code.
3) Delete the entire c:\users\\[yourusername]\\.azureml directory
4) Start VS Code.
5) Ensure you have a Python 3.6 environment selected as the default python interpreter. It's preferable that this interpreter is not an Anaconda or Miniconda install, but as long as Python is not 3.7+ it should be ok.
6) Install the Azure ML extension again.
7) Open the Azure panel on the sidebar and interact with the Azure Machine Learning panel.

The extension should indicate that it is installing runtime dependencies. This will take a few minutes. After it's complete, the Azure Machine Learning extension should operate normally, even if you change VS Code's Python interpreter to 3.7+ again.

**Comment by rodneyjoyce** [comment]
I've got this issue but the above steps do not work:

I cannot find a folder called .azureml
c:\users\[yourusername]\.azureml directory

I downgraded my Anaconda Python to 3.6.9 (failed) and then to 3.6.8 and made sure it was selected as the interpreter (I can run code) and then installed the ML extension again. It always throws this error message below:
https://www.screencast.com/t/9N4FoXUpt

Any help appreciated.

**Comment by greazer** [comment]
@rodneyjoyce, please try the latest, version 0.6.2. This version completely removes the dependence on a Flask Python server.

**Comment by rodneyjoyce** [comment]
Thanks, that resolves all issues
