### ISSUE TITLE
Expose notebook VM's through Azure ML explorer

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#291]
Related to #258. At minimum we should expose Notebook VM's as a expandable node in the Azure ML explorer UI. Functionality is on par with Pipelines. Viewing, but no other operations are supported.

**Comment by maxluk** [comment]
Is connecting with VS Remote SSH to that Notebook VM going to be supported?

**Comment by greazer** [comment]
Yes, additional functionality is planned for upcoming releases. Just likely not the first time we expose Notebook VM's through the extension.

**Comment by shsuman** [comment]
Waiting for kaitlin to provide the correct icons for tree View
