### ISSUE TITLE
Add Support for Snapshot Run in Run Experiment in Azure

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#293]
Currently, the extension only supports running experiment through the zip file path, where the entire project directory has to be zipped and uploaded to the server. Although this method has better performance, it imposes a limit of 25 MB on the project directory. There is an another method called snapshot service, where a snapshot of the directory can be uploaded and then the experiment can be run by  providing the snapshotId in the definition file. This is a limit of ~300 MB

**Comment by greazer** [comment]
Note that this was discovered by an outside customer: https://github.com/MicrosoftDocs/azure-docs/issues/41134.
