### ISSUE TITLE
Register existing workspace

### ISSUE THREAD

**Issue by GaryStrange** [microsoft/vscode-tools-for-ai#294]
Hi,

When I try to create a workspace via the VS Code UI I receive the error:

error: Deployment template validation failed: 'The provided value 'northeurope' for the template parameter 'location' at line '1' and column '416' is not valid. The parameter value is not part of the allowed value(s): 'eastus,eastus2,southcentralus,southeastasia,westcentralus,westeurope,westus2'.'.

It's not clear how I can control which region the workspace will be created in. It would be easier if I was able to create the workspace in azure and then register the workspace in VS Code. We have azure policies that prevent new assets from being created unless certain tags are present. So I believe this will also create blocker for me.

**Comment by shsuman** [comment]
The workspace is created in the region of your resource group. 

Any workspace you create in the portal in your subscription is automatically visible in the UI extension, you don't have to register it.

Also, this is a bug and northeurope is a perfectly valid location and we are working to fix it. After the fix, you would be able to create the workspace in northeurope

**Comment by GaryStrange** [comment]
My existing workspaces aren't visible in the UI extension. I have assumed the Azure asset type 'Machine Learning Studio workspace' is the applicable workspace. Could you confirm?

**Comment by shsuman** [comment]
Machine Learning Studio is a completely different product. You need to create an Azure Machine Learning Service Workspace. Here is the link to create an Azure Machine Learning Service Workspace through Azure portal https://ms.portal.azure.com/#create/Microsoft.MachineLearningServices
Here is the link to Azure Machine Learning documentation: 
https://docs.microsoft.com/en-ca/azure/machine-learning/

**Comment by GaryStrange** [comment]
Thanks for the feedback shsuman.

So I created a West Europe RG and tried to create a workspace from VSCode. As expected I received an error from the policy in-place.

error: Resource 'kvbq2sxirtnwmuu' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Resources Tags","id":"/subscriptions/7f767153-63c4-4ea8-97aa-28c5ad38bc43/providers/Microsoft.Authorization/policyAssignments/Resources Tags"},"policyDefinition":{"name":"Resources Tags","id":"/subscriptions/7f767153-63c4-4ea8-97aa-28c5ad38bc43/providers/Microsoft.Authorization/policyDefinitions/Resources Tags"}}]'.

So then I went on to try to create a workspace resource via the portal (in my west europe RG). It's great that I could add custom tags in the creation process. However, the deployment fails with the notification "Workspace deployment error", "Template Error".

**Comment by shsuman** [comment]
We have fixed the bug in our latest patch release 0.6.4. Now, you should be able to create a workspace in all the available Azure ML regions. 

Regarding your policy problem, this is something which is controlled at the subscription level, and I guess can be changed by the owner (you need to contact Azure Subscription help). " Resource 'kvbq2sxirtnwmuu'" refers to one of the dependent resources which is needed while creating workspace, it can be a key vault, application insight, storage account or container registry. I am guessing your subscription does not allow you to create something (probably key vault) in west Europe
