### ISSUE TITLE
Running an experiment locally is broken.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#299]
This may be my fault from the refactoring I did for 0.6.3.

**Comment by shsuman** [comment]
The default Run Configuration object is a pretty large object but we only use the minimalist properties needed in a runconfig to run an Experiment. The Azure ML probably changed the minimum set of properties which is needed for a local run config. Now it also needs the environment.docker property. Although, by default docker is set to false, but it needs it to be there.

Need to have the docker property in local run config to fix this
