### ISSUE TITLE
64-bit support?

### ISSUE THREAD

**Issue by PabloDoval** [Microsoft/vscode-tools-for-ai#3]
Hi all! When trying to install in my x64 instance of VS Code, I get an unsupported version error. I presume - though I am not entirely sure - that it is due to the 64 bit version. If that's the case, a 64-bit build would be appreciated :)

**Comment by chris-lauren** [comment]
Which build of VS Code are you running? VS Code Tools for AI requires VS code version >= 1.16. You may want to upgrade VS Code and try again
