### ISSUE TITLE
Can't find installed ML Workbench

### ISSUE THREAD

**Issue by revodavid** [Microsoft/vscode-tools-for-ai#30]
When running "AI: Open Azure ML Sample Explorer" from the command palette, I get the message "Please install the azure ml workbench to enable azure ml feature of this extension.". Azure ML Workbench is indeed installed.

**Comment by qfyin** [comment]
Hi @revodavid Azure ML workbench was updated after release of vscode tools for ai 0.1.7.
Please update to latest 0.1.8 and this should be solved.
