### ISSUE TITLE
Create spec for data reference set in run config experience.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#303]
We'll need to work through the experience we're trying to enable here.

**Comment by samuel100** [comment]
any update on this? I would like to use a dataset - in the SDK this is done as follows:

src = ScriptRunConfig(source_directory=script_folder, 
                      script='train_diabetes.py', 
                      # to mount the dataset on the remote compute and pass the mounted path as an argument to the training script
                      arguments =[dataset.as_named_input('diabetes').as_mount('tmp/dataset')])


it is not clear how to achieve this in a runconfig file
