### ISSUE TITLE
Make run logs and outputs visible in the extension per run.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#304]
Scenario: User has a failed run and wants to quickly see what's wrong.

**Comment by sevillal** [comment]
Merged into master

Branch: https://msasg.visualstudio.com/OpenMind%20Studio/OpenMind%20Studio%20Team/_git/OpenMindVSCode?version=GBsevillal%2Fissue_304_stream_logs

Commit: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/commit/515ad95d1f889d2fcb2c44e220cdff9f52a2db28?refName=refs%2Fheads%2Fmaster
