### ISSUE TITLE
Cache all resources when list <Resource> is called

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#306]
Even when the user opens the tree view first and then submits an experiment, the quick pick takes time to load, this shouldn't happen as we had already called the list function in the treeview. This should cache the data and present it immediately the second time. We should cache call such resources. Also, it should be kept in mind to refresh the cache immediately whenever a resource is created, deleted etc...

**Comment by greazer** [comment]
Not needed yet.
