### ISSUE TITLE
Experiment run status stops updating after a while

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#318]
After the extension has run for a while, the status of a run stops updating. Even though it's complete in the portal, the extension still has the spinner.

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/5cdb0d100f84751dcd8fd498/c063c493-321f-498c-850b-447c30bc7ec9)

![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/5cdb0d100f84751dcd8fd498/0f5c2f0e-65a4-42d1-af63-db7db22f27d4)

**Comment by shsuman** [comment]
I am not able to understand something here. In the screenshot of the portal, where is Run 45 which is Running in the extension ?
