### ISSUE TITLE
'View in Azure Portal' not working for run

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#319]
When you right click on a run and click on 'View in Azure Portal', the following page opens up:

![Capture.PNG](https://images.zenhubusercontent.com/5c1828cfc50615756d6b3d5a/6b678190-5384-4bfc-869e-3547b523300a)

**Comment by tbombach** [comment]
AML updated the service to point to a new webpage for managing experiments and runs. We updated our extension and fixed this for the 0.6.7 release
