### ISSUE TITLE
Prototype referencing datasets specified in runconfig

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#321]
We are going to start displaying datasets/datastores in the tree. Additionally, we are going to build UI to assist users in selecting a dataset when running an experiment. We want to prototype adding datasets in the runconfig so that they can be referenced in the python script. I believe it should go in the DataReferences section of the run config. Please use this tutorial: https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-train-with-datasets#access-the-input-dataset-in-your-training-script for referencing the dataset after manually adding the dataset information in the runconfig.

I believe Dan had problems referencing the dataset when running a script via the extension. Please see if this works as expected by manually adding the information to runconfig. I think this might be because we don't let users edit everything in the runconfig before it's uploaded to aml service? We may need to allow users to add this section when we show them the runconfig

**Comment by tbombach** [comment]
@sevillal and @shsuman If either of you guys need a next task, please start investigating datasets in the runconfig

**Comment by shsuman** [comment]
The "data" or the "dataReferences" field is used while specifying datasets for a run. I have successfully tried in using the data field, haven't got into the dataReferences field. Also, arguments field need to be exposed in a UI like structure if data field will be used
