### ISSUE TITLE
Consider removing "Deploy Service" command from the context menu of Endpoints node to keep up with the new portal

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#325]

**Comment by SiddhanthUnnithan** [comment]
Follow up with Daniel to better understand why the operation was removed.

**Comment by SiddhanthUnnithan** [comment]
Revisiting this - I don't think we need to be 1:1 with the portal. Removing the "Deploy Service" command forces users to create/register a model before creating an endpoint. I don't know how often this scenario is hit but I think users should still have the flexibility to create endpoints from local models that they don't wish to register with the service.

Even if they could only deploy a model by first registering it, I think its ok for us to have a starting point from the "Endpoints" node. This is intuitive and follows our model of multiple starting points for the same operation (e.g. running an experiment).
