### ISSUE TITLE
Refresh compute environments

### ISSUE THREAD

**Issue by omartin2010** [Microsoft/vscode-tools-for-ai#33]
Hi, I would suggest that we should be able to refresh the list of compute targets without restarting code.exe. For instance, right clicking on "AzureML - Run Configuration" could show an option "Refresh" so information is re-read from the project folder (in the case that you rename the compute target for example, or other changes that aren't necessarily launched from this menu but by another application or by the user browsing to the compute and runconfig files. Same for Batch AI, if I create a cluster from the portal, it would be nice to see the possibility to refresh the menu.

**Comment by qfyin** [comment]
Thanks @omartin2010 for the good suggestion. We'll consider adding this in future version.

**Comment by greazer** [comment]
This is possible with the latest extension.
