### ISSUE TITLE
Investigate whether single string of arguments can be passed directly to AML

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#330]

**Comment by shsuman** [comment]
A single string of argument doesn't work. I tried to ruin an experiment but got this error:
The arguments were provided as follows: arguments: ["--data-folder DatasetConsumptionConfig:mnist_opendataset --regularization 0.5"]
train.py: error: unrecognized arguments: --data-folder DatasetConsumptionConfig:mnist_opendataset --regularization 0.5

**Comment by SiddhanthUnnithan** [comment]
Follow up with run config channel to figure out why we need an array of arguments and how positional arguments work.

**Comment by shsuman** [comment]
From William Baumann:
    It's the vector form of argv.
    So ["--key", "value", "--flag"]
    That removes the need to worry about shell escaping.

**Comment by greazer** [comment]
Yes, for sure it's a vector form of argv, but can I get an example as to the problems we run into if we try and support just a single string?

**Comment by shsuman** [comment]
usage: train.py [-h] [--regularization REG]
train.py: error: unrecognized arguments: --regularization 0.6

This is the error when I use: "arguments": [
        "--regularization 0.6"
    ],

and the experiment runs successfully with 
"arguments": [
        "--regularization",
        "0.6"
    ],

**Comment by shsuman** [comment]
![Capture](https://user-images.githubusercontent.com/44413557/72570081-bf961c80-3870-11ea-8fa0-17dd63168f4b.PNG)

**Comment by shsuman** [comment]
Closing this as I think its settled now that we cannot pass single string, we need to pass an array
