### ISSUE TITLE
Only show Aml Computes in the path of creating run configuration, also remove create run configuration from the context menu of other types of compute 

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#337]

**Comment by SiddhanthUnnithan** [comment]
@SiddhanthUnnithan look into telemetry to see how often users are creating run configurations with non-AML computes

**Comment by shsuman** [comment]
https://msdata.visualstudio.com/Vienna/_queries/edit/587205 this is the bug that is tracked on the aml side, once its fixed, we won't need the workaround anymore
