### ISSUE TITLE
Investigate sending telemetry events with properties from extension.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#346]
We want to send telemetry events with properties from the extension and be able to query these records via Kusto. Today there's no indication of key-value properties that we specify in the code, thus limiting the degree to which we can analyze telemetry events. The catalog has been updated correctly to match GDPR-requirements.

We can begin by specifying Exception properties when the user hits error events. This can be tested with known-error situations (e.g. removing a compute which returns a 404 response). From here we can catalog all known exceptions (future issue) and create a dashboard around exception frequency for the extension.

**Comment by SiddhanthUnnithan** [comment]
Follow up to check with Graham about how exception/error cataloging is being done.

**Comment by tbombach** [comment]
Follow-up will be to go to office hours to diagnose why properties aren't showing up

**Comment by SiddhanthUnnithan** [comment]
We are able to see Properties in telemetry. In Kusto this can be accessed via record['Properties']. The next step is to make sure that events are logging appropriate properties.
