### ISSUE TITLE
Investigate disabling the "Save" prompt when cancelling via a codelens

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#347]
After creating an experiment from scratch, I edited the final JSON and proceeded to cancel the submission via the codelens. Upon cancelling I was prompted with a dialog asking if I wanted to save my changes to the temporary file. This was a confusing experience as I wasn't told where the file was saved and whether I could use it in a future workflow.

We shouldn't store artifacts from experiment submission workflow if these artifacts can't be used in the future. We need to investigate why the save prompt is appearing and how we might disable it for temporary files.

**Comment by SiddhanthUnnithan** [comment]
VS Code custom editor APIs might be able to help with solving this problem (and others). @tbombach  to follow up.

**Comment by tbombach** [comment]
Assigning to Sergio since he has a fix

**Comment by sevillal** [comment]
Merged to master https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/commit/ddcd4257fab1b1be8a4768c7a640b028c4590625/
