### ISSUE TITLE
Remove PII information from telemetry events (2 in particular)

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#349]
Both of these events need the property values adjusted. The first can be adjusted to not include the path. Instead we should just send the numeric error code as the property.  

For the second event, just remove the property altogether.

Name: vscode-ai/azureml/submit  Property:error   SampleValue: <class 'azureml.exceptions._azureml_exception.ExperimentExecutionException'>: c:\Users\jimg\OneDrive\Source\mnist-shane\mnist\train.py script path doesn't exist. The script should be inside the project folder
 
and 
 
Name: vscode-ai/azureml/service/edit   Property:scoringuri    SampleValue: http://52.163.203.74:80/api/v1/service/car-recommend-aks/score

**Comment by SiddhanthUnnithan** [comment]
Can we find a way to ensure that we don't do this accidentally in the future? What information can we send back that would be useful that isn't PII?

**Comment by tbombach** [comment]
The first pII example was fixed in September. I have verified that it no longer appears in the event. A fix for the second example is in PR right now
