### ISSUE TITLE
realtime log watch

### ISSUE THREAD

**Issue by shikbupt** [Microsoft/vscode-tools-for-ai#35]
I am using VS Code to submit jobs to a vm, but the log/stdout only has preview, there is no idea to  watch the realtime log. I think it is a good function.

**Comment by linmajia** [comment]
@shikbupt , thank you very much for the feedback.

This is a good idea to show realtime stdout/stderr. We will add it to our backlog.

**Comment by greazer** [comment]
This extension has been reconfigured to target scenarios only dealing with Azure Machine Learning.
