### ISSUE TITLE
Auto-refresh nodes in extension tree

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#351]
Where appropriate, can we auto-refresh nodes so that the user doesn't need to hit _Refresh_ to get an updated status. Examples of nodes that change state and require explicit refresh actions include running experiments and logs.

**Comment by shsuman** [comment]
Closing this as we already have auto refresh feature in our extension. Open issues for particular scenarios which does not supports auto refresh or if it is broken
