### ISSUE TITLE
Spec for renaming and restructuring experiment output logs

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#352]
Investigate how to structure and rename output logs before they're presented to the user.

Document what each log represents / contains and come up with appropriate structure + naming scheme so that users are clear about what they should stream and/or download.

E.g. 70_drive_log.txt is ambiguous, but this is the log file that users should stream to ensure that their experiment is running smoothly (not preparation).

[Stretch] Automatically stream output logs during relevant parts of the experiment run. For example, right after the user submits the experiment and their compute/environment is being prepared we want to stream the preparation-related logs.

**Comment by SiddhanthUnnithan** [comment]
Suggestion for the service team to think about. Follow up with Daniel S.

**Comment by sevillal** [comment]
@SiddhanthUnnithan I recently saw portal updated the way it shows Logs and Outputs, this can be helpful on our decision:

![image](https://user-images.githubusercontent.com/56176070/73797551-3c783000-4765-11ea-808e-c9e223e0cb13.png)
