### ISSUE TITLE
Investigate average queue time for multiple experiments being run on a single compute

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#354]
What is the average run_queued to run_start durations for the case in which multiple experiments are running on a single machine?

Is it possible for us to identify the above scenario (from telemetry) and do we have events in place that correspond to run queue and run start times?

How does this time compare to the average time it takes for a run to start (from the queue) when it is the only run on a compute? Is it possible from an engineering standpoint to bring these two averages close to one another? What is the work involved in making that happening?

**Comment by SiddhanthUnnithan** [comment]
Try and replicate this ourselves and log how long the experiments are taking. How is it different if we run a single experiment on a single compute?

We can follow up with Daniel S. or the Execution Service team.

**Comment by shsuman** [comment]
So, I ran 4 experiments back to back on a single compute and it all ran quite smoothly, within half an hour all of them completed. I did not see them queued longer than usual, also 3 experiments were running on the compute at the same time.

**Comment by shsuman** [comment]
Closing this as we didn't find any conclusive evidence that multiple experiments are taking longer than usual
