### ISSUE TITLE
vmSize of all newly created computes is shown as "Standard_NC6" irrespective of what users select

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#358]
Create a new AML Compute of any size (say F family), and then View the properties of the compute from the tree view. The vmSize is displayed as Standard_NC6

If this is indeed a bug on our side, we need to fix it immediately because NC computes are GPU enabled compute which I am guessing is costly.

**Comment by shsuman** [comment]
Also, consider showing a json with all editable properties of the compute (e.g. scaleSettings ) before submission

**Comment by SiddhanthUnnithan** [comment]
Make a separate issue for editable properties

**Comment by shsuman** [comment]
Merged PR https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1472459
