### ISSUE TITLE
Update API versions to latest in all Azure ML Requests

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#359]
The latest api-versions can be fetched from here
https://docs.microsoft.com/en-us/rest/api/azureml/workspacesandcomputes/machinelearningcompute/delete

Also, make sure all requests use api-version string in the form of a constant which is mentioned in azureMLWebRequests.ts rather than using floating values

**Comment by SiddhanthUnnithan** [comment]
Evaluate cost of updating versions

**Comment by shsuman** [comment]
No longer valid as we are moving to V2 APIs
