### ISSUE TITLE
Support Attach for non-VM Compute 

### ISSUE THREAD

**Issue by jdmsrdot4774** [microsoft/vscode-tools-for-ai#367]
Error Received: "error: Internal extension error: Unknown compute type encountered: ComputeInstance" 

Error is analogous to Issue #140 , #152 

It appeared in #152 that you needed a spec.  If need be, please provide instructions so I can retrieve that for you.

**Comment by shsuman** [comment]
What type of compute are you trying to attach ? Can you please provide some details as to repro the error ?

**Comment by JackB1ack** [comment]
I got the same error message after creating Compute Instance (previously Notebook VM) through the portal. And my newly created Instance is not shown in extension's resource tree.

**Comment by shsuman** [comment]
@JackB1ack We have taken note of this problem and will be fixing it soon

**Comment by shsuman** [comment]
#390  to track this
