### ISSUE TITLE
Improve experience for creating a new run configuration from the compute node in tree

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#368]
Newly create computes may not have run configurations tied to them (until a training run is submitted). The user is presented with a "Right-click to create a run configuration" option, however right clicking that _node_ only displays a "Refresh" option.

If we're going to show "Right-click..." users should be allowed to correctly follow the command. It is not intuitive that the "Right-click..." command is referring to right-clicking the compute node.

**Comment by tbombach** [comment]
We discussed using view actions (https://code.visualstudio.com/api/extension-guides/tree-view#view-actions) which would allow us to add a plus icon next to the compute node.

**Comment by tbombach** [comment]
Duplicate of https://github.com/microsoft/vscode-tools-for-ai/issues/434
