### ISSUE TITLE
Change the message (may be add a plus sign at the beginning) which is displayed under the subscription node when there is no workspace in a subscription

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#369]
![Capture.PNG](https://images.zenhubusercontent.com/5c1828cfc50615756d6b3d5a/b7f28ecb-302c-4e73-9e3b-65fbff76e90c)

**Comment by tbombach** [comment]
Similar to the run config in compute nodes, we would like to build off the "filter" button that appears next to the subscription node. We would add a plus to allow the user to create a workspace.

**Comment by tbombach** [comment]
From Sergio: https://code.visualstudio.com/api/extension-guides/tree-view#view-actions
