### ISSUE TITLE
Show something like this in the Tree Explorer when Azure is not signed in

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#370]
This is what the cosmos DB and the Azure storage extension show 

![Capture.PNG](https://images.zenhubusercontent.com/5c1828cfc50615756d6b3d5a/ece2ffe6-10af-476d-96de-4ffbaaba87e2)

**Comment by sevillal** [comment]
Merged to master, should be available 0.6.23
