### ISSUE TITLE
How to configure remote linux machine environment

### ISSUE THREAD

**Issue by JingLiu95** [Microsoft/vscode-tools-for-ai#39]
After submitting a job, the state of my job is completedfail. 
The log of stderr is:
Traceback (most recent call last):
  File "mnist/main.py", line 3, in <module>
    import torch
ImportError: No module named torch

It seems that the environment in the remote Linux machine is not configured.

**Comment by linmajia** [comment]
@JingLiu95 , thank you very much for the feedback.

Have you set up the deep learning environment on your remote Linux machine? You may use our [one-click installer](https://github.com/Microsoft/vs-tools-for-ai/blob/master/docs/prepare-localmachine.md#one-click-installer) to install the required packages. If you want to understand more details, please read the document [Preparing development environment](https://github.com/Microsoft/vs-tools-for-ai/blob/master/docs/prepare-localmachine.md).

After the above step, you need to update ~/.bashrc to [enable remote job submission via non-interactive Bash session](https://github.com/Microsoft/vs-tools-for-ai/blob/master/docs/tensorflow-vm.md#update-bashrc-to-enable-remote-job-submission-via-non-interactive-bash-session):
- Login to your remote Linux machine using a tool like Putty or similar.
- Execute this command in a terminal: " echo -e ". /etc/profile\n$(cat ~/.bashrc)" > ~/.bashrc "

Thanks.

**Comment by elyase** [comment]
is there an example with some details on how to config VSCode and the remote machine to run docker containers?

**Comment by elyase** [comment]
@linmajia thanks for your reply but it still not clear to me how VSCode knows the IP of the address it has to run the job on or what steps I should do on the remote machine in order to prepare it to accept jobs.

**Comment by linmajia** [comment]
@elyase , here are the steps:
1. Configure your remote machine to install AI/DL frameworks and enable SSH. Please refer to the above [comment](https://github.com/Microsoft/vscode-tools-for-ai/issues/39#issuecomment-408342268).
2. Add your remote machine to Tools for AI by right clicking the "Remote Linux -SSH Endpoints" node in the AI EXPLORER. Then input the IP, user name and password (or the private key file path if you use SSH Key-Based Authentication).
3. Submit your project as a job to your remote machine. Please refer to this [document](https://github.com/Microsoft/vscode-tools-for-ai/blob/master/docs/quickstart-01-submitting-training-jobs.md).

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning.  In the [archive](/archive) folder, you can find the [0.3.1 vsix installer](/archive/ms-toolsai.vscode-ai-0.3.1.vsix) that includes  previous features before this redesign, along with corresponding docs.
