### ISSUE TITLE
LinuxVM Job List: Error - ssh failed, exit code: 123

### ISSUE THREAD

**Issue by linmajia** [Microsoft/vscode-tools-for-ai#40]
*From @fucknamel  on Auguest 14, 2018*

It shows "Error - ssh failed, exit code: 123" after I successfully submited my job. However, I can ssh my VM on my terminal. And it shows "exit code: 127" in the same situation sometimes. 

*Copied from original issue: https://github.com/Microsoft/vs-tools-for-ai/issues/27*

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning.  In the [archive](/archive) folder, you can find the [0.3.1 vsix installer](/archive/ms-toolsai.vscode-ai-0.3.1.vsix) that includes  previous features before this redesign, along with corresponding docs.
