### ISSUE TITLE
Command for cancelling an experiment run

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#400]

**Comment by shsuman** [comment]
Here's the api for cancelling a run:
execution/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}      /providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/experiments/{experimentName}runId/{runId}/cancel

**Comment by sevillal** [comment]
Merged as part of: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1839687
