### ISSUE TITLE
CodeLens disappears after switching to another file

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#405]
Found in bug bash: 
* The codelens disappears from a file if I switch from that file to another one (e.g. my training script). We want the codelens to stay so that the user can reference their source code while still being able to execute experiment steps.

**CodeLens visible**

![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/475769ea-e0b8-4421-90ea-a4d5755018f9)

**CodeLens disappers after going to train.py and coming back**

![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/498f5ad6-f183-4a25-901c-62b721fa8301)

**Comment by shsuman** [comment]
It seems like after switching to another file, the json file with codelens is being deleted from the memory

**Comment by shsuman** [comment]
After hitting multiple dead ends, its conclusive that its not possible in the current scenario, there's a trade off between not deleting the file if the user loses focus and the process doesn't terminate for a few minutes if the user closes the json directly

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1585744
