### ISSUE TITLE
slow auto complete for tensorflow in python

### ISSUE THREAD

**Issue by peanhuang** [Microsoft/vscode-tools-for-ai#41]
eg:
when typing tf dot, the auto complete window popups after 4-5 sec  

my os is window 10 and vscode version is  1.26.0
the extension version is 0.1.9

**Comment by linmajia** [comment]
@peanhuang , thank you very much for the feedback.

The auto-completion is provided by the [Python extension for VS Code](https://github.com/Microsoft/vscode-python). You may open an issue on its repos.

Thanks.
