### ISSUE TITLE
Change 'Right-click to create run configuration.." to 'Click to create run configuration'.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#434]
The current behaviour for the 'Right-click...' node is a context menu with a 'Refresh' option. That process isn't obvious so we want to change that to 'Click to create run configuration'.

The desired behaviour:
User clicks on the node.
System triggers the run configuration creation workflow.

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1573222
