### ISSUE TITLE
Improve file selector QuickPick 

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#435]
During QP  we found that users struggle understanding the QuickPick for file selection:

1. Select train script
2. Select conda yml file
3. Select requirements.txt file

Possible options:
1. If possible add a "Browse" button in the QuickPick. This will open the file browser.
2. List the files under the current active directory (i.e. for training script list all the *.py files)

**Comment by tbombach** [comment]
To start, we'd want to implement a "Browse" button that opens the file browser (which Enter does today). If that doesn't solve discoverability issues, then we'll investigate a larger solution.

**Comment by shsuman** [comment]
Closing the non relevant and old V1 issues.
