### ISSUE TITLE
Use QuickPickItem.details to show more info about the environment creation methods

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#437]
During QP we found the users struggling with the methods to create environments, one way to provide more information would be to add details to the quick pick items.

**Proposal**:
![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/c2e52691-27c9-4539-86dd-4833054b4795)

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1767433
