### ISSUE TITLE
Environment creation flow shows file not found when entering name of a file in the current active directory

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#438]
Seems like Environment Creation flow is not considering the project active folder as the basePath for the text introduced when selecting either conda.yml or requirements.txt.

**Steps to reproduce:**
- Project directory has env.yml
![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/aa162d1d-9186-4087-a105-3fdd5f9d5503)

- Start flow to create environment

- Give any name to the environment

- Select "Conda dependencies file"
![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/3adc55a5-c40a-4ca8-9521-aed01f7eb7fd)

- Type "env.yml" and hit enter
![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/33afa036-36f0-4a22-a783-eb2e054a2f0d)

- Error shown
![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/6646ec76-92b6-4180-85f7-5b6213ed1f99)

**Comment by tbombach** [comment]
Fix will be to prepend the active directory path if the user types a relative path. If it's an absolute path, then we will just use it as-is

**Comment by sevillal** [comment]
Merged to master
