### ISSUE TITLE
Connect to AzureML attached compute as Jupyter server from VSCode

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/vscode-tools-for-ai#441]
I would love to be able to connect my local VSCode to Jupyter on Azure ML Attached Compute (new Notebook VM in Azure ML), but currently that is not possible, seems to be due to security on the attached compute side, but that could be solved when integrating that through the extention and using AAD auth through that (I think).

**Comment by SiddhanthUnnithan** [comment]
Hi @eavanvalkenburg. Thanks for bringing this to our attention! I just want to clarify - by Attached Compute do you mean Compute Instance (as this is what Notebook VMs were renamed to)?

**Comment by eavanvalkenburg** [comment]
Indeed the Compute Instances that run Jupyter and JupyterLab, would be amazing to be able to connect to that instance from VSCode locally!

**Comment by SiddhanthUnnithan** [comment]
Hi @eavanvalkenburg! Circling back on this - we shipped this capability in September.

https://techcommunity.microsoft.com/t5/azure-ai/power-your-vs-code-notebooks-with-azml-compute-instances/ba-p/1629630

Would love if you could give it a try and provide some feedback!
