### ISSUE TITLE
Escape doesn't work perfectly in Create Workspace workspace

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#447]
Here's the repro: 

Create a new workspace
Enter the workspace name and press enter when prompted for a name
Select Subscription if prompted for subscription
Select Create New Resource Group when prompted for Resource Group
When prompted for resource group's name press Esc

The SKU quickpick is still presented and if a SKU is selected, nothing happens

**Comment by sevillal** [comment]
Merged to "data" branch.
