### ISSUE TITLE
Submitting experiment through runconfig throws error with a particular workflow

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#448]
Repro Steps:

Create a Run Configuration
When prompted to select a environment, select an existing curated Azure ML Environment
In the final JSON, edit the environment section of the Run Configuration
Save and Continue

Now, submit the experiment using this run config. It fails for obvious reasons

Here's the error:
"Environment name can not start with the prefix AzureML. To alter a curated environment first create a copy of it."

**Comment by tbombach** [comment]
Solution will be to remove the name property from the environment section. This will cause AzureML to create an auto environment and avoid conflicts with the curated environments.

**Comment by sevillal** [comment]
Merged to master
