### ISSUE TITLE
ipynb can't be show on vscode

### ISSUE THREAD

**Issue by frankuo** [Microsoft/vscode-tools-for-ai#45]
Hi, I want to open ipynb file in Jupyter server but show nothing on vscode.
Is there anything that I should do? My host OS is Win10.

![jupyter_show_fail](https://user-images.githubusercontent.com/1409167/44654427-39332d80-aa24-11e8-9db8-936c67bbfbc8.png)

**Comment by linmajia** [comment]
@frankuo , thank you very much for the feedback.

Would you please open the Task Manger and check whether a jupyter-notebook.exe process is created?

**Comment by Doongka** [comment]
I have encountered the same problem.  I've checked and can confirm that a jupyter-notebook.exe process has been created.

**Comment by linmajia** [comment]
@frankuo and @Doongka , please help try the following things:
1. Launch jupyter-notebook.exe manually in a terminal to see if it works and you can view notebooks:
```cmd
"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Scripts\jupyter-notebook.exe" --notebook-dir="your notebook dir"
```
Please change the path of "jupyter-notebook.exe" if it is installed in another folder. The above command will start the Jupyter server and open a web browser instance to connect.
2. Then, please verify whether the file "%USERPROFILE%\\.jupyter\jupyter_notebook_config.json" exists and the content is:
```json
{
    "NotebookApp": {
        "tornado_settings": {
            "headers": {
                "Content-Security-Policy": "frame-ancestors  file://* "
            }
        }
    }
}
```

Thanks.

**Comment by linmajia** [comment]
@frankuo and @Doongka , does this issue still exist?

Thanks.

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning. The Python Extension for VSCode now supports the ability to import, modify, and export jupyter notebooks.
