### ISSUE TITLE
Automate cleaning deployments in "amlextensiontestrg" resource group to keep pipeline running 

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#450]
There is a threshold of 800 deployments per resource group that once reached prevents the creation of new resources. 

Currently we are hitting it and SmokeTest is failing.

Workaround: Manually delete some deployments at https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/b856ff87-00d1-4205-af56-3af5435ae401/resourceGroups/amlextensiontestrg/deployments

**Comment by tbombach** [comment]
Investigate whether this should be done as part of test cleanup or an automated script that runs periodically.

**Comment by sevillal** [comment]
Merged to master
