### ISSUE TITLE
Notebooks should open by default on Jupyter server

### ISSUE THREAD

**Issue by jmew** [Microsoft/vscode-tools-for-ai#48]
When opening a .ipynb file in VS Code, it should by default open in the Jupyter server view, rather than opening it as a raw text file. Since 100% of users that want to open/interact with a .ipynb file, want to do so in the Notebook environment.

**Comment by jmew** [comment]
@linmajia Thanks for the reply!

My only concern is that the context-menu access to open a .ipynb file is not intuitive or visible to the average user. The only way they would know to go through the context menu is by reading up on documentation. As well, i see no use case at all for a user wanting to actually open a .ipynb file in its raw text format.

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning. The Python Extension for VSCode now supports the ability to import, modify, and export jupyter notebooks.
