### ISSUE TITLE
Telemetry not logging Errors information

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#485]
Not sure if this is expected but the Error instances are not logged in telemetry.

As part of some telemetry events we pass either the resource object created or Error in case of any.

**Example**:
const ws: IWorkspace | Error = await withProgress(...dataprovider.create());
sendTelemetry('workspace/add', ws);

function sendTelemetry(event, props) {
    const cleanProps: object = cloneDeep(props); 
}

Lodash cloneDeep returns an empty object on Error instances.

**Comment by shsuman** [comment]
From lodash dcoumentation 

Note: This method is loosely based on the structured clone algorithm and supports cloning arrays, array buffers, booleans, date objects, maps, numbers, Object objects, regexes, sets, strings, symbols, and typed arrays. The own enumerable properties of arguments objects are cloned as plain objects. An empty object is returned for uncloneable values such as error objects, functions, DOM nodes, and WeakMaps.

**Comment by shsuman** [comment]
Merged PR https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1612866
