### ISSUE TITLE
While selecting many models while deploying a service, account for the case when user selects a Add new Model and cancels the process in between

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#486]
If we deploy a service, we get a quickpick where we can select many models, now if we select say n existing models as well as the create new model option as well, we are directed to the create model workflow, now if the user presses Esc during this process, it needs to be handled

**Comment by SiddhanthUnnithan** [comment]
Investigate whether this causes a failure when deploying an endpoint.

**Comment by shsuman** [comment]
Add new Option removed with the below mentioned PR

Merged PR: 
https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1633222
