### ISSUE TITLE
April 2020 Telemetry Improvements

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#487]
Instrument telemetry to track when a user starts a certain operation (e.g. run experiment) and chain all subsequent steps. 

Return chain_id for each event in telemetry so that we can calculate start_event (first event in the chain by time) and end_event (last event in the chain) to see where users are dropping off.

This will **significantly** help with cohort and duration analysis as we will be able to see how often users of a cohort are dropping-off during a workflow, where these users are dropping off, and how much time (on average) users are spending for each workflow.

**Comment by shsuman** [comment]
Both issues in this epic merged for April release
