### ISSUE TITLE
Generate a unique id each time a user starts the experiment run flow and log it as a property for each step they complete

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#489]
We want to be able to track how far a user gets when they start the "run an experiment" flow. We want to distinguish different times when the user starts the flow by generating a unique id when they start the flow, then logging that id as a property for telemetry events as the user completes each step in the flow (e.g. selecting environment, selecting compute, etc).

**Comment by shsuman** [comment]
Merged PR https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1578575
