### ISSUE TITLE
Notebook VMs not showing in navigation view

### ISSUE THREAD

**Issue by derdanh** [microsoft/vscode-tools-for-ai#490]
I was wondering if it's been noted that the Notebooks available and created and saved in the ml.azure.com Service do not show up in the navigation view in the VS code extension.

![image](https://user-images.githubusercontent.com/49188262/77640537-d8027180-6f5a-11ea-8d9a-e714fffb5e94.png)

![image](https://user-images.githubusercontent.com/49188262/77640770-40515300-6f5b-11ea-9d36-87841e48b903.png)

Experiments, environments... all show up - is this intended behaviour? Where can I sync my ML notebooks?

**Comment by shsuman** [comment]
Related to #456.

**Comment by SiddhanthUnnithan** [comment]
Hi @derdanh thanks for bringing this to our attention. Right now there's a slight discrepancy between Compute Instances created in the Studio and Notebook VMs in the extension. The Notebook VM concept you see in the extension is actually the compute instance on which your notebook would run in. We're currently working to design and implement support for viewing Notebooks in the extension as well as running / opening them against a compute instance.

Sorry for the confusion!

**Comment by SiddhanthUnnithan** [comment]
Closing this as the compute type is now unified to compute instances. The larger issue is a way for users to access their Notebook files in the extension - this should be solved with the remote work (either full experience or sandbox).
