### ISSUE TITLE
Need to update our Run Configuration Schema

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#495]
The current schema does not contain data section which we use for injecting datasets information in the run configuration

Adi Yadav should be able to help us with it

**Comment by tbombach** [comment]
Updated link: https://github.com/microsoft/MLOps/blob/master/infra-as-code/runconfigschema.json

**Comment by SiddhanthUnnithan** [comment]
Consider automating updating the schema (as the AML team updates it).

**Comment by shsuman** [comment]
There is no difference between our schema and the schema in the above repo except a reference to a schema for the schema.

**Comment by shsuman** [comment]
Mailed Adi Yadav and William Baumann regarding this

**Comment by shsuman** [comment]
Merged PR https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1573781
