### ISSUE TITLE
Add Configuration doesn't work when az configure has output set to table

### ISSUE THREAD

**Issue by ezwiefel** [Microsoft/vscode-tools-for-ai#5]
I typically leave my ```az configure``` settings set to ```table```, but I wasn't able to add configuration in VS Code.

When I switched to ```jsonc``` it worked.

**Comment by visionalsky** [comment]
Thank you for reporting this ezwiefel. Yes, our tool use the json format parse the configuration. We will investigate how to enable table output support. I have opened working item for this.

**Comment by ezwiefel** [comment]
In your computetarget call, could you add the output switch? (Not sure how you’re hitting the compute target list, but presumably you’d have access to the same arguments that the cli uses)

I know the cli command would be: ```az ml computetarget list -o json```

**Comment by visionalsky** [comment]
Yes, we are just investigating and are going to do so. I think it will be shipped in our next push. Will update status once we finish it. Thank you again!

**Comment by qfyin** [comment]
Fixed in 0.1.6
