### ISSUE TITLE
Log subscription information on subscription/getchildren and workspace/getchildren events

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#502]
Subscription IDs have been deemed OII - organizationally identifying information. We can store subscription IDs so long as they are in clear text.

From Day 1 retention analysis we see a large % of users invoke the getchildren event for both subscriptions and workspaces. If we can see how many of those users **only** invoke these commands and what subscriptions they belong to then we can work with the AML team to reach out to them (without explicitly stating that we're tracking their subscriptions). We can answer questions such as "What % of AML users are invoking passive view-only commands with the extension, but otherwise have heavy AML usage?".

**Comment by SiddhanthUnnithan** [comment]
Also log how many expanded subscriptions have > 0 AML workspaces.

**Comment by tbombach** [comment]
After talking with Sid, we agreed that adding a new telemetry event is acceptable (we don't need to modify `getChildren`). This means that we don't need to change the infrastructure in `AzureMLTreeDataProvider`, instead we can just log a new event in `AzureMLSubscriptionTreeNode.getChildren`

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1573855
