### ISSUE TITLE
Investigate adding a filter inline with the workspace node for users to filter workspaces.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#507]
Mimic the behaviour of the subscription node and allow users to apply a filter to their workspaces.

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/48e7e0fb-cfe0-405a-877e-347f7d213561)

This was an ask from the AML team - they expect most of the users to only focus on one subscription and one workspace at the same time.

We can think about adding a toolbar-based filter for mutli-dimensional filtering (subscriptions and workspaces in sequence).

**Comment by SiddhanthUnnithan** [comment]
Add a description for the experience with images.

**Comment by sevillal** [comment]
Solution merged to v2_tooling branch https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2094742

**Comment by sevillal** [comment]
Merged to master, available 0.6.21
