### ISSUE TITLE
Remove the intermediate prompt when opening a Run in the AML Portal

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#511]
Other Azure extensions (VM, Storage) provide a single-click way for the user to go from VS Code to the Portal. We don't need the intermediate step that prompts the user whether they'd like to go to the Browser.

**Comment by SiddhanthUnnithan** [comment]
Investigate whether this behaviour works for other Azure extensions when using Remote SSH.

**Comment by tbombach** [comment]
Limitation of the VS code API for opening an external link
