### ISSUE TITLE
Add "Run Last" and "Resubmit Run" context menu options to the Experiment and Run nodes, respectively.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#514]
Give users a way to re-run their most recent experiment through a context menu option for the **specific** Experiment node.

In a similar way, give users a way to re submit an experiment run through a context menu option for the Run node.

I would imagine that both operations will translate to "run the last configuration of Run N" where N is the most recent run for the "Run Last" option and N is the specific run for the "Resubmit Run" option.

**Comment by shsuman** [comment]
Closing the non relevant and old V1 issues.
