### ISSUE TITLE
Investigate adding better logging of "steps" when assets are being created.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#515]
Other Azure extensions do a good job of showing what is happening when assets are being created. For example, when I create a new VM through the Azure VM extension I'm told the exact set of steps that the extension is taking to create the VM.

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/d93d7c6b-a9a4-4bc8-9adb-392d7b49a0a7)

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/d43e4cf1-ab3d-4f53-9962-dbacbdc9e637)

Some of these steps are "defaults" without any final confirmation of what the extension has defaulted. We don't fully agree with this approach which is why we have the final JSON for users to make changes to if they wish.

The first question to answer re: this bug is **What information do we get from the AML service when we execute <asset create> commands?**

**Comment by SiddhanthUnnithan** [comment]
Investigate what information we get back from the AML service. Once we know what is not returned, we can talk to the AML team about making changes.

**Comment by shsuman** [comment]
Closing the non relevant and old V1 issues.
