### ISSUE TITLE
Run experiment: Streamlining the 'create workspace' workflow for new users.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#516]
Currently, the "Create Workspace" command involves the following steps:

1. Input name
2. Choose subscription
3. Choose resource group [separate branch - name, region]
4. Workspace SKU

Workspace creation is the first step for many new users to AML. Only 39.8% of users successfully create workspaces. We can't measure drop-off today, starting from the workspace create event, but we can use a proxy for finding drop-off when the experiment ID telemetry is in product.

Streamlining the workspace creation process brings new users to the point of seeing and interacting with AML assets. The extension provides no value for users with no workspace.

We can streamline the workspace creation process by limiting it to the following steps:
1. Input name.
2. Choose subscription if num_subscriptions > 0.

The system automatically creates a new resource group for the user, defaulting the name and region (investigate how other extensions default region). A Basic SKU is automatically given to the workspace. We can investigate ways for users to "upgrade" their workspace SKU in the future (e.g. context menu option).

The selection criterion for running this experiment is:
1. A new user to the AML extension with no previous workspaces. If this population is too small, then we can loosen the criterion to users creating a workspace for a subscription with no workspaces. If the previous criterion is still too tight, we can loosen it to a % of users creating a workspace.

We want to measure:
1. How many users then proceed to interacting with and creating AML assets. What level of interaction do these users employ?
2. How many of these users churn from the extension?
3. How many of these users delete the workspace that we've streamlined for them.

**Comment by shsuman** [comment]
Closing the non relevant and old V1 issues.
