### ISSUE TITLE
Cannot open the first startup page. I was only shown once.

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/vscode-tools-for-ai#52]
When I've installed this extension, I was shown some page that had a link to "tun a script to set up your environment and install tools".
Unfortunately, I've restarted VS code after seeing that page. Now I cannot get to that page again.
It's not the "AI: Open Tools for AI start Page" - it's different. It also does not have the link to the environment setup script.
I've tried reinstalling the extension, but that page was never shown again.

Expected behavior: There is a way to view that first startup page again.

P.S. Maybe you should just merge it to the AI Tools Start Page.

**Comment by linmajia** [comment]
@Ark-kun , thank you very much for the feedback.

We have commands to show these pages. Please open the Command Palette, enter "AI: Open" prefix and then you will see these commands.

Thanks.

![image](https://user-images.githubusercontent.com/9329359/45093555-5023ff00-b14b-11e8-9a4c-9165cffeb485.png)

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning.  In the [archive](/archive) folder, you can find the [0.3.1 vsix installer](/archive/ms-toolsai.vscode-ai-0.3.1.vsix) that includes  previous features before this redesign, along with corresponding docs.
