### ISSUE TITLE
Make options more visible / discoverable in JSON files.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#521]
Users can use the "ctrl+space" hotkey in a property string to show a list of options. Today these options are:
1. Cut-off. We got feedback that the GPU string couldn't be seen.
2. Not discoverable for users.

We want to investigate ways in which we can make these options more discoverable to users.

**Comment by shsuman** [comment]
Closing this as it is not valid with V2
