### ISSUE TITLE
AML Extension UX Consistency 

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#522]
[Spec](https://microsoft.sharepoint.com/:w:/t/python/EX5O4TCMdJxIvs9-Kgi4e-ABOFojNvZ6GKRCbGnN1RctTw?e=gnUKe2&CID=4BDA65C9-9B0F-4B35-AEBF-3E68A79B2F1E&wdLOR=c6D1B9787-082D-475A-83DD-40505980C922)

**Comment by tbombach** [comment]
For failed computes, we'll use the same compute icon and add a "failed" label
