### ISSUE TITLE
The codelenses read "Submit Experiment" and "Cancel Experiment" in all JSON files when run experiment is in progress

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#523]
The run experiment in progress here does not mean on Azure but refers to a state of the extension from the moment an experiment run is started to it is submitted

**Comment by SiddhanthUnnithan** [comment]
Ah I totally saw this and meant to create an issue but forgot about it. Thanks for catching this Shantnu!

**Comment by shsuman** [comment]
Closing this as it is not valid with V2
