### ISSUE TITLE
No Batch Ai Job 

### ISSUE THREAD

**Issue by DHOFM** [Microsoft/vscode-tools-for-ai#53]
Hi,
i do not see the possibility to submit a azure batch ai Job in VS Code. I installed the tools for ai extension. Also there is no Batch AI in the AI Explorer. I am running VS Code on Mac OS. What needs to be installed to see Batch AI in VS Code?

<img width="392" alt="image" src="https://user-images.githubusercontent.com/27775323/45096871-d1669c00-b121-11e8-85a6-2b2b8b4d5229.png">

Thanks in Advance...
Kind regards,

Dirk

**Comment by linmajia** [comment]
@DHOFM , thank you very much for the feedback.

In the latest release 0.2.0, Azure Batch AI support is temporarily removed, and we may get it back soon.

Thanks.

**Comment by DHOFM** [comment]
@linmajia Thanks very much for your reply. Yes it is 0.2.0 that i have installed. Support for batch coming back would be nice, especially with support of running low priority GPU Jobs...
