### ISSUE TITLE
Implement redeploy for failed compute deployments

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#530]
For computes that are in the failed state, we can extract the compute creation parameters from the properties. We want to provide an option to redeploy the failed compute, by deleting the failed compute and deploying with the same creation parameters.

**Comment by tbombach** [comment]
@SiddhanthUnnithan: Follow up with AML compute team about the reasoning behind retaining failed computes and returning them via the API. Do they have plans around redeploy?
