### ISSUE TITLE
Change "Create" to "Register" in Datastore workflow components.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#534]
We got feedback from the AML team that the "Register" message is more clear to users than "Create". We want to update all the components of the original "Create a Datastore" to reflect the "Register" verb.

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/9b73642d-72a8-4b7f-afd1-afb6d75094dd)

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/1f4d84b7-c4f3-4d56-9487-02ae646d4380)

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/4dd24153-32b8-408a-bd1a-35bb6497c1ff)

**Comment by sevillal** [comment]
Merged to "data" shared branch.
