### ISSUE TITLE
Change messaging from "create a data reference for" to "use a Dataset during" when submitting an experiment.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#543]
The current "use dataset during training" workflow prompts the user with the following message:

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/915a6843-252f-49fb-8ecc-905fed93ac69)

The AML team has advised us to use "Dataset" in place of "data reference". The intent is still clear if the user is asked to "use Datasets".

**Comment by shsuman** [comment]
Merged PR https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1695730
