### ISSUE TITLE
QP: Error "Cannot read property slice of undefined" when creating a Datastore

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#554]
## Expected Behavior
Show multi-step input asking for datastore name

## Actual Behavior
Error "Cannot read property slice of undefined"

## Steps to Reproduce the Problem

  1. Right click Datastore node and select "Register Datastore"
  2. Error shown in display window

## Specifications

  - Version: 0.6.10 (Build used for Datastore/Dataset QP)
  - Platform: Win

**Comment by SiddhanthUnnithan** [comment]
The fix for this was setting the current workspace as active. We can extend this to allow the user to "Set Active Workspace" with a single click.

**Comment by sevillal** [comment]
Fix merged to master
