### ISSUE TITLE
QP: Error AuthorizationResourceTypeMismatch when creating Dataset that uses a Sas Datastore

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#555]
## Expected Behavior
Create Dataset and upload files to Datastore

## Actual Behavior
Error AuthorizationResourceTypeMismatch

## Steps to Reproduce the Problem

  1. Create a Datastore with SAS Token authorization
  2. Right click Dataset and select "Create Dataset"
  3. Select Name, File Dataset, Local Files
  4. Select a file to upload
  5. Select Datastore created in step 1
  6. Select default "files/"

## Specifications

  - Version: 0.6.10 (QP build)
  - Platform: Win

![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/ca9ff107-82ee-4e06-adec-7bec356f5ed8)

**Note:** Also seen in the ML Studio

**Comment by tbombach** [comment]
I have verified that creating a SAS token with the right permissions does not reproduce this error. We need to have better instructions for the user when they don't allow all the permissions needed when they create the SAS token
