### ISSUE TITLE
Add the "Authentication Type" step to datastore creation.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#564]
We removed the Authentication Type input option to streamline bringing the user to the final JSON. User studies have shown that users are confused by the input option + JSON paradigm and don't know how to change the default properties.

After choosing a container, the user is asked to choose an authentication type. Options are:
1. Account Key
2. Shared Access Signature (SAS) Token

If the user chooses Account Key as the authentication type we automatically create the datastore.

If the user chooses SAS token we show an input box for the user to provide a SAS Token. We should investigate a method to link directly to the "Shared Access Signature" view in the Portal (for the storage account the user chooses).

We don't show a final JSON in this workflow.

**Comment by tbombach** [comment]
If authentication fails when using account key, we would like to show the final JSON so that the user could possibly use the second key.
