### ISSUE TITLE
Change the order of dataset creation steps

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#567]
[Step 1] Input the name

[Step 2] Create the dataset from
1. Local file system
2. Web URL
3. Existing datastore (eventually)

[Step 3 is dependent on Step 2]

[Step 4] Please select a datastore type (Tabular or File)

We should investigate whether it makes to default or suggest types based on the user's initial input.

We should also change the label string for Tabular datasets to specify that CSV, TSV, Parquet, and JSON lines are supported file formats. User studies have shown that its confusing to say what "Tabular" covers from a file format perspective.

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1779409
