### ISSUE TITLE
Plugin uses port 8080

### ISSUE THREAD

**Issue by mmusket** [Microsoft/vscode-tools-for-ai#57]
I use VS code for different projects and I noticed that this extension uses port 8080. 
This unfortunately clashes with nodejs. 
I could use another port but in ideal world I would like to configure this extension to use a different port.

Is that at all possible?

**Comment by linmajia** [comment]
@mmusket , thank you very much for the feedback.

VS Code Tools for AI searches available port starting from 8080 for internal use, and we are sorry to cause the inconvenience. We will use another starting port and add a configuration for this in the new release.

Currently, you can start nodejs first, and then VS Code Tools for AI to mitigate this issue.

Thanks.
