### ISSUE TITLE
Investigate why Intellicode gives users schema violating properties as suggestions in the JSON views. 

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#574]
An example of this would be "Shared access signature" as a suggested property in datastore registration flow.

We need to investigate what all the different options are across each of our JSON + codelens views and whether the suggestions are consistent.

**Comment by tbombach** [comment]
For this, we can simply change the double quotes around "Shared access signature" in the comment and it avoids the suggestion. We'll make that simple change to address this.

**Comment by shsuman** [comment]
VS Code IntelliSense offers different types of completions, including language server suggestions, snippets, and simple word-based textual completions. (source: https://code.visualstudio.com/docs/editor/intellisense)

Schema is a type of static language service and there can be other suggestions based on word-based textual completions which can be in addition to the schema.
