### ISSUE TITLE
[Investigate] Users can test the connection to their datastore

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#577]
**Experience** 
Right-click the datastore node and choose the "Test connection" context menu option.

**Questions**
1. Does the AML service have an API to do this?
2. Do we need to upload and then delete a small packet to the datastore the user is testing?
3. Is this step performant enough so that we can include it during the "Create dataset" workflow?

**Comment by tbombach** [comment]
Investigate the points of failure when using SAS tokens - if the user doesn't have the correct permissions set when they created the token, where do datastores/sets fail? Can we check for the correct permissions when creating a datastore?
