### ISSUE TITLE
Dataset nodes are given a label to denote the type of dataset.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#589]
Dataset nodes in the tree are given a label to denote which type of dataset it is: Tabular or File.

If a dataset has multiple versions, the parent node is given the label.

**Comment by sevillal** [comment]
Closing since it will be fixed by adding icons instead with issue https://github.com/microsoft/vscode-tools-for-ai/issues/677
