### ISSUE TITLE
Make disabling Start Page opening on startup easier

### ISSUE THREAD

**Issue by nphmuller** [Microsoft/vscode-tools-for-ai#59]
The Tools for AI extension is often installed as part of the Azure Extension Pack.

Now imagine if every extension part of this pack had a Start Page that opened automatically. It would give a pretty bad experience to users.

Currently however only the Tools for AI extension does this. But it does this on every startup of VSCode by default. This behavior can be disabled by unchecking an option on the start page, but this option is not visible at first glance. You have to scroll all the way down the start page to find it.

Would it perhaps be possible to implement one of the following changes?:
- Disable opening the start page on startup by default when the extension is installed via the Azure Extension Pack.
- Make the option to disable this behavior visible at first glance from the start page (without scrolling).

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning and no longer displays a start page.  In the [archive](/archive) folder, you can find the [0.3.1 vsix installer](/archive/ms-toolsai.vscode-ai-0.3.1.vsix) that includes  previous features before this redesign, along with corresponding docs.
