### ISSUE TITLE
Users can select files and folders for their snapshot if the size of their current workspace exceeds 25 MB.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#592]
Experiment submission fails if the extension tries to use a workspace > 25MB as a snapshot. In scenarios where we find the size of the current workspace is too large, users should be able to select a set of files and folders to define as the snapshot. This process is recursive until the user defines a <= 25 MB snapshot.

**Comment by tbombach** [comment]
Users are able to accomplish this using the .amlignore file and specify a glob pattern. The work here is to make this more discoverable.
