### ISSUE TITLE
Can't create a File dataset with very large zip file.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#594]
## Expected Behavior
- Users can create File datasets through the extension with a file size of ~800 MB.
- The file can be uploaded directly to storage using the Azure Storage extension.
- The dataset can be created through the Studio UI.

## Actual Behavior
- The request immediately fails with the following messages:
![MicrosoftTeams-image (3).png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/bca4bc5a-c8e5-4617-9bce-287d9449f5d2)

## Steps to Reproduce the Problem

  1. Create a File dataset using a single zip file that is ~800 MB large.

## Specifications

  - Version: April Release Build
  - Platform: Windows

**Comment by tbombach** [comment]
Our timeout was set too low (about 1.8 seconds) because it wasn't set correctly in milliseconds. Fixed now

**Comment by SiddhanthUnnithan** [comment]
Thanks Thomas! :)
