### ISSUE TITLE
Give options for users to sign into Azure or create a new Azure account.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#596]
If the user doesn't have an Azure login, the AML extension shows no options in the tree. We want to follow the pattern of other Azure extensions and do something like:

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/b2ec4e62-a57f-4cf7-b1e6-19f564c5b4bb)

**Comment by tbombach** [comment]
Duplicate of: https://github.com/microsoft/vscode-tools-for-ai/issues/370
