### ISSUE TITLE
Users can archive experiments from the extension tree node.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#597]
[Experience]
Users can right-click and choose the 'archive experiment' context menu option to remove the experiment from the current tree view.

Users can right-click on the top-level experiment node in the current workspace to 'View Archived Experiments'. This will update the tree to only show archived experiments.

Users can right-click on an archived experiment to unarchive it.

**Comment by sevillal** [comment]
@SiddhanthUnnithan  this feature is mentioned in UX Consistency, is it ok with you to put it in that epic?
