### ISSUE TITLE
Unable to load sample gallery and then AI sample gallery command is gone

### ISSUE THREAD

**Issue by vykhand** [Microsoft/vscode-tools-for-ai#6]
![image](https://user-images.githubusercontent.com/498481/30994954-6b191558-a4b7-11e7-9283-0b8d01048572.png)

![image](https://user-images.githubusercontent.com/498481/30994915-2dfffccc-a4b7-11e7-8f5d-26ea61538ab8.png)

![image](https://user-images.githubusercontent.com/498481/30994986-ace7015c-a4b7-11e7-8861-1418cf2413bf.png)

Dear  team, 

I am trying to run to browse a gallery (ctrl-shift-p, AI Sample Gallery). After I choose it, it says it is unable to load and then this command disappears from the menu

**Comment by chris-lauren** [comment]
Did you install Azure Machine Learning Workbench ?https://docs.microsoft.com/en-us/azure/machine-learning/preview/quickstart-installation

Assuming so can you successfully login to your azure machine learning account?

**Comment by vykhand** [comment]
@chris-lauren Nope. I haven't noticed any mention that I need to do so. Why should I login to see the gallery? :) In any case, I believe. the correct behavior should be to give an error message smth like "You need to install AML Workbench, AML experimentation and Model management account and login"

**Comment by linmajia** [comment]
Fixed. A notification message is popped up for installing Azure ML Workbench.
