### ISSUE TITLE
doesn't show notebook content ???

### ISSUE THREAD

**Issue by FoeinLove** [Microsoft/vscode-tools-for-ai#60]
I follow the instruction step and it also give me the sign that  --> verbose: Jupyter server started in the output panel , but I can't see any ipynb file content, somebody got the same problem ?

**Comment by linmajia** [comment]
@FoeinLove , thank you very much for the feedback.

Which OS, VS Code and Tools for AI are you using? Please refer to issue #45 and verify whether you could view .ipynb files manually in your browser.

Thanks.

**Comment by FoeinLove** [comment]
1. my OS is windows 10 and my VS code version is the latest, and yes , I use' Visual Studio Code Tools for AI' extension to view ipynb file through jupyter server.
2. I got the same problem like issue#45 and I've checked that I can manually view ipynb files by typing jupter notebook in my browser, it's just seems that vscode cannot get the browser content into the edite window.
Thanks for your reply!!!

At 2018-09-17 11:11:47, "HX Lin" <notifications@github.com> wrote:


@FoeinLove , thank you very much for the feedback.

Which OS, VS Code and Tools for AI are you using? Please refer to issue #45 and verify whether you could view .ipynb files manually in your browser.

Thanks.

**Comment by Cisnocxie** [comment]
I got the exactly same case as you did.

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning. The Python Extension for VSCode now supports the ability to import, modify, and export jupyter notebooks.

**Comment by FoeinLove** [comment]
ok then, thanks mate.






At 2018-12-14 15:52:47, "Jim Griesmer" <notifications@github.com> wrote:


This extension has been redesigned to target scenarios only dealing with Azure Machine Learning. The Python Extension for VSCode now supports the ability to import, modify, and export jupyter notebooks.
