### ISSUE TITLE
Investigate showing the percentage progress of a file upload when creating a dataset from local files.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#601]
[Experience] show users the percentage progress of their file uploads when creating a dataset from local files.

Investigate showing this progress in the notification:

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/c73a07a4-4113-4a01-8a93-d599c1018119)

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1821012
