### ISSUE TITLE
Show a progress indicator while retrieving curated environments

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#602]
## Expected Behavior
Retrieving curated environments should show a progress indicator (or loading bar). 

## Actual Behavior
The UI displays nothing until the curated environments are returned and the list is populated

## Steps to Reproduce the Problem

  1. Create an environment in any workspace
  1. Select "Curated Azure ML Environment"
  1. Note that there is no UI indication that the curated environments are being retrieved

## Specifications

  - Version: latest
  - Platform: all

**Comment by sevillal** [comment]
Fix merged to master, available on next release 6.12
