### ISSUE TITLE
jupyter-notebook path incorrect with virtual environments 

### ISSUE THREAD

**Issue by bbrauchl** [Microsoft/vscode-tools-for-ai#61]
When loading up jupyter-notebook.exe with python installed in a virtual environment on windows it cannot find the executable because it is looking for \<PythonVenvDirecory>\Scripts\jupyter-notebook.exe

![image](https://user-images.githubusercontent.com/10524506/45599076-6fc0f000-b9b3-11e8-8aef-7016279b9158.png)

for the virtual environment the python executable is in the same directory as the jupyter-notebook. 

as a workaround, from my python scripts directory I ran:
`mklink /D Scripts .`

A symbolic link causes the plugin to see the jupyter-notebook executable on the aforementioned path, and it works.

**Comment by linmajia** [comment]
@bbrauchl , thank you very much for the feedback. We will add Jupyter path configuration in the future update.

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning. The Python Extension for VSCode now supports the ability to import, modify, and export jupyter notebooks.
