### ISSUE TITLE
Smoke test: should login to Azure with a common test account

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#617]
## Expected Behavior
When smoke test run, it should check if the VS Code under test is logged into Azure, if not it should connect with a common test account.

## Actual Behavior
Smoke test opens extension host and runs test regardless if logged in to Azure.

Also seen, the test fails after timeout (60min) and does not indicate that the issue was it was not logged in, making it hard to identify what it failed.

Dev needs to login to Win vm and login manually to azure with his account.

## Steps to Reproduce the Problem

  1. Connect to Win VM and loggout from azure
  2. Run smoke test

## Specifications

  - Version: any
  - Platform: any

**Comment by shsuman** [comment]
No longer valid as we moved to GitHub actions and ditched our testing machines
