### ISSUE TITLE
Users are warned about compute cluster costs when creating a new compute cluster.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#623]
If minNodes >0 when the compute cluster we want to warn the user about costs.

[Upstream work to see what messaging the AML team comes up with] We should be consistent here.

**Comment by tbombach** [comment]
To address this, we want to remove the minNodes from the JSON if the value is 0 (or when the user creates a compute and is seeing the JSON values for the first time). This will require the user to type in the property to set the value and make it more intentional on their part.

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1764786
