### ISSUE TITLE
Python Path Environment Variable Bug

### ISSUE THREAD

**Issue by michael-clarkson** [Microsoft/vscode-tools-for-ai#63]
I am unable to open a jupyter notebook with an environment variable in my python path: ${env:HOME}/.../python
The extension cannot find jupyter.
The extension works correctly when I change the path to a normal one.

**Comment by linmajia** [comment]
@michael-clarkson , thank you very much for the feedback. It seems that Tools for AI does not handle environment variables very correctly. We will fix it in the new release.

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning. The Python Extension for VSCode now supports the ability to import, modify, and export jupyter notebooks and is actively being developed. Please try it out and log issues on the Python extensions issues list.
