### ISSUE TITLE
Investigate using the Remote containers extension to enable users to build, run, and attach to containers (AML Environments).

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#631]
The AML SDK provides us with a way to build environments locally. Given a user has Docker installed and the remote containers extension, we can provide a way for them to build their AML environments, run the environment as a container, and then attach to that container (using the Remote Containers extension).

There are outstanding tasks around whether we can have extensions pre-installed (e.g. Python, AML ext) and whether we can open a specific folder. There's also an open question on whether we can connect to a container running on a compute instance (given the user has SSH access to the CI).

**Comment by shsuman** [comment]
Prototype in this branch https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode?version=GBshsuman%2Fcontainer-prototype
