### ISSUE TITLE
PRESS <ENETR> TO BROWSE NOT WORKING

### ISSUE THREAD

**Issue by shivprasad94** [microsoft/vscode-tools-for-ai#639]
Issue Type: <b>Bug</b>

**Press 'Enter' to browse**
**please select a conda dependencies files(press 'Enter' to confirm or 'Escape' to cancel)**

**Enter key does not work here....**

Extension version: 0.6.11
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SiddhanthUnnithan** [comment]
Hey Shiva, thanks for bringing this to our attention. Are you experiencing a similar issue for other "Enter-type" input prompts? For example, do you have the same issue when selecting a pip requirements file or a training script?

**Comment by shivprasad94** [comment]
**Yes, for all "Enter-type" to confirm**  
- I faced this issue, to be precise 3 times today!
- I had to close my VS Code, had to restart again to make it work
- this happens, all a sudden randomly while working, so my only option was to kill VS Code and start all over again from start..

**Comment by shsuman** [comment]
Hey @shivprasad94, 

Did you input anything in the input box before hitting enter? Maybe a space or something else? 
And what happens exactly after you press the Enter key ?

**Comment by shivprasad94** [comment]
- I thought maybe a space or something gave me that issue initially, but when it happened for 2nd and 3rd time I had a clear look at it, it was without space or any other interruption.
- as soon I press "Enter" it doesn't even consider my key, it just gets stoped there (crossed verified and my enter key working fine) 
- now in case, I type Esc i,e 'Escape' to cancel it works absolutely fine

so basically when I type enter in command box
please select a conda dependencies files(press 'Enter' to confirm or 'Escape' to cancel)

a file explorer should open to give my file path, but that was not opening..
- My VS code was just getting struck at that Enter key point. and i had to restart again from start to make it work
