### ISSUE TITLE
Remove installation page

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#640]
We show the installation page to new users (unclear exactly when). The page is outdated.

Shantnu has an issue for revamping it, but we should remove it altogether for now (and then eventually revamp it).

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1738265
