### ISSUE TITLE
Error Creating Environment

### ISSUE THREAD

**Issue by luisquintanilla** [microsoft/vscode-tools-for-ai#641]
## Expected Behavior

Show prompt(s) to create environment.

## Actual Behavior

Error is output to the console.

```text
error: Cannot read property 'slice' of undefined
```

## Steps to Reproduce the Problem

  1. Right-click `Environments` node
  1. Select `Create Environment`

One thing to note is that I had no directory / files open. This was a blank VS Code window.

## Specifications

  - Version: 0.6.11
  - Platform: Windows 10

![image](https://user-images.githubusercontent.com/46974588/83798039-9a644800-a671-11ea-8e8e-f9fdef468ea2.png)

**Comment by sevillal** [comment]
Fix merged to master.
