### ISSUE TITLE
Reveal experiment run for dataset profile generation job 

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#647]
## Expected Behavior
Reveal experiment run node when user triggers dataset profile generation

## Actual Behavior
We only show the experiment name and run number to track in the notification
![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/333109ea-341a-4a7e-b06f-24c7122a4fac)

## Steps to Reproduce the Problem

  1. Create a dataset with the following characteristics: Tabular, Parquet File
  2. To preview parquet file you will be asked to Generate Profile, click the button on the notification
  3. You will see the information message with the id of the experiment and run to track

**Comment by shsuman** [comment]
Merged PR https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1895769
