### ISSUE TITLE
Opening URLs don't show intermediate prompt confirming with the user whether they want to "Open in Browser", add to trusted domains, etc

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#649]
## Expected Behavior
When opening an URL from the extension like "View Experiment in Studio" do not prompt for confirmation to open in the browser.

## Actual Behavior
User is shown the following intermediate prompt:
![image](https://user-images.githubusercontent.com/56176070/84701917-a9b58200-af0a-11ea-81bc-3a4509fcece1.png)

## Steps to Reproduce the Problem

  1. Expand "Experiments" node
  2. Right click one experiment node and select "View Experiment"

**Comment by sevillal** [comment]
Investigation:

1. The popup is shown because azure.com is not registered as a trusted domain.
2. There is a thread on VSCode about adding trusted domains https://github.com/microsoft/vscode/issues/82794 which can help us resolve this.

**Comment by SiddhanthUnnithan** [comment]
We want the user to control/specify trusted domains.
