### ISSUE TITLE
The View Dataset Properties operation takes 3-4 seconds more to display the JSON even after the "Getting Azure ML Dataset.." progress bar has finished

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#656]

**Comment by tbombach** [comment]
Please also investigate if this is wide-spread or just view dataset properties

**Comment by shsuman** [comment]
A network call is made to get the data path of the dataset which takes the additional time

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1781936
