### ISSUE TITLE
Investigate YAML-based config files for resource creation/editing

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#663]
Questions to answer:
- What is the JSON vs YAML editing experience in VSCode? Autocomplete/type checking, etc.
- Do we need to convert to json to submit to AML service?
- Can we still do schema validation?
- Can we still get intellisense experience w/ providers like Sergio prototyped for json?

**Comment by sevillal** [comment]
Answer an information about this can be found at the following [OneNote.](https://microsoft.sharepoint.com/teams/python/_layouts/OneNote.aspx?id=%2Fteams%2Fpython%2FDocuments%2FDocuments%2FPython%20Team&wd=target%28Azure%20ML%20Extension%2FFeature%20Design.one%7C96C47AD5-760A-49C7-9356-C1CF440053F9%2FJSON%20to%20YAML%7C89533ACB-4261-496B-B84B-1B5E6E604AAC%2F%29
onenote:https://microsoft.sharepoint.com/teams/python/Documents/Documents/Python%20Team/Azure%20ML%20Extension/Feature%20Design.one#JSON%20to%20YAML&section-id={96C47AD5-760A-49C7-9356-C1CF440053F9}&page-id={89533ACB-4261-496B-B84B-1B5E6E604AAC}&end)
