### ISSUE TITLE
Evaluate reducing max-line-length in the project

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#667]
Discuss with the team the preference on **max-line-length**.

Prettier default: 80

Commonly used values: 120, 140

**Comment by greazer** [comment]
I haven't written a bunch of code in AzML extension for a while, but if you default it to 80, I'll quit.  You guys know I'm pretty easy going and can accept a lot of things, but 80 is ridiculously and unacceptably small. If it were me (and it's not, I realize), I would keep it on the high side... say 160. Actually if it were me, I wouldn't have a maximum line length. I find it pointless. To me, a good software engineer "knows" when a line is getting too long.

How's that for an opinion?

I'll let you guys hash it out though. 😄
________________________________

**Comment by shsuman** [comment]
We decided on 120.
