### ISSUE TITLE
VS Code Notebook users can connect to compute instances

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#681]
https://microsoft.sharepoint.com/:w:/t/python/EZDp_lrwrMhCofZ1EDbkvQUBlliVv4z-qPCFhgcmliGpcA?e=3S1Vgn

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1767533
