### ISSUE TITLE
Incorrect path for user-inputted scoring script 

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#683]
![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/a5ac0f0a-fb61-4e93-91e2-7d166e632734)

The path inputted by a user when specifying a scoring script is different from what the extension tries to use. As shown in the above screenshot, the initial path inputted was <current_workspace>/score.py.

This is preventing users from inputting script file paths themselves. The same issue occurs in the subsequent conda dependency file step.

**Comment by tbombach** [comment]
Fixed by @shsuman as part of deployment model changes
