### ISSUE TITLE
Show extension loading notification as Python ext does

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#691]
[Yesterday 4:07 PM] Sid Unnithan
    One thought - when the user invokes the "Python: Specify local..." command for the first time in a new VS Code instance there's a slight delay for both the Python and AML extensions to activate.
​[Yesterday 4:08 PM] Sid Unnithan
    Is it possible to have a notification with an indeterminate loader to show both of the extensions being activated.
​[Yesterday 4:09 PM] Sid Unnithan

The Python extension shows this today, I'm wondering whether we can do the same thing for the AML extension? 

![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/833ecfbd-8c45-455c-9884-159005c931aa)

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1779542
