### ISSUE TITLE
Can't find ML Sample

### ISSUE THREAD

**Issue by shilf** [Microsoft/vscode-tools-for-ai#7]
![1](https://user-images.githubusercontent.com/1725360/30997479-b716749e-a4fa-11e7-9322-fce72a911cab.jpg)

Can't find ML Sample

**Comment by chris-lauren** [comment]
Please install Azure Machine Learning Workbench, restart VSCode and try again https://docs.microsoft.com/en-us/azure/machine-learning/preview/quickstart-installation
