### ISSUE TITLE
Error when selecting new experiment in Golden Path

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#702]
## Expected Behavior
The experiment execution should be successful

## Actual Behavior
There is an uncaught error shown in the notifications

## Steps to Reproduce the Problem

1.	On training script, right click and select “Run as experiment in Azure”
2.	Select an existing subscription
3.	Select an existing workspace
4.	Select “Create new experiment”
5.	Select an existing compute
6.	Select an existing run config
7.	Submit the experiment
8.	The following error is shown

![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/59c744de-0aa0-4ddc-b9a5-c8003e6a87ec)

## Specifications

  - Version: 0.6.13
  - Platform: All

**Comment by SiddhanthUnnithan** [comment]
Failing on validate JSON step.
