### ISSUE TITLE
Avoid showing the Active experiment prompt when the user doesn't have an active experiment in the workspace.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#705]
When the user doesn't have an active experiment in their workspace we should avoid showing the prompt:

"Would you like to switch the active experiment?"

Instead we should default to setting an active experiment based on the current experiment the user is running against.

**Comment by shsuman** [comment]
Closing the non relevant and old V1 issues.
