### ISSUE TITLE
Create compute instance flows should be a multi-step operation.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#706]
Flows:
1. Connecting via the Python extension.
2. Creating from tree node.

**Comment by SiddhanthUnnithan** [comment]
Infra changes:
1. Remove number of steps from optional / branch flows.
2. Enable users to go "back" when stepping into an optional / branch flow.

**Comment by SiddhanthUnnithan** [comment]
Refactor to have reusable steps across different flows.

**Comment by shsuman** [comment]
Closing the non relevant and old V1 issues.
