### ISSUE TITLE
Abstract away run configurations from users.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#707]
The run configuration concept confuses users when they see it during the experiment submission flow. Users should be able to re-run an experiment by right-clicking on the experiment in the tree node. Users should still be able to see the run configuration associated with their experiment (non-editable).

**Comment by SiddhanthUnnithan** [comment]
Remove runconfig filename from the final JSON when submitting an experiment.

**Comment by shsuman** [comment]
Closing the non relevant and old V1 issues.
