### ISSUE TITLE
vscode run machin learning experiments got error: The subscription 'xxxxx' could not be found.

### ISSUE THREAD

**Issue by cici-zhang** [microsoft/vscode-tools-for-ai#711]
1.accord this https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-train-deploy-image-classification-model-vscode test
 2.When running to the Train the model step, got error The subscription'xxxx' could not be found. but I have login my account
![image](https://user-images.githubusercontent.com/69502113/90585395-5829bc00-e207-11ea-9573-2f2c1c41d466.png)
  
![image](https://user-images.githubusercontent.com/69502113/90585521-9fb04800-e207-11ea-9031-f7ebb92bf229.png)

  - Version:Azure  Machine Learning Extension 0.6.13
  - Platform:windows

**Comment by SiddhanthUnnithan** [comment]
Hi @cici-zhang I see another message in the Output console about you not having a folder open in VS Code. Do you mind retrying submitting the training run after opening a folder?

**Comment by cici-zhang** [comment]
hi     @SiddhanthUnnithan   I open  a folder, I still got the same  error
![image](https://user-images.githubusercontent.com/69502113/90711474-680ed200-e2d3-11ea-9005-a17ec21ea531.png)

**Comment by cici-zhang** [comment]
hi  @SiddhanthUnnithan  i have opend a folder, i  still got the same error
![image](https://user-images.githubusercontent.com/69502113/90711568-ae643100-e2d3-11ea-8eff-f358bff3d32f.png)
thanks.

**Comment by SiddhanthUnnithan** [comment]
Hi @cici-zhang are you able to see the tree view in the Azure tab with a list of all of your subscriptions? Do you mind taking a screenshot of the tree view?

**Comment by cici-zhang** [comment]
hi  @SiddhanthUnnithan  ok My vscode can display the login subscription

![image](https://user-images.githubusercontent.com/69502113/90845922-a66ec480-e399-11ea-8dab-995b6767533b.png)

**Comment by SiddhanthUnnithan** [comment]
Hi @cici-zhang thanks for your patience with this. Is it possible for us to follow up over mail to further investigate the issue you're running to? Our hypothesis is that there might be an issue with the execution service for your specific subscription. Feel free to email me at siunnith@microsoft.com if you're uncomfortable with inputting your email here.

**Comment by SiddhanthUnnithan** [comment]
Hi @cici-zhang wondering whether you're still running into this issue? As said above, I'd be happy to help over mail.

**Comment by tbombach** [comment]
Hi @cici-zhang! We're closing this for now, but please feel free to add more details if you're still encountering this issue.
