### ISSUE TITLE
Automatically stream the experiment control log while the local debug session is being prepared.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#712]
Today when users run a local experiment in a debug session they see the following: "Starting debug session, this might take some time".

This toast notification is good in telling the user that something is happening, but it lacks finer details that the user may wish to see. After running for a long period of time users may get easily frustrated by not knowing what's happening (and may assume that something is wrong with the setup).

We should instead stream the control log in the user's console. The control log provides information to the user image being built, dependencies being installed, and the container being ran. The last line of the streamed control log should be an injected message from the AML extension saying that the debugging session is ready and/or the experiment is being started.

**Comment by sevillal** [comment]
Merged as part of: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1839687
