### ISSUE TITLE
Create a script to verify no missing strings between message.ts and package.json.nls

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#713]
It could be a good idea to create a small script to verify messages.ts and package.json.nls matches, as a stretch it could be part of our build or prepublish tasks.

**Comment by shsuman** [comment]
With the new localization infra as mentioned in #1642, there will be no need for duplicated strings in message.ts and package.nls.json. All the user facing strings will live in the source files itself
