### ISSUE TITLE
Filter azureml_globaldataset datastore from list of datastores

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#718]
azureml_globaldataset is a datastore created by the Studio designer when you use a sample that uses the open datasets option. The studio filters this datastore out from lists if the user selects a datastore in other parts of the UI.

## Expected Behavior
azureml_globaldataset appears in the list of datastores, but we do not have permissions to read from it. If a user selects it, they will be unable to create a dataset from it.

## Actual Behavior
azureml_globaldataset should be filtered out of the list

## Steps to Reproduce the Problem

  1. Create a pipeline using the designer in the Studio
  1. Observe that there is an azureml_globaldataset datastore in the workspace
  1. Attempt to use this datastore during Create Dataset -> From existing datastore

## Specifications

  - Version:
  - Platform:

**Comment by zhimin-z** [comment]
> azureml_globaldataset is a datastore created by the Studio designer when you use a sample that uses the open datasets option. The studio filters this datastore out from lists if the user selects a datastore in other parts of the UI.
> 
> ## Expected Behavior
> azureml_globaldataset appears in the list of datastores, but we do not have permissions to read from it. If a user selects it, they will be unable to create a dataset from it.
> 
> ## Actual Behavior
> azureml_globaldataset should be filtered out of the list
> 
> ## Steps to Reproduce the Problem
> 1. Create a pipeline using the designer in the Studio
> 2. Observe that there is an azureml_globaldataset datastore in the workspace
> 3. Attempt to use this datastore during Create Dataset -> From existing datastore
> 
> ## Specifications
> * Version:
> * Platform:

I am a bit confused. Do you expect the azureml_globaldataset datastore to be filtered out or not? The current actual behavior is misleading. @tbombach 
![image](https://user-images.githubusercontent.com/8592144/217059690-e1cf3441-86a0-4981-b2f4-21601f14494c.png)
