### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Allaye** [microsoft/vscode-tools-for-ai#719]
- Issue Type: `Bug`
- Extension Name: `vscode-ai`
- Extension Version: `0.6.13`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by shsuman** [comment]
Can you please provide us with some details ?

**Comment by SiddhanthUnnithan** [comment]
Closing because of missing details.
