### ISSUE TITLE
On Mac having a python venv in directory seems to block AzureML deployment

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-tools-for-ai#726]
## Expected Behavior

Run is successfully submitted to AzureML

## Actual Behavior

![image](https://user-images.githubusercontent.com/812783/93373994-f90d9600-f80a-11ea-808b-fca4703803af.png)

## Steps to Reproduce the Problem

  1. On Mac, create a new directory
  1. In that new directory run "python -m venv .newEnv" (this is a usual step I do with a new python directory)
  1. Add some type of training script to that directory, contents don't matter
  1. Attempt to run the training script remote or locally
  1. I seem to always get an error where it's failing on the added environment on deploy (see picture above)

## Specifications

  - Version: This was a build specifically for the bug bash on 9/16/2020
  - Platform: MacOS

**Comment by sevillal** [comment]
Findings:

1. Not a regression
2. This is only reproducible on Mac
3. Extension is not excluding the virtual environment folder from the experiment, thus it is trying to copy it to the tmp dir and fails trying to copy the python symlink

**Comment by tbombach** [comment]
Iterate through the user's workspace and determine if there are any symlinks. If there are any symlinks, we should show an error that they cannot start an experiment with the symlink in their workspace. This error notification should have a button that lets the user automatically add any symlink paths to their aml ignore file.
