### ISSUE TITLE
Handle duplicated workspace id's when rendering tree view

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#727]
**Issue**

- Found duplicated workspace ids in certain subscription prevents render of the treeview
- From Azure ML: "I checked those workspaces are more than two years old while AML was in preview. We did find a potential racing condition if customer hit multiple createWorkspace within 1s, which we will fix, but in reality, I double customers do that. So such bug won't be repro outside of the subscription I think"

**Comment by tbombach** [comment]
Let's filter out any duplicate workspace ids that are returned from the service. We don't expect customers to run into this because workspace id is supposed to be unique. This will prevent the tree from having multiple nodes with the same id

**Comment by SiddhanthUnnithan** [comment]
Edited the title to reflect that we want to work on this (was previously in a Discuss state). @sevillal can you add details here that you think might be relevant to the work we want to do.
