### ISSUE TITLE
Exception "Element with id XXX is already registered" when trying to unfold subscription and see list of workspaces

### ISSUE THREAD

**Issue by yanrez** [microsoft/vscode-tools-for-ai#728]
## Expected Behavior
Click on subscription in left pane and see list of workspaces

## Actual Behavior
Click on subscription in left pane and seeing exception, list of workspaces doesn't show.

Exception, with some identifiable info scrubbed. Contact me if you need full string :

Element with id /subscriptions/5f08d643-1910-4a38-_rest-of-guid_/resourceGroups/_resourcegroup_/providers/Microsoft.MachineLearningServices/workspaces/_workspacename_ is already registered

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: 
Extension version v0.6.14
VC Code:
Version: 1.49.0 (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by sevillal** [comment]
@yanrez thanks for filing this. 

Do you mind sharing the subscription you are trying to access?

**Comment by tbombach** [comment]
Issues has been fixed
