### ISSUE TITLE
Users can connect to a remote Jupyter server from a stopped compute instance.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#729]
We should surface stopped compute instances in the extension, with the option for users to pick one to connect to. The AML extension should streamline starting the compute instance on behalf of the user and then connecting to the remote server when it's ready.

**Comment by shsuman** [comment]
https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1855294
