### ISSUE TITLE
Change prompt messaging for environment creation.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#733]
**Create Azure ML Environment from...**

**Curated Azure ML Environment**
Pre-registered environments provided by Azure ML.

**Conda dependencies file**
Yaml file with the required dependencies.

**Pip requirements file**
Text file with the required dependencies.

**Existing Conda environment**
Local Conda environment.

**Custom**
Build your own environment from scratch.

Is there a way for us to provide links in the quick-pick options?

**Comment by tbombach** [comment]
No, I don't think you can have links in quick pick items. You can have a quick pick item that opens a web page, but not a link in a description/title.

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1879351
