### ISSUE TITLE
Remove Pipelines from the extension tree view.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#734]
Pipelines have no real function in the extension today. The only thing a user can do is view their list of pipelines and get redirected to the ML Studio for further viewing.

From an information perspective, the Pipelines node creates clutter without serving any purpose. Until we redefine the Pipeline interaction experience for the user, we want to hide it from the tree view.

**Comment by shsuman** [comment]
Merged PR https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1879956
