### ISSUE TITLE
Show users Azure ML extension activation messages as a toast notification

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#735]
Today users see activation / loading messages in the toolbar:

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/ab11c37b-08b2-400a-8e08-51ee98d3ba6c)

One complaint we've heard from partner teams (AML) is that it's easy to miss the activation message given the size and placement of the toolbar. In addition to the toolbar notification we also want to show a toast (bottom-right) to indicate that the extension is being activated.

Is it possible for us to automatically expand the notification tray (there are already activation messages there)?

**Comment by tbombach** [comment]
All we need to do is change `vscode.ProgressLocation.Window` to `vscode.ProgressLocation.Notification` in `extension.ts`

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1879360
