### ISSUE TITLE
Azure ML partners can invoke a registered URI from any browser and be led to an extension action in VS Code

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#736]
**Scope:** Productionizing the URI handler so that it's ready for release and use in public flight of the Studio UI.

**Comment by shsuman** [comment]
Merged PR https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1938340
