### ISSUE TITLE
Feature request: allow use of vscode text editing key-binds for Jupiter session!

### ISSUE THREAD

**Issue by antoncode007** [Microsoft/vscode-tools-for-ai#74]
What an awesome project!!

I'd love to be able to make use of all of my vscode set editing key-binds to interact with text in a Jupiter notebook cell. Hopefully others want this too!

**Comment by ronglums** [comment]
Good suggestion! In the current experience the Jupyter notebook is simply being hosted in a web view in VS Code , so there isn't a way to easily customize the key bindings. Curious though - if we were to offer an editor-centric experience in VS Code for data exploration (similar to Jupyter but you primarily work in the editor) and VS Code settings would apply, would that be something you'd be interested in? Or would you rather have the Jupyter notebook hosted in VS Code as is?

**Comment by ronglums** [comment]
Thanks! We are looking into building such an experience. :) Although, can you elaborate on this one "Ability to handle and review print print statement spam"?

**Comment by antoncode007** [comment]
In general i've noticed that apps and extensions which offer in app code execution are awesome at first, but typically break down as soon as they have to handle a ton of log output from the running code. Electron becomes bogged down and stops responding (same thing for looking at large files). This is unfortunate because producing a ton of stdout log output by inserting print statements into an app is a common, minimalistic, light-weight way to get insight into the state of your code while it's running at nearly fully speed. One solution could be to bypass the regular rendering engine. Another could be to introduce some log slicing or sampling middleware to separate output and presentation. IMO a data-focused extensions that lets you run code at nearly full speed, pause it's execution and inspect state (debugger is nice for this), or view a huge amount of stdout log output would have a really good shot at improving data science / data engineering coding experience. Is this possible? I'm not sure :)

**Comment by ronglums** [comment]
I see. If you had the debugger for inspecting states, do you still using print statements a ton? Also, how do you work around this problem today, i.e. view large log files, in editors?

**Comment by antoncode007** [comment]
I generally alternate between developing with debugger and only use a significant amount of logging while running the application in a terminal. My use case for viewing a ton of log output is primary understand if my data transformations are "reasonable" as opposed to trying looking for access to code objects. As for large files in editors, I never open them editor because I know not to, but sometimes do by accident, and endure the whatever happens next.

The bare minimal functionality I would personally hope for, is avoiding having to shut down my editor when this code is run by accident:
``` Python
while True:
  print("Hello")
```

Anyway, it sounds like this issue is understood by the team so I'll close this. Feel free to reach out, if you'd like to chat more about this though. antonlakin at gmail com
