### ISSUE TITLE
Evaluate usage of deprecated APIs

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#741]
UX: VSCode Extension using deprecated API run-history POST Run/QueryRuns
UX: VSCode Extension using deprecated API run-history GET RunArtifacts/GetSasForArtifactsInPath
UX: VSCode Extension using deprecated API run-history GET Run/GetRuns

**Comment by SiddhanthUnnithan** [comment]
@sevillal has a different issue for this work already.

**Comment by sevillal** [comment]
Duplicate of https://github.com/microsoft/vscode-tools-for-ai/issues/795
