### ISSUE TITLE
Write automated tests for remote connection

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#747]
We need automated tests that validate that the remote connection code is working correctly

### Unit tests
- Remote authority resolver
- Util code used by resolver

### Integration/end-to-end tests
- Go through UI to install server on a compute instance and connect to the remote instance

**Comment by SiddhanthUnnithan** [comment]
@tbombach can we add this to the testing rearchitecture work?

**Comment by shsuman** [comment]
https://github.com/microsoft/vscode-tools-for-ai/issues/1444
