### ISSUE TITLE
Users don't need to have a folder open to invoke the remote commands

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#755]
Today users must have a folder open when invoking the remote command. If we have information about subscription/workspace (e.g. from URI) then we shouldn't need a folder open and prompt the user to input additional parameters.

**Comment by omartin2010** [comment]
your comment makes sense on the need for workspace, I didn`t think if it that way. I don`t use the command line too much yet in AML so these features are second thoughts for me.

**Comment by tbombach** [comment]
The experience we will have is that users:
- Don't need to have a folder open to run commands
- We will store the user's active workspace/subscription choice in global storage
- When the extension loads, it will read the active workspace/subscription and show the user the workspace/subscription from the last session
- If the extension is responding to the URI handler, we will update the active workspace/subscription in global storage

**Comment by SiddhanthUnnithan** [comment]
**Artifact:** [Workspace Selection/Initialization](https://microsoft.sharepoint.com/teams/python/_layouts/OneNote.aspx?id=%2Fteams%2Fpython%2FDocuments%2FDocuments%2FPython%20Team&wd=target%28Azure%20ML%20Extension%2FFeature%20Design.one%7C96C47AD5-760A-49C7-9356-C1CF440053F9%2FWorkspace%20Selection%5C%2FInitialization%7C7E6F16B2-9263-44E0-9731-49A875C41B2D%2F%29
onenote:https://microsoft.sharepoint.com/teams/python/Documents/Documents/Python%20Team/Azure%20ML%20Extension/Feature%20Design.one#Workspace%20Selection/Initialization&section-id={96C47AD5-760A-49C7-9356-C1CF440053F9}&page-id={7E6F16B2-9263-44E0-9731-49A875C41B2D}&end)

**Comment by tbombach** [comment]
For now, we don't want to show this error. If the user doesn't have a folder open, then we're okay with not saving the default workspace/subscription information. If we can't write to settings.json, then we don't need to show anything to the user.

Later on we can implement any behavior changes that we brainstormed above.

@shsuman

**Comment by SiddhanthUnnithan** [comment]
Assigning this to you @shsuman. Let me know if there's anything you need from me.

**Comment by shsuman** [comment]
Merged PR https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1933403
