### ISSUE TITLE
Available documentation list is blank

### ISSUE THREAD

**Issue by floft** [Microsoft/vscode-tools-for-ai#76]
Before 0.3.1 it would list PyTorch, TensorFlow, and Keras documentation that could be downloaded and searched through when I press Ctrl+Shift-i. As of yesterday (presumably when it updated to 0.3.1, which was released 2 days ago), it doesn't list any documentation?

I'm on Linux primarily, but I just installed on Windows to test and it gives the same blank list.

![screenshot from 2018-10-18 09-47-08](https://user-images.githubusercontent.com/303109/47170585-400b4d80-d2bb-11e8-8d81-75251d4208e1.png)

**Comment by btruhand** [comment]
Ditto just checked on Mac

**Comment by linmajia** [comment]
@floft and @btruhand, thank you very much for the feedback. The documentation storage has an issue, and we are solving it now.

**Comment by btruhand** [comment]
@linmajia checked it out and it works! Thank you
