### ISSUE TITLE
Users can initialize their Azure ML workspace when they first interact with the extension

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#763]
Entry points for workspace initialization:
1. Command palette: "Azure ML: Initialize Workspace"
2. Welcome view in the tree.
3. Any other command / UI (e.g. toolbar) interaction.

If the user isn't signed into their Azure account we should prompt for a sign-in and then immediately move onto the initialization flow.

The flow:
1. Prompt the user for a subscription.
2. Prompt the user for a workspace. The user can choose an existing workspace or create a new one. If a user has 0 workspaces, default to taking them through the workspace creation step.
3. Store subscription and workspace information at the **user** level.
4. Filter the subscription and workspace shown to the user.

The user is shown a toolbar icon (need design) that they can click on to switch workspaces. Lead the user through the same flow but show the previously chosen subscription and workspace at the top of their steps as "recently used".

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/bac9da66-4539-49df-9eac-1e5919627772)

**Comment by sevillal** [comment]
Solution merger to v2_tooling branch https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2094742

**Comment by sevillal** [comment]
Available 0.6.21
