### ISSUE TITLE
error: The subscription '6273fbea-8a11-498b-8218-02b6f4398e12' could not be found.

### ISSUE THREAD

**Issue by karoschang** [microsoft/vscode-tools-for-ai#768]
## Actual Behavior
when i  use  'Run Experiments' of Azure,it shows me the error

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:

**Comment by karoschang** [comment]
urgent!!!help me!

**Comment by SiddhanthUnnithan** [comment]
Hi there! Do you mind sharing some more information of how this error came up?

You said you were using the "Run Experiment" command? Were you doing this from the toolbar/command palette or directly from the experiment node in the tree?

**Toolbar**
![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/38695612-e5a4-4683-af58-f944a4cd8800)

**Command Palette**
![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/a01633a1-8f38-4069-b5ab-4d1f23906184)

**Tree Node**
![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/4e63734b-5548-4843-baad-143077b4b18b)



If you were using the toolbar/command palette, were you able to see a list of subscriptions in the quick-pick options?

**Comment by SiddhanthUnnithan** [comment]
@karoschang if you're open to it I can also set up a quick 15 - 30 minute call for us to walk through and diagnose the issue that you're seeing!

**Comment by SiddhanthUnnithan** [comment]
Some more questions from us to help you better diagnose your issue:
1. Do you have any experiments with runs on it? Do you see them as part of the tree view?
2. Are you able to create other resources (i.e. Datastore, Dataset, Environment, Compute)?

**Comment by SiddhanthUnnithan** [comment]
@karoschang feel free to re-open this if you have more details!
