### ISSUE TITLE
Data reference mode "download" not working properly

### ISSUE THREAD

**Issue by schoennenbeck** [Microsoft/vscode-tools-for-ai#77]
I am running an experiment on a batchAI-cluster and need some data from the workspace filestore. The folder structure is test_0/test_1/needed_data. I tried downloading the data using the dataReferences in the runconfig as follows:
{
                "data": {
                  "data_store_name": "workspacefilestore",
                  "mode": "download", 
                  "path_on_data_store": "test_0/test_1", 
                  "path_on_compute": "/my_data"
                  }
}

However the /my_data folder on the batchAI-node is empty (and so is the folder $AZUREML_DATAREFERENCE_data). When I substitute "path_on_data_store": "test_0" it works (however I am not willing to do this since test_0 contains quite a bit more data so the download takes too long). Also if I change the mode to "mount" it works (other than the fact that I can't provide the path_on_compute) however, I want the data to be downloaded for technical reasons.

**Comment by greazer** [comment]
This extension has been redesigned and as it stands now, the functionality to interact with data stored on batchai clusters is not available. We will add this again in the future. For the time being, you'll have to use the azure portal.

**Comment by greazer** [comment]
For the record, the batch AI service is now renamed as Azure ML compute. This service should now support the scenario you're referring to. For further issues on the user of Azure ML, please head over to this forum: https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=machinelearning
