### ISSUE TITLE
Reconnecting remote window with a different bearer token

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#783]
This also should cover starting the vscode remote session with Open -> Recents

**Comment by SiddhanthUnnithan** [comment]
- Reloading window when the token expires
- File => Open Recents (no new bearer token; VS Code tries with expired token)
- Ship private preview with this as a "known issue"
- If the reconnection fails, the user must go to the Studio UI and use the URI
- Prioritize for 0.6.18

**Comment by SiddhanthUnnithan** [comment]
Solution: we have a bearer token; gets passed from Az account extension to remote authority resolver

Pass a refresh token to the remote window. The refresh token (lasts longer) is used to get a new Bearer token.

Remote authority resolver uses the refresh token to get the bearer token.

[Separate] Start a conversation with the core team about why dependencies are not correctly loaded in the remote window.

**Comment by shsuman** [comment]
The new remote extension uses the refresh token model as described above to reacquire a new bearer token every time the bearer token expires.
