### ISSUE TITLE
[Verify] Azure ML Output shown twice in the remote window

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#786]
## Expected Behavior
Only one Azure ML Output

## Actual Behavior
To instances of Azure ML Output
![image.png](https://images.zenhubusercontent.com/5d97c96655905700018a502f/c9e37828-9a61-4b92-954c-a3a1c0492ae1)

Track whether we're seeing this issue after we ship the second remote extension.

**Comment by SiddhanthUnnithan** [comment]
- Think that it might be solved with opening the remote host in the window

**Comment by sevillal** [comment]
Still reproducible if opening the remote host in a new window, need to further investigate.

**Comment by SiddhanthUnnithan** [comment]
Let's track whether we still see this issue after building and shipping the second remote extension.

**Comment by SiddhanthUnnithan** [comment]
Confirmed that there is only one output for the main window.
