### ISSUE TITLE
Use a different URI scheme for websocket server when the user is connecting to a compute in a private-link enabled workspace

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#787]
Connections don't work for computes in a private-link enabled workspace.

This is due to the fixed URI scheme we use for the websocket server: < ci-name >-< port >.< region > ... 

In a private-link enabled workspace the scheme that must be used for all non-Jupyter app servers is < ci-name >.< region >.instances.azureml.ms:< port >

We've reached out to Rajat Garg from the CI team about how to know when the user is in a private link enabled workspace (the Studio UI has this knowledge).

**Comment by SiddhanthUnnithan** [comment]
Add information from Ahmet about property value for private-link.

**Comment by sevillal** [comment]
This will be solved by https://github.com/microsoft/vscode-tools-for-ai/issues/830, closing this.
