### ISSUE TITLE
Connect to compute instance Jupyter server not showing "AML CI" option with new remote bits

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#788]
Python extension is loaded

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/b170cd54-722b-4291-b867-105b721cf750)

**Comment by shsuman** [comment]
We have disabled this feature in all Azure ML remote windows. As for local windows, its been activated and is working properly
