### ISSUE TITLE
Python 3.7 not supported

### ISSUE THREAD

**Issue by seank-com** [microsoft/vscode-tools-for-ai#79]
Not a super big deal but the docs say 3.5 or greater and 3.7 is greater than 3.5

**Comment by greazer** [comment]
Xiaoyun, I'm not sure whether this limitation is due to the requirements of the Azure ML SDK or if it's related to the flask server. Please investigate

**Comment by LittleLittleCloud** [comment]
sure

**Comment by linmajia** [comment]
TenosrFlow (1.12.0), CNTK (2.6), Caffe2 (0.8.1) don't have official wheel packages for Python 3.7 yet.

**Comment by LittleLittleCloud** [comment]
it has nothing do with azureml-sdk. to be precise, our test machine using python 3.7 to test extension. So it must be other third-party packages
