### ISSUE TITLE
[Verify] Reloading the window after installing the Azure account extension cancels the remote operation

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#797]
If the user doesn't have the Azure Account extension installed they're prompted for an install when the URI is invoked. After installing, the user's window is reloaded and in the new window there's no continuation of the original URI handling/remote operation.

Is a window reload required in order to install the extension?

1. Uninstall Azure account extension.
2. Invoke URI.
3. Click "Install Now"
4. Window Reloads.
5. Check to see whether the remote operation continues.

**Comment by SiddhanthUnnithan** [comment]
For private preview, we ask customers to install Azure Account and Azure ML extensions before hand.

**Comment by SiddhanthUnnithan** [comment]
Temporary mitigation is #803.

**Comment by SiddhanthUnnithan** [comment]
The correct fix for this is the double extension route.

**Comment by SiddhanthUnnithan** [comment]
Tested with dummy extension:
1. Prompted to install extensions
2. Asks to reload **with** URI
3. Opens as expected.

**Comment by shsuman** [comment]
This shouldn't happen now. We have tested it with the dummy extensions. Dummy Extension - Main registers a URI handler which displays the path of the URI being invoked. Dummy Extension - Remote is a dependency of the Dummy Extension - Main. Dummy Extension - Main is in extension pack of Dummy Extension - Remote.

1. Try to open a URI like vscode://shsuman.dummy-extension-main/testPath
2.  Install the Dummy Extension - Main when prompted to do so by VSCode
3. Reload and open URI as asked
4. Verify that both Dummy Extension - Main and Dummy Extension - Remote are installed
5. Verify that testPath is displayed in the information message

**Comment by shsuman** [comment]
We won't be able to actually verify it with our extensions until we release

**Comment by shsuman** [comment]
Verified this. Doesn't happen with the newly released extensions
