### ISSUE TITLE
Investigate retaining Notebook context (when moving to 2 extension model)

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#798]
We eventually want to move the remote authority resolver and connection to a second remote-aml extension.

This extension will be responsible for setting up the connection to the remote CI. Even with the move to this extension we can't automatically open Notebook files (and retain context) as part of extension activation.

We think there might be a different way for us to open Notebook files. The steps are:
1. User invokes URI and lands in VS Code.
2. The main Azure ML extension installs the VS Code server and websocket server.
3. The main extension creates an activation file in the target directory of the remote window. This file contains information about the required context.
4. The main extension opens a remote window. The remote extension invokes the resolver and establishes the connection.
5. The Azure ML extension is automatically activated **in the new remote window**. The activation file is used to automatically open the desired files in the editor.

**Comment by SiddhanthUnnithan** [comment]
Tested activation files in the workspace - AML extension automatically activates, along with Azure account, and Python.

We might be able to achieve the same activation and retaining file context without waiting for the second remote extension.

We write to the folder that the user will land in and rely on the AML extension activating after the remote window is created.

**Comment by tbombach** [comment]
If we want to enable this without activation files, there are two parts:
1. Be able to open a file in from the remote workspace based on the path provided by the URI handler
2. Open the file at the right time, as the remote workspace loads

I'm currently working on #1 right now. I'm trying to figure out the right URI to open with openTextDocument, and I think it needs the vscode-remote:// scheme. I'm testing that out today.

#2 seems a bit trickier. I looked into the events that we can subscribe to and it doesn't seem like the (onDidChangeWorkspaceFolders event](https://code.visualstudio.com/api/references/vscode-api#workspace) fires at the right time for us to open the file that we need. I can try with some of the other events but it doesn't seem like they are firing at the right time
