### ISSUE TITLE
400 Bad Request viewing experiment

### ISSUE THREAD

**Issue by seank-com** [Microsoft/vscode-tools-for-ai#80]
Following the steps [here](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-vscode-tools) I create an experiment and attach a local folder. Then I right click on the experiment and choose **View Experiment** and this is the result.

![image](https://user-images.githubusercontent.com/1326518/47821568-5800b980-dd1e-11e8-8620-ef4ce1f3089f.png)

**Comment by greazer** [comment]
We have not seen this for a while using the latest extension (0.4.1). Please re-activate if this is still a problem for you.
