### ISSUE TITLE
Add second extension id to the list of allowed extensions to use proposed APIs in stable

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#805]
We want to enable our second (remote-only) extension to register a RemoteAuthorityResolver. This needs to be merged into vscode to be part of a stable release

**Comment by SiddhanthUnnithan** [comment]
Peng from the Core team helped add the second extension to allowed list:

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/ef402ad2-64bd-4e07-8e8b-a271445a80be)
