### ISSUE TITLE
.jupyter directory

### ISSUE THREAD

**Issue by dboaretti** [Microsoft/vscode-tools-for-ai#81]
I tried to run a jupyter notebook in VS Code on Windows but I have this issue:
error: EPERM: operation not permitted, mkdir 'C:\.jupyter'
I am a user of a laptop managed by my organization so I don't have admin rights to write there, is there a workaround to choose that folder which I already have in my user folder?

Thanks for any feedback!

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning. The Python Extension for VSCode now supports the ability to import, modify, and export jupyter notebooks and is actively being developed. Please try it out and log issues on the Python extensions issues list.
