### ISSUE TITLE
[P0] Connect to compute instance Jupyter server command not working.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#810]
Referencing the old Python extension command.

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/7a00be0c-86a1-485a-b32c-c14337361134)

Needs to be updated to use the new Jupyter command.

**Comment by SiddhanthUnnithan** [comment]
- Joyce prepared a PR for Jupyter extension migration
- Check if we need more before merging

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/1965257
