### ISSUE TITLE
Upgrade to VS Code's webview API 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-tools-for-ai#82]
Hi, I'm on the VS Code team. I noticed that your extension uses the `vscode.previewHtml` command which is deprecated and which we are actively working to remove: https://github.com/Microsoft/vscode/issues/62630

We've developed a [webview API][docs] that provides a much better developer experience and offers a number of important security and compatibility benefits over `previewHtml`. We cannot fix `previewHtml` without breaking backwards compatibility, and have instead opted to remove it. 

To ensure that your extension continues to work properly in VS Code, please try upgrading to use the new Webview API. You can find documentation on the API usage [here][docs]. Let me know if you have any questions or concerns about this migration

[docs]: https://code.visualstudio.com/docs/extensions/webview

**Comment by shsuman** [comment]
We are using previewHtml currently only to show webpages which we fetch from a server like azure portal or jupyter server. Correct me if I am wrong but from what I understand the web view api only asks you for a html string and is meant to be used only if you want to your own web pages. So, is there a way to fetch a web page from a server using its uri, say "https:\\www.bing.com" and display it as it is in the 
Webview panel using the Webview API

**Comment by mjbvz** [comment]
No, this is by design. You can either fetch the html to populate the webview html or use a fullwidth iframe in the webview

**Comment by shsuman** [comment]
but the iframe does not work when you reference local files, like when i try to redirect to the jupyter server it says "refused to display " localhost.............notebook name"  in a frame because an ancestor violates the following content security policy directive: "frame-ancestors file://*" and also if a redirect to a local html file it says "local files are not allowed"

**Comment by mjbvz** [comment]
You need to change the CSP directive and probably rethink what you are doing. Webviews are much more like normal browser windows in terms of isolation. Nothing is served from `file:`

**Comment by shsuman** [comment]
We have already escalated it to p0. We are currently using previewHtml() for one command and that will be changed to webview pretty soon.

**Comment by greazer** [comment]
We decided to open portal pages in a separate browser rather than deal with this change. We (Rong, Shane and I) all agreed opening a separate browser window to the portal is a better experience anyway.
