### ISSUE TITLE
[Verify] VSCode extension doesn't reconnect after I restart my compute

### ISSUE THREAD

**Issue by AbeOmor** [microsoft/vscode-tools-for-ai#822]
## Expected Behavior
When I restart my compute in AML, the VSCode extension doesn't reconnect to the compute instance

## Actual Behavior
When I restart my compute in AML, the VSCode extension should reconnect to the compute instance

## Steps to Reproduce the Problem

  1. Open from a Notebook with the Edit with VSCode button in AzureML
  2. Restart compute in AzureML
  3. Remote window in VSCode keeps trying to reconnect

## Specifications

  - Version: 0.6.17
  - Platform: VSCode 1.15

**Comment by SiddhanthUnnithan** [comment]
We think by moving the VS Code server and websocket server spin-up to the second extension that we'll be able to reconnect to the compute from a cold/restart state to running.

Prioritize investigation once we start the second extension work.

**Comment by SiddhanthUnnithan** [comment]
Verify that reloading the window will address this. We think it should because we get fresh installs of VS Code and websocket servers.

**Comment by SiddhanthUnnithan** [comment]
Verified.
