### ISSUE TITLE
No way of seeing what is wrong with a failed job

### ISSUE THREAD

**Issue by syagev** [Microsoft/vscode-tools-for-ai#83]
VSCode 1.28.2
VSCode-tools-for-AI 0.3.1
Windows 10/1809

When submitting a job using docker:
```
{
    "version": "0.0.1",
    "job": {
        "type": "General",
        "files": {
            "includes": [
                "**/*.py"
            ]
        },
        "name": "Config",
        "startupCommand": "python",
        "startupScript": "simu_mcmk_get_config_v2.py",
        "arguments": "-opdir /workspace",
        "workingDirectory": "/code",
        "batchArguments": [],
        "docker": {
            "useRoot": false,
            "type": "Docker",
            "image": "gcr-repos.redmond.corp.microsoft.com:5000/styagev/simulation_multisource_v2"
        },
        "author": "MIDDLEEAST.styagev"
    },
    "platform": {}
}
```

my job fails (get's "interrupted"). There is no information in the job detail for me to see what went wrong.

![image](https://user-images.githubusercontent.com/5247438/48228009-a829ec80-e3ac-11e8-82e0-bf867058a9e2.png)

Also - I couldn't find in the docs a simple explanation of what is happening when I "submit a job" to a linux remote machine. Is the code copied and mounted on the container? where? Can I mount additional data directories on the container? 

Thanks

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning.  In the [archive](/archive) folder, you can find the [0.3.1 vsix installer](/archive/ms-toolsai.vscode-ai-0.3.1.vsix) that includes  previous features before this redesign, along with corresponding docs.
