### ISSUE TITLE
Azure ML users can access compute instances in private link enabled workspaces.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#830]
Placeholder issue for community upvotes.

**Comment by csiebler** [comment]
Super important for many enterprise customers, as they typically have their storage behind VNET and Private Endpoint hidden, which requires them to have an Azure Machine Learning workspace with Private Link enabled.

**Comment by vyasdev** [comment]
Second this. Its almost guranteed enterprise storage, SQL etc have VNet enabled and AML with private endpoints enabled is the only way to get features like Datasets (explore), view results in Designer etc to work.

**Comment by michalmar** [comment]
+1 since most customers (telco, banking) I work with plan to use Private Link enabled Workspace and SSH is almost forbidden from Security depts.

**Comment by rajd90** [comment]
+1 this is critical for our project & organisation as well. as with michalmar's situation, we are required to use privatelink and ssh is forbidden. right now we are required to set up DSVMs in the vnet and access the AML workspace via bastion host.

**Comment by maureenxu** [comment]
+1

**Comment by anirbansaha96** [comment]
This is an absolute necessity.

**Comment by csiebler** [comment]
Any update on this?

**Comment by SiddhanthUnnithan** [comment]
Hey @vyasdev, @michalmar, @rajd90, @maureenxu!

We've shipped the latest version of the extension (0.6.20) with support for private-link enabled workspaces (and major stability improvements) :)

Please give it a try and let us know if you're unable to connect.

Kind Regards,
Sid
