### ISSUE TITLE
Investigate copying large files from local to remote

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#832]
Check whether copying issues has to do with fileshare throttling or connection issues.

**Comment by shsuman** [comment]
What's the definition of large here? 100MB, 1GB, 10GB

**Comment by shsuman** [comment]
So, I tested copying some files and folders over to a CI from my Windows machine with a hardwired connection of 100Mbps. Here are the findings:

1. One folder, with 4 files and size 1.08GB. Transferred successfully within an hour
2. One folder, with 5000 and 898 subfolders, and size 1.23 GB, transferred successfully in about 2 hours
3. One file with size 4.54 GB, still copying for more than 3 hours

Other than some reconnects, there was no other issue
