### ISSUE TITLE
Even if local VS Code window is in focus, invoking the URI doesn't bring the desktop client to the forefront

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#838]
We expect invoking the URI from the Studio to bring your local VS Code window in focus (assuming one desktop window is already open).

Sometimes the top-most window isn't brought into focus. The user has to navigate to their VS Code window and find the one responsible for installing the server and invoking the remote window.

This pushes entry points in the Studio from compute instance nodes and the remote-explorer tab.

**Comment by SiddhanthUnnithan** [comment]
Try reproing with a smaller extension for VS Code Core to pickup and fix.

Could also be because "trusted extension" popup was disabled in VS Code.

**Comment by tbombach** [comment]
One possible mitigation would have been to see if we can focus the window ourselves in our code. Unfortunately it doesn't appear to be possible in VS Code extensions: https://github.com/microsoft/vscode/issues/99569

**Comment by SiddhanthUnnithan** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2578

Issue as a reference for better understanding the "multi window open" scenario.

**Comment by SiddhanthUnnithan** [comment]
After some testing with the separate remote extension we confirmed that the URI handler works even if the remote window is "topmost".

This issue originally dealt with bringing windows in "focus" - outside of the scope of what our extension can do. For now we want to continue testing the "topmost" window URI handling.
