### ISSUE TITLE
Output window constantly grabs focus

### ISSUE THREAD

**Issue by syagev** [Microsoft/vscode-tools-for-ai#84]
VSCode 1.28.2
VSCode-tools-for-AI 0.3.1
Windows 10/1809

The output window is constantly automatically grabbing focus whenever I submit/list jobs, browse the storage explorer, etc. It is extremely frustrating and the info in the output window is not really important.

Please do not switch focus, see https://github.com/Microsoft/vscode/issues/31474

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning.  In the [archive](/archive) folder, you can find the [0.3.1 vsix installer](/archive/ms-toolsai.vscode-ai-0.3.1.vsix) that includes  previous features before this redesign, along with corresponding docs.
