### ISSUE TITLE
Users can invoke a remote window for their compute instances from the Remote Explorer tab

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#842]
Support Remote Explorer entry point for compute instance connections.

If we don't currently support the one-sub, one-ws model then we prompt the user to set a default workspace before showing them a list of compute options.

This work also includes adding commands to the "Resource Label" in the bottom-left corner of VS Code. Investigate whether we can just contribute a command to that today: "Azure ML: Connect to Compute Instance".

**Comment by SiddhanthUnnithan** [comment]
Thomas to add link to Codespaces extension codebase.

**Comment by SiddhanthUnnithan** [comment]
Split this work into resource label (0.6.18 potentially) and remote explorer (0.6.19).

**Comment by tbombach** [comment]
Codespaces codebase for reference: DevDiv VSO -> Cascade (omitting actual link since this is public)
