### ISSUE TITLE
Base telemetry for remote connection

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#846]
We want to add basic, core telemetry for the remote connection. This will emit the following events for now:

1. URI handler invoked.
2. VS Code server install event.
3. Websocket server install event.
4. Remote window invoked.

Ideally, we can chain the above events to create a funnel for where users are having trouble.

We eventually want more comprehensive telemetry for private preview 2 / public preview. Comprehensive telemetry can be found [here](https://microsoft.sharepoint.com/teams/python/_layouts/OneNote.aspx?id=%2Fteams%2Fpython%2FDocuments%2FDocuments%2FPython%20Team&wd=target%28Azure%20ML%20Extension%2FFeature%20Design.one%7C96C47AD5-760A-49C7-9356-C1CF440053F9%2FTelemetry%20Deep-Dive%7CD3136604-507C-4184-939D-D36EFFB140C3%2F%29)

**Comment by sevillal** [comment]
Merged to master
