### ISSUE TITLE
Can the Azure Machine Learning app be installed into Visual Studio 2019 and run by that IDE ?

### ISSUE THREAD

**Issue by agribot2** [microsoft/vscode-tools-for-ai#847]
The information about  the Azure Machine Learning app mentions VS code, but may potential new users  of that app are using Visual Studio 2019 , not VS Code. It would be an improvement to address the question ;- 
Can the Azure Machine Learning app be installed into Visual Studio 2019 and run by that IDE ?

**Comment by SiddhanthUnnithan** [comment]
Hi there! As of right now there are no plans to port the Azure ML extension to Visual Studio (VS). Our current priorities revolve around capabilities within VS Code (e.g. remote experience, debugging, language server validation).

If you don't mind me asking, what team / company are you a part of?

**Comment by SiddhanthUnnithan** [comment]
Closing due to no response. If needed, please reopen.
