### ISSUE TITLE
[Verify] Extension not installed/enabled in WSL2

### ISSUE THREAD

**Issue by tailaiw** [microsoft/vscode-tools-for-ai#848]
## Expected Behavior
The extension should be installed to WSL instead of local automatically, as stated [here](https://code.visualstudio.com/docs/remote/wsl#_managing-extensions)

## Actual Behavior
The extension is installed to local. While we can force local extensions to be installed in remote, it is automatically disabled in remote because it is enabled in local already.

## Steps to Reproduce the Problem

  1. Run vscode in a Windows with WSL2 Ubuntu
  2. Go to the extensions tab of vscode, install the extension, you will see it in local.
  3. Click the download icon on "LOCAL - INSTALLED" and select the extension to be installed to WSL, you will see it installed to WSL but disabled automatically.

## Specifications

  - Version: v0.6.18
  - Platform: Windows 10 Build 20262.1010 + WSL2 (Ubuntu 18.04) + VS Code v1.51.1

**Comment by SiddhanthUnnithan** [comment]
Thanks for submitting this @tailaiw! This is a regression that was introduced with version 0.6.17 of the extension, which was when we introduced experimental remote capabilities. We're working on a mitigation for the upcoming release (0.6.19) that should enable remote installation of the AML extension. I'm really sorry about the inconvenience - I'll make sure to follow up once we have the mitigation out.

**Comment by SiddhanthUnnithan** [comment]
One way to overcome this is by continuing to use the older version of the extension (i.e. 0.6.16 or older).

**Comment by tailaiw** [comment]
Thank you so much for the quick reply @SiddhanthUnnithan. Looking forward to the new version!

**Comment by shsuman** [comment]
Verified it. Azure ML extension is working in WSL remote window

**Comment by shsuman** [comment]
Closing this as the new bits work fine in WSL
