### ISSUE TITLE
Can't find View in Jupyter Server command in the latest update (0.3.2)

### ISSUE THREAD

**Issue by bat67** [Microsoft/vscode-tools-for-ai#85]
Hi~ 
Thanks for this great extension! But when I updated it today, I noticed that View in Jupyter Server command is not there anymore (and I used it yesterday which worked well). I prefer to edit Jupyter Notebooks in VScode with this extension, instead of in the browser. (I followed [this page](https://github.com/Microsoft/vscode-tools-for-ai/blob/master/docs/quickstart-06-jupyter.md)'s instructions). Had it changed or something? And how could I find it?
Thanks!

**Comment by greazer** [comment]
Yes, we moved the essence of this functionality from this extension to the main Python extension and have been quickly iterating on it.  Please take a look at this blog, https://blogs.msdn.microsoft.com/pythonengineering/2018/11/08/data-science-with-python-in-visual-studio-code/, and let us know what you think! 

Also see take a look through the readme (https://github.com/Microsoft/vscode-tools-for-ai) for more details about the changed role of this particular extension.

**Comment by bat67** [comment]
Thanks! 
I'll have it a try~😄
