### ISSUE TITLE
[Validate] Error when switching accounts but keeping the same folder open

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#853]
When you have an open folder with an active experiment set and you switch Azure accounts and reload, we get the following error: Error: At least one of endpoint or subscription should be provided in the web request. Please make sure you have selected your subscription correctly

The error comes from the fact that the subscription mentioned in project.json does not exist anymore. The extension activation sets the active experiment Id which checks if the workspace Id exists which tries to get the subscription from uri which returns undefined which is then passed into the sendRestRequest() which throws the error

Call Stack:

AzureMLWebRequest.SendRequestInner
AzureMLWebRequest.SendRequest
AzureMLWebRequest.SendRestRequest
AzureMLWorkspaceProvider.get
AzureMLWorkspace.exists
AzureMLExperimentMgr.setActiveExperimentId
AzureMLExperimentMgr.register

**Comment by shsuman** [comment]
WE should get rid of active experiment altogether.

**Comment by tbombach** [comment]
Let's verify this isn't a problem once active workspace is gone.

**Comment by shsuman** [comment]
When switching accounts, this is the error shown in the output pane and also the tree keeps loading infinitely:

![image.png](https://images.zenhubusercontent.com/5c1828cfc50615756d6b3d5a/88c1c76e-6423-4f37-aee3-b0d207736a1e)

Only after reloading the window, the tree view works

**Comment by shsuman** [comment]
This has been resolved with the new default workspace model
