### ISSUE TITLE
workspace was not listed

### ISSUE THREAD

**Issue by HAYAKAWATuyosi** [microsoft/vscode-tools-for-ai#854]
Issue Type: <b>Bug</b>

The extention "Azure Machine Learning" v0.6.18 doesn't list my workspaces,
so I have to down grade to v0.6.17 for now.

I use the extention "Azure Account" v0.9.4, which seems works well.
After signing in, the another extention "Azure Storage" v0.11.0 works well
and succeeds to list up the storage linked to the machine learning's workspace.

I'm afraid I have special situation:
There are 2 directories associated to the same mail address registered by my company.
First directory is for business with real customer, and the second is for learning and exercise.
My company is one of partner of microsoft,
so the directory I had missed is named "Visual Studio Uitimate with MSDN".

so I have tried setting the config "azure.tenant" as the value of directory ID, but in vain.

Addtionally, my local python is "v3.6.4 64-bit".
Is it too old?

![v0 6 18](https://user-images.githubusercontent.com/29587917/101276992-4ee35000-37f4-11eb-86f7-edc46c4126de.png)
![v0 6 17](https://user-images.githubusercontent.com/29587917/101276991-4db22300-37f4-11eb-80a7-134d99346218.png)
![v0 6 18_config-azure tenant](https://user-images.githubusercontent.com/29587917/101276993-50147d00-37f4-11eb-8d8d-791562a677d5.png)

Extension version: 0.6.17
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.74GB free)|
|Process Argv|--crash-reporter-id db694683-2370-4adc-86aa-7929cce829e7|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sevillal** [comment]
Hi @HAYAKAWATuyosi, 

Thanks for bringing this up. Do you mind enabling "debug" log level in the extension and share the "Azure ML Output"?

Steps:
1. Go to Azure Machine Learning extension settings:
![image](https://user-images.githubusercontent.com/56176070/101377353-90acde80-3866-11eb-8b2b-8d890e061ad1.png)
2. Look for "Ai > Logger > Level: Channel" setting and change it to "debug"
![image](https://user-images.githubusercontent.com/56176070/101377491-bafe9c00-3866-11eb-9650-086a7ea7c009.png)
3. Reload the window and open the extension
4. Obtain the output under "Azure ML Output"
![image](https://user-images.githubusercontent.com/56176070/101377618-e71a1d00-3866-11eb-8749-481b83e30c8b.png)

**Comment by HAYAKAWATuyosi** [comment]
Hi @sevillal  thank you for your replying.
After setting and reloading, however, the "Azure ML Output" does not appear in the list.
Also I have set settings for both user and workspace, but no effect was achieved.

![20201210_AzureMLOutput-not-listed](https://user-images.githubusercontent.com/29587917/101771073-b79c3680-3b2c-11eb-91a3-adf5a7fc8b06.png)
![20201210_setting_user](https://user-images.githubusercontent.com/29587917/101771079-b9fe9080-3b2c-11eb-8066-7fe125cd2a6f.png)
![20201210_setting_workspace](https://user-images.githubusercontent.com/29587917/101771084-bbc85400-3b2c-11eb-9dc4-c253ed2706d5.png)

**Comment by sevillal** [comment]
@HAYAKAWATuyosi  thanks for trying that out and for your patience with this issue.

Are you open to setup a call to do further triage? To avoid you putting your email here, you can email me at sevillal@microsoft.com and I can schedule some quick 15-20 min call to triage the issue together. 

Thanks in advance!

**Comment by HAYAKAWATuyosi** [comment]
@sevillal  thanks for your offering a triage, however no triage is needed.

I can make the best of web browser without VSCode to access "Azure Machine Learning",
because my intention is on learning NO-CODE predictive model, and so on.
Further more my listening to English is not so good.

anyway, I hope just you get in touch when it's modified someday.

**Comment by sevillal** [comment]
@HAYAKAWATuyosi thanks for you patience. I will update you once we found what's the cause of this issue and it is fixed. Th

**Comment by sebastianzolg** [comment]
I'm facing the same issue. Downgraded to Version 0.6.17. 
Version 0.6.18 and 0.6.19 both doesn't list my ML workspace nor the subscriptions.

**Comment by sevillal** [comment]
@HAYAKAWATuyosi @sebastianzolg we have found there is a bug in the extension and we are working on a fix for our next release.

Workaround: 
- We have detected that other YAML related extensions lead to this issue (i.e Docs Authoring Pack)
-  If you know of another extension that provides yaml validation is installed you could try to disable it before activating Azure ML

**Comment by sebastianzolg** [comment]
Thanks, @sevillal. I've tested it and it's indeed the Docs Authoring Pack. More specifically, it's the [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) on which the Docs Authoring Pack depends. I'll downgrade the ML extension for now, but of course, disabling the others is also an option. Thanks.
