### ISSUE TITLE
Failed to connect to the remote extension host server

### ISSUE THREAD

**Issue by luisquintanilla** [microsoft/vscode-tools-for-ai#860]
## Expected Behavior

Connect to remote compute instance

## Actual Behavior

Received the following message in the remote window:

```
Failed to connect to the remote extension host server (Error: No remote extension installed to resolve amlext.)
```

First two steps in connection process appear to have worked:

1. VS Code server being installed on the remote machine.
1. Websocket server being installed on the remote machine.

## Steps to Reproduce the Problem

  1. From VS Code, open Command Palette
  1. Enter command `Azure ML: Connect to Compute Instance`
  1. Selected the instance I wanted to connect to

## Specifications

  - VS Code Version: 1.5.1
  - Platform: Windows 10

**Comment by luisquintanilla** [comment]
Creating a new workspace and compute seemed resolved the issue.

**Comment by SiddhanthUnnithan** [comment]
Closing this issue as we were able to resolve this during the docs sync.

**Comment by konabuta** [comment]
I have same issue. How to resolve this ?

**Comment by SiddhanthUnnithan** [comment]
Hi @konabuta can you confirm what versions you have of the following:
1. VS Code
2. Azure Machine Learning extension (Main).
3. Azure Machine Learning - Remote extension.

Thanks!

**Comment by SiddhanthUnnithan** [comment]
Closing because we don't have enough information to continue.
