### ISSUE TITLE
Gracefully handle errors when listing compute instances on treeview

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#863]
Currently the "Compute instances" node in tree view lists the union of:

1. Notebook VMs
2. Compute Instances

Gracefully handle issues with endpoint calls on any of the two types of targets.

Issue:
Currently we see an empty list if one of the two rest calls fails.

**Comment by mobaniha** [comment]
keep getting the below message every time I try to list compute instances 
![image](https://user-images.githubusercontent.com/62829419/102194893-858d2a80-3ec6-11eb-9d56-f66b3ba40a7c.png)

**Comment by stawo** [comment]
I do experience the same as @mobaniha

**Comment by sevillal** [comment]
@mobaniha @stawo this was fixed in the latest version of the extension **0.6.19**, could you please update and give it a try?

**Comment by stawo** [comment]
@sevillal, thanks for the update.
I currently have version 0.6.13, but VS Code says there are no updates available.
Just to be sure, I waited couple days since your comment, closed and restarted VS Code, but no luck.
This is the info of my setup:

> Version: 1.41.1 (system setup)
> Commit: 26076a4de974ead31f97692a0d32f90d735645c0
> Date: 2019-12-18T14:58:56.166Z
> Electron: 6.1.5
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Windows_NT x64 10.0.18363

Has the update you mention already been made available? Or do we have to install it manually?

**Comment by sevillal** [comment]
@stawo thanks for your message.

Could you please update your VS Code to the latest version?

You can run command "Code: Check for Updates..." or click through "Help" in the toolbar then "Check for Updates". 

After updating you should be able to see the new 0.6.19 version of the extension.

Please let me know if you face any issue.

**Comment by stawo** [comment]
@sevillal , sorry for the late response.
I managed to update my VS Code (problems due to the fact that software installations are managed by IT) and update the extension as well.
It now works as expected and I can see all the instances listed correctly, thanks!
