### ISSUE TITLE
Command 'Azure ML: Connect to Compute Instance' resulted in an error 

### ISSUE THREAD

**Issue by luisquintanilla** [microsoft/vscode-tools-for-ai#864]
## Expected Behavior

Connect to remote compute instance

## Actual Behavior

Received the following prompt:

```
Command 'Azure ML: Connect to Compute Instance' resulted in an error (command 'vscodeai.azureml.remote.connect' not found)
```

![image](https://user-images.githubusercontent.com/46974588/102251411-c2f7b500-3ed2-11eb-9cf4-4ee5490dd05a.png)

## Steps to Reproduce the Problem

  1. Open Command Palette
  1. Enter command Azure ML: Connect to Compute Instance

## Specifications

  - VS Code Version: 1.52.0
  - Platform: Windows 10
  - AML Extension Version: 0.6.18

## Additional Details

For some reason, my AML resources are not displayed either (even though I am logged in with my Azure account). 

![image](https://user-images.githubusercontent.com/46974588/102251584-081be700-3ed3-11eb-8e23-2f68bf54d782.png)

Restarting VS Code did not fix the issue either.

**Comment by SiddhanthUnnithan** [comment]
Hey @luisquintanilla, is this an issue you're seeing in a remote window or in a local VS Code window?

**Comment by luisquintanilla** [comment]
Local window

**Comment by SiddhanthUnnithan** [comment]
Can you try manually removing the extension from the C:\Users\<alias>\.vscode folder and then trying a reinstall?

**Comment by luisquintanilla** [comment]
@SiddhanthUnnithan no luck. I get the same error message.

**Comment by SiddhanthUnnithan** [comment]
- Understood that this was occurring due to YAML language server
- TOOD: Investigate what the exact issue was.
