### ISSUE TITLE
The remote extension installs the websocket server using a dynamic port

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#869]
Switch from static port to dynamic ports for websocket server.

Check whether this will resolve the websocket closing issue that's being seen with the second remote extension.

**Comment by SiddhanthUnnithan** [comment]
Investigate whether this is related to the time limit issue that we're seeing when using the second remote extension and connecting to compute.

**Comment by sevillal** [comment]
Merged to master

https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCodeRemote/pullrequest/2045794

#900
