### ISSUE TITLE
Users can kill VS Code server and retry connecting after maximum retries are exhausted (when installing VS Code server)

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#877]
Once the extension reaches maximum retries when installing the VS Code server, a toast notification is shown explaining what occurred and prompting the user to "Kill VS Code server and retry".

The extension attempts to kill a VS Code server that's already running on the machine and then reattempts the server install + connection.

This is equivalent to:
1. User hits max retry.
2. User runs "kill VS Code server" command manually.
3. User retries connection.

We know the above to work, so we can try and package the steps in a single-click option for the user to see if it helps fix the first-time issue users may encounter.

**Comment by SiddhanthUnnithan** [comment]
Do we want to decrease the number of retries? Currently 10.

At the point of success can we log the number of retries?

**Comment by SiddhanthUnnithan** [comment]
Do the same thing for websocket server - "Kill Websocket server and Retry" after hitting maximum number of retries.

**Comment by shsuman** [comment]
Merged PR https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCodeRemote/pullrequest/2014741

Telemetry added to log the number of retries after which installation is successful to help us determine the max retry number in the future
