### ISSUE TITLE
Validate that we can use an extension pack to ensure main extension is installed with remote.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#879]
1. Create a dummy extension pack.
2. Specify a second dummy extension as part of the pack.
3. List the first dummy extension as a hard dependency of the second one.
4. Publish the dummy extension to the marketplace.
4. Install the dummy extension and ensure that there are no conflicts with a "circular" install.

**Comment by shsuman** [comment]
Done. Tested with shsuman.dummy-extension-main and shsuman.dummy-extension-remote. Also, tested with vscode uri's (vscode://shsuman.dummy-extension-main) and it works fine
