### ISSUE TITLE
ipynb can't show content

### ISSUE THREAD

**Issue by mddiallo** [Microsoft/vscode-tools-for-ai#88]
hello
In last release, we do not have the option to do right click on ipynb file to show in Jupyter server.

We have:
Verbose: Flask Stdout: 
warn: Starting local flask server timed out.
warn: Azure ML extension flask server couldn't be initialized: Error: Timeout of 500ms exceeded

**Comment by swanderz** [comment]
My team is experiencing the same issue

**Comment by gramster** [comment]
Jupyter support is no longer part of this extension which is becoming more focused on Azure ML. If you have the core Microsoft Python extension you can work with .ipynb files right inside VSCode.

**Comment by gramster** [comment]
It’s possible the old functionality hasn’t been completely removed and you’re seeing remnants of it.

The new functionality is described here: https://blogs.msdn.microsoft.com/pythonengineering/2018/11/08/data-science-with-python-in-visual-studio-code/

**Comment by ronglums** [comment]
@mddiallo, The AML extension needs to start up a flask server in a private env, which the “Azure ML: Install Azure ML SDK” command sets up. We’re looking into making this part of the extension activation event to eliminate this manual step, but for the time being, please run this command from the VS Code command palette (if you see an error, try to run it again. This is a known issue that happens sometimes)

**Comment by mddiallo** [comment]
Thanks for the info. I will try this.

**Comment by greazer** [comment]
The 0.4.0 build of the extension should alleviate the need to run the "Azure ML: Install Azure ML SDK" command.

**Comment by wmpauli** [comment]
When I run "Azure ML: Install Azure ML SDK” nothing whatsoever happens. Should I see some indication of progress when I run this command?
