### ISSUE TITLE
[Investigate] Use VS Code "credential store" to manage tokens for remote connection

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#881]
Look into VS Code credential API to see if we can store refresh token to be used cross-extension (i.e. created and stored by main AML, used by remote).

Follow up with Jupyter team who are currently using this today for token management.

**Comment by shsuman** [comment]
We have finalized how to use credential store and the PRs are ready. for that. Tracked by #901
