### ISSUE TITLE
[Investigate] Window crashing when connecting to remote instance

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#882]
Since 1.52 release, some customers have complained about window crash when connecting to a remote instance. These customers were seeing different behaviour for different CIs. 

Need to work with the core team to understand what the issue and what we can do to try and root cause.

Customers that are running into the issue have resolved by downgrading VS Code to 1.51.

**Comment by csiebler** [comment]
Downgraded to 1.15.1, did not seem to help:

```
debug: Azure ML for VSCode 0.6.19
debug: Platform: win32
debug: VSCode Azure Account extension not found
error: Failed to forward incoming connection to remote server: Unexpected server response: 401
error: Failed to forward incoming connection to remote server: Unexpected server response: 401
```

Any idea when we could expect a fix?

**Comment by SiddhanthUnnithan** [comment]
VS Code has pushed workaround, currently in Insiders, which should solve window crash. Any new users that encounter the issue should be prompted to try Insiders (as opposed to downgrade option we were previously going with).

**Comment by shsuman** [comment]
Closing this as it has been fixed in latest VSCode
