### ISSUE TITLE
[Investigate] Time limit issue when connecting to remote instance

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#883]
Behaviour was seen when:
1. Create remote instance.
2. VS Code server installs.
3. Websocket server installs.
4. Window remains stuck in "Opening: Remote" state, and eventually hits timeout (notification: Time limit reached...).

We've resolved the issue by only restarting the websocket server so we need to investigate what related to the ws server is causing this.

For starters, we're testing dynamic ports to see if that helps resolve.

**Comment by sevillal** [comment]
Fix to get dynamic ports for websocket server merged to master.

Merged to master

https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCodeRemote/pullrequest/2045794

#900
