### ISSUE TITLE
How to use the VS Code Azure ML Extension to interact with Azure ML Workspace sitting behind a VNET?

### ISSUE THREAD

**Issue by anirbansaha96** [microsoft/vscode-tools-for-ai#884]
## Expected Behavior
Add a proxy setting like we add proxies when we need to interact with the AzureML workspace sitting behind a VNET by making changes to hosts file and add exceptions in the proxy.

## Actual Behavior
Not returning any data.

**Comment by shsuman** [comment]
Are you trying to use the extension from a machine which is outside the vNET ? 
Also, are you able to connect to and use the Studio (ml.azure.com) using this setting ?

**Comment by anirbansaha96** [comment]
> Are you trying to use the extension from a machine which is outside the VNET?

Yes, the machine is outside the VNET where the AML workspace resides.

> Also, are you able to connect to and use the Studio (ml.azure.com) using this setting?

Yes, the authentication was successful but VS-Code did not populate any of the blades (Experiments/ Datastores/ Computes and so on) in VS Code.

Additional Information: 
The Local Machine on which the VS-Code is installed also resides in a Virtual Network with proxy exceptions for all the sites needed while trying to access the AML Web UI. 

Similar issues added:
#830 and #721 

@SiddhanthUnnithan may be able to help with some more information.

**Comment by sevillal** [comment]
Thanks for your reply @anirbansaha96 

Are you open to have a call to discuss your setup? Feel free to email us directly and we can arrange some time: sevillal@microsoft.com, siunnith@microsoft.com

**Comment by anirbansaha96** [comment]
Yes, sure I will reach out to you via email and set up a call. Thanks!

**Comment by Gergues** [comment]
To follow up on our call , I have attached the communication where this fail / time out 
the blob storage type traffic (htts) on 443 is not allowed on this network - 
**The function missing :** Exploring experiments and experiment runs. 
See below 
Thanks

![image](https://user-images.githubusercontent.com/7481105/106151485-64b52780-614a-11eb-857c-62250100b09c.png)
