### ISSUE TITLE
Extension pack dependencies are not respected when installing via the VS Code URI

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#888]
Reproduce:
1. Use bits of dummy main and remote extensions.
2. Confirm that the main extension is part of an extension pack with remote.
3. Invoke the URI from a browser (vscode://<dummy main ext>)
4. Confirm that the remote extension is NOT installed.

**Comment by shsuman** [comment]
Tracking with VSCode: https://github.com/microsoft/vscode/issues/114587

**Comment by shsuman** [comment]
This is actually working. I don't know why it wasn't working for me at the time
