### ISSUE TITLE
Uninstalling the Azure ML - Remote extension will uninstall the Azure ML extension as well.

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#893]
My initial thought was VSCode won't allow uninstalling Azure ML - Remote extension because Azure ML extension depends on it but that's not the case.

**Comment by SiddhanthUnnithan** [comment]
The Remote extension is an extension pack, that auto installs the main extension.

As a result, uninstalling remote will also uninstall main.

Keeping it as an extension pack is priority because we want users that install only remote to always get main as well.
