### ISSUE TITLE
The terminal in remote window persists VS Code server install script commands

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#896]
Repro:
1. Connect to a compute instance (fresh).
2. Open a terminal.
3. Hit the "up" arrow key.
4. Observe VS Code server install script commands.

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCodeRemote/pullrequest/2044851
