### ISSUE TITLE
Change quick-pick label of "Connect to Compute Instance" command

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#907]
The "Azure ML: Connect to Compute Instance" command currently has the label "Select ... to connect to Jupyter Notebook". We want to change that title string to "Select Azure ML Compute Instance".

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/47a5d21b-6d0c-46be-962c-8766078741d5)

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2056316
