### ISSUE TITLE
Remote extension telemetry

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#909]
**Artifact**: https://microsoft.sharepoint.com/:w:/t/python/ETlJ0rb7SPBHrvIwBN-Tq9kBcqvROT7Tbt4LnCBCbTcM5A?e=d0usRP
**Outcome**: Better engineering excellence reporting for AML and CSS teams to reference

**Comment by shsuman** [comment]
Closing this because it's already in 0.6.23 release
