### ISSUE TITLE
VScode giving error message when starting

### ISSUE THREAD

**Issue by xnone** [Microsoft/vscode-tools-for-ai#91]
Error message:

> Internal extension error: Azure ML extension flask server couldn't be initialized: Error: getaddrinfo ENOTFOUND undefinedversion undefinedversion:80

**Comment by sramayanam** [comment]
same on my Mac

**Comment by ronglums** [comment]
This is a setup problem. Please refer to #88 .

**Comment by greazer** [comment]
Build 0.4.0 should alleviate this problem.
