### ISSUE TITLE
Unknown errors when running experiments (local and remote) from compute instance

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#913]
When connected to a compute instance (via remote extension) and running either a local or remote experiment, the submissions fail with the following errors:

[Local Experiment]
![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/39f12eb1-a180-4dd5-b60d-20f743012f9e)

[Remote Experiment]
![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/e2b1cc90-f926-4625-bfaf-b6795626c8de)

**Comment by shsuman** [comment]
I cannot repro these. I tried running both local and remote experiments with the latest bits but could not repro these.
