### ISSUE TITLE
Unable to write to Workspace

### ISSUE THREAD

**Issue by clkalyan** [microsoft/vscode-tools-for-ai#915]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Getting the following message

error: Unable to write to Workspace Settings because no workspace is opened. Please  open a workspace first and try again.  

though I am running command 
View -> Command Palette -> Azure ML : Connect to Compute instance Jupyter server -> Azure ML Compute Instances -> [Workspace selected] -> [Compute Instance selected]

Extension version: 0.6.19
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (19.64GB free)|
|Process Argv|--crash-reporter-id cfb79dea-0ce1-4878-b502-7208e30d3bdc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt600cf:30251589

```

</details>

**Comment by shsuman** [comment]
Can you update the extension to 0.6.20. The issue has been mitigated in the latest release

**Comment by shsuman** [comment]
Closing this as we haven't received in over a month
