### ISSUE TITLE
Renaming folders or file is not supported - VS Code with Azure ML & Azure Blob 

### ISSUE THREAD

**Issue by saimanoj18** [microsoft/vscode-tools-for-ai#916]
## Expected Behavior
To be able to rename the file from Azure Blob container in VS Code

## Actual Behavior
"Renaming folders or file is not supported"

## Steps to Reproduce the Problem

I have connected VSCode to Azure Machine Learning account. I have opened the connected Azure Blob container and tried to rename a file in it, using VSCode. Then I get a notification that "Renaming folders or file is not supported".

## Specifications

  - Version: Azure ML 0.6.19 and VS Code 1.52.0
  - Platform: Ubuntu 18.04

**Comment by SiddhanthUnnithan** [comment]
Hi @saimanoj18 I'm curious what you mean by "connected Azure blob container"? Are you using the Azure Storage extension to mount the Blob to your local VS Code and then trying to rename a file?

Do you mind providing screenshots of what you're doing (steps) and the error that you're seeing?

Thanks!

**Comment by saimanoj18** [comment]
Yes, I am using the Azure storage extension to load the files. I have provided screen recording which shows the steps I did. I am able to create and delete files but not able to rename them.

https://user-images.githubusercontent.com/4462455/106950606-f286a900-672e-11eb-8508-5480af180f34.mp4

**Comment by SiddhanthUnnithan** [comment]
Thanks for sharing the recording @saimanoj18! That looks like an issue with the way in which the Azure Storage extension mounts the blob container to your VS Code workspace.

Do you mind filing the same issue with the screen recording here: https://github.com/microsoft/vscode-azurestorage/issues

Please also add a comment in this issue once you've created the other one so we can help track it and expedite if required!

Regarding your second question - do you mean the Notebooks tab in the Azure ML studio (ml.azure.com)? We have a capability that is in private preview right now that allows you to access those Notebook files and work directly against the remote compute. If that's something you're interested in trying out please let us know!

**Comment by saimanoj18** [comment]
@SiddhanthUnnithan I have just created the issue https://github.com/microsoft/vscode-azurestorage/issues/926 and it would be of great help if I can get past this :)

Regarding the Notebooks tab in Azure ML Studio - I am exactly looking for the capability that you mentioned. I would like to try it out. Can you please set me up for it ?

**Comment by SiddhanthUnnithan** [comment]
Awesome! @saimanoj18 can you please fill out [this form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR8JCzYlmCRNKqxQiW4IH9rdUMk0wQUtXRFFLODhYQUU5STNWUDJJSU1QMy4u).

We'll work to have you onboarded to the private preview capability soon :)

**Comment by saimanoj18** [comment]
@SiddhanthUnnithan  Thank you Siddhanth, I have filled the form :)
