### ISSUE TITLE
Use the new VSCode loading icon in the extension

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#919]
VSCode has upgraded its loading icon in 1.53. We should use the same in our extension.

E.g. We use the loading icon to indicate the run status.

**Comment by shsuman** [comment]
From Marisa: 

New loading icon: https://github.com/microsoft/vscode-codicons/blob/main/src/icons/loading.svg

**Comment by SiddhanthUnnithan** [comment]
@shsuman where is this icon used in our extension?

**Comment by SiddhanthUnnithan** [comment]
Hey @shsuman did we update the icons? Do we need anything from the design team?

**Comment by shsuman** [comment]
Sorry, I thought we did it but I guess we didn't.  Reopening it and adding it in the #1443

**Comment by shsuman** [comment]
Use ThemeIcon class to get this icon. Looks like:
new ThemeIcon('loading~spin')
