### ISSUE TITLE
Cannot sign into Azure Machine Learning behind proxy server

### ISSUE THREAD

**Issue by revolz** [Microsoft/vscode-tools-for-ai#92]
**System Configuration**
Azure Machine Learning Version 0.3.1
Visual Studio Code Insiders
Version: 1.30.0-insider (user setup)
Commit: 86571ec5a50b5bce09db45f458b407b77a33674a
Date: 2018-12-07T06:19:55.529Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.15063

-----

**Step to Reproduce**
1. Run Visual Studio Code Insiders in Proxy Server environment (non proxy environment works fine)
2. Refresh the Azure Machine Learning, Click on `Sign In` when prompted `Not signed in, sign in first`
3. No pop up appears, no authentication code, the following error message appears

**Error Message**
verbose: Flask Stdout: 
warn: Get subscriptions failed in AzureMLTreeView, not logged in
warn: Starting local flask server timed out.
warn: Azure ML extension flask server couldn't be initialized: Error: Timeout of 500ms exceeded
warn: Get subscriptions failed in AzureMLTreeView, not logged in

**Comment by revolz** [comment]
It was working fine a week or two. So it is some code change in between causes this issue.
Refer to this when it was still working. [https://github.com/Microsoft/vscode-azure-account/issues/27#issuecomment-443633154](url)

**Comment by ronglums** [comment]
This is a setup problem. Please refer to #88 .

**Comment by greazer** [comment]
Build 0.4.0 should alleviate this problem.
