### ISSUE TITLE
Completions for $schema by showing the supported schemas by Azure ML V2 

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#926]
1. Define a mechanism to get the list of supported schemas
2. Implement completions for the $schema tag

**Comment by SiddhanthUnnithan** [comment]
- It looks like the current public blob is where the schemas are going to remain for the extension (https://azuremlsdk2.blob.core.windows.net/latest/)

- There's a way to list all of the current schemas in that container => https://azuremlsdk2.blob.core.windows.net/latest?restype=directory&comp=list

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2088315
