### ISSUE TITLE
Research if Azure ML can include something in their schemas to facilitate the completions and validation of Azure resources on yaml files

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#927]
Research if by chainging/adding something to the current Azure ML schemas we can collect the Azure resources by a schema driven approach

**Comment by SiddhanthUnnithan** [comment]
https://microsoft.sharepoint.com/:w:/t/python/EfwHvNWXvLpOhtjKKdbIk34BGQyYwEm-i9dMdHfOcj4nqw?e=rYyWjz

- Can we create a dictionary mapping property names to its corresponding Azure resource identifier
- Share dictionary with AML and ask them how they can maintain and serve that for the extension to consume
- Validate whether we can add custom attributes to the JSON schema, and if so make a case for a custom signature

**Comment by sevillal** [comment]
We've agreed to include a property called arm_type that points to the AzureML resource being edited. Find the map of arm_type ids to resouces in the design document.
