### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Dmarch28** [microsoft/vscode-tools-for-ai#930]
- Issue Type: `Performance`
- Extension Name: `vscode-ai`
- Extension Version: `0.6.20`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Steve\AppData\Local\Temp\ms-toolsai.vscode-ai-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by SiddhanthUnnithan** [comment]
Hi @dmarch28, do you mind attaching the file that you have listed in the description?

**Comment by SiddhanthUnnithan** [comment]
Closing for now. If more info is provided, please feel free to move back to New Issues.
