### ISSUE TITLE
Test ipywidgets in remote instance

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#931]
Check with Jupyter team to see if they have sample Notebooks to help test.

**Comment by SiddhanthUnnithan** [comment]
Refer to Notebook that Rich sent - if unable to find, reach out to me (Sid).

**Comment by temiwale88** [comment]
Hello @SiddhanthUnnithan ,

Thanks. I see the file attached to the email. Am I supposed to run this notebook in AML (remote VS Code) to see if it runs?
![image](https://user-images.githubusercontent.com/21104282/108905249-54229080-75d4-11eb-8dd9-9b213be7ff7a.png)

**Comment by shsuman** [comment]
The ipyleaflet_simple.ipynb does not show the widget in the remote window

**Comment by shsuman** [comment]
Closing this as Elijah's problems are now resolved. #932 for overall tracking of widgets
