### ISSUE TITLE
Implement completions for commandJob schema

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#934]
Contribute the completions required for commandJob

1. Datastores
2. Computes
3. Datasets
4. Snapshots (codes)
5. Environments

**Comment by SiddhanthUnnithan** [comment]
Clarification: completions for the above resources will be available in all valid config files. The commandJob scope is referring to how we prioritize.

**Comment by sevillal** [comment]
Done merged to master.
