### ISSUE TITLE
Show compute type as detail in compute  completions

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#943]
Use compute type as detail in compute completions to improve the experience and group them when shown:

i.e.
target1 <aml cluster>
target2 <aml cluster>
target3 <ci>
target4 <ci>

**Comment by shsuman** [comment]
Should we merge this ?

**Comment by SiddhanthUnnithan** [comment]
Final Approach: Alphabetical ordering and compute type as detail

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2106031
