### ISSUE TITLE
Test compute instance connection with sovereign clouds

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#952]
Instructions:

https://msdata.visualstudio.com/Vienna/_wiki/wikis/vienna-wiki/15384/Validating-Private-Link-scenarios-for-your-service

**Comment by SiddhanthUnnithan** [comment]
Communication: we support private link and are still in the process of supporting sovereign cloud

**Comment by shsuman** [comment]
We do support both Fairfax and Mooncake. Although, you need to set Azure: Cloud (azure.cloud) setting to the respective value
