### ISSUE TITLE
[Investigate] Changing the default workspace should update diagnostics

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#964]
Currently, updating the active/default workspace does not automatically update diagnostics for files open in the editor. The user needs to manually  make a code change in order for the diagnostics to be refreshed.

We want to avoid users having to make code changes to see the diagnostics. If the user switches their current default workspace, diagnostics should be automatically updated. If at any point in time the user has files open in the editor, the extension activated, and a default workspace set, the user should see diagnostics.

**Comment by SiddhanthUnnithan** [comment]
Desired outcome: what is the work involved with updating diagnostics when the workspace values are changed.

**Comment by sevillal** [comment]
Merged to master. Should be available 0.6.23
