### ISSUE TITLE
Remove the message "resource should start with azureml prefix"

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#966]
We don't want to have to check whether a current property only supports azure ML resources as values. We also don't want to assume that only a resource can be provided and that the azureml: moniker is required.

We should remove any messages that indicate the wrong moniker has been used unless we're **confident** that only that moniker is supported for that property.

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2138692
