### ISSUE TITLE
Compute->target completion shows local duplicated

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#968]
This might be because RedHat and AzuremL extensions are both installed.

**Comment by SiddhanthUnnithan** [comment]
[P0] Follow up with Seth to see whether he has both extensions installed.

[P0] Investigate what is the work involved with changing how we handle contributions when RH extension is present, or if there's a quick fix.

[P1] Do the work to change how we handle contributions.

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2185478
