### ISSUE TITLE
Reduced installation readme 

### ISSUE THREAD

**Issue by paloukari** [microsoft/vscode-tools-for-ai#97]
I'd like to see a minimum installation documentation instead of the [current one](https://github.com/Microsoft/vscode-tools-for-ai/blob/master/docs/installation.md). Ideally, a one-liner that says "Click here to install everything". Then if the user wants to search for alternative installation options or installation details, read this document.

**Comment by greazer** [comment]
Most definitely!

**Comment by SiddhanthUnnithan** [comment]
Hey @greazer
