### ISSUE TITLE
Connect to remote compute instance in private link and public access enabled

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#974]
Allow remote experience for compute instances in private link with public access enabled.

Findings:
- User tries to connect from outside the private link Vnet
- From outside vnet <ci>.<region>.instances.azureml.ms:<port> does not work
- From outside vnet <ci>-<port>.<region>.instances.azureml.ms work
- Workspace.properties.allowPublicAccessWhenBehindVnet indicates if public access is enabled

**Comment by SiddhanthUnnithan** [comment]
Want to merge before we public preview.

**Comment by sevillal** [comment]
Merged to master, available 0.6.22.
