### ISSUE TITLE
Remove our telemetry flag and stick to vscode-extension-telemetry package enable/disable handling

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#978]
vscode-extension-telemetry which is the package we use to send telemetry events enables/disables telemetry following Telemetry: Enable Telemetry configuration in VS Code.

**Comment by SiddhanthUnnithan** [comment]
@sevillal is this already being tracked in the refactoring work? If not, can we assign this to the right epic under refactoring and move it there.

**Comment by sevillal** [comment]
Should be fixed as part of GA work, assigning it to the right epic.
