### ISSUE TITLE
Automate folder attachment 

### ISSUE THREAD

**Issue by paloukari** [Microsoft/vscode-tools-for-ai#98]
Reading through the getting started doc, in the section "Attach your folder to your experiment" I got confused about which folder to attach and why. A code-first approach instead of this would be easier to understand, something like "Clone this sample or open your existing project" before any Azure provisioning and folder attachment

**Comment by greazer** [comment]
Build 0.4.0 should alleviate this problem. At least it should be a good first step. Attaching a folder is now referred to as setting an active experiment. When possible the extension will now assume that the folder opened in VSCode is the folder that should be "attached" to the "active" experiment.
