### ISSUE TITLE
[Investigate] Timeout when unable to access Models or Endpoints

### ISSUE THREAD

**Issue by JorickvdHoeven** [microsoft/vscode-tools-for-ai#981]
## Expected Behavior
I'm expecting that when I try to open the Models tray or the Endpoints tray and the extension is unable to resolve the addresses because of a forbidden or not found error that the extension gives up after a while and provides a visual indication that contacting that portion of the workspace failed with a small retry link and a more details link

## Actual Behavior
When I click to expand the Models or Endpoints tabs when connected to my workspace which is on a VNet they forever spin as loading. I never see the registered models or pipeline end points. 

## Steps to Reproduce the Problem

  1. Create workspace in VNet
  2. Connect to workspace from local with a hosts file redirect to link DNS to IP addresses 
  3. Use VSCode to access the workspace either from local or using VSCode remote run. in both cases the model and pipeline tabs spin out.

## Specifications

__VSCode Spec (local)__
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

__Azure ML Extension Spec (local)__
- ms-toolsai.vscode-ai v0.6.22
- ms-toolsai.vscode-ai-remote v0.2.0

__Azure ML Extension Spec (remote)__
- ms-toolsai.vscode-ai v0.6.22
- ms-toolsai.vscode-ai-remote v0.2.0

**Comment by SiddhanthUnnithan** [comment]
@shsuman do you know if the new 2.0 APIs will fix this? Can we test VNET and private link scenarios with those APIs before we merge the changes?

**Comment by shsuman** [comment]
Sure. I can test that

**Comment by shsuman** [comment]
I have tested the SDK on the [sevillal-win-vm](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/asset/Microsoft_Azure_Compute/VirtualMachine/subscriptions/b856ff87-00d1-4205-af56-3af5435ae401/resourceGroups/sevillal_ws_rg/providers/Microsoft.Compute/virtualMachines/sevillal-win-vn) and all the APIs seems to work as expected
