### ISSUE TITLE
Deploy new model ACI select scrpt Browse doesn't pop up

### ISSUE THREAD

**Issue by rlhull6** [microsoft/vscode-tools-for-ai#982]
When attempting to Deploy Service From Registered model, the step for selecting the scoring script doesn't bring up a pop up window

Steps to reproduce
  1.Right click Model in left Panel window
  2.Choose Option  "Deploy Service From Registered Model"
  3. Please enter a service name (Press Enter)  -> 'mytest'
  4.Please select service type "Azure Container Instances"
  5. **Choose script to run (Press 'Enter' to confirm or "Escape" to cancel**

Hitting enter nothing happens.  I provided a manual path ie) C:\Users\me\score.py and it seems to continue onto the next step however I get other errors later  (I"m guessing those are unrelated though)

![image](https://user-images.githubusercontent.com/9659518/114885965-c5104880-9dcc-11eb-896f-08277c58f767.png)

## Specifications
  - Platform: Windows 10 Enterprise version 1809 build 17763.1817
  - Azure Machine Learning License: v0.6.22
  - Visual Studios Code Version: 1.55.2
  - Electron 11.3.0
  - Chrome: 87.0.4280.141
  - Node.js 12.18.3
  - V8: 8.7.22.0.31-electron.0

**Comment by SiddhanthUnnithan** [comment]
Closing this issue in favour of moving to the new 2.0CLI flows in the extension (CLI-dependent) that will no longer show quick-pick prompts.
