### ISSUE TITLE
Replace all existing experiment entry points with the new job configuration flow

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#989]
Flask icon in the toolbar: Show a quick pick for the user to pick between job types (Sweep, Command) at the time of writing.

Python script: Choose command job template type and auto-populate the python script field.

Compute: Remove this option.

Experiment: Remove "Create Experiment" and standardize on "Create Job" > quick pick.

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2219396
