### ISSUE TITLE
Multiple runtime issues when previous extension and/or SDK version is installed

### ISSUE THREAD

**Issue by paloukari** [Microsoft/vscode-tools-for-ai#99]
I got multiple runtime issues like resource provisioning failures, Flask connection timeouts etc. After deleting the old SDK, the extension worked like a charm.

**Comment by greazer** [comment]
I'm not sure what may have happened here. What I do know is that the extension requires it's own "private" copy (python environment) of the 1.0.2 version of the Azure ML SDK. Sounds like you got it updated and all is fine now.
