### ISSUE TITLE
Run experiment from "Compute Cluster" results in "Cannot read property 'match' of undefined"

### ISSUE THREAD

**Issue by sjuratov** [microsoft/vscode-tools-for-ai#992]
## Expected Behavior
I can't run experiment from "Compute Cluster" entry point. It has been working for a long time.

## Actual Behavior
I used to navigate extension, going to "Compute Cluster", selecting cluster, selecting run config and and executing run experiment. This has worked for a long time, but not anymore. It results in "Cannot read property 'match' of undefined" error. I've tried this on a few AML WS.
Instead, I've discovered new entry point that works - via "Experiments", selecting experiment and then running experiment. 

## Steps to Reproduce the Problem

  1. Go to "Compute Cluster"
  2. Select cluster
  3. Select run configuration (or first create new one)
  4. Right click run configuration and then select run experiment

## Specifications

  - Version: 0.6.22
  - Platform: Windows 10

**Comment by sevillal** [comment]
Fix merged should be available on version 0.6.23.
