### ISSUE TITLE
Order experiments based on last submitted run

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#995]
Experiments are ordered in the tree based on creation date, with newly created experiments at the bottom.

To be consistent with the Studio UI, we want experiments to be ordered with the last submitted run shown at the top of the tree. If the user submits a new run for an older experiment the tree should be updated to show that experiment at the top.

**Comment by sevillal** [comment]
Merged, should be available in version 0.6.23.
